Clown Stump add
SerbiaStrong-220/space-station-14 pull request #1011
Opened 2024-05-15 07:22 UTC by Surani1

## Описание PR
Добавлена коробка с рандомной рофлопечатью главы в шкаф клоуна и мима.
Рофлопечати
- главсрач
- глава сраной безопасности
- кокпитан
- центкам
- сраный инженер
- БЛАТА НЕТ (Печать Одобрено заменена на Доверие)

**Медиа**
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/154987464/aad296ac-cdf7-46e6-bb84-587df19a0f61)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Surani
- add: Добавлены рофлопечати клоуну.

2024-05-15 07:23 UTC, Surani1 commented
Жду от madscaven реапдейтнутую коробку, не мерджить

2024-05-15 07:24 UTC, Surani1 commented
ебать, че с чеками

2024-05-15 08:19 UTC, Surani1 commented
@DexlerXD ни я ни скалдет не знают в чем проблема

2024-05-17 22:53 UTC, DexlerXD approved these changes

2024-05-21 07:33 UTC, DexlerXD commented
@Surani1 чини :)

2024-05-21 08:24 UTC, Surani1 commented
@DexlerXD чеки посмотри

2024-05-21 09:39 UTC, DexlerXD requested changes

2024-05-21 09:39 UTC, DexlerXD commented on Resources/Locale/en-US/paper/stamp-component.ftl
перенести
у нас в англ языке тоже наша папка есть

2024-05-21 09:39 UTC, DexlerXD commented on Resources/Locale/ru-RU/paper/stamp-component.ftl
перенести в ss220

2024-05-21 09:39 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/paper.ftl
перенести в ss220

2024-05-22 08:54 UTC, DexlerXD approved these changes

2024-05-22 08:55 UTC, merged