Better Knifes Update
SerbiaStrong-220/space-station-14 pull request #1013
Opened 2024-05-15 16:51 UTC by jellycrab-sprite

## Описание PR

Данный ПР вводит изменения в метательные ножи. Их метательный урон порезами понижен на пять единиц, взамен дана возможность смазывать метательные ножи любым веществом. Вместимость ножа такая же, как у копья - 2u. Этот апдейт создан для того, чтобы сделать метательные ножи интереснее и практичнее, так как теперь их можно будет смазать токсинами или снотворными веществами.
Также данный ПР исправляет проблему с непрямым полётом боевых и метательных ножей.
Сделан респрайт метательных ножей на основе билда ss13.

**Медиа**

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/105733702/1c597290-b994-4845-b2bb-dfd47d0b130a)

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: jelly.crab

- fix: Исправлен вектор полёта боевых и метательных ножей, теперь они летят остриём вперёд.
- tweak: Изменены метательные ножи. Теперь их можно смазывать любым веществом.
- tweak: Изменены текстуры метательных ножей. 
<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-05-17 14:14 UTC, DexlerXD requested changes

2024-05-17 14:14 UTC, DexlerXD commented on Resources/Textures/Objects/Weapons/Melee/throwing_knife.rsi/meta.json
>      "license": "CC-BY-SA-3.0",
лицензия старая

2024-05-17 16:12 UTC, jellycrab-sprite commented on Resources/Textures/Objects/Weapons/Melee/throwing_knife.rsi/meta.json
>      "license": "CC-BY-SA-3.0",
какую лицензию поставить вместо старой?

2024-05-17 22:52 UTC, DexlerXD commented on Resources/Textures/Objects/Weapons/Melee/throwing_knife.rsi/meta.json
>      "license": "CC-BY-SA-3.0",
> какую лицензию поставить вместо старой?

`EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt`

2024-05-18 23:38 UTC, jellycrab-sprite commented on Resources/Textures/Objects/Weapons/Melee/throwing_knife.rsi/meta.json
>      "license": "CC-BY-SA-3.0",
Обновлено.

2024-05-21 07:54 UTC, DexlerXD commented
@jellycrab-sprite спрайты почини

2024-05-21 15:43 UTC, DexlerXD approved these changes

2024-05-21 15:45 UTC, merged