Syndie Chembox Update
SerbiaStrong-220/space-station-14 pull request #1016
Opened 2024-05-15 22:20 UTC by jellycrab-sprite

## Описание PR

**Данный ПР создан для увеличения иммерсивности игры антагонистов.** 

1. Изменён набор химического синтеза синдиката. Список изменений:
> - Убрана одна мензурка
> - Убрана пустая колба
> - Добавлен один шприц стимулятора
> - Добавлена пробирка со свинцом
> - Добавлена пробирка с ураном
> - Стандартные медицинские очки изменены на новые кроваво-красные очки анализа, выполняющие функции мед и хим худов одновременно.
2. Добавлены кроваво-красные очки анализа. Спрайт создан **_D1nazewwr_** специально для SS220.
3. Изменена стоимость набора химического синтеза в аплинке. Теперь он стоит 5ТК (увеличение цены на 1ТК.)
4. Добавлены пробирки свинца и урана.

**Медиа**
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/105733702/54af6be6-5ff9-4f81-b6d8-d9760618c3a8)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/105733702/8c85bc01-9c28-4f44-9aef-ce33b6fdf077)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/105733702/d60b02f8-ac66-4fb7-a2a7-7936e9ee7601)

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: jelly.crab

- add: Добавлены новые хим-мед очки для синдиката!
- tweak: Изменён состав набора химического синтеза синдиката.
- tweak: Изменена цена набора химического синтеза в аплинке. Теперь он стоит 5ТК!

2024-05-17 14:12 UTC, DexlerXD requested changes

2024-05-17 14:12 UTC, DexlerXD commented on Resources/Prototypes/Entities/Clothing/Eyes/hud.yml
перенести в SS220

2024-05-17 14:12 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Specific/chemistry-vials.yml
перенести в SS220

2024-05-17 14:12 UTC, DexlerXD commented on Resources/Textures/Clothing/Eyes/Hud/syndchem.rsi/meta.json
перенести в SS220

2024-05-17 14:12 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/eyes/hud.ftl
перенести в SS220

2024-05-17 14:12 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/chemistry-vials.ftl
перенести в SS220

2024-05-17 17:04 UTC, jellycrab-sprite commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/chemistry-vials.ftl
Перенесено

2024-05-17 22:51 UTC, DexlerXD commented
@Ady4ik одобрено?

2024-05-21 07:40 UTC, DexlerXD commented on Resources/Textures/SS220/Clothing/Eyes/syndchem.rsi/meta.json
> +  "license": "CC-BY-4.0",
на каких основаниях такую лицензию поставили?

2024-05-21 07:54 UTC, jellycrab-sprite commented on Resources/Textures/SS220/Clothing/Eyes/syndchem.rsi/meta.json
> +  "license": "CC-BY-4.0",
лицензиии это моя слабая сторона

2024-05-21 07:57 UTC, DexlerXD commented
@jellycrab-sprite еще и спрайты починить надо...

2024-05-21 08:04 UTC, jellycrab-sprite commented
> @jellycrab-sprite еще и спрайты починить надо...
Сейчас коммит сделаю

2024-05-21 13:40 UTC, Ady4ik approved these changes

2024-05-21 15:39 UTC, DexlerXD approved these changes

2024-05-21 16:08 UTC, merged