Brigmedic loadout add
SerbiaStrong-220/space-station-14 pull request #1023
Opened 2024-05-17 06:52 UTC by Surani1

## Описание PR
Добавлен лодаут бригмедика ( его вообще не было :) )

**Медиа**
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/154987464/1e6fafaa-3260-45e8-9c63-30e1f8b99515)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Surani
- add: Добавлен лодаут бригмедика.

2024-05-17 14:08 UTC, DexlerXD requested changes
в локах тоже пометки сделай

2024-05-17 18:50 UTC, Surani1 commented
@DexlerXD проверяй

2024-05-17 22:48 UTC, DexlerXD approved these changes

2024-05-21 08:34 UTC, Surani1 commented
@DexlerXD заливай хуйню

2024-05-21 09:04 UTC, merged