Dragon cant eat zombie now
SerbiaStrong-220/space-station-14 pull request #1025
Opened 2024-05-17 13:32 UTC by Ady4ik

## Описание PR
Дракоша больше не страдает от колик в животике, потому что перестает есть зомби и нулевых пациентов.
(Да да, это код от адуча)

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Ady4
- fix: Исправлена возможность за дракона поедать нулевых пациентов и зомби.

2024-05-17 13:57 UTC, DexlerXD requested changes

2024-05-17 13:57 UTC, DexlerXD commented on Content.Shared/Devour/SharedDevourSystem.cs
> +        if (args.Handled || component.Blacklist?.IsValid(args.Target, EntityManager) == true)
```suggestion
        if (args.Handled || component.Blacklist?.IsValid(args.Target, EntityManager))
```

Методы, возвращающие `bool`, можно не приравнивать к какому-либо значению.

2024-05-17 13:57 UTC, DexlerXD commented on Content.Shared/Devour/Components/DevourerComponent.cs
> +    // SS220 Zombie and Infected check before devour start
```suggestion
    // SS220 Zombie and Infected check before devour end
```

2024-05-17 13:57 UTC, DexlerXD commented on Content.Shared/Devour/SharedDevourSystem.cs
> +            _popupSystem.PopupClient(Loc.GetString("devour-action-popup-message-fail-target-zombie"), uid,uid);
Создали блеклист (общий), однако сообщение только под зомбей. Тогда уже можно было бы написать какое-то общее сообщение, что данную сущность нельяз поглотить (просто что будет, если в блеклист попадёт что-то кроме зомбей).

2024-05-17 16:24 UTC, Ady4ik commented
[] Предотвратить сценарий поедания драконом ентити, которое не превратилось в зомби, но заражено

2024-10-03 11:44 UTC, Ady4ik commented
Fix #1998

Пора возвращаться в старое доброе русло

2024-10-13 19:55 UTC, closed without merging