Centcom comms circuitboard
SerbiaStrong-220/space-station-14 pull request #1031
Opened 2024-05-18 14:52 UTC by Kirus59

## Описание PR

Добавлена плата консоли связи Центком.

Зачем?
Т.к. ручка ЦК (как и ручка киберсан) обладает компонентом отвертки - то ей можно было случайно разобрать консоль (буквально 1 мисклик) и при обратной сборке получалась обычная консоль связи, а не Центкомоская. 
**Медиа**

https://github.com/SerbiaStrong-220/space-station-14/assets/145689588/95dff207-fac7-4f56-88d9-96dc680e878e

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

no cl

2024-05-18 14:53 UTC, Kirus59 commented
Эмм.... А что тут поменялось?
В визуалке не отображало что были тут изменения
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/145689588/569ec718-0931-49a1-83a2-6c6164673702)

2024-05-20 10:28 UTC, DexlerXD requested changes

2024-05-20 10:28 UTC, DexlerXD commented on Resources/Prototypes/Corvax/Entities/Structures/Machines/Computers/computers.yml
> +- type: entity
убрать
скорее всего приколы с окончаниями строк, могу порекомендовать скачать файл с репо, вставить с заменой в локалку и изменения ниже вставить по новой (тут всего 2 строки)

2024-05-21 09:03 UTC, DexlerXD approved these changes

2024-05-21 09:03 UTC, merged