NewDrinksSprites
SerbiaStrong-220/space-station-14 pull request #1035
Opened 2024-05-20 09:49 UTC by in1ef

## Описание PR
Добавлены новые спрайты для Саке и Поски. Из нового: добавлено банкате и его спавн в техах

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

:cl: D1nazewwr, inlef
- add: Банкате
- tweak: Изменены спрайты Саке и Поски

2024-05-20 10:45 UTC, Kit0vras requested changes

2024-05-20 10:45 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Drinks/brokenjar.yml
> +  name: Разбитая банка
```suggestion
  name: разбитая банка
```

2024-05-20 10:45 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Drinks/bankatejar.yml
> +  name: Банка банкате
```suggestion
  name: банка банкате
```

2024-05-20 10:45 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Drinks/brokenjar.yml
> +  description:  В этой банке было что-то отвратительное
```suggestion
  description: В этой банке было что-то отвратительное.
```

2024-05-20 10:45 UTC, Kit0vras commented on Resources/Prototypes/SS220/Reagents/Consumable/Drink/drinks.yml
> +  metamorphicChangeColor: false
```suggestion
  metamorphicChangeColor: false
  reactiveEffects:
    Acidic:
      methods: [ Touch ]
      effects:
      - !type:HealthChange
        scaleByQuantity: true
        ignoreResistances: false
        damage:
          types:
            Caustic: 0.3
      - !type:PopupMessage
        messages: [ "жидкость жжётся!" ]
        visualType: MediumCaution
        probability: 0.3
        type: Local
```
банкате просто как напиток это ведь скучно, зато могли бы использовать в качестве оружия, хоть и слабого

2024-05-21 09:28 UTC, DexlerXD commented
@in1ef YAML линтеру плохо...

2024-05-21 12:50 UTC, Kit0vras requested changes

2024-05-21 12:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Reagents/Consumable/Drink/drinks.yml
> +  flavors: horrible
```suggestion
  flavor: horrible
```

2024-05-21 18:52 UTC, in1ef commented
Сорян, времени в последние дни не было, больше не буду брать работы, если буду вымотан по времени и здоровью...

2024-05-21 21:51 UTC, DexlerXD approved these changes

2024-05-21 21:52 UTC, merged