Assistent uniforms
SerbiaStrong-220/space-station-14 pull request #1045
Opened 2024-05-22 15:04 UTC by RobUster0

## Описание PR

Добавляет:
- Комбинезоны и юбки для интерна, технического и научного ассистента.
- Два комбинезона и две юбки в одеждоматы отделов.
- Выбор ассистенского комбинезона и обычного цветного в лодаут.

**Медиа**

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/160126098/5763f780-cafd-4ae2-8552-ac67b7ecc16a)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/160126098/1664ca3f-d03d-4b1a-acd8-86d9c95f8ecc)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Vimenant
- add: Добавлены комбинезоны для интерна, технического и научного ассистента. Проверьте ваши гардеробы и одеждоматы!
<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-05-22 19:10 UTC, Kit0vras requested changes
https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/1ca90151-0c02-42f2-a61e-7d20baf5aa3b

2024-05-22 19:10 UTC, Kit0vras commented on Resources/Prototypes/Loadouts/Jobs/Medical/medical_intern.yml
> +- type: loadout
Перенести в 220

2024-05-22 19:10 UTC, Kit0vras commented on Resources/Prototypes/Loadouts/Jobs/Science/research_assistant.yml
> +- type: loadout
Перенести в 220

2024-05-22 19:10 UTC, Kit0vras commented on tatus
> +Author: vimenant <dr.steamplayer@yandex.ru>
убрать

2024-05-23 15:09 UTC, RobUster0 commented
fixed

2024-05-23 19:35 UTC, DexlerXD requested changes

2024-05-23 19:35 UTC, DexlerXD commented on Resources/Prototypes/Loadouts/Jobs/Engineering/technical_assistant.yml
откатить
ноль изменений здесь

2024-05-23 19:35 UTC, DexlerXD commented on Resources/Prototypes/Loadouts/Jobs/Medical/medical_intern.yml
откатить
ноль изменений здесь

2024-05-23 19:35 UTC, DexlerXD commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/assistant_uniforms.yml
между прототипами всё-таки стоит отступ в строчку делать для читаемости

2024-05-29 19:12 UTC, DexlerXD commented
@RobUster0 чинить будем?

2024-05-31 18:14 UTC, DexlerXD commented
@RobUster0 а что с изменениями, которые я попросил откатить?

2024-06-03 19:01 UTC, closed without merging