Rnd Resprite
SerbiaStrong-220/space-station-14 pull request #1047
Opened 2024-05-22 21:05 UTC by Kit0vras

## Описание PR

Респрайт униформы Рнд.
**Медиа**

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/a148fa07-9794-4dd0-9891-2044187fd473)
**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl:
- tweak: Изменены спрайты униформы РнД.

2024-05-23 19:26 UTC, DexlerXD requested changes
![Untitled](https://github.com/SerbiaStrong-220/space-station-14/assets/69513582/2d70750b-3398-41b7-950f-a9f9d5a20033)

2024-05-23 19:47 UTC, Kit0vras commented
> ![Untitled](https://private-user-images.githubusercontent.com/69513582/333314968-2d70750b-3398-41b7-950f-a9f9d5a20033.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTM4NjYsIm5iZiI6MTcxNjQ5MzU2NiwicGF0aCI6Ii82OTUxMzU4Mi8zMzMzMTQ5NjgtMmQ3MDc1MGItMzM5OC00MWI3LTk1MGYtYTlmOWQ1YTIwMDMzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxOTQ2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2FiOWUyNjkwYmUwZDdlMmFjODBkNTc2YzgzN2UwZTAwNzRmZWE0ZjE5NjY3YzcwNGZjNzdjYzlmNjVhNjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b5MQLRpyanZZ24LaX9eQl3nCWv6aB-WaKKUMHgaOXbQ)

самое главное, что до этого - ему было пофиг и было вполне вкусно жить без каких то там стейтов на воксов, нигде чеки не ронялись, а как я что-то делаю - так мы не довольны и хотим стейты для воксов

2024-06-03 13:21 UTC, Kit0vras commented
@DexlerXD он до меня тут чё то не по теме теперь докопался

2024-06-03 16:33 UTC, DexlerXD approved these changes

2024-06-03 17:01 UTC, merged