Carpet&Natural Tiles
SerbiaStrong-220/space-station-14 pull request #1052
Opened 2024-05-24 10:30 UTC by EstKemran

## Описание PR

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

:cl: Kit0vras
- add: Добавлены 9 разноцветных ковров.
- add: Добавлены 3 тайла грунта, 2 тайла воды и тайл песка.

2024-05-25 19:57 UTC, Kit0vras requested changes

2024-05-25 19:57 UTC, Kit0vras commented on Resources/Prototypes/SS220/Tiles/floors.yml
> +  baseTurf: Plating
```suggestion
  baseTurf: FloorDirt
```

2024-05-25 19:57 UTC, Kit0vras commented on Resources/Prototypes/SS220/Tiles/floors.yml
> +  id: FloorTileCarpetMud
всм грязевой ковёр? это типа грязь, как обычная грязь, или "сухой пол пещеры"

2024-05-25 19:57 UTC, Kit0vras commented
а де водичка и песочек...

2024-05-25 20:18 UTC, EstKemran commented
> а де водичка и песочек...

Завтра:jokerge:

2024-05-25 20:36 UTC, Kit0vras commented
> > а де водичка и песочек...
> 
> Завтра:jokerge:

а, я думал ты забыл
тогда оки

2024-07-21 17:03 UTC, EstKemran commented
Да ебаный его рот

2024-07-31 09:48 UTC, EstKemran commented
@DexlerXD Готово к мёрджу. Чертов песок решил уйти и не мешать :9catsmilee:

2024-07-31 15:34 UTC, DexlerXD commented
> @DexlerXD Готово к мёрджу. Чертов песок решил уйти и не мешать :9catsmilee:

нифига, ну ща

2024-07-31 15:47 UTC, DexlerXD commented
А что по нынешним коврам? Они заменяются этими? А то сейчас прям увы увы

2024-07-31 15:51 UTC, DexlerXD approved these changes

2024-07-31 15:52 UTC, merged

2024-07-31 16:04 UTC, EstKemran commented
> А что по нынешним коврам? Они заменяются этими? А то сейчас прям увы увы

Нет. Это другие