[WIP] Centcom Fashion
SerbiaStrong-220/space-station-14 pull request #1055
Opened 2024-05-25 17:16 UTC by EstKemran

## Описание PR

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Kemran
- add: Добавлена новая экипировака ЦК.
- tweak: Изменена новая палитра ЦК, черный цвет стал чище.
- tweak: Изменены старые спрайты ЦК под новую палитру.

2024-06-05 14:50 UTC, Kirus59 commented
@EstKemran замени еще мб ручку в кпк авд (и его чемодане вроде) на черную цкшную, а то у него старая зеленая

2024-06-05 14:55 UTC, EstKemran commented
> @EstKemran замени еще мб ручку в чемодане авд на черную цкшную, а то у него старая зеленая

Спрайт ручки изменен. Везде, где раньше была старая ручка теперь новая (кроме нахождения их на картах).

2024-06-05 14:58 UTC, Kirus59 commented
> > @EstKemran замени еще мб ручку в чемодане авд на черную цкшную, а то у него старая зеленая
> 
> Спрайт ручки изменен. Везде, где раньше была старая ручка теперь новая (кроме нахождения их на картах).

Адич на старые предметы просто no spawn накинул, в игре они все еще есть под старыми id, на который и ссылается storage fill у чемодана авд

2024-06-05 15:00 UTC, Kirus59 commented
А забей, я коммит выше не глянул......

2024-06-17 18:39 UTC, FriedrichStrassen commented
@EstKemran Привет. Хочу рецензию оставить, короче, две вещи:
1. Будет ли альтернатива катане? Не каждому нравится азиатское, я слыхал о том, что будет и шпага(рапира), это правда?
2. Мне кажется у полевой одежды ПОЦКа маловато деталей. Выглядит крайне пусто спрайт. Можно добавить погоны например массивные.. или ещё что-нибудь. Я покумекал, попробовал, но я лох и  у меня ничего особо не вышло. 

В остальном... ты ахуенен.

2024-06-17 19:01 UTC, EstKemran commented
> @EstKemran Привет. Хочу рецензию оставить, короче, две вещи:
> 
> 1. Будет ли альтернатива катане? Не каждому нравится азиатское, я слыхал о том, что будет и шпага(рапира), это правда?
> 2. Мне кажется у полевой одежды ПОЦКа маловато деталей. Выглядит крайне пусто спрайт. Можно добавить погоны например массивные.. или ещё что-нибудь. Я покумекал, попробовал, но я лох и  у меня ничего особо не вышло.
> 
> В остальном... ты ахуенен.

1. Да, планируется рапира
2. Полевая форма пОЦК была сделана на скорую руку, чтобы сегодня получить ревью Кита на весь Центком. Пытался не добавлять лишних деталей в угоду оригинального спрайта. От спрайта отказались (Квадратный + непонятный шов), планируется переделать

Спасибо

2024-06-22 06:30 UTC, FriedrichStrassen commented
@EstKemran Микроповоняю, в общем мне уже всё нравится. Не нравится в полевой формы ЦК одна деталь: эмблема НТ на спине. 
На флотской униформе нет большой геральдики на всю спину. 

Ну это просто мое мнение, в общем и целом мне форма нравится, геометрическая форма аналогичная хосу выглядит отлично. Одежды разной и крутой столько, что заебёшься подбирать себе набор по душе

2024-06-23 10:02 UTC, EstKemran commented
@Kit0vras @DexlerXD Мы должны это до деплоя замерджить :gonnacryhampter: 

@DexlerXD Осталась одна проблема, связанная с печатью ЦК. Не меняется цвет печати на бумаге с целью, не поможешь? :)

2024-06-23 10:04 UTC, DexlerXD commented
> @Kit0vras @DexlerXD Мы должны это до деплоя замерджить :gonnacryhampter: 
> 
> @DexlerXD Осталась одна проблема, связанная с печатью ЦК. Не меняется цвет печати на бумаге с целью, не поможешь? :)

есть проблема - апстрим
могут быть проблемы с мержем

2024-06-23 12:14 UTC, Kit0vras requested changes

2024-07-05 16:45 UTC, EstKemran commented
@UrPrice С изменением карт проблем не будет? В основном меняется цвет печати на бумагах, по типу брифингов, и на парочку картах старая печать заменяется на новую

2024-07-05 19:32 UTC, DexlerXD approved these changes

2024-07-05 19:46 UTC, merged

2024-07-05 21:05 UTC, UrPrice commented
> @UrPrice С изменением карт проблем не будет? В основном меняется цвет печати на бумагах, по типу брифингов, и на парочку картах старая печать заменяется на новую

Почему такие изменения сначала делаются, а потом согласовываются? В связи с чем потом у меня люди ловят мердж конфликты на тех файлах, которые тупо сложно потом исправить, кроме как втупую брать и заново вносить все изменения...

Если потом возникнут конфликты при патчах из-за этого PR - будем ревертить.

@DexlerXD не мерджи, пожалуйста, то, что я не аппрувнул по файлам карт.