add game card's/Добавление игровых карт.
SerbiaStrong-220/space-station-14 pull request #1056
Opened 2024-05-25 22:53 UTC by spo9k

## Описание PR
Добавление колоды карт.
Карты находятся в аппарате: Безобидные развлечения.
Как играть:

Сначала надо выбросить содержимое Упаковки с картами на пол при помощи кнопки "Высыпать на землю".
Затем надо обратно собрать все карты в Упаковку это их перемешает
После этого игрокам надо взять "Колоду карт" она работает в качестве "руки", типо "карты на руке", она хранит карты.

Подготовка завершена.
Упаковка - колода со всеми картами, оттуда надо добирать карты, оттуда достаётся тузовая карта,    НО  она НЕ  стопка сброса.
что-бы перевернуть карту в мире или инвентаре: надо нажать на E.
что-бы в руке: ЛКМ по карте.

Готово, дальше все как в обычных картах.

**Медиа**

https://github.com/SerbiaStrong-220/space-station-14/assets/135381384/c08e59f1-c561-4160-ba94-db9a5d318aaa

**Проверки**

- [+] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [+] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [+] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [+] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: spo9k
- add: Добавлены игровые карты.

2024-05-25 23:36 UTC, Kit0vras requested changes

2024-05-25 23:36 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Fun/cards.yml
> +
?

2024-05-25 23:36 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Fun/cards.yml
> +
?

2024-05-25 23:36 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Fun/cards.yml
> +
?

2024-05-25 23:38 UTC, Kit0vras requested changes

2024-05-25 23:38 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Fun/cards.yml
> +  description: Есть идеи что на этой карте?
```suggestion
  description: Предназначена для настольной игры. Погасите свою мысль о том, что она может быть отличным метательным оружием - это заблуждение.
```

2024-05-25 23:38 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Fun/cards.yml
> +  name: Карта
```suggestion
  name: карта
```

2024-05-25 23:43 UTC, Kit0vras commented
> После этого игрокам надо взять "Колоду карт" она работает в качестве "руки", типо "карты на руке", она хранит карты.

Это выглядит очень проклято, но да, я даже не знаю, как можно было бы сделать по другому

> Сначала надо выбросить содержимое Упаковки с картами на пол при помощи кнопки "Высыпать на землю".

А вот это - точно проклято, нужно сделать так, чтобы можно было нажать пкм по колоде и выбрать "перемешать", чтобы перемешать карты. Также было бы хорошо, если бы колода была "портативной корзиной для бумаг", чтобы можно было положить её на стол, а потом просто кликать лкм, чтобы взять новую карту, что-то в этом роде.

2024-05-25 23:45 UTC, spo9k commented
> > После этого игрокам надо взять «Колоду карт», она работает в режиме «руки», типа «карты на руке», она хранит карты.
> 
> Это выглядит очень проклято, но да, я даже не знаю, как можно было бы сделать это во втором раунде.
> 
> > Сначала надо выбросить святые Упаковки с картами на пол с помощью кнопки «Высыпать на землю».
> 
> А вот это - точно проклято, нужно сделать так, чтобы можно было нажать ПКМ на колоде и выбрать «перезапустить», чтобы перезапустить карту. Также было бы хорошо, если бы колода была "портативной корзиной для бумаги", чтобы можно было положить ее на стол, а потом просто щелкнуть лкм, чтобы взять новую карту, что-то в этом роде.

Хмм, ну можно так то сделать, чтоб было так, просто прототип сделан чисто из Т-луча. ( Ну свойств его, да выглядит тип сыро но что есть, собираю из говна и палок yml )

2024-05-25 23:48 UTC, spo9k commented on Resources/Prototypes/SS220/Entities/Objects/Fun/cards.yml
> +
Да это чтоб я не путался были пробелки, тип разделение, тип по мастям и т.д

2024-05-25 23:53 UTC, spo9k commented
Ну это пока первая версия, чтоб люди хоть поиграли в карты, потом апну изменю спрайты на более уже лучший вид, и добавлю джокера. А то его нет в колоде.

2024-05-26 00:00 UTC, Kit0vras commented
> > > После этого игрокам надо взять «Колоду карт», она работает в режиме «руки», типа «карты на руке», она хранит карты.
> > 
> > 
> > Это выглядит очень проклято, но да, я даже не знаю, как можно было бы сделать это во втором раунде.
> > > Сначала надо выбросить святые Упаковки с картами на пол с помощью кнопки «Высыпать на землю».
> > 
> > 
> > А вот это - точно проклято, нужно сделать так, чтобы можно было нажать ПКМ на колоде и выбрать «перезапустить», чтобы перезапустить карту. Также было бы хорошо, если бы колода была "портативной корзиной для бумаги", чтобы можно было положить ее на стол, а потом просто щелкнуть лкм, чтобы взять новую карту, что-то в этом роде.
> 
> Хмм, ну можно так то сделать, чтоб было так, просто прототип сделан чисто из Т-луча. ( Ну свойств его, да выглядит тип сыро но что есть, собираю из говна и палок yml )

убери миллион пустых строк, я отметил их вопросиками

2024-05-26 00:01 UTC, Kit0vras commented
@Ady4ik

2024-05-26 00:06 UTC, spo9k commented
Ща уберу и спать

2024-05-28 18:29 UTC, DexlerXD approved these changes
аппруваем, потом отправляем на доработку

2024-05-28 18:30 UTC, merged