Neck problems
SerbiaStrong-220/space-station-14 pull request #1070
Opened 2024-05-30 14:53 UTC by disssr

## Описание PR
Почти всю одежду на шею можно было съесть или разделать ножом (Например, значок адвоката, стетоскоп). Исправлено. Теперь лишь некоторую одежду (плащи, мантии, шарфы и др.) можно съесть и разделать.
Шарф-хамелеон нельзя разделать или съесть.
Хамелеон шарфа был исправлен.

**Медиа**

**Проверки**
- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

🆑 Disssr
- fix: Исправлен баг с хамелеоном шарфа
- remove: Удалена возможность разделывать/съедать любую одежду для шеи.

2024-05-30 15:18 UTC, SkaldetSkaeg commented on Resources/Prototypes/Entities/Clothing/Neck/scarfs.yml
> -  - type: Tag
Вот это надо бы вернуть

2024-05-30 15:18 UTC, SkaldetSkaeg commented on Resources/Prototypes/Entities/Clothing/Neck/scarfs.yml
> -    - type: Tag
И это вернуть

2024-05-30 15:21 UTC, SkaldetSkaeg commented
@DexlerXD можешь глянуть, у меня есть подозрение, что это через миграции надо делать вобще.

2024-05-30 16:31 UTC, DexlerXD requested changes
пупупуууу
Во-первых, если мы делаем изменения не в наших файлах, то обязательно ставиться пометка о том, что изменение наше, к примеру:
`- type: Comp #SS220-some-change`
Во-вторых, удалять теги просто так не стоит, как тут сделано с тегами Иана, например;
В-третьих, если в игру добавляется новый прототип от нас, то это делать надо в наших файлах, т. е. в нашей папке сделать аналогичный путь тому, который был бы обычно.

2024-05-30 16:31 UTC, DexlerXD commented on Resources/Prototypes/Entities/Clothing/Neck/base_clothingneck.yml
убрать, пустое изменение

2024-05-30 16:31 UTC, DexlerXD commented on Resources/Prototypes/Entities/Clothing/Neck/ties.yml
> +  id: ClothingNeckTieBase
necktie - целое слово

2024-05-30 16:32 UTC, DexlerXD commented
> @DexlerXD можешь глянуть, у меня есть подозрение, что это через миграции надо делать вобще.

через миграцию заменяются прототипы, которые стоят на мапе, например, ты сделал новый холодильник и старые нужно удалить и добавить новые. Заместо того, чтобы удалять со всех мап или удалять файл старого холодоса ты просто в миграции пишешь замену одного на другое, и при инициализации карт старый холодос будет указывать на новый.

2024-05-30 18:54 UTC, disssr commented on Resources/Prototypes/Entities/Clothing/Neck/base_clothingneck.yml
Так в базовом классе теги Ианов стоят же

2024-05-30 18:56 UTC, disssr commented on Resources/Prototypes/Entities/Clothing/Neck/base_clothingneck.yml
> Так в базовом классе теги Ианов стоят же

А на некоторых шарфах теги переписываются, чтобы все было, как в изначальной версии.

2024-06-05 17:18 UTC, DexlerXD commented
@disssr доделывать будем?

2024-06-08 13:33 UTC, closed without merging