Real stealth for ninja and syndie box
SerbiaStrong-220/space-station-14 pull request #1075
Opened 2024-06-01 15:04 UTC by TryHardo7

## Описание PR

Изменил прозрачность эффекта стелса, теперь его действительно трудно заметить. 

**Медиа**

https://github.com/SerbiaStrong-220/space-station-14/assets/166473301/a7aa31fa-e02f-4f81-bd95-39eb2d8c8351

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил видео демонстрации PR в игре.

**Изменения**

:cl: Lancevrot
- tweak: Изменена сила эффекта невидимости для ниндзи и коробки синдиката, теперь их действительно трудно заметить. Также ниндзя не будет отображаться у СБ в худах.

2024-06-01 15:47 UTC, DexlerXD requested changes
Хорошее изменение, но есть нюансы:
1. Если мы делаем измерения за пределами наших папок и пространства имён, то мы обязаны комментариями помечать таковые изменения, например:
```
//SS220-something
DoSomething();
```
или
```
//SS220-something begin
DoSomething();
DoStuff();
//SS220-something end
```
2. Изменения переменной в StealthComponent не самое лучшее решение, т. к. это стандартное значение датафилда. Лучше поменять именно это поле в нужном прототипе.

2024-06-01 17:05 UTC, EstKemran commented
Это одобряли?

2024-06-02 08:53 UTC, UrPrice commented
Отоброжение оверлея худов при этом скрывается?
Без фикса оверлея мало смысла менять сам эффект невидимости

2024-06-02 14:45 UTC, TryHardo7 commented
> 1. Если мы делаем измерения за пределами наших папок и пространства имён, то мы обязаны комментариями помечать таковые изменения, например:

Правильно?

2024-06-02 15:06 UTC, DexlerXD requested changes

2024-06-02 15:06 UTC, DexlerXD commented on Content.Shared/Stealth/Components/StealthComponent.cs
> +    /// SS220 - changed maximum visibility to be equal to minimum so that ninja will be actually invisible, not just blur effect everyone sees immediately.
как я написал в пункте 2 ревью, изменения в коде лучше в принципе убрать. 
попробуй поменять компонент StealthClothing в одежде ниндзя

2024-06-02 16:09 UTC, TryHardo7 commented
Убрал изменения в коде, всё сделано через прототипы. Базовые системы, на которые что-либо ссылается не затронуты.

2024-06-02 16:14 UTC, DexlerXD commented
@Surani1 мнение

2024-06-02 16:49 UTC, Surani1 commented
> Убрал изменения в коде, всё сделано через прототипы. Базовые системы, на которые что-либо ссылается не затронуты.

1. Изменения в коде влияют на стеллс коробку?
2. Как работает HUD's с данными модификаторами? Приложи пожалуйста видеоролик.

Тема со стеллсом - прямое изменение баланса, это наболевшая проблема как у игроков, не любящих когда их ВХшут, так и у администрации. Нужно создать трекер с предложением и обязательно голосованием, в котором можно будет понять, каково мнение игроков на этот счёт.

После этого я пингану адуча и там уже будет решение, про два пункта выше так-же жду ответа.

2024-06-02 20:43 UTC, TryHardo7 commented
> 1. Изменения в коде влияют на стеллс коробку?
> 2. Как работает HUD's с данными модификаторами? Приложи пожалуйста видеоролик.

1) Вот видео с коробкой. 
https://github.com/SerbiaStrong-220/space-station-14/assets/166473301/bb9bc12d-de20-4486-95df-4858c6959c91
2) Видео с худом приложено изначально - на ниндзю надел СБ очки, иконки нет. Полоска здоровья же будет отображаться в мед худах. 

Я против трекера, потому что там 95% васяны которые спамят пиво на всё подряд и им в принципе посрать. С момента когда я начал админить с печальной регулярностью этот вопрос всплывал в спорах. Я считаю лучшее решение - сделать так, чтобы игрок не думал "а не нарушаю ли я правила?" во время просто игры. Плюс тот инвиз что есть вовсе не инвиз, толку от него минимум, только атмосферу рушит ибо каждый думает что не должен его видеть, хотя отчётливо видит. По-моему данное изменение решит как и вопрос споров о правилах, так и добавит комфорта игрокам, так и подходит по смыслу для ниндзи, который должен быть всё-таки скрытный.

2024-06-03 19:47 UTC, Surani1 commented
> > 1. Изменения в коде влияют на стеллс коробку?
> > 2. Как работает HUD's с данными модификаторами? Приложи пожалуйста видеоролик.
> 
> 1. Вот видео с коробкой.
>    https://github.com/SerbiaStrong-220/space-station-14/assets/166473301/bb9bc12d-de20-4486-95df-4858c6959c91
> 2. Видео с худом приложено изначально - на ниндзю надел СБ очки, иконки нет. Полоска здоровья же будет отображаться в мед худах.
> 
> Я против трекера, потому что там 95% васяны которые спамят пиво на всё подряд и им в принципе посрать. С момента когда я начал админить с печальной регулярностью этот вопрос всплывал в спорах. Я считаю лучшее решение - сделать так, чтобы игрок не думал "а не нарушаю ли я правила?" во время просто игры. Плюс тот инвиз что есть вовсе не инвиз, толку от него минимум, только атмосферу рушит ибо каждый думает что не должен его видеть, хотя отчётливо видит. По-моему данное изменение решит как и вопрос споров о правилах, так и добавит комфорта игрокам, так и подходит по смыслу для ниндзи, который должен быть всё-таки скрытный.

С трекером решать @Ady4ik.

Проблема с коробкой - из-за твоих изменений она стала какой-то имбалансной,  скорость захода в инвиз слишком быстрая и при передвижении медленно спадает.

Был момент где я пытался исправить нормально инвиз, но по итогу вышла сильная каша, поэтому идею отложил на будущее.

2024-06-04 09:08 UTC, Ady4ik requested changes
1. Увеличить длительность вхождения в инвиз
2. Увеличить эффект размытия пространства во время ходьбы у ниндзи, чтобы его было более заметно во время ходьбы

2024-06-04 15:27 UTC, TryHardo7 commented
> 1. Увеличить длительность вхождения в инвиз
> 2. Увеличить эффект размытия пространства во время ходьбы у ниндзи, чтобы его было более заметно во время ходьбы

1) зачем? какую ценность для геймплея несёт увеличение вхождения в инвиз? 
2) Я специально ухожу от бесполезного инвиза, потому что он создаёт проблемы+неудобства и игрокам и администрации. Зачем ниндзю должно быть лучше видно при любых условиях?

2024-06-05 15:43 UTC, Ady4ik commented
> зачем? какую ценность для геймплея несёт увеличение вхождения в инвиз?
> Я специально ухожу от бесполезного инвиза, потому что он создаёт проблемы+неудобства и игрокам и администрации. Зачем ниндзю должно быть лучше видно при любых условиях?
1. Увеличение длительность вхождения в инвиз позволяет игроку хотя бы заметить ниндзю, потому что из-за слишком быстрого ухода в инвиз будет увеличена его наглость. Буквально: забежал, убил СБ на глазах у другого, ушел в инвиз за 0.01 - остался безнаказанным.
2. Размытие в движении даст хотя бы намек на то, что перед тобой что-то да есть. Это позволяет игроку хотя бы приготовится к тому, что его скоро постигнет кара ниндзи.

2024-06-07 21:06 UTC, TryHardo7 commented
> 1. Увеличение длительность вхождения в инвиз
> 2. Размытие в движении 

Всем селом думали как это сделать, по итогу придумали: теперь ниндзя красиво модно уходит в инвиз плавно. 


https://github.com/SerbiaStrong-220/space-station-14/assets/166473301/fa201714-0581-4934-bc5a-facb6e072948

2024-06-08 10:10 UTC, DexlerXD approved these changes

2024-06-08 10:10 UTC, DexlerXD commented
@Ady4ik мнение после изменений?

2024-06-11 06:57 UTC, Ady4ik approved these changes
Идеально

2024-06-11 08:30 UTC, merged