Beret CE
SerbiaStrong-220/space-station-14 pull request #1083
Opened 2024-06-02 20:16 UTC by NightmareStalker

## Описание PR

**Медиа**

![NewCanvas5](https://github.com/SerbiaStrong-220/space-station-14/assets/162575884/6ceed8bc-e9d7-4cc2-9602-54a515590ddd)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлен берет Старшего Инженера в игру, лодаут и комод.

2024-06-03 11:41 UTC, Kit0vras approved these changes
https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/d2d785ef-4798-4795-9ebe-12e75f311aa0

2024-06-03 16:43 UTC, DexlerXD requested changes

2024-06-03 16:43 UTC, DexlerXD commented on Resources/Prototypes/Catalog/Fills/Lockers/dressers.yml
> +      - id: ClothingHeadHatBeretCE #SS220-Resprite
```suggestion
      - id: ClothingHeadHatBeretCE #SS220-CEBeret
```
всё же стоит поподробнее писать, что за респрайт

2024-06-03 16:43 UTC, DexlerXD commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +#ss220-loadout-chief-engineer-end
```suggestion
  - BeretCE #SS220-CEBeret
```
изменение в одну строчку, + пометки, желательно. должны быть одни и те же на весь пр

2024-06-03 16:43 UTC, DexlerXD commented on Resources/Prototypes/SS220/Entities/Clothing/Head/beret_ce.yml
пометки в наших файлах в принципе не нужны, их стоит убрать

2024-06-04 05:19 UTC, NightmareStalker commented on Resources/Prototypes/SS220/Entities/Clothing/Head/beret_ce.yml
я это копипиздил с обычного берета инжевского, потому и есть пометки... на будущее учту...

2024-06-04 12:23 UTC, DexlerXD commented on Resources/Prototypes/SS220/Entities/Clothing/Head/beret_ce.yml
> я это копипиздил с обычного берета инжевского, потому и есть пометки... на будущее учту...

так че не убрал в итоге?

2024-06-05 08:42 UTC, NightmareStalker commented on Resources/Prototypes/SS220/Entities/Clothing/Head/beret_ce.yml
убрал, наверное?... я в душе не чаю, как с этим всем работать...

2024-06-05 17:13 UTC, DexlerXD approved these changes

2024-06-05 17:44 UTC, merged