Better Vulpkanin
SerbiaStrong-220/space-station-14 pull request #1099
Opened 2024-06-08 20:19 UTC by TryHardo7

Очередные несколько шагов в сторону играбельных вульп:
1) Они хищные так что голодают быстрее
2) Добавлен акцент соответствующий расе. ррр
3) Добавлены озвученные эмоуты для воя, рычания и гавкания. 

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

:cl: Lancevrot
- add: Озвучка эмоутов и акцент для вульп
- tweak: Вульпы быстрее голодают

2024-06-09 07:55 UTC, Surani1 commented
@Ady4ik @DexlerXD

2024-06-09 13:27 UTC, DexlerXD commented on Content.Server/SS220/Speech/EntitySystems/VulpAccentSystem.cs
> +        );
legit

2024-06-09 13:27 UTC, DexlerXD commented on Content.Server/SS220/Speech/EntitySystems/VulpAccentSystem.cs
> +
static, я думаю, не обязательно...

2024-06-09 13:42 UTC, DexlerXD commented on Content.Server/SS220/Speech/EntitySystems/VulpAccentSystem.cs
> +
@TryHardo7 у тебя щас полетят чеки полетят, т. к. это не закоммитил

2024-06-10 17:50 UTC, DexlerXD requested changes
перенеси что Мира просила

2024-06-11 07:01 UTC, Ady4ik commented
@TryHardo7 
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/141335742/946e8f5e-fee0-4142-9787-6ffe214b3e5a)
Не наблюдаю лора вульп - откуда информация?

2024-06-11 08:33 UTC, TryHardo7 commented
> Не наблюдаю лора вульп - откуда информация?
А откуда ему взяться если для сс14 никто не писал лор? Раса то не раундстартовая пока, я вообще вопрос не понял. В 13 у нас есть нормальный лор вульп если хочешь почитать. 
Если речь про голод то это просто шаг в сторону от рескина хумана, вроде логичный.

2024-06-11 13:35 UTC, DexlerXD commented
@TryHardo7 линтер все еще валяется

2024-06-12 14:11 UTC, DexlerXD approved these changes

2024-06-12 14:40 UTC, merged