No vocal emotes when muzzled
SerbiaStrong-220/space-station-14 pull request #1101
Opened 2024-06-08 21:36 UTC by SkaldetSkaeg

## Описание PR
Увидел на стриме у Никиты, что игроки спокойно кричат эмоционируют, с кляпом во рту.
Это явно баг. Чтобы сделать систему со звуками приглушенными была мысль, но идей особо нету, как это сделать адекватно, так как сама VocalSystem отсосная.

**Медиа**

**Проверки**
- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
 :cl:
 - tweak: персонажи в кляпах больше не воспроизводят эмоции со звуком.

2024-06-08 21:36 UTC, SkaldetSkaeg commented
Нужно будет согласование/возможно какие-то идеи от других людей.

2024-06-08 22:08 UTC, Kit0vras commented
а во сне? я мог плакать, свистеть и тд во сне

2024-06-09 08:15 UTC, SkaldetSkaeg commented
> а во сне? я мог плакать, свистеть и тд во сне

эт, вроде фиксили уже с ноктюрином, но посмотрю.

2024-06-09 08:33 UTC, SkaldetSkaeg commented
> > а во сне? я мог плакать, свистеть и тд во сне
> 
> эт, вроде фиксили уже с ноктюрином, но посмотрю.

бля, охуенно, там чисто на кнопку ограничения

2024-06-09 13:39 UTC, DexlerXD requested changes

2024-06-09 13:39 UTC, DexlerXD commented on Content.Server/Speech/EntitySystems/VocalSystem.cs
> +        if (_entities.TryGetComponent<ReplacementAccentComponent>(uid, out var accentComp) && accentComp.Accent == "mumble")
хардкод убери, сделай через константую переменную лучше где-то в классе

2024-06-09 14:49 UTC, SkaldetSkaeg commented on Content.Server/Speech/EntitySystems/VocalSystem.cs
> +        if (_entities.TryGetComponent<ReplacementAccentComponent>(uid, out var accentComp) && accentComp.Accent == "mumble")
> хардкод убери, сделай через константую переменную лучше где-то в классе

там ещё при сне это работает, я думаю на уровне Чата перенести

2024-06-10 15:03 UTC, DexlerXD requested changes

2024-06-10 15:03 UTC, DexlerXD commented on Content.Shared/SS220/Muzzle/SharedMuzzleSystem.cs
> +    private void OnGotUnequipped(EntityUid uid, MuzzleComponent component, ref ClothingGotUnequippedEvent args)
по новой форме обработки ивентов оформь
т. е.
```
private void Func(Entity<Comp> ent, ref EventClass args) {}
```

2024-06-10 15:03 UTC, DexlerXD commented on Content.Shared/SS220/Muzzle/MuzzledComponent.cs
> +[RegisterComponent, NetworkedComponent()]
```suggestion
[RegisterComponent, NetworkedComponent]
```

2024-06-10 15:03 UTC, DexlerXD commented on Content.Shared/SS220/Muzzle/MuzzleComponent.cs
> +[RegisterComponent, NetworkedComponent()]
```suggestion
[RegisterComponent, NetworkedComponent]
```

2024-06-10 15:03 UTC, DexlerXD commented on Content.Server/Chat/Systems/ChatSystem.cs
> +    [Dependency] private readonly IPrototypeManager _proto = default!;// SS220 No vocal emotes when muzzled
на это пометки можно не ставить

2024-06-11 07:51 UTC, SkaldetSkaeg commented
@DexlerXD ну, крч, я пофиксил всё, кроме переноса в Server. При попытке переноса туда у меня почему-то ломаются голопроекторы атмосские.

2024-06-11 08:29 UTC, DexlerXD commented
>  @DexlerXD ну, крч, я пофиксил всё, кроме переноса в Server. При попытке переноса туда у меня почему-то ломаются голопроекторы атмосские.

я посмотрю сегодня

2024-06-18 08:28 UTC, Alwayswannahunt commented
@SkaldetSkaeg добавь в описание PR следующую строчку - fixes #1181 чтобы github сам закрыл issue при мердже PR.

2024-10-11 05:28 UTC, Kirus59 commented
@SkaldetSkaeg тут как дела?...

2024-10-12 03:12 UTC, SkaldetSkaeg commented
> @SkaldetSkaeg тут как дела?...

![image](https://github.com/user-attachments/assets/99735aef-e48e-44fe-a1ba-98e12cebf3a2)

2024-10-12 04:06 UTC, closed without merging

2024-10-12 04:06 UTC, SkaldetSkaeg commented
надо переписывать, там поменяли конкретно