Game cards fix
SerbiaStrong-220/space-station-14 pull request #1125
Opened 2024-06-13 20:11 UTC by stalengd

## Описание PR
Исправляет [баг игровых карт, которые в "включенном" состоянии просвечивают проводку под полом](https://discord.com/channels/1097181193939730453/1246528566238380122) путём заменты `TrayScannerComponent` в прототипах карт на созданный `ToggleAppearanceOnUseComponent`, который просто меняет внешний вид без остального функционала, который был в `TrayScannerComponent`.

**Медиа**
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/33173619/398c322b-b554-47c8-b0b2-9f4d3842fbb6)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- fix: Игральные карты больше не просвечивают проводку под полами.

2024-06-13 20:26 UTC, DexlerXD requested changes

2024-06-13 20:26 UTC, DexlerXD commented on Content.Shared/SS220/Appearance/ToggleAppearanceOnUseSystem.cs
Обработчики ивентов пишем по новой форме:
`Func(Entity<Comp> entity, ref Event args) {}`

2024-06-14 00:05 UTC, stalengd commented on Content.Shared/SS220/Appearance/ToggleAppearanceOnUseSystem.cs
Исправил

2024-06-14 06:10 UTC, DexlerXD approved these changes
megahorosh

2024-06-14 06:22 UTC, merged