Thermal Vision
SerbiaStrong-220/space-station-14 pull request #1131
Opened 2024-06-14 12:30 UTC by TryHardo7

Добавляет систему термального зрения(и ночное зрение, но оно пока что неразделимо с термальным), показывающего существ сквозь препятствия. 
В данном ПРе добавлены термальные очки и имплант дающий термальное зрение. Оба в аплинке, имплант дороже очков. 

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Lancevrot
- add: Очки термального зрения в аплинк
- add: Имплант термального зрения в аплинк

2024-06-14 12:31 UTC, TryHardo7 commented
https://github.com/SerbiaStrong-220/space-station-14/assets/166473301/14c94e43-5c94-4016-8c2b-0b647bb2aa0a

2024-06-14 13:04 UTC, Kit0vras commented
Half - выглядит прикольно, а Full как-то меее

2024-06-14 13:18 UTC, Kit0vras commented
если в Full вместо переключения освещения просто переключать FOV - то это X-Ray очочки будут. Как бы вроде и видишь через стены, но просто через стены - если за стеной темно, то и у тебя темно будет.

Термалы - это "видит горяченькое", тут упрощённо - существ, так что Full по идее вообще тут не должен быть

Но если сделать в Full переключение Fov, то в конце концов визоры можно будет через рнд или что ещё объединять и будет X-ray (видеть через стены, но просто через стены, а не ночное зрение) + Термалы (видеть подсвеченных сущностей)

2024-06-14 13:21 UTC, Kit0vras commented
Если идти ещё дальше - то в Half можно дополнительно накладывать маску на моба (типа он будет не просто светиться, а светиться красно-оранжевым чем то таким, как при термальном просмотре), разделить маску на два типа - если моб жив - "горячая", а если мёртв - "холодная", синяя.

А также при включении термалов затемнять экран, ограничивая видимость (однако все существа всё равно будут видны)

2024-06-14 13:23 UTC, Kit0vras commented
вроде такого
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/dc4d736b-5392-4c18-85bd-22bb4c820561)

2024-06-14 13:38 UTC, TryHardo7 commented
> Если идти ещё дальше - то в Half можно дополнительно накладывать маску на моба (типа он будет не просто светиться, а светиться красно-оранжевым чем то таким, как при термальном просмотре), разделить маску на два типа - если моб жив - "горячая", а если мёртв - "холодная", синяя.
Я хотел Артура попросить с шейдерами помочь, это будет попозже, я не умею с этим работать. 
Фулл в данный момент вообще не используется, я чуть позже сделаю ещё найтвижен который не сквозь стены без термалов.

2024-06-14 14:24 UTC, DexlerXD commented
@Ady4ik обобрение

2024-06-14 14:43 UTC, DexlerXD requested changes

2024-06-14 14:43 UTC, DexlerXD commented on Content.Server/Mindshield/MindShieldSystem.cs
>  using Content.Server.Administration.Logs;
????

2024-06-14 14:43 UTC, DexlerXD commented on Content.Server/SS220/Thermals/ThermalVisionImplantSystem.cs
> +                EnsureComp<ThermalVisionComponent>(args.Performer);
Предлагаю избавиться от спагетти кода, делая обратные проверки и делая return, 
аналогично со строками 24 и 26.

2024-06-14 14:43 UTC, DexlerXD commented on Content.Shared/SS220/Thermals/SharedThermalVisionSystem.cs
> +    ThermalVisionRemoved(ent);
отступы

2024-06-14 14:43 UTC, DexlerXD commented on Content.Shared/SS220/Thermals/SharedThermalVisionSystem.cs
> +    private void OnThermalMapInit(Entity<ThermalVisionComponent> ent, ref MapInitEvent args)
?

2024-06-14 14:43 UTC, DexlerXD commented on Resources/Prototypes/SS220/Entities/ThermalVisionGoogles/ThermalVisionProto.yml
> +- type: entity
в наших файлах пометки зачем?...

2024-06-14 14:43 UTC, DexlerXD commented on Resources/Prototypes/SS220/Catalog/uplink_catalog.yml
пометки зачем?

2024-06-14 14:43 UTC, DexlerXD commented on Resources/Prototypes/tags.yml
у нас свой файл есть для тегов

2024-06-14 14:43 UTC, DexlerXD commented on Content.Shared/SS220/Thermals/ThermalVisionImplantComponent.cs
> +[DataField, AutoNetworkedField]
отступы

2024-06-14 14:43 UTC, DexlerXD commented on Content.Shared/SS220/Thermals/SharedThermalVisionSystem.cs
> +    protected virtual void ThermalVisionChanged(Entity<ThermalVisionComponent> ent)
?

2024-06-14 14:43 UTC, DexlerXD commented on Content.Shared/SS220/Thermals/SharedThermalVisionSystem.cs
> +    protected virtual void ThermalVisionRemoved(Entity<ThermalVisionComponent> ent)
?

2024-06-14 17:44 UTC, Ady4ik approved these changes

2024-06-25 11:49 UTC, Alwayswannahunt commented on Content.Client/SS220/Thermals/ThermalVisionSystem.cs
> +// Original code github.com/CM-14 Licence MIT, EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
```suggestion
// Original code github.com/CM-14 Licence MIT, All edits under © SS220, EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
```
Правильно подметили, что лицензия написана непонятно, предлагаю такое решение, хотя лучше спросить кого по опытнее.

2024-07-03 13:03 UTC, DexlerXD approved these changes

2024-07-24 18:06 UTC, merged