respriteRatkingAction
SerbiaStrong-220/space-station-14 pull request #1202
Opened 2024-06-19 19:39 UTC by EstKemran

## Описание PR

**Медиа**
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/157578255/4196c4a1-7590-4f81-821c-6f50c318682b)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Мракобес
- tweak: Изменены спрайты action короля крыс

2024-06-19 21:06 UTC, Alwayswannahunt commented on Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml
> +      sprite: SS220/Interface/actions/actions_rat_king.rsi #SS220-resprite-ratking-action
Пупупу... Лучше всё-таки добавь в правильную папку `Actions` вместо той, что с маленькой буквы. 
Хотя бы новое будет идти в папку с правильным наименованием.

2024-06-19 21:16 UTC, EstKemran commented on Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml
> +      sprite: SS220/Interface/actions/actions_rat_king.rsi #SS220-resprite-ratking-action
Правильной папки..  нету.. Да и создавать два аналогичных файла с разным регистром буквы.. Зачем?

2024-06-19 21:23 UTC, Alwayswannahunt commented on Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml
> +      sprite: SS220/Interface/actions/actions_rat_king.rsi #SS220-resprite-ratking-action
> Правильной папки.. нету.. Да и создавать два аналогичных файла с разным регистром буквы.. Зачем?

Потому что тот, кто сделал actions не заметил, что папка должна называться Actions. Однако, да с регистрами уже была проблема.
@DexlerXD, вызываю тебя. У нас в нашей папке с текстурами есть проблема в виде папки `actions`, должно было быть `Actions`. Просить человека исправить название папки и все зависимости всё-таки жестоко, создать папку с правильным регистром и положить туда новые файлы не приведёт к аме ишью снова?

2024-07-04 21:12 UTC, EstKemran commented
@DexlerXD Что мне с этим делать?

2024-07-04 21:13 UTC, DexlerXD commented
> @DexlerXD Что мне с этим сделать?

я всё написал

2024-07-04 21:14 UTC, DexlerXD commented
ой бля, а ревью то не нажалось...

2024-07-04 21:14 UTC, DexlerXD requested changes

2024-07-05 19:48 UTC, DexlerXD approved these changes

2024-07-05 20:04 UTC, merged