Fixing nozzle
SerbiaStrong-220/space-station-14 pull request #1206
Opened 2024-06-20 05:34 UTC by Ady4ik

## Описание PR
Необходимо переписать систему SharedGunSystem.Clothing под спрей и это позволит ему тейкать солюшны из танкера в спрей.

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Ady4
- add: Добавлена возможность пневматическим распылителем высокого давления очищать декали и лужи.
- tweak: Изменено название форсунка-распылитель на пневматический распылитель высокого давления.

2024-06-20 19:07 UTC, Ady4ik commented
@DexlerXD когда будешь смотреть объясню, что нужно сделать, чтобы вся эта ебатория работала
Надо как-то загетить солюшн из танкера на спине и передать его в спрей.
Для этого был создан метод OnGetSolution, который предполагает, что при поднимании ивента мы отдаем ему часть солюшна, который содержится в танкере, а если его нет, то не отдаем (логично).
Сейчас основная ебля осталась как раз таки с тем, что мы не знаем как передать ему юид солюшна и как передать ему количество солюшна, которое требуется для передачи и  вычитания при поднимании ивента.

2024-08-26 21:38 UTC, DexlerXD reviewed
В целом много вопросов, потом в войсе лучше обсудим

2024-10-14 17:21 UTC, UrPrice requested changes

2024-10-14 17:21 UTC, UrPrice commented on Resources/Maps/Nonstations/nukieplanet.yml
> +- proto: SprayNozzle
Здравствуйте, пожалуйста, не трогайте, мне страшно

2024-10-14 17:21 UTC, UrPrice commented on Resources/Maps/Shuttles/dart.yml
> -- proto: WeaponSprayNozzle
И это тоже

2025-03-08 09:43 UTC, closed without merging

2025-03-08 17:05 UTC, UrPrice commented
# П О Р А Ж Е Н И Е