Mime relic
SerbiaStrong-220/space-station-14 pull request #1217
Opened 2024-06-25 11:45 UTC by Alwayswannahunt

## Описание PR

Новый предмет для мима - реликвия, позволяющая ставить стенку в три блока! 
Реликвией может пользоваться только кукла с MimePowersComponent (мим), с ненарушенным обетом.
Минимальный размер стены - один блок, максимальный - три блока (см. скрин 1). 
Стена сдвигается если место занято, а с другой стороны есть свободный тайл (см. скрин 2).
Предмет также будет добавлен в аплинк мимам антагам, но контрабандой считаться не будет (напомню, что если при помощи него нарушается КЗ, то его можно изъять), знания о нём регулируются при помощи IC описания, зависящего от работы. Так как реликвия легальна, то СБ будут знать зачем она и что делает.
Стенка ставится относительно взгляда, поэтому возможны и не "прямые" стены (см. скрин 3).

**Медиа**

![Снимок экрана 2024-06-25 135037](https://github.com/SerbiaStrong-220/space-station-14/assets/25709454/b24e3767-70c3-4130-b490-4bc2300c60cb) ![Снимок экрана 2024-06-25 134450](https://github.com/SerbiaStrong-220/space-station-14/assets/25709454/28a9db00-2777-41fc-9e20-07c3961d6144) ![Снимок экрана 2024-06-25 135825](https://github.com/SerbiaStrong-220/space-station-14/assets/25709454/8fcbb10f-bfc6-4021-be1c-42431ea1f3e5)

**TODO**
- [ ] Сделать название и описание
- [ ] Добавить IC знания для работ
- [ ] Спрайт 

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: AlwyAnri
- add: Добавлена реликвия мимов в аплинк молчуну!

2024-06-25 11:46 UTC, Alwayswannahunt commented
@Ady4ik Довёл идею до реализации, жду от тебя решения - добавлять/не добавлять. Если скажешь, что можно добавлять - буду доделывать и просить спрайтеров нарисовать.

2024-06-25 14:31 UTC, Ady4ik approved these changes
идея прекрасная, нужно довести до релиза

2024-07-03 13:13 UTC, DexlerXD requested changes

2024-07-03 13:13 UTC, DexlerXD commented on Content.Server/SS220/MimeRelic/MimeRelicSystem.cs
> +        private void OnMimeRelicActivate(EntityUid uid, MimeRelicComponent component, ActivateInWorldEvent args)
переписать обработчик ивента по новой форме

2024-07-04 17:52 UTC, DexlerXD approved these changes

2024-07-04 17:52 UTC, merged