Increase automatic rifles spread
SerbiaStrong-220/space-station-14 pull request #1225
Opened 2024-06-26 20:24 UTC by Kirus59

## Описание PR

Увеличил разброс АКМС и Лектера при удержании в 2х руках (1/2 -> 2/12 (min/max)).
Уменьшил точность АКМС и Лектера при непрерывной стрельбе (через `angleIncrease` и `angleDecay`).
При стрельбе одиночными точность будет выше

Сделано это в связи с тем, что АКМС и Лектер обладали такой же точностью, как и снайперская винтовка (Христов), независимо от того, насколько интенсивно ведется стрельба
**Медиа**

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: kirus59
- tweak: Уменьшена точность АКМС и Лектера при непрерывной стрельбе.

2024-06-26 20:36 UTC, Kirus59 commented
@Ady4ik нид ёр опинион

2024-06-29 15:01 UTC, EstKemran approved these changes

2024-07-03 13:17 UTC, DexlerXD requested changes
пометки где?

2024-07-03 13:18 UTC, Kirus59 commented
Уэээээ

2024-07-03 13:44 UTC, DexlerXD approved these changes

2024-07-03 13:44 UTC, merged