InternalAffairs
SerbiaStrong-220/space-station-14 pull request #1232
Opened 2024-06-27 18:27 UTC by EstKemran

## Описание PR
Я устал ждать КЗ и трудовой договор... Я хочу поиграть за департамент внутренних дел... Я хочу, что бы у нас была своя частота... 

**Медиа**
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/157578255/20423f6e-0db0-42d2-84a6-37da778a6445)

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/157578255/47f99110-74a1-41da-bf91-e00b59ff1a82)

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/157578255/c9927ba6-b4df-4b61-91d1-c55468a5a70a)

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/157578255/7c766ae7-a041-4c48-ab0a-bdbda00e0cdd)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Kemran
- add: Добавлен департамент внутренних дел.
- add: Добавлена частота департамента внутренних дел.
- tweak: Офицер "Синий Щит", Агент внутренних дел, Адвокат перенесены в департамент внутренних дел.
- tweak: Изменена форма в копировальном аппарате "Юридический отдел станциии" на "Департамент внутренних дел", с отличным от СБ цветом и бланком.

2024-06-27 19:52 UTC, UrPrice commented
@EstKemran Докрути идейку, предложи перенести Детектива в Департамент Внутренних Дел. Давно хотел такую штуку предложишь, обсуждали еще с Млаффи как-то очень давно в личке. А то в сервисе это конечно круто, но в Департаменте Внутренний Дел ему как-будто есть место.

Ну и PR у тебя сейчас встанет на месте, пока не пройдет этап согласований с ВикиЛороДрочью.

2024-06-27 19:54 UTC, EstKemran commented
> @EstKemran Докрути идейку, предложи перенести Детектива в Департамент Внутренних Дел. Давно хотел такую штуку предложишь, обсуждали еще с Млаффи как-то очень давно в личке. А то в сервисе это конечно круто, но в Департаменте Внутренний Дел ему как-будто есть место.
> 
> Ну и PR у тебя сейчас встанет на месте, пока не пройдет этап согласований с ВикиЛороДрочью.

Он сейчас даже с адучем не согласован :xdd:

2024-07-16 06:05 UTC, FriedrichStrassen commented
Кстати, в тринашке этот канал связи называется "Процессуальный", или в "Процедурный"

2024-08-06 14:51 UTC, EstKemran commented
Завершено, хоть и не в том виде, в котором хотелось бы.

@DexlerXD Он жалуется на то, что департамента нет на маппах? Есть тут еще что-то, что надо доделать

@Ady4ik @gogenych Ревью, и пару вопросов:
1. Получается, АВД у нас глава департамента и может командовать детективом?
2. Детективу нужен МЩ?
3. Время для открытия менять сейчас или потом? Если сейчас, то у нас ближайшие 1-2 недели не будет АВД, ОСЩ и детектива и будут забиты роли адвоката, чтобы наиграть на ДВД

2024-08-06 15:32 UTC, Ady4ik commented
Do not merge.

2024-08-06 18:00 UTC, DexlerXD commented
@EstKemran 
![image](https://github.com/user-attachments/assets/94472d5c-2a2f-400b-a059-72642d4cb7b2)
ты локализацию не написал правильно, а назвал всё прямо в прототипах
оффы теперь запрещают это делать

2024-08-06 18:00 UTC, EstKemran commented
> @EstKemran ![image](https://private-user-images.githubusercontent.com/69513582/355553897-94472d5c-2a2f-400b-a059-72642d4cb7b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Njc1MTEsIm5iZiI6MTcyMjk2NzIxMSwicGF0aCI6Ii82OTUxMzU4Mi8zNTU1NTM4OTctOTQ0NzJkNWMtMmEyZi00MDBiLWEwNTktNzI2NDJkNGNiN2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE4MDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3ZDcxMmFjMjQxNGY5MDM1OGJkZmUxNWUxMTg0NTQ0YTJlOTkzNWYwY2RlOWJjMmM4ZDlhNTdhYWI2NGI2ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.42noVY24sW1HiafjARpRBcyvsnZdaSdtSJPwjMQpLp4) ты локализацию не написал правильно, а назвал всё прямо в прототипах оффы теперь запрещают это делать

Ужас

2024-08-08 20:58 UTC, EstKemran commented
Чеки, вроде, по рофлу упали, так что все готово, наверное

2024-08-11 20:15 UTC, EstKemran commented
@Ady4ik

2024-08-11 20:37 UTC, gogenych commented
А как чат улья попал в ДВД?

2024-08-11 20:40 UTC, Kirus59 commented
> А как чат улья попал в ДВД?

Был замержен раньше

2024-08-11 20:40 UTC, Kirus59 commented
Он же отдельно, а не в двд
![image](https://github.com/user-attachments/assets/6bc2a019-4591-4ecd-b4d1-ad6338caf3d5)

2024-08-12 14:18 UTC, DexlerXD requested changes

2024-08-12 14:18 UTC, DexlerXD commented on Resources/Locale/ru-RU/prototypes/access/accesses.ftl
> +id-card-access-level-lawyer = Внутренние дела
добавить пометку

2024-08-12 14:18 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/electronics/door_access.ftl
> +    .suffix = Внутренние дела, Закрыт
добавить пометку

2024-08-12 14:18 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/electronics/door_access.ftl
> +    .suffix = Служба безопасности/Внутренние дела, Закрыт
добавить пометки

2024-08-12 14:18 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/airlocks/access.ftl
> +    .suffix = Внутренние дела, Закрыт
добавить пометки

2024-08-12 14:18 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/airlocks/access.ftl
> +    .suffix = Служба безопасности/Внутренние дела, Закрыт
добавить пометки

2024-08-12 14:18 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/airlocks/access.ftl
> +    .suffix = Внутренние дела, Закрыт
добавить пометки

2024-08-12 14:18 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/airlocks/access.ftl
> +    .suffix = Служба безопасности/Внутренние дела, Закрыт
добавить пометки

2024-08-12 14:18 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/airlocks/access.ftl
> +    .suffix = Внутренние Дела, Закрыт
добавить пометки

2024-08-12 14:18 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/doors/windoors/windoor.ftl
> +    .suffix = Служба Безопасности/Внутренние Дела, Закрыт
добавить пометки

2024-08-12 14:18 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/wallmounts/switch.ftl
> +    .suffix = Внутренние дела
добавить пометки

2024-08-12 14:18 UTC, DexlerXD commented on Resources/Prototypes/Corvax/Roles/Jobs/Command/iaa.yml
> +  supervisors: job-supervisors-magistrate
добавить пометки

2024-08-12 14:18 UTC, DexlerXD commented on Resources/Prototypes/Roles/Jobs/Civilian/detective.yml
> +  supervisors: job-supervisors-IAA
добавить пометки

2024-08-14 15:55 UTC, DexlerXD commented on Resources/Prototypes/Corvax/Roles/Jobs/Command/iaa.yml
> +  supervisors: job-supervisors-magistrate
@EstKemran ?

2024-08-14 15:57 UTC, DexlerXD approved these changes

2024-08-14 15:59 UTC, DexlerXD commented on Resources/Prototypes/Roles/Jobs/Civilian/detective.yml
> +  supervisors: job-supervisors-IAA
@EstKemran ?

2024-08-14 16:59 UTC, DexlerXD approved these changes

2024-08-14 17:00 UTC, DexlerXD commented
@EstKemran чини чеки, там скорее всего скрытый симмвол есть

2024-08-16 17:07 UTC, closed without merging