Ss220 telepathy
SerbiaStrong-220/space-station-14 pull request #1233
Opened 2024-06-27 19:14 UTC by NailMinnigalin

## Описание PR

Добавил канал телепатии. Поддерживает программные анонсы, возможность иметь разные каналы телепатии, возможность помечать пользователей которые могут и не могут отправлять сообщения в канал.

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

- add: Телепатический канал общения. :cl: DisappearedCat

2024-06-27 19:20 UTC, NailMinnigalin commented on Content.Server/SS220/Telepathy/TelepathySystem.cs
> +            "chat-manager-server-wrap-message",
Тут нужно гейм-дизайнерское решение. Как форматировать телепатическое сообщение?

2024-06-28 00:21 UTC, SkaldetSkaeg commented
@DexlerXD как думаешь, телепатия в чате должна быть или по кнопке?

2024-06-28 02:20 UTC, UrPrice commented
> @DexlerXD как думаешь, телепатия в чате должна быть или по кнопке?

В 13 она через чат сделана просто

2024-07-03 13:18 UTC, DexlerXD requested changes
Порешать конфликты, проверить, чтобы всё работало после мержа апстрима в эту ветку

2024-07-05 19:50 UTC, DexlerXD commented
@NailMinnigalin на будущее, чейнджлог должен выглядить как-то так:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/69513582/f006eb14-12e3-4cb2-84a6-19ccb9ec28a5)

А также тут чейнджлог вовсе не обязателен, т. к. в игре это на данный момент не используется. Майндслейв я потом прикручу к телепатии

2024-07-05 19:51 UTC, DexlerXD approved these changes

2024-07-05 19:54 UTC, merged