new-security-status
SerbiaStrong-220/space-station-14 pull request #1247
Opened 2024-06-29 17:56 UTC by EstKemran

## Описание PR

**Медиа**
_Не могу предоставить из-за интернета_

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [c] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Kemran
- add: Добавлено 4 новых статуса в криминалистическую консоль: Патруль, Подозреваемый, Заключенный, Вышел из заключения.
- add: Добавлена локализация иконкам криминалистической консоли.

2024-06-29 18:28 UTC, EstKemran commented
![Content Client_nbpatGoyaj](https://github.com/SerbiaStrong-220/space-station-14/assets/157578255/2b2187de-e856-49c5-b32d-d4a14aaf6772)

2024-06-29 18:36 UTC, EstKemran commented
Active status: Need a review

@Ady4ik @Kit0vras

2024-06-29 18:42 UTC, Ady4ik approved these changes
Задумка отличная, только нужно будет скинуть инфу буренке перед мерджем, чтобы игроки понимали, какие статусы за какие отвечают.
В идеале сдалать статью в справочнике в игре касательно этих статусов. Если запаришься и сделаешь - плюс вайб будет

2024-06-30 15:49 UTC, TheArturZh commented
Лишний белый пиксель
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/16546901/44f6bc47-427e-42b2-a587-277a448b086f)

2024-06-30 15:59 UTC, EstKemran commented
> Лишний белый пиксель ![image](https://private-user-images.githubusercontent.com/16546901/344477602-44f6bc47-427e-42b2-a587-277a448b086f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NjMxODUsIm5iZiI6MTcxOTc2Mjg4NSwicGF0aCI6Ii8xNjU0NjkwMS8zNDQ0Nzc2MDItNDRmNmJjNDctNDI3ZS00MmIyLWE1ODctMjc3YTQ0OGIwODZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE1NTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNjQyYWI1NzNkMDQ4NGU4YjQ4NDM4MTBiNmFhZjU3YjViYTAyZTliMWVhYWJkYjI0NGZmOTFmYzlkYWRmNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kTAw9R8PowR00WhiI1SKpt7kErl6M7xsDZy1iasV13g)

Оно убрано в кормите "fix" :gonnacryhampter:

2024-07-01 06:38 UTC, FriedrichStrassen commented
Не вижу конечно особо смысла в переводе на русский язык. Некоторые иконки не соответствуют золотому сечению из-за этого, оставляя пустые места. 
Смысла менять пиктограммки особо нет. Ну как бы и POHUY. 

Меня больше волнует статус "заключённый" и "вышел из заключения", нужна возможность настраивать статус у куклы через SHIFT+CLICK, тогда эти нововведения будут прекрасно смотреться(как и в тринашке, лол)

2024-07-01 12:33 UTC, EstKemran commented
> Не вижу конечно особо смысла в переводе на русский язык. Некоторые иконки не соответствуют золотому сечению из-за этого, оставляя пустые места. Смысла менять пиктограммки особо нет. Ну как бы и POHUY.
> 
> Меня больше волнует статус "заключённый" и "вышел из заключения", нужна возможность настраивать статус у куклы через SHIFT+CLICK, тогда эти нововведения будут прекрасно смотреться(как и в тринашке, лол)

Перевод был сделан из-за жалоб игроков. 

К кодерам :(

Вышел гайдбук, со справочным материалом криминалистической консоли, посмотри на нее. Оцени ее как мейнер вардена

2024-07-01 16:08 UTC, EstKemran commented
> @EstKemran перенеси статусы на вики, чтобы игроки могли получать оттуда информацию оттуда. Через Burenka.

Уже передал Буренке. 

Я не особо творческий в этом плане (придумывание текста), @Kit0vras дай ревью на спрайты, орфографические ошибки, и логическую состовляющую текста

2024-07-01 16:12 UTC, EstKemran commented
> @EstKemran перенеси статусы на вики, чтобы игроки могли получать оттуда информацию оттуда. Через Burenka.

Там, кстати, статусы следить и подозреваемый выполняют одинаковую(?) функцию, или просто различия в смысле минимальные. По механикам различие в том, что статус "подозреваемый" отображается в чате СБ. Как думаешь, стоит их оставить, или одно из них убрать?

2024-07-01 20:31 UTC, Kit0vras requested changes

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +  Консоль криминальных записей доступна в отделе безопасности каждой станции, она служит для отслеживания и управления криминальной историей и стутусом любого члена экипажа.
```suggestion
  Консоль криминальных записей доступна в отделе безопасности каждой станции, она служит для отслеживания и управления криминальной историей и статусом любого члена экипажа.
```

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +  Любой может открыть UI консоли, но только те, кто имеет доступ "Служба безопасности", могут изменять что-либо
```suggestion
  Любой может открыть интерфейс консоли, но только те, кто имеет доступ "Служба безопасности", могут ей пользоваться.
```

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +  UI консоли состоит из следующих элементов:
```suggestion
  Интерфейс консоли состоит из следующих элементов:
```

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +  - Список всех членов экипажа в манифесте, при выборе одной из записей отображается уголовная запись члена экипажа. Список фильтруется строкой поиска, поэтому убедитесь, что она пуста, если вам нуже
```suggestion
  - Список всех членов экипажа в манифесте. При выборе одной из записей отображается уголовная запись члена экипажа. Список фильтруется строкой поиска, поэтому убедитесь, что она пуста, если вам нужен полный список!
```

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +    - Посмотреть информацию о членах экипажа, связанной с безопасностьью, например их имени, отпечатков пальцев и ДНК.
```suggestion
    - Посмотреть информацию о членах экипажа, например их имя, отпечатки пальцев и ДНК.
```

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +    - Изменить статус между [color=gray]"Без статуса"[/color], [color=red]"В розыске"[/color], [color=#a4885c]"Заключенный"[/color] и т.д.. При установке статуса "В розыске", "Увольнение", "Подозрева
```suggestion
    - Изменить статус между [color=gray]"Без статуса"[/color], [color=red]"В розыске"[/color], [color=#a4885c]"Заключённый"[/color] и т.д. При установке статуса "В розыске", "Увольнение", "Подозреваемый" и "Казнить" будет предложено указать причину.
```

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +    - Открыть окно "Криминальные записи", чтоьы проверить или изменить её.
```suggestion
    - Открыть окно "Криминальные записи", чтобы проверить или изменить их.
```

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +  Криминальные записи содержат список преступлений, совершенных человеком, и может быть изменено различными способами:
```suggestion
  Криминальные записи содержат список преступлений, совершенных экипажем, и могут быть изменены различными способами:
```

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +    - Автоматически, просто установив для кого-то статус "Заключенный". В причинах будет указано "Заключенный:", чтобы было легко увидеть автоматические записи.
```suggestion
    - Автоматически, просто установив для кого-то статус "Заключённый". В причинах будет указано "Заключённый", чтобы было легко увидеть автоматические записи.
```

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +    - Добавление новой строки, нажав "Сменить статус" и написав что-нибудь в поле ввода. При добавлении записи не забудьте указать ПРЕСТУПЛЕНИЕ и ПРИГОВОР члена экипажа. Консоль автоматически укажет
```suggestion
    - Добавление новой строки, нажав "Сменить статус" и написав что-нибудь в поле ввода. При добавлении записи не забудьте указать ПРЕСТУПЛЕНИЕ и НАКАЗАНИЕ члена экипажа. Консоль автоматически укажет время после начала смены, так что вам не придётся этого делать!
```

Забавно же, не?

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +    - Выберите строку нежелательной записи и нажмите "Удалить", чтобы удалить ее. Это отличный способ сохранить записи в чистоте после выходоок клоуна с украденными ID картами.
```suggestion
    - Выберите строку нежелательной записи и нажмите "Удалить", чтобы удалить ее. Это отличный способ сохранить записи в чистоте после выходок клоуна с украденными ID картами.
```

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +    - [color=gray]Без статуса[/color]: Член экипажа чист как белый лист.
```suggestion
    - [color=gray]Без статуса[/color]: Член экипажа чист, как белый лист.
```

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +    - [color=#6699ff]Следить[/color]: Члену экипажа с этом статусом стоит отноститься с особой осторожностью, и следить за каждым его шагом.
```suggestion
    - [color=#6699ff]Следить[/color]: Члену экипажа с этом статусом стоит относиться с особой осторожностью и следить за каждым его шагом.
```

2024-07-01 20:31 UTC, Kit0vras commented on Resources/ServerInfo/Guidebook/Security/CriminalRecords.xml
> +    - [color=cyan]Подозреваемый[/color]: Член экипажа с этим статус подозревается в каком-то правонарушении. Статус отобразиться в частоте СБ.
```suggestion
    - [color=cyan]Подозреваемый[/color]: Член экипажа с этим статусом подозревается в каком-то правонарушении. Статус отобразится в частоте СБ.
```

2024-07-01 20:44 UTC, EstKemran commented
Благодарю ❤

2024-07-03 13:25 UTC, DexlerXD approved these changes

2024-07-03 13:47 UTC, merged

2024-07-09 03:16 UTC, Dmitry2777 commented
Было бы круто оффам предложить.

2024-07-09 05:21 UTC, DexlerXD commented
> Было бы круто оффам предложить. 

прошу заметить, что система криминальных записей у нас своя