Corpses equipment fix
SerbiaStrong-220/space-station-14 pull request #1265
Opened 2024-07-01 17:30 UTC by Kirus59

## Описание PR

Добавил новые (по факту возврат старых, до лодаута которые были) `startingGear` для ролей, в которых спавнятся неопознанные трупы.
Сделано это для того, чтобы трупы спавнились в присущей для своей должности базовой экипировке (а то сейчас они спавнятся даже без комбинезона).

Также добавил парамедика, бригмедика и пилота в спавнеры трупов.
Перенес детектива в сервис, а также убрал возможность спавна трупа со шмотками ОЦК (тем более что они старые, обсудим с гогенычем нужно ли добавлять ОЦК в этот спавнер)
**Медиа**

(На видео ОЦК в новых шмотках т.к. я записывал его, когда тестил это)
https://github.com/SerbiaStrong-220/space-station-14/assets/145689588/6cfc5659-9127-40ac-ab10-e1c96055cda7

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: kirus59
- fix: Исправлена экипировка, в которую одеты неопознанные трупы

2024-07-01 18:05 UTC, gogenych commented
по этому трекеру 
https://discord.com/channels/1097181193939730453/1257283179513905202/1257283179513905202

2024-07-03 13:31 UTC, DexlerXD requested changes

2024-07-03 13:31 UTC, DexlerXD commented on Resources/Prototypes/SS220/Roles/Jobs/standartGear.yml
напиши в шапке файла для чего ты вернул эти прототипы

2024-07-03 16:59 UTC, Kirus59 commented
А че чеки упали, эти прототипы существуют же

2024-07-04 17:53 UTC, DexlerXD commented
> А че чеки упали, эти прототипы существуют же

эти прототипы были удалены после апстрима

2024-07-04 18:16 UTC, Kirus59 commented
Бляяя, ну их возвращать уже не буду, будут тогда с пустыми спавниться.
Чуть позже изменю

2024-07-04 21:43 UTC, Kirus59 commented
Уэээээ и чоу тесты упали.....

2024-07-04 22:20 UTC, DexlerXD approved these changes

2024-07-04 22:20 UTC, merged