Fix Eclipse and Emergency Shuttle
SerbiaStrong-220/space-station-14 pull request #1271
Opened 2024-07-02 10:52 UTC by NightmareStalker

## Описание PR

Внесены изменения в карту Эклипс и ее шаттл. Заливаю по просьбе Rtmfool(Отвечает за поддержку карты)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Rtmfool
- add: Добавлена записка в заброшенную комнату инженеров.
- add: На кухню добавлен ящик с коровой.
- add: В барменскую добавлена обучающая книга.
- add: Добавлено освещение в коридоре РНД.
- remove: Убраны окна выходящие в тех. тоннели.
- fix: Перемещены атмос элементы в комнате гейта.
- fix: Почтовые блоки кухни и гидропоники переименованы и функционируют.
- fix: Заваренная двустволка бармена теперь точно не стреляет.
- fix: Кнопочки в психушке теперь рабочие.
- fix: В кабинете ОСЩ заменены пустые имплантеры трекеров на полные.
- fix: Исправлены шлюзы в тех. тоннелях.
- fix: Пополнено снаряжение пилотов СБ.
- fix: Переименованы факсы.
- fix: Поправлены отсылки.
- fix: Поправлены предметы в помещениях.
- fix: Исправлены шлюзы в барной зоне.

2024-07-02 13:56 UTC, UrPrice reviewed
- 'потёртый берет "М.Техасова"'
- Факс приемной АВД?
- Почему изменены цвета труб?

2024-07-02 14:01 UTC, UrPrice requested changes
1. Изменить 
```
name: 'потёртый берет Техасова'
```
На
```
name: 'потёртый берет "М. Техасова"'
```

2. Зачем нам факс "приемной АВД" и факс "АВД". Насколько я помню, в приемной факса не было. Были факсы "Магистрат", "АВД", "Адвокаты". Также факс "Буткемпа", тоже не нужен, можно убрать.

3. В связи с чем изменены цвета труб.
```
'#DC4840FF' на '#FF1212FF'
'#415EDAFF' на '#0335FCFF'
```

Увы VSC не захотел через плагин отсылать ревью, поэтому через сайт

2024-07-02 15:26 UTC, NightmareStalker commented
> 1. Изменить
> 
> ```
> name: 'потёртый берет Техасова'
> ```
> 
> На
> 
> ```
> name: 'потёртый берет "М. Техасова"'
> ```
> 
> 2. Зачем нам факс "приемной АВД" и факс "АВД". Насколько я помню, в приемной факса не было. Были факсы "Магистрат", "АВД", "Адвокаты". Также факс "Буткемпа", тоже не нужен, можно убрать.
> 3. В связи с чем изменены цвета труб.
> 
> ```
> '#DC4840FF' на '#FF1212FF'
> '#415EDAFF' на '#0335FCFF'
> ```
> 
> Увы VSC не захотел через плагин отсылать ревью, поэтому через сайт

поправил

2024-07-03 17:36 UTC, UrPrice commented
Не исправлено: https://discord.com/channels/1158128815311171638/1238857831336247306/1256237395821461535 
Ожидайте апстрима, после апстрима выкатывайте коммит с исправлением internal - external привязок шлюзов, и самых различных привязок кнопок. 

Не вижу чтобы было поправлено и это: https://discord.com/channels/1158128815311171638/1238857831336247306/1256920165904416831 

До момента апстрима у вас еще время, чтобы сделать это и последующие заметки:
https://discord.com/channels/1158128815311171638/1238857831336247306/1257684236006326272

Ставьте в PR [WIP], снимайте галку с того, что вы все сделали и дорабатывайте карту. Я изначально говорил, что спешить некуда, ваш первый патч карты должен выйти после апстрима.

2024-07-20 10:53 UTC, UrPrice requested changes
Проговорили в войсе

2024-07-20 11:07 UTC, UrPrice approved these changes
arpvd

2024-07-20 11:08 UTC, UrPrice commented
@DexlerXD Можно мержить

2024-07-20 11:34 UTC, DexlerXD approved these changes

2024-07-20 11:34 UTC, merged