[WiP] Dark Reaper consume fix
SerbiaStrong-220/space-station-14 pull request #1272
Opened 2024-07-02 19:08 UTC by Kirus59

## Описание PR

Добавлен компонент, который не позволяет Жнецу поглотить энтити с этим компонентом.
Однако если за этот энтити зайдет игрок (гостроль) - то жнец сможет поглотить его после убийства.

Сделано это для предотвращения абуза культистов, при игре на Жнеце на карте Eclipse.
Также добавил культистам пару мобов во враждебных (Дракон и Ксеносы), чтобы ИИ их атаковала при виде.
**Медиа**

Под контролем ИИ:

https://github.com/SerbiaStrong-220/space-station-14/assets/145689588/23482275-e094-42cb-b33e-06cd88075c4a

После взятия гостроли:

https://github.com/SerbiaStrong-220/space-station-14/assets/145689588/61d6632d-18de-4422-907a-bd7ef8992e80

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: kirus59
- tweak: Тёмный жнец больше не может поглощать культистов, пока за них не зайдут игроки

2024-07-02 19:17 UTC, Kirus59 commented
Need Help:
Т.к. компонент находится в `Contant,Shared` - то он накидывается и на клиент и на сервер.
Однако при взятии гостроли - он удаляется только на сервере.
Как сделать так, чтобы он удалялся на клиенте, когда как метод, отвечающий за взятие гостроли, находится в `Content.Client`?

2024-07-02 19:49 UTC, Surani1 commented
@TheArturZh

2024-07-21 17:54 UTC, Kirus59 commented
@DexlerXD Да, теперь работает как нужно, спасибо

2024-07-21 22:33 UTC, DexlerXD requested changes

2024-07-21 22:33 UTC, DexlerXD commented on Resources/Prototypes/ai_factions.yml
> +  #Add miss hostiles end
а вот это - в отдельный пр

2024-07-22 18:32 UTC, DexlerXD approved these changes

2024-07-22 18:34 UTC, merged