Resprites clothes - chaplain, journalist, lawyer
SerbiaStrong-220/space-station-14 pull request #1273
Opened 2024-07-02 20:36 UTC by NightmareStalker

## Описание PR

Респрайт одежды священика, журналиста и адвоката. 

**Медиа**

20 штук спрайтов, пощадите, пустите без медиа...

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено белое одеяние священника 
- add: Добавлен красный костюм журналиста
- tweak: Изменены спрайты одежды священника
- tweak: Изменены спрайты одежды журналиста
- tweak: Изменены спрайты одежды адвоката

2024-07-05 19:51 UTC, NightmareStalker commented
> This pull request has conflicts, please resolve those before we can evaluate the pull request.

та жеванный ты крот

2024-07-05 19:58 UTC, NightmareStalker commented
куда жмать, что делать, я не понимаю...

2024-07-06 19:19 UTC, DexlerXD requested changes
пометки на файлах вне наших папок обязательны

2024-07-06 20:48 UTC, NightmareStalker commented
рано или поздно я перестану забывать о пометках... простите пожалуйста... 
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/162575884/556525d3-2051-4fe6-9a97-2a024895cf80)

2024-07-06 20:59 UTC, DexlerXD approved these changes

2024-07-06 20:59 UTC, merged