Agent card chat fix
SerbiaStrong-220/space-station-14 pull request #1274
Opened 2024-07-02 23:07 UTC by 13lackHawk

## Описание PR
Фиксит ошибку из-за которой не меняется цветное отображение должности в чате при ее смене с помощью агентской карты(вне зависимости от названия профессии и значка для визора цвет должности всегда как у пассажира)
Фикс работает только при условии если название профессии написано правильно(значок визора все еще не влияет на отображение в чате).

**Медиа**
Было:
![1](https://github.com/SerbiaStrong-220/space-station-14/assets/26493665/27e953a8-e557-4aee-ba24-f7122204bb0c)

Стало:
![2](https://github.com/SerbiaStrong-220/space-station-14/assets/26493665/21a1253c-7139-40f7-9635-a04a2fa0320d)

**Проверки**
- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
🆑 13lackHawk
- fix: Исправлено некорректное цветное отображение профессии у агентской ID карты при отправке сообщений в рацию. Для корректного отображения цвета фейковой должности не забывайте писать существующее название профессии.

2024-07-03 13:39 UTC, DexlerXD requested changes

2024-07-03 13:39 UTC, DexlerXD commented on Content.Server/Access/Systems/PresetIdCardSystem.cs
> +        foreach (var department in departments.Where(department => department.Roles.Contains(jobCode)))
тут бы пометку

2024-07-03 13:39 UTC, DexlerXD commented on Content.Shared/Access/Systems/SharedIdCardSystem.cs
> +        Dirty(uid, id);
тут тоже пометку бы

2024-07-03 13:39 UTC, DexlerXD commented
и вообще, сразу можно готовить к пушу оффам, т. к. мы все багфиксы стараемся им тоже мержить

2024-07-03 14:29 UTC, 13lackHawk commented
> и вообще, сразу можно готовить к пушу оффам, т. к. мы все багфиксы стараемся им тоже мержить

У оффов нет системы цветного чата насколько мне известно.

2024-07-03 15:38 UTC, 13lackHawk commented on Content.Shared/Access/Systems/SharedIdCardSystem.cs
> +        Dirty(uid, id);
Там над ним уже и сверху и снизу есть SS220 Job-Color, уверен что еще надо?

2024-07-03 15:40 UTC, 13lackHawk commented on Content.Server/Access/Systems/PresetIdCardSystem.cs
> +        foreach (var department in departments.Where(department => department.Roles.Contains(jobCode)))
✔

2024-07-04 18:04 UTC, DexlerXD approved these changes

2024-07-04 18:06 UTC, merged