FractWar Ebent UpdateV0.6
SerbiaStrong-220/space-station-14 pull request #1275
Opened 2024-07-03 10:46 UTC by Kirus59

## Описание PR

Некоторые изменения по ивенту:
Добавлен свой `npcFaction` для каждой фракции, также он может сменяться при помощи `JobIconChanger` (спасибо ReeZer2 за это)
Добавлены турели для каждой фракции.
Добавил `JobIconChanger` в шкафы каждого ивентового главы.
Добавил разрывную гранату в РПС каждой ивентовой роли
**Медиа**

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

no cl

2024-07-03 12:05 UTC, Kirus59 commented
@DexlerXD мержнуть бы в ближайшие дни.....

2024-07-03 13:41 UTC, DexlerXD requested changes

2024-07-04 06:47 UTC, Kirus59 commented
Пока не мержить, никитка мб успеет сделать шлюзы

2024-07-04 20:57 UTC, Kirus59 commented
@DexlerXD
![BITmeeerge](https://github.com/SerbiaStrong-220/space-station-14/assets/145689588/5e70990b-58d4-46cf-9152-22bf4df19927)

2024-07-04 21:08 UTC, DexlerXD approved these changes

2024-07-04 21:09 UTC, merged