Vehicles fix
SerbiaStrong-220/space-station-14 pull request #1276
Opened 2024-07-03 16:15 UTC by 13lackHawk

## Описание PR
Фикс данного ишшуе - #1184 .
Машины теперь взрываются при контакте с лавой, нанося не критический но достаточно солидный урон водителю.
Также при въезде в сухожилия урон теперь наносится как машине, так и водителю.

**Проверки**

- [х] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [х] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [х] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
 :cl: 13lackHawk
fix: Машины теперь взрываются при контакте с лавой, нанося не критический но достаточно солидный урон водителю.
fix: Исправлен баг при котором водителю не наносился урон от сухожилий, если он ездил по ним на машине.

2024-07-04 18:03 UTC, DexlerXD requested changes

2024-07-04 18:03 UTC, DexlerXD commented on Content.Server/Tiles/LavaSystem.cs
> +using Content.Shared.Damage.Systems; // SS220-vehicles-go-boom-in-lava
юзинги и депенденси не обязательно помечать

2024-07-04 18:03 UTC, DexlerXD commented on Content.Server/Tiles/LavaSystem.cs
> +        if(HasComp<VehicleComponent>(args.Tripper))
```suggestion
        if (HasComp<VehicleComponent>(args.Tripper))
```

2024-07-04 18:03 UTC, DexlerXD commented on Content.Server/Tiles/LavaSystem.cs
> +                _damageable.SetAllDamage(args.Tripper, damageablecomp, 600); // Hardcoded number but its enough to destroy any vehicle rn
лучше убрать хардкод хотя бы в отдельную константу

2024-07-04 18:03 UTC, Ady4ik commented
@13lackHawk если хочешь прикрепить issue для ПР - пиши в названии ПРа фразу "fix #1184 ". Тогда автоматически сюда прикрепится.

2024-07-04 18:04 UTC, Ady4ik commented on Content.Server/Tiles/LavaSystem.cs
> +using Content.Shared.Damage.Systems; // SS220-vehicles-go-boom-in-lava
депенденси лучше помечать, т.к если депенденси не используется, то оно, по моему, не выдаст информации о не используемом депенденси. А юзинги уже пометит.
Поправь - если не прав

2024-07-04 21:16 UTC, DexlerXD commented on Content.Server/Tiles/LavaSystem.cs
> +using Content.Shared.Damage.Systems; // SS220-vehicles-go-boom-in-lava
> депенденси лучше помечать, т.к если депенденси не используется, то оно, по моему, не выдаст информации о не используемом депенденси. А юзинги уже пометит. Поправь - если не прав

депенденси всё равно в визуалке помечаются неиспользуемые

2024-07-09 14:20 UTC, 13lackHawk commented on Content.Server/Tiles/LavaSystem.cs
> +using Content.Shared.Damage.Systems; // SS220-vehicles-go-boom-in-lava
Не думаю что лишние комментарии в коде когда-нибудь кому-нибудь навредили.

2024-07-09 18:08 UTC, DexlerXD commented on Content.Server/Tiles/LavaSystem.cs
> +                _damageable.SetAllDamage(args.Tripper, damageablecomp, 600); // Hardcoded number but its enough to destroy any vehicle rn
> Хардкод есть хардкод, пусть он и выглядит как говно но свою функцию исполняет, а мое первое правило: "если работает - не трогай".

я всё же настаиваю на том, что хотя бы выше локальную переменную сделать

2024-07-13 12:20 UTC, 13lackHawk commented on Content.Server/Tiles/LavaSystem.cs
> +                _damageable.SetAllDamage(args.Tripper, damageablecomp, 600); // Hardcoded number but its enough to destroy any vehicle rn
> > Хардкод есть хардкод, пусть он и выглядит как говно но свою функцию исполняет, а мое первое правило: "если работает - не трогай".
> 
> я всё же настаиваю на том, что хотя бы выше локальную переменную сделать

✔

2024-07-13 19:44 UTC, DexlerXD approved these changes

2024-07-13 19:47 UTC, merged