Seniors again
SerbiaStrong-220/space-station-14 pull request #1306
Opened 2024-07-07 10:49 UTC by spo9k

## Описание PR
Инструктора

**Медиа**

**Проверки**

- [+] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [+] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [+] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [+] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: spo9k

- add: Добавлены роли ведущих!

2024-07-07 13:12 UTC, TheArturZh commented
Карты в CRLF, нужно исправить
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/16546901/f1334977-bd42-4f3a-8888-d98af4f6bed9)

2024-07-08 10:43 UTC, Kirus59 commented
Судя по изменениям в файлах карт он уже их поставил

2024-07-08 10:47 UTC, UrPrice commented
> Error Message: There is no spawnpoints for SeniorEngineer, SeniorPhysician, SeniorResearcher, SeniorOfficer on Frankenstein. Assert.That(jobs, Is.Empty)
> 
> @UrPrice ему нужно спавнпоинты поставить. Шо думаешь?

Пусть уберет изменения карт и не будут падать феилы о картах. Я это указал изначально.

2024-07-08 10:48 UTC, UrPrice commented
В PR не должно быть изменений карт.

2024-07-08 13:00 UTC, spo9k commented
Именно в самих картах убрать? Точки спавна? Или убрать еще в ss220/maps еще их роли?

2024-07-08 13:31 UTC, spo9k commented
@DexlerXD Надо займеджить, чтоб я или мапперы, поставили спавнпоинты. Как объяснили тут.

2024-07-08 13:45 UTC, UrPrice commented
> Именно в самих картах убрать? Точки спавна? Или убрать еще в ss220/maps еще их роли?

просто оставь ямлы карты неизмененными. Выйдут патчи карт с апстримом, появятся спавны у сеньоров. Пока, так как в прототипе будут - будут летать с терминала.

2024-07-08 14:28 UTC, spo9k commented
> > Именно в самих картах убрать? Точки спавна? Или убрать еще в ss220/maps еще их роли?
> 
> просто оставь ямлы карты неизмененными. Выйдут патчи карт с апстримом, появятся спавны у сеньоров. Пока, так как в прототипе будут - будут летать с терминала.

окей тогда в yml карт оставлю.

2024-07-08 14:53 UTC, spo9k commented
Крч в yml, серавно пишет ошибку, то что точек спавна нет, так что лучше там после апстрима все добавить.

2024-07-08 15:51 UTC, UrPrice commented
> Крч в yml, серавно пишет ошибку, то что точек спавна нет, так что лучше там после апстрима все добавить.

Хорошо

2024-07-08 19:48 UTC, DexlerXD requested changes
пометок вне наших файлов - ноль
хоть даже оффы их завтра вернут сами, но изменения ты уже сделал
playtimetracker вообще можно было бы вынести в наши файлы

2024-07-09 13:17 UTC, spo9k commented
Ну пометки сделал то что наше изменения вне наших файлах, playtimetracker перенёс.

2024-07-09 18:14 UTC, DexlerXD requested changes
лицензии на наших спрайтах - `EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt`
копирайт - `Sprited by Ваш ник (Github) for SS220` или `Sprited by Ваш ник (Discord) for SS220`
[источник](https://discord.com/channels/1158128815311171638/1224030042384760942/1240724832228999261)

2024-07-09 18:14 UTC, DexlerXD commented on Resources/Textures/Interface/Misc/job_icons.rsi/meta.json
> +			"name": "SeniorService"
указание лицензии выше + форматирование

2024-07-09 18:14 UTC, DexlerXD commented on Resources/Textures/Objects/Devices/pda.rsi/meta.json
> +	  "name": "pda-seniorservice"
указание лицензии выше + форматирование

2024-07-09 18:14 UTC, DexlerXD commented on Resources/Textures/Objects/Misc/id_cards.rsi/meta.json
> +	  "name": "idseniorservice"
указание лицензии выше + форматирование

2024-07-09 18:14 UTC, DexlerXD commented on Resources/Textures/SS220/Clothing/Head/Hats/seniorsercap.rsi/meta.json
> +  "copyright": "spo9k\u0026D1nazewwr",
исправить лицензию/копирайт

2024-07-09 18:14 UTC, DexlerXD commented on Resources/Textures/SS220/Clothing/Uniforms/Jumpsuit/senior_service.rsi/meta.json
> +  "copyright": "spo9k\u0026D1nazewwr",
исправить лицензию/копирайт

2024-07-19 15:56 UTC, spo9k commented on Resources/Textures/Objects/Misc/id_cards.rsi/meta.json
> +	  "name": "idseniorservice"
тут уже указана лицензия наша

2024-07-19 16:41 UTC, spo9k commented
Что еще надо? @DexlerXD

2024-07-19 16:43 UTC, DexlerXD commented on Resources/Textures/SS220/Clothing/Uniforms/Jumpskirt/senior_service.rsi/meta.json
> +  "copyright": "spo9k\u0026D1nazewwr",
@spo9k тут неверно указано

2024-07-19 16:43 UTC, DexlerXD commented on Resources/Textures/SS220/Clothing/Uniforms/Jumpsuit/senior_service.rsi/meta.json
> +  "copyright": "spo9k\u0026D1nazewwr",
@spo9k тут неверно указано

2024-07-19 16:44 UTC, DexlerXD commented on Resources/Textures/SS220/Clothing/Head/Hats/seniorsercap.rsi/meta.json
> +  "copyright": "spo9k\u0026D1nazewwr",
@spo9k тут неверно указано

2024-07-19 16:44 UTC, DexlerXD commented on Resources/Textures/Interface/Misc/job_icons.rsi/meta.json
> +			"name": "SeniorService"
@spo9k 
![image](https://github.com/user-attachments/assets/9c104a48-ad87-4028-98f2-c86ce2bdeb25)
не вижу тут ss220 и/или наших ников нигде

2024-07-19 16:45 UTC, DexlerXD commented
@spo9k забей на пинги, у меня гитхаб чут-чут ебнулся

2024-07-19 16:48 UTC, DexlerXD requested changes

2024-07-19 16:48 UTC, DexlerXD commented on Resources/Textures/SS220/Clothing/Uniforms/Jumpskirt/senior_service.rsi/meta.json
> +  "copyright": "Sprited by Ваш ник @dinazewwr for SS220",
```suggestion
  "copyright": "Sprited by dinazewwr (Discord) for SS220",
```

2024-07-19 16:48 UTC, DexlerXD commented on Resources/Textures/SS220/Clothing/Uniforms/Jumpsuit/senior_service.rsi/meta.json
> +  "copyright": "Sprited by Ваш ник @dinazewwr for SS220",
```suggestion
  "copyright": "Sprited by dinazewwr (Discord) for SS220",
```

2024-07-19 16:48 UTC, DexlerXD commented on Resources/Textures/Interface/Misc/job_icons.rsi/meta.json
> +    "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
ну так тоже нельзя, по факту, тут две лицензии должно быть, иначе мы так все спрайты себе присываиваем

2024-07-19 16:48 UTC, DexlerXD commented on Resources/Textures/SS220/Clothing/Head/Hats/seniorsercap.rsi/meta.json
> +  "copyright": "Sprited by Ваш ник @dinazewwr for SS220",
```suggestion
  "copyright": "Sprited by dinazewwr (Discord) for SS220",
```

2024-07-19 16:59 UTC, spo9k commented
Понял не пингую

2024-07-19 17:01 UTC, spo9k commented on Resources/Textures/Interface/Misc/job_icons.rsi/meta.json
> +    "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
Хм, ну могу нашу и их лицензию ебнуть.

2024-07-19 17:04 UTC, spo9k commented on Resources/Textures/Interface/Misc/job_icons.rsi/meta.json
> +    "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
Ну я как посмотрел, у нас уже стоит эта лицензия в pda, тип такая же. Вроде же не предъявляли нам

2024-07-19 18:58 UTC, DexlerXD approved these changes

2024-07-19 18:58 UTC, DexlerXD commented
![image](https://github.com/user-attachments/assets/c8aee123-e273-4f63-ab19-a03b9579eb35)
и на будущее: это пишется так `[x]`

2024-07-19 18:59 UTC, merged