Chat msg and emotes fix
SerbiaStrong-220/space-station-14 pull request #1309
Opened 2024-07-07 16:43 UTC by ReeZer2

## Описание PR
Фичи с борды (fix Уникальность сообщений, fix Запрет спама в чат)
Теперь строчить одинаковые месседжи в чат можно, но каждые 2 секунды. 
Так же у каждой расы был добавлен кулдаун в 5 секунд между эмоутами.

**Медиа**

https://github.com/SerbiaStrong-220/space-station-14/assets/63300653/9975f1b2-621f-406a-b8b3-2c2800628873

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: ReeZii
- add: Добавлена уникальность сообщений в чате
- add: Добавлен 5 секундый кулдаун всем расам на эмоции

2024-07-07 23:44 UTC, DexlerXD requested changes

2024-07-07 23:44 UTC, DexlerXD commented on Content.Server/Chat/Systems/ChatSystem.cs
> +    public TimeSpan ChatMsgCooldown = TimeSpan.FromSeconds(2); //ss220 chat unique fix
сделать `readonly` ?

2024-07-07 23:44 UTC, DexlerXD commented on Content.Server/Chat/Systems/ChatSystem.cs
> +        if (message.Length > MaximumLengthMsg && LastMessage != null && LastMessage == message && currentTime - LastChatMsgTime < ChatMsgCooldown)
страх

2024-07-07 23:44 UTC, DexlerXD commented on Content.Server/Chat/Systems/ChatSystem.cs
> +        LastMessage = message;
а не будет ли это так работать, что оно на весь сервер будет записывать одно сообщение? это же не отдельный компонент обрабатывается, тем более, это всё на сервере. боюсь предположить, что одно сообщение на весь сервер будет, как и таймер.

2024-07-08 04:33 UTC, closed without merging

2024-07-08 12:52 UTC, ReeZer2 commented on Content.Server/Chat/Systems/ChatSystem.cs
> +        if (message.Length > MaximumLengthMsg && LastMessage != null && LastMessage == message && currentTime - LastChatMsgTime < ChatMsgCooldown)
sry for shitcode :(