new battle maps
SerbiaStrong-220/space-station-14 pull request #1312
Opened 2024-07-07 21:01 UTC by Surani1

## Описание PR
Нужно переделать спрайты карт именно в игре, спрайтерам работка, буду ждать. А пока так насрал инверсией и сжатым фото

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
no cl no fun

2024-07-07 23:46 UTC, DexlerXD requested changes

2024-07-07 23:46 UTC, DexlerXD commented on Resources/Prototypes/SS220/Entities/Structures/Furniture/tacmap.yml
> +  parent: FrankensteinTacmap
прикольно наследуется
можно было бы тогда абстрактный прототип сделать, а потом все мапы наследовать от него

2024-07-08 10:32 UTC, Surani1 commented on Resources/Prototypes/SS220/Entities/Structures/Furniture/tacmap.yml
> +  parent: FrankensteinTacmap
> прикольно наследуется можно было бы тогда абстрактный прототип сделать, а потом все мапы наследовать от него

аче)

2024-07-08 14:05 UTC, TTTomaTTT commented
![Eclipse](https://github.com/SerbiaStrong-220/space-station-14/assets/155060886/f68704de-354d-4761-9764-8f3c9304ce20)
![Nox](https://github.com/SerbiaStrong-220/space-station-14/assets/155060886/66e7a606-4f24-48dc-8abe-97763198f245)
![Axioma](https://github.com/SerbiaStrong-220/space-station-14/assets/155060886/2f1f5609-3e49-419f-b614-876bc384d180)

2024-07-08 19:51 UTC, DexlerXD approved these changes

2024-07-08 19:51 UTC, merged