Map NukeOutpost v0.2
SerbiaStrong-220/space-station-14 pull request #1318
Opened 2024-07-08 18:36 UTC by Surani1

## Описание PR
Фиксы старых багов, связанных с поломкой маппинга от оффов.

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Surani
- fix: Исправлены баги карты аванпоста nukeops

2024-07-08 18:50 UTC, Surani1 commented
ну кто бы сомневался

2024-07-08 18:58 UTC, UrPrice requested changes
```
    - type: DeviceLinkSource
      linkedPorts:
        invalid:
        - Pressed: DoorBolt
```
Удалить шобы бралось от прототипа, пупупу

2024-07-08 18:59 UTC, Surani1 commented
> ```
>     - type: DeviceLinkSource
>       linkedPorts:
>         invalid:
>         - Pressed: DoorBolt
> ```
> 
> Удалить шобы бралось от прототипа, пупупу
да это кнопки, я их вырезал с корнями

2024-07-14 20:15 UTC, Surani1 commented
анлак

2024-07-14 20:15 UTC, closed without merging