fix: Исправлено кол-во предметов для кражи у вора
SerbiaStrong-220/space-station-14 pull request #1329
Opened 2024-07-09 15:43 UTC by ReeZer2

## Описание PR
Исправлено кол-во предметов для кражи у вора (fix: https://github.com/SerbiaStrong-220/space-station-14/issues/1324)

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: ReeZii
- fix: Исправлено кол-во предметов для кражи у вора

2024-07-09 18:16 UTC, DexlerXD approved these changes

2024-07-09 18:17 UTC, DexlerXD commented
@Ady4ik @Surani1 кол-во для цели согласовано?

2024-07-09 19:10 UTC, Ady4ik requested changes
Эти чейнджи необходимы, т.к. 2 печати максимально легко добыть: буквально у клоуна и у мима есть печати. Поэтому минимальное количество 4, максимальное - 7.

2024-07-09 19:10 UTC, Ady4ik commented on Resources/Prototypes/Objectives/thief.yml
> +    minCollectionSize: 3 # ss220 5 -> 3 max
```suggestion
    minCollectionSize: 4 # ss220 5 -> 4 min 
```

2024-07-09 19:10 UTC, Ady4ik commented on Resources/Prototypes/Objectives/thief.yml
> +    maxCollectionSize: 5 # ss220 15 -> 5 max
```suggestion
    maxCollectionSize: 7 # ss220 15 -> 7 max
```

2024-07-11 18:33 UTC, DexlerXD approved these changes

2024-07-14 09:29 UTC, Ady4ik approved these changes

2024-07-14 19:58 UTC, merged