Cryo migration
SerbiaStrong-220/space-station-14 pull request #1402
Opened 2024-07-20 13:49 UTC by MiraHell

## Описание PR
Переход на крио оффов. Перенос наших фич для крио. Fix #1395 

- [x] Телепортация в крио
- [x] Крио в манифесте
- [x] Вещи из крио
- [x] Миграция
- [x] Чистка кода

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
no cl for now

2024-07-20 16:43 UTC, UrPrice commented
@MiraHell Ку
Скажи потом какие криоподы будут активные под обычное понимание "крио" и какие под "лейт джоины", чтобы у меня была возможность после прокатки этого пиара, быстро на карты пролить крио апдейты, заменив поды.

2024-07-21 16:25 UTC, DexlerXD requested changes

2024-07-21 16:25 UTC, DexlerXD commented on Content.Server/SS220/TeleportAFKtoCryoSystem/TeleportAFKtoCryoSystem.cs
> +        var portal = Spawn("CryoStoragePortal", Transform(target).Coordinates);
хардкод бы убрать

2024-07-21 16:54 UTC, DexlerXD commented on Content.Shared/CCVar/CCVars.cs
> +            CVarDef.Create("afk.teleport_to_cryo", 1800f, CVar.SERVERONLY);
а я думал там в минтуха типа хдд

2024-07-21 17:15 UTC, DexlerXD approved these changes

2024-07-21 17:19 UTC, merged