Thermals fix
SerbiaStrong-220/space-station-14 pull request #1474
Opened 2024-07-28 17:56 UTC by Alwayswannahunt

## Описание PR

Исправил известные баги с термалами, плюс провёл небольшой рефактор оверлея для дальнейшего расширения :cat: 

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: AlwyAnri
- tweak: Изменено "термальное" зрение!
- fix: Исправлена видимость "термальным" зрением!

2024-07-28 23:34 UTC, DexlerXD requested changes

2024-07-28 23:34 UTC, DexlerXD commented on Content.Client/SS220/Overlays/IgnoreLightVisionOverlay.cs
> +                    return true;
а можно не надо?

2024-07-29 11:14 UTC, Alwayswannahunt commented on Content.Client/SS220/Overlays/IgnoreLightVisionOverlay.cs
> +                    return true;
О, хотел драфтануть, потому что нашёл ещё что поправить, повезло повезло

2024-07-30 13:18 UTC, DexlerXD requested changes

2024-07-30 13:18 UTC, DexlerXD commented on Content.Server/SS220/Thermals/ThermalVisionImplantSystem.cs
> +            if (HasComp<ThermalVisionComponent>(args.Performer))
ну ебана
перенеси всë под &&

2024-07-30 13:18 UTC, DexlerXD commented on Content.Server/SS220/Thermals/ThermalVisionImplantSystem.cs
> +            if (!TryComp<ThermalVisionComponent>(args.Performer, out var thermalVision))
и тут тоже

2024-07-31 11:06 UTC, Alwayswannahunt commented on Content.Server/SS220/Thermals/ThermalVisionImplantSystem.cs
> +            if (HasComp<ThermalVisionComponent>(args.Performer))
строчкой ниже else, ты мне предлагаешь написать 4 отдельных if?

2024-08-01 21:12 UTC, DexlerXD requested changes

2024-08-01 21:12 UTC, DexlerXD commented on Content.Client/SS220/Overlays/IgnoreLightVisionOverlay.cs
> +            if (target.Comp.CurrentState == MobState.Dead)
```suggestion
        if (states.Contains(MobState.Dead) &&
        states.Contains(MobState.Alive) &&
        target.Comp.CurrentState == MobState.Dead)
```

2024-08-01 22:10 UTC, DexlerXD approved these changes

2024-08-01 22:12 UTC, merged