More Directional windows
SerbiaStrong-220/space-station-14 pull request #1476
Opened 2024-07-28 20:13 UTC by NightmareStalker

## Описание PR

С какого-то времени нельзя больше строить в одном тайле несколько направленных окон, также при маппинге текстуры окон накладываются друг на друга, что выглядит достаточно не очень. Добавляю рабочие(не пропускают существ и газы) варианты направленных окон одним объектом.
Также изменил текстуру урановых окон под общий вид остальных.

**Медиа**

![image](https://github.com/user-attachments/assets/4a39924c-3066-4908-949d-b7f44a4d16ce)
![image](https://github.com/user-attachments/assets/3f7dfdc5-900d-45f5-913f-c7ff49562788)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены разные виды направленных окон из существующих стекол, как объекты, так и в крафт
- tweak: Изменены текстуры уранового и укрепленного уранового стекол под общий стиль

2024-07-28 21:10 UTC, NightmareStalker commented
я не понимаю, что оно хочет...
![image](https://github.com/user-attachments/assets/28cade59-02b9-414c-92ed-3be069e0b91f)

2024-07-28 21:24 UTC, Kirus59 commented
Стоимость стекла (строения) ниже, чем стоимость материалов, получаемых при его разборке.
Т.е. например у тебя UraniumReinforcedWindowDirectionalO имеет StaticPrice = 70.
А при разборке получаешь 4 ед. SheetRUGlass1, у каждого из которых StaticPrice = 50, следовательно 4*50 = 200
![image](https://github.com/user-attachments/assets/132b2c69-a5c8-48b4-af9b-a2a7167450e1)

2024-07-28 23:49 UTC, EstKemran approved these changes

2024-07-28 23:52 UTC, EstKemran commented
Со спрайтами все отлично. В мете лишние пробелы, но это скорее косметика

2024-07-29 20:34 UTC, DexlerXD requested changes
вот бы поправить отступы в мете...

2024-07-30 02:06 UTC, NightmareStalker commented
> вот бы поправить отступы в мете...

где? перед clock и plasma window?...

2024-07-30 13:19 UTC, DexlerXD commented on Resources/Textures/SS220/Structures/Windows/directionals/angular.rsi/meta.json
> +	  },
вот это тоже

2024-07-30 16:08 UTC, NightmareStalker commented
я вот вообще не понял, что это и как это было, учитывая, что в вск оно выглядело нормально, а тут... эээ...
![image](https://github.com/user-attachments/assets/47fb9621-02f9-4efe-9778-217f7cb00c96)
но, вроде, поправил...

2024-07-31 08:41 UTC, DexlerXD reviewed
![image](https://github.com/user-attachments/assets/580187ee-12ec-40ae-8f8e-f30d92cf09d2)
а че по названиям?

2024-07-31 08:48 UTC, NightmareStalker commented
> ![image](https://private-user-images.githubusercontent.com/69513582/353760389-580187ee-12ec-40ae-8f8e-f30d92cf09d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTU5MjQsIm5iZiI6MTcyMjQxNTYyNCwicGF0aCI6Ii82OTUxMzU4Mi8zNTM3NjAzODktNTgwMTg3ZWUtMTJlYy00MGFlLThmOGUtZjMwZDkyY2YwOWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA4NDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZmFmYWQ3NTk4MTczZGI3YWY5ZTM0ODg5MzQwZDJkNDk5ZWUxNjA0NTA1YjVlOTNlYTZhNzljMjc3NjgwYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.smtDIUFTJVSH__BWf8oHcVBrgZEna7OGjwWtLsTG5oQ) а че по названиям?

кринжа сделал, не придумав ничего лучше... исправить?

2024-07-31 08:50 UTC, DexlerXD commented
> > ![image](https://private-user-images.githubusercontent.com/69513582/353760389-580187ee-12ec-40ae-8f8e-f30d92cf09d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTU5MjQsIm5iZiI6MTcyMjQxNTYyNCwicGF0aCI6Ii82OTUxMzU4Mi8zNTM3NjAzODktNTgwMTg3ZWUtMTJlYy00MGFlLThmOGUtZjMwZDkyY2YwOWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA4NDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZmFmYWQ3NTk4MTczZGI3YWY5ZTM0ODg5MzQwZDJkNDk5ZWUxNjA0NTA1YjVlOTNlYTZhNzljMjc3NjgwYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.smtDIUFTJVSH__BWf8oHcVBrgZEna7OGjwWtLsTG5oQ) а че по названиям?
> 
> кринжа сделал, не придумав ничего лучше... исправить?

лучше да...

2024-07-31 08:51 UTC, NightmareStalker commented
> > > ![image](https://private-user-images.githubusercontent.com/69513582/353760389-580187ee-12ec-40ae-8f8e-f30d92cf09d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTU5MjQsIm5iZiI6MTcyMjQxNTYyNCwicGF0aCI6Ii82OTUxMzU4Mi8zNTM3NjAzODktNTgwMTg3ZWUtMTJlYy00MGFlLThmOGUtZjMwZDkyY2YwOWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA4NDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZmFmYWQ3NTk4MTczZGI3YWY5ZTM0ODg5MzQwZDJkNDk5ZWUxNjA0NTA1YjVlOTNlYTZhNzljMjc3NjgwYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.smtDIUFTJVSH__BWf8oHcVBrgZEna7OGjwWtLsTG5oQ) а че по названиям?
> > 
> > 
> > кринжа сделал, не придумав ничего лучше... исправить?
> 
> лучше да...

окей

2024-07-31 09:06 UTC, NightmareStalker commented
только заметил, что нет локализации, хотя помню, что делал... бляхамуха...

2024-08-01 09:18 UTC, DexlerXD approved these changes

2024-08-01 09:18 UTC, merged