Добавление новых звуковых эффектов для "падения" предметов p.1 (Weapons)
SerbiaStrong-220/space-station-14 pull request #1489
Opened 2024-07-30 00:39 UTC by MIXnikita

## Описание PR

Задача: Улучшить и разнообразить звуковое оформление проекта;

- Добавлены звуки падения для объектов типа "Weapons";
- Добавлены звуки в прототипы всех объектов типа "Weapons" (Огнестрел, гранаты, лазеры, мили оружия, бросаемые предметы);

**Медиа**

Демонстрация на некоторых образцах:
[https://youtu.be/R8tLVBJsC3Y](url)

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl: MIXnikita
- add: Добавлены новые звуки падения для всего (почти) оружия!

2024-07-30 13:22 UTC, DexlerXD commented
![Screenshot_2024-07-30-16-21-25-082-edit_com.github.android.jpg](https://github.com/user-attachments/assets/6bc350d8-29ea-411f-a13c-7502798ed16c)

в следующий раз не забудь раскомментить

2024-07-30 13:23 UTC, DexlerXD requested changes
добавить пометки на наши изменения вне наших папок

2024-07-30 16:06 UTC, MIXnikita commented
> добавить пометки на наши изменения вне наших папок

Добавил комменты в прототипы + добавил ещё больше звуков

2024-07-31 08:39 UTC, DexlerXD commented
@MIXnikita 
![image](https://github.com/user-attachments/assets/3e80c978-656b-4fb7-9e8a-d0d00ccc8ee5)
у тебя тут прототипы немного сломались

2024-08-21 17:18 UTC, Ady4ik commented
@MIXnikita hello?

2024-08-22 16:42 UTC, MIXnikita commented
> @MIXnikita hello?

A? Da?

2024-09-01 18:31 UTC, DexlerXD approved these changes

2024-09-01 18:31 UTC, merged