[WiP] Add random voices for borgs
SerbiaStrong-220/space-station-14 pull request #1505
Opened 2024-08-02 19:32 UTC by Kirus59

## Описание PR

Добавлена возможность делать список из определенных ТТС голосов, из которого будет рандомно выбираться 1 голос при инициализации TTSComponent.

Боргам добавлен свой список голосов.
**Медиа**

При спавне борга:

https://github.com/user-attachments/assets/a1b73f55-247a-43ca-b526-c92fac22c42a

При сборке борга:

https://github.com/user-attachments/assets/d14438e9-5e1c-44aa-b85b-8ef9ca171f96

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: kirus59
- add: Боргам добавлена выдача рандомного ТТС (из своего списка) при их спавне/сборке

2024-08-02 19:36 UTC, Kirus59 commented
Жду еще пока @gogenych ответит по поводу списка голосов для боргов.

2024-08-04 18:46 UTC, Kirus59 commented
@DexlerXD Перезапусти тесты пж

2024-08-04 21:22 UTC, DexlerXD requested changes

2024-08-04 21:22 UTC, DexlerXD commented on Content.Server/SS220/TTS/TTSSystem.cs
> +    private void OnInit(Entity<TTSComponent> ent, ref ComponentInit args)
так оно на все энтити с ттсом будем рандомизировать?

2024-08-04 22:28 UTC, Kirus59 commented on Content.Server/SS220/TTS/TTSSystem.cs
> +    private void OnInit(Entity<TTSComponent> ent, ref ComponentInit args)
> так оно на все энтити с ттсом будем рандомизировать?

Нет, `RandomVoicesList` по дефолту = null, и в `SetRandomVoice` есть проверка на то, что если `RandomVoicesList is null` то замена не выполняется.

2024-08-04 22:30 UTC, Kirus59 commented on Content.Server/SS220/TTS/TTSSystem.cs
> +    private void OnInit(Entity<TTSComponent> ent, ref ComponentInit args)
Будет рандомизировать только если в прототипе в `TTSComponent` указать параметр `randomVoicesList` с ссылкой на прототип списка голосов.

2024-08-05 18:46 UTC, DexlerXD approved these changes

2024-08-05 23:18 UTC, merged