Add Multifaze gun
SerbiaStrong-220/space-station-14 pull request #1581
Opened 2024-08-13 11:13 UTC by Kirus59

## Описание PR

Добавление системы для мультифазового энергетического пистолеета

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: kirus59
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-08-14 13:30 UTC, Kirus59 commented
@DexlerXD Глянь пожалуйста как будет время, и скажи что нужно исправить/изменить.

2024-08-14 15:19 UTC, DexlerXD requested changes

2024-08-14 15:19 UTC, DexlerXD commented on Content.Shared/Weapons/Ranged/Systems/BatteryWeaponFireModesSystem.cs
> +                return;
обязательно?

2024-08-14 15:19 UTC, DexlerXD commented on Content.Shared/Weapons/Ranged/Systems/BatteryWeaponFireModesSystem.cs
>              {
лишняя осталась

2024-08-14 15:19 UTC, DexlerXD commented on Content.Shared/Weapons/Ranged/Systems/BatteryWeaponFireModesSystem.cs
> +            {
лишняя

2024-08-14 15:19 UTC, DexlerXD commented on Content.Shared/Weapons/Ranged/Systems/BatteryWeaponFireModesSystem.cs
в целом исправить форматирование в местах, где я отписал

2024-08-14 16:19 UTC, Kirus59 commented on Content.Shared/Weapons/Ranged/Systems/BatteryWeaponFireModesSystem.cs
Слушай, а `BatteryWeaponFireModeSystem` в `Content.Client` оставлять в общей папке или лучше перенести в SS220?

2024-08-14 16:20 UTC, Kirus59 commented on Content.Shared/Weapons/Ranged/Systems/BatteryWeaponFireModesSystem.cs
> +                return;
В целом нет, если не хитскан и не энтити то просто пустая строка будет (тогда и режим по идее не должен поменяться).
Чуть позже изменю тогда.

2024-08-14 16:34 UTC, DexlerXD commented on Content.Shared/Weapons/Ranged/Systems/BatteryWeaponFireModesSystem.cs
> Слушай, а `BatteryWeaponFireModeSystem` в `Content.Client` оставлять в общей папке или лучше перенести в SS220?



> Слушай, а `BatteryWeaponFireModeSystem` в `Content.Client` оставлять в общей папке или лучше перенести в SS220?

код наш -> 220

2024-08-15 08:14 UTC, DexlerXD commented
@Kirus59 в принципе норм, что-то еще будешь доделовать?

2024-08-15 11:26 UTC, Kirus59 commented
> @Kirus59 в принципе норм, что-то еще будешь доделовать?

Сделал обновление `Apperance` при смене режима (через `UpdateShots` ибо при выборе режима не обновлялось количество выстрелов (в компоненте), а в этом методе заодно и обновляется `Apperance`).

Хотел бы еще сделать обновление UI количества зарядов (которое около руки отображается).
Я пытался через `UpdateAmmoCount` и пытался отдельно вызывать `UpdateAmmoCounterEvent`, однако в обоих случаях обновления UI не происходит......
Хотя вот при выстреле и при взятии оружия в руку - UI обновляется (как я понял через метод `UpdateAmmoCount`, однако у меня этим методом не вышло обновить UI).

2024-08-15 18:10 UTC, Kirus59 commented
Пока раскомменчу чтобы чеки глянуть.
Жду еще спрайт ЭМИ проджектайла от Кемрана.

2024-08-15 21:00 UTC, Kirus59 commented
Не придумал как сделать этот апдейт иначе, чем через `AppearanceChangeEvent`.
В теории можно написать новый ивент и райзить его в `UpdateShots` (или в `UpdateAppearance`), но я подумал что через `AppearanceChangeEvent` будет проще (ну и не факт что способом выше будет работать как нужно).

2024-08-15 21:28 UTC, Kirus59 commented
Заодно и чеки перезапусти пожалуйста

2024-08-16 07:44 UTC, DexlerXD requested changes

2024-08-16 07:44 UTC, DexlerXD commented on Content.Client/SS220/Weapons/Ranged/Systems/BatteryWeaponFireModesSystem.cs
> +    private void OnFireModeChange(EntityUid uid, BatteryWeaponFireModesComponent component, ChangeFireModeEvent args)
подписку переписать под новый вид

2024-08-16 07:44 UTC, DexlerXD commented on Content.Client/Weapons/Ranged/Systems/GunSystem.Battery.cs
> +    private void OnAppearanceChange(EntityUid uid, BatteryAmmoProviderComponent component, ref AppearanceChangeEvent args)
подписку переписать под новый вид

2024-08-16 07:44 UTC, DexlerXD commented on Content.Server/Weapons/Ranged/Systems/GunSystem.Battery.cs
> +    private void OnFireModeChange(EntityUid uid, BatteryAmmoProviderComponent component, ref ChangeFireModeEvent args)
подписку переписать под новый вид

2024-08-16 07:44 UTC, DexlerXD commented on Content.Shared/Weapons/Ranged/Components/BatteryWeaponFireModesComponent.cs
> +    public string? FireModeName;
реализация такая себе, лучше через enum переделай

2024-08-16 07:44 UTC, DexlerXD commented on Content.Shared/Weapons/Ranged/Components/BatteryWeaponFireModesComponent.cs
> +    public string? MagState;
также через enum

2024-08-16 15:41 UTC, Kirus59 commented
@DexlerXD перезапусти чеки пж

2024-08-16 18:58 UTC, DexlerXD approved these changes

2024-08-17 08:53 UTC, FriedrichStrassen commented
Понимаете же, как долго он будет заряжаться от обычного зарядинка
вечность блять

2024-08-17 08:59 UTC, Kirus59 commented
> Понимаете же, как долго он будет заряжаться от обычного зарядинка вечность блять

50 секунд, за столько же и обычный станнер заряжается

2024-08-17 09:01 UTC, Kirus59 commented
И лазерный карабин стольео же заряжается

2024-08-18 10:52 UTC, Ady4ik commented
Замерджу сам, когда сделаем статью на вики

2024-08-19 08:29 UTC, FriedrichStrassen commented
@Ady4ik Ну я сказал бурёнке, пусть поручит таск кому-нибудь

2024-08-19 09:47 UTC, FriedrichStrassen commented
@Ady4ik https://wiki14.ss220.club/index.php?title=%D0%9E%D1%81%D0%BE%D0%B1%D0%BE_%D1%86%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5_%D0%BF%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82%D1%8B

Добавлено. Ещё в СРП охраны накинули уже

2024-08-19 15:39 UTC, merged