mindslave removed from loneop uplink
SerbiaStrong-220/space-station-14 pull request #1638
Opened 2024-08-22 08:42 UTC by Oxygen033

## Описание PR

Убран имплант майндслейв из аплинка Одиночного Ядерного Оперативника. [issue](https://github.com/SerbiaStrong-220/space-station-14/issues/1635)

**Медиа**

![image](https://github.com/user-attachments/assets/880680aa-7cd7-4081-ab6f-9cf0211287c3)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl:
- remove: Убран имплант подчинитель разума из аплинка одиночного ЯО

2024-08-22 18:52 UTC, Ady4ik requested changes

2024-08-22 18:52 UTC, Ady4ik commented on Resources/Prototypes/SS220/Catalog/uplink_catalog.yml
> +          - LoneOpsUplink
```suggestion
          - LoneOpsUplink # SS220 mindslave fix
```

2024-08-22 19:45 UTC, DexlerXD commented on Resources/Prototypes/SS220/Catalog/uplink_catalog.yml
> +          - LoneOpsUplink
> 

работу отбираешь :xylipizdish:

2024-08-23 05:21 UTC, Ady4ik approved these changes

2024-08-23 05:21 UTC, merged