Pet E-N
SerbiaStrong-220/space-station-14 pull request #1641
Opened 2024-08-22 13:05 UTC by TTTomaTTT

## Описание PR

Питомец для робототехников по имени Е-Н
**Медиа**

![image](https://github.com/user-attachments/assets/05fa7e42-6700-455c-97ad-6de7f2730c22)

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

2024-08-22 19:53 UTC, DexlerXD requested changes
+ решить мерж конфликт

2024-08-22 19:53 UTC, DexlerXD commented on Resources/Locale/ru-RU/interaction/interaction-popup-component.ftl
> +petting-success-robot = Вы гладите { $target } по его металлической голове.
перенести в 220

2024-08-22 19:53 UTC, DexlerXD commented on Resources/Locale/en-US/interaction/interaction-popup-component.ftl
> +petting-success-robot = You pet {THE($target)} on {POSS-ADJ($target)} metal head.
перенести в 220

2024-08-22 19:53 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
> +ent-MobEN = Е-Н
перенести в 220

2024-08-22 20:27 UTC, gogenych commented
Как читать его имя? Он Е-Ха или И-Аш?

2024-08-25 10:38 UTC, Ady4ik requested changes
Исправить упавшие чеки (стектрейс внутри чеков есть) 
Внести последнюю правку от декслера

2024-08-25 10:38 UTC, Ady4ik commented on Resources/Textures/SS220/Mobs/Pets/E-N/e-n.rsi/meta.json
> +      "name": "E-N",
```suggestion
```
```
RSI валидатор ругается на этого E-N, так как файла с таким названием в папке нет.

2024-08-25 10:38 UTC, Ady4ik commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
Удалить все изменения в данном файле, так как падает чек из-за задвоения.
![image](https://github.com/user-attachments/assets/818432d0-7d6e-4c5d-83a3-2fb832c2cb31)

2024-08-26 07:58 UTC, Ady4ik requested changes
Добавь чейнджлог 

:cl: TTTomaTTT
- add: Добавлен питомец Е-Н для робототехников.

2024-08-26 09:01 UTC, merged