upd Eclipse
SerbiaStrong-220/space-station-14 pull request #1648
Opened 2024-08-24 10:43 UTC by Rtmfool

## Описание PR

- Добавлены камеры.
- Проведен атмос для животных.
- Изменены полы в КПП СБ на станции.
- Исправлены ошибки в документах.
- Добавлена консоль робототехника.
- Добавлены Cutter`s.
- Каркасы стыковочных шлюзов заменены на рабочие стыковочные шлюзы.
- Починен мусоропровод в химии меда.
- На мостик добавлены ставни.

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:

- tweak: Изменена карта ИСН "Затмение"

2024-08-24 11:14 UTC, UrPrice requested changes
Удалить Инвалидов
Поменять наименование бумаги с печатью СЕ о ремонте
```
      stampedBy:
      - stampedColor: '#C69B17FF'
        stampedName: Инженер
```
Добавить маршрутизатор камер [Общий]
Поставить Y образную утилизационную трубу перед аварийным коридором вместо трубы маршрутизатора

2024-08-24 11:17 UTC, UrPrice commented
Не мерджить пока не поправит

2024-08-25 06:07 UTC, UrPrice commented
Пересмотреть все интеркомы на станции. Проверить их текущую работу и необходимость в соответствии с доступными частотами связи. Общедоступный командный расположить около стойки ГП недалеко, чтобы ГП мог контролировать его визуально. 

Остальные по базе переставить, чтобы не было командного доступа на каждом интеркоме.

2024-08-25 06:14 UTC, UrPrice commented
Убрать консоль связи с конференц-комнаты на мостике (заменить на что-то менее ценное)

2024-09-05 16:36 UTC, UrPrice approved these changes

2024-09-05 17:07 UTC, DexlerXD approved these changes

2024-09-05 17:07 UTC, merged