Add syringe gun
SerbiaStrong-220/space-station-14 pull request #1653
Opened 2024-08-25 13:26 UTC by Kirus59

## Описание PR

Добавлен шприцемёт, способный стрелять шприцами с различными инъекциями!
 
Ввиду отсутствия некоторых необходимых компонентов для ввода инъекции из шприца при его полёте - то в системах `SyringeGunSystem` они добавляются, а при промахе или при извлечении шприца из тела - эти компоненты удаляются.

Пока без спрайтов(
**Медиа**

https://github.com/user-attachments/assets/74f5b121-7dc1-4901-9015-32a4be78cd80

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: kirus59
- add: Добавлено шприцемёт!

2024-08-25 14:41 UTC, Kirus59 commented
@DexlerXD Глянь пж по коду

2024-08-26 21:38 UTC, DexlerXD requested changes

2024-08-26 21:38 UTC, DexlerXD commented on Content.Shared/SS220/SyringeGun/SyringeGunComponent.cs
> +    public float SyringeRemovalTime = 1f;
переделать через `TimeSpan`

2024-08-26 21:38 UTC, DexlerXD commented on Content.Shared/SS220/SyringeGun/TemporarySyringeComponentsComponent.cs
очень стремная идея
особенно момент с их удалением
почему бы поле с компонентами просто не перенести в `SyringeGunComponent`? создавать лишние компоненты такое себе

2024-08-26 21:54 UTC, Kirus59 commented on Content.Shared/SS220/SyringeGun/SyringeGunComponent.cs
> +    public float SyringeRemovalTime = 1f;
В компоненте `EmbeddableProjectileComponent` переменная `RemovalTime` имеет тип `float`.
`SyringeRemovalTime` используется лишь для замены `RemovalTime` при эншуре этого компонента, имеет ли смысл делать разные типы данных и разве будет это вообще работать?

2024-08-26 22:05 UTC, Kirus59 commented on Content.Shared/SS220/SyringeGun/TemporarySyringeComponentsComponent.cs
В таком случае же для каждого шприца будет общий набор компонентов для удаления, а не индивидуальный (что в целом некритично, т.к. все шприцы не имеют этих компонентов), не?
Или ты предлагаешь через `Dictionary` сделать?

В любом случае возникает вопрос, как триггерить удаление этих компонентов, после вытаскивания шприца из тела или промаха?....

2024-08-26 22:09 UTC, DexlerXD commented on Content.Shared/SS220/SyringeGun/SyringeGunComponent.cs
> +    public float SyringeRemovalTime = 1f;
> В компоненте `EmbeddableProjectileComponent` переменная `RemovalTime` имеет тип `float`. `SyringeRemovalTime` используется лишь для замены `RemovalTime` при эншуре этого компонента, имеет ли смысл делать разные типы данных и разве будет это вообще работать?
`EmbeddableProjectileComponent` оффовское?

2024-08-26 22:10 UTC, DexlerXD commented on Content.Shared/SS220/SyringeGun/TemporarySyringeComponentsComponent.cs
> В таком случае же для каждого шприца будет общий набор компонентов для удаления, а не индивидуальный (что в целом некритично, т.к. все шприцы не имеют этих компонентов), не? Или ты предлагаешь через `Dictionary` сделать?
> 
> В любом случае возникает вопрос, как триггерить удаление этих компонентов, после вытаскивания шприца из тела или промаха?....

через Dictionary
а у шприцов нету своего компонента?

2024-08-26 22:11 UTC, Kirus59 commented on Content.Shared/SS220/SyringeGun/SyringeGunComponent.cs
> +    public float SyringeRemovalTime = 1f;
> `EmbeddableProjectileComponent` оффовское?

Да

2024-08-26 22:18 UTC, Kirus59 commented on Content.Shared/SS220/SyringeGun/TemporarySyringeComponentsComponent.cs
`InjectorComponent`, хотя я бы не назвал его уникальнымидля шприцев, но пока он используется только ими (либо я не нашел нде еще).

Ну и есть уникальный тег `Syringe` еще

2024-08-27 17:27 UTC, DexlerXD commented on Content.Shared/SS220/SyringeGun/TemporarySyringeComponentsComponent.cs
так подпишись на эти ивенты через SyringeComponent тогда

2024-08-27 19:19 UTC, Kirus59 commented on Content.Shared/SS220/SyringeGun/TemporarySyringeComponentsComponent.cs
> так подпишись на эти ивенты через SyringeComponent тогда

?? 
У них же нет `SyringeComponent`
Я говорил что есть тег `Syringe` (это `TagComponent`, который в переменной `tags` имеет  значение "Syringe" (вернее одно из значений, т.к. `tags` это лист)).

2024-08-28 14:26 UTC, DexlerXD commented on Content.Shared/SS220/SyringeGun/TemporarySyringeComponentsComponent.cs
> > так подпишись на эти ивенты через SyringeComponent тогда
> 
> ?? У них же нет `SyringeComponent` Я говорил что есть тег `Syringe` (это `TagComponent`, который в переменной `tags` имеет значение "Syringe" (вернее одно из значений, т.к. `tags` это лист)).

шизофрения
я хотел написать InjectorComponent, и думаю что через него подписаться можно;
только в подписках на тег Syringe проверяй и всё

2024-09-20 05:31 UTC, Kirus59 commented
Делают оффы

2024-09-20 05:31 UTC, closed without merging