Add stunmode to Blueshield revolver
SerbiaStrong-220/space-station-14 pull request #1663
Opened 2024-08-27 17:18 UTC by Bomjojuk

## Описание PR
Добавление альтернативного режима стрельбы станнером для лазерного револьвера Синего Щита (+обновленный спрайт с отображением степени заряда и режима стрельбы)

**Медиа**
![base](https://github.com/user-attachments/assets/751c3a27-a697-47a0-b808-eb71dc56f002)
![Revolver2](https://github.com/user-attachments/assets/5d3e513f-ce4f-4b3a-be42-2f3229886976)

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl:
- add: Добавлен альтернативный режим стрельбы лазерному револьверу Синего Щита

2024-08-27 17:55 UTC, DexlerXD requested changes

2024-08-27 17:55 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +    - state: laser-mag-unshaded-5
```suggestion
    - state: laser-mag-unshaded-5 #SS220-add-stun-mode
```

2024-08-27 18:13 UTC, DexlerXD approved these changes

2024-08-29 18:49 UTC, Ady4ik approved these changes

2024-08-29 18:49 UTC, merged