Add auto-form system
SerbiaStrong-220/space-station-14 pull request #1665
Opened 2024-08-27 21:40 UTC by Kirus59

## Описание PR

Добавлена возможность автоматического заполнения определенных позиций в документе, при написании соответствующего ключа. ([трекер](https://discord.com/channels/1097181193939730453/1264120128556105739))

**Текущие ключи:**
- %data (%дата) - записывает сегодняшнюю дату по UTC+3 (с учетом игрового года)
- %time (%время) - записывает текущее время смены
- %name (%имя) - записывает имя куклы (можно поменять на имя с ID, но тогда обязательно её наличие в соответствующем слоте)
- %job (%должность) - записывает должность (с ID карты, обязательно её наличие в слоте ID карт (или в кпк в том же слоте))

**Медиа**

При ручном написании:

https://github.com/user-attachments/assets/2343f8cf-8811-4e94-8ec5-bdac97b04c5b

При использовании в заранее заполненной форме (с принтера например):

https://github.com/user-attachments/assets/69f9e57e-3def-4ebc-aa2a-fdc6c0dd68f0

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: kirus59
- add: Добавлена возможность автоматического заполнения определённой информации (дата, время, имя, должность) при написании в документе соответствующего ключа.

2024-08-28 06:14 UTC, stalengd commented on Content.Shared/SS220/Paper/PaperAutoFormSystem.cs
> +            return content;
Проверка на null не нужна, поскольку content не nullable, нужна ли проверка на пустоту?

2024-08-28 06:46 UTC, Kirus59 commented on Content.Shared/SS220/Paper/PaperAutoFormSystem.cs
> +            }
`Now` разве не учитывает пояса?
Ну, вчера тестил у меня писало дату по моему часовому поясу (UTC+3).

Игровой год независим от года ирл.

2024-08-28 06:48 UTC, Kirus59 commented on Content.Shared/SS220/Paper/PaperAutoFormSystem.cs
> +            return content;
Уэээээ, за основу брал систему чатфильтра и там была эта проверка, по сути она не нужна, т.к. значения `null` в данном контексте быть не может, а если строка пустая - то `Regex.Replace` попросту не найдет позиций с заданной структурой.

2024-08-28 06:51 UTC, stalengd commented on Content.Shared/SS220/Paper/PaperAutoFormSystem.cs
> +            }
Учитывать можно по разному, `Now` - часовой пояс на локальном устройсте, то что он у тебя UTC+3 это хорошо, но он же у всех должен по UTC+3 быть, а не так что у одного клиента одно, у другого другой, у сервера третий

2024-08-28 06:59 UTC, stalengd commented
Возможно было бы лучше не изобретать новый синтаксис тегов, а использовать уже существующий, те что с квадратными скобками. Да, они не заменяются текстом, а используются для задавания стилей тексту, но всё же.

2024-08-28 07:02 UTC, Kirus59 commented on Content.Shared/SS220/Paper/PaperAutoFormSystem.cs
> +            }
Так сделать чтобы выводило дату только по определённому поясу?
Я чет когда писал думал что лучше выводить дату пользователя, но мб с датой по одному поясу и правда будет лучше.

2024-08-28 07:04 UTC, Kirus59 commented
> Возможно было бы лучше не изобретать новый синтаксис тегов, а использовать уже существующий, те что с квадратными скобками. Да, они не заменяются текстом, а используются для задавания стилей тексту, но всё же.

Ну, в трекере предложили такой тег (и гоген говорил что мб лучше и такой), в целом то изменить его на другой не проблема.

2024-08-28 07:06 UTC, Kirus59 commented on Content.Shared/SS220/Paper/PaperAutoFormSystem.cs
> +        return Regex.Replace(content, "\\u0025\\b(\\w+)\\b", match =>
![Без названия (2)](https://github.com/user-attachments/assets/03875e5c-aedf-4cfd-ac85-d92e7654e149)

2024-08-28 07:12 UTC, stalengd commented on Content.Shared/SS220/Paper/PaperAutoFormSystem.cs
> +        return Regex.Replace(content, "\\u0025\\b(\\w+)\\b", match =>
Я тут вспомнил насчёт regex-а, его вроде можно прекомпилировать, не будет лишним, что-то вроде такого:

```cs
    [GeneratedRegex(@"\u0025\b(\w+)\b")]
    private static partial Regex ReplaceTagRegex();
```

ну и использовать
```cs
        return ReplaceTagRegex().Replace(content, match =>
```

2024-08-28 07:14 UTC, Kirus59 commented on Content.Shared/SS220/Paper/PaperAutoFormSystem.cs
> +        return Regex.Replace(content, "\\u0025\\b(\\w+)\\b", match =>
Понял, спасибо

2024-08-28 07:17 UTC, stalengd commented on Content.Shared/SS220/Paper/PaperAutoFormSystem.cs
> +            }
Тут как минимум не круто что сервер и клиент разные выдадут и теоретически пользователь будет видеть одно, тогда как на сервере другое. Ну и Surani говорил что IC дата по МСК (UTC+3) поясу, странно если она у всех будет разная.

2024-08-28 09:20 UTC, FriedrichStrassen commented
Хайпово

2024-08-28 16:54 UTC, Kirus59 commented
> в целом Стален уже всё отписал поправить бы regex и дату/время исправить на время по МСК

Использование аттрибута `GeneratedRegex` вызывает ошибку на клиенте (Стален [сказал](https://discord.com/channels/1158128815311171638/1158128816724639746/1278395173729996865) что на клиенте он не разрешен значит)

2024-08-28 22:01 UTC, DexlerXD requested changes

2024-08-28 22:01 UTC, DexlerXD commented on Content.Shared/SS220/Paper/PaperAutoFormSystem.cs
> +                var writerUid = (EntityUid)ent.Comp.Writer;
каст зачем?
у `EntityUid?` есть свойство `Value`, которое всегда возвращает `EntityUid`
т. е. `ent.Comp.Writer.Value`

2024-08-28 22:39 UTC, stalengd commented on Content.Shared/SS220/Paper/PaperAutoFormSystem.cs
> +                var writerUid = (EntityUid)ent.Comp.Writer;
Предлагаю так
```suggestion
            if (ent.Comp.Writer is { } writerUid)
            {
```

2024-08-29 03:57 UTC, Kirus59 commented on Content.Shared/SS220/Paper/PaperAutoFormSystem.cs
> +                var writerUid = (EntityUid)ent.Comp.Writer;
Про `Value` не знал, в визуалке предлагалось такое приведение.
Изменю тогда чуть позже.

2024-08-29 09:07 UTC, Kirus59 commented
Сделал возможность назначения нескольких тегов на вывод одной информации.

2024-08-29 09:13 UTC, stalengd commented
:dela:
Сомнительно, но окэй.

2024-08-29 20:29 UTC, DexlerXD approved these changes
ебать спагетти конечно
но сойдет

2024-08-29 20:30 UTC, merged