Janitor new loadout
SerbiaStrong-220/space-station-14 pull request #1670
Opened 2024-08-28 15:24 UTC by yulilok

## Описание PR
Добавлены оранжевые вещи за 50 наигранных часов в loadout уборщика. Такие, как: оранжевые галоши, оранжевая каска, фиолетовая униформа с оранжевыми подтяжками и оранжевые резиновые перчатки.

**Медиа**
![Торгар Балдерк-South](https://github.com/user-attachments/assets/b317312d-210b-48a3-a4b2-207f188e3540)![icon1](https://github.com/user-attachments/assets/e7449ee9-53ff-41e0-9852-5ab7ce2d6a96)![icon2](https://github.com/user-attachments/assets/3190369c-091c-484e-8274-9a71e4640a7d)![icon3](https://github.com/user-attachments/assets/6e22d781-c683-4e53-867d-fbc974f47851)![icon4](https://github.com/user-attachments/assets/3792a9a0-6b9f-4ed9-859c-7256f8aef1bd)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Себастьян Воров, yulilok
- add: Добавлены новые ботинки за наигранное время уборщику.
- add: Добавлены новые перчатки за наигранное время уборщику.
- add: Добавлена новая униформа за наигранное время уборщику.
- add: Добавлен новый головной убор за наигранное время уборщику.

2024-08-28 15:42 UTC, DexlerXD requested changes

2024-08-28 15:42 UTC, DexlerXD commented on Resources/Textures/SS220/Clothing/Head/Hats/janitor.rsi/meta.json
> +  "copyright": "Sprited by funny_mushroom for SS220",
для копирайтов после ника дописать `(Discord)`, так как оттуда взяли ник

2024-08-28 15:42 UTC, DexlerXD commented on Resources/Prototypes/Loadouts/Jobs/Civilian/janitor.yml
> +
```suggestion
# Shoes
#SS220-Add-Goloshes-to-the-loadout begin
- type: loadout
  id: JanitorShoes
  equipment:
    shoes: ClothingShoesGaloshes #SS220-Add-Goloshes-to-the-loadout end

```
рекомендую для больших блоков так помечать

2024-08-28 15:42 UTC, DexlerXD commented on Resources/Prototypes/Roles/Jobs/Civilian/janitor.yml
при удалении строчек вне наших файлов лучше комментировать нужную строчку, то есть:
```yaml
#shoes: ClothingShoesGaloshes SS220 janitor new loadout
```
и данная строчка станет неиспользуемой в самом прототипе

2024-08-28 15:42 UTC, DexlerXD commented on Resources/Prototypes/SS220/Entities/Clothing/Head/hats.yml
> +    sprite: SS220/Clothing/Head/Hats/janitor.rsi
рекомендую добавить часто используемые теги:
```yaml
  - type: Tag
    tags:
    - ClothMade
    - HamsterWearable
    - WhitelistChameleo
```

2024-08-28 15:49 UTC, DexlerXD commented
Ещё по поводу чейнджлога:
1. строчки ниже нужно удалять всегда, так как они будут лишний раз писать чейнджлог:
![image](https://github.com/user-attachments/assets/ce80e0e9-4084-4d0a-b795-81fa4a874285)
2. для того, чтобы чейнджлог сработал, нужно обязательно добавить `:cl:`, а если оставить после него пустое место, то оно подтянет твое имя с гитхаба, однако тут нужно дать кредит и спрайтеру, поэтому после `:cl:` я перечислил ники через запятую;
3. также для работы чейнджлога нужно перечислять изменения списком, т. е. как:
```
- изменение
- изменение 2
...
```
В итоге выйдет как-то так:
![image](https://github.com/user-attachments/assets/76c324fe-470e-4cc6-8eaf-26c43ee501db)
Я тебе уже всё сделал, просто на будущее чтобы знать

2024-08-28 23:03 UTC, closed without merging

2024-08-28 23:05 UTC, EstKemran commented
@yulilok Мёрджконфликты легко чинятся, не нужно даже из браузера выходить

2024-08-29 07:02 UTC, yulilok commented
Я ДУРАК СНЁС СБОРКУ, УЭЭЭЭЭЭ