FIX stunner machine gun
SerbiaStrong-220/space-station-14 pull request #1671
Opened 2024-08-28 16:51 UTC by disssr

## Описание PR

Станнер-пулемет больше не игнорирует резисты к стамин дамагу.
[#1667](https://github.com/SerbiaStrong-220/space-station-14/issues/1667)
Дамаг по стамине увеличен с 15 до 20.

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

- fix: Станнер-пулемет больше не игнорирует резисты к стамина урону
- tweak: Урон по стамине повышен до 20

2024-08-28 21:13 UTC, DexlerXD requested changes
удаление строчек мы делаем через комментирование, т. е.:
```yaml
#- type: Something SS220-some-changes
```

2024-08-28 21:58 UTC, disssr commented
> удаление строчек мы делаем через комментирование, т. е.:
> 
> ```yaml
> #- type: Something SS220-some-changes
> ```

так?

2024-08-28 22:06 UTC, DexlerXD requested changes

2024-08-28 22:06 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +        Stamina: 20
а тут пометку что 220 забыл

2024-08-28 22:06 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Projectiles/projectiles.yml
> +  #  damage: 15
и тут тоже надо

2024-08-29 20:31 UTC, DexlerXD approved these changes

2024-08-30 07:03 UTC, gogenych commented
> @gogenych need to be tested

без проблем, сейчас закинем

2024-09-05 13:18 UTC, disssr commented
> > @gogenych need to be tested
> 
> без проблем, сейчас закинем

завтра, как говорится

2024-09-05 20:47 UTC, gogenych commented
> > > @gogenych need to be tested
> > 
> > 
> > без проблем, сейчас закинем
> 
> завтра, как говорится

оно протестировано, просто я тут не писал. Всё работает как надо, Адуч знает

2024-09-06 09:09 UTC, merged