LaserTurret
SerbiaStrong-220/space-station-14 pull request #1687
Opened 2024-08-29 16:46 UTC by yulilok

## Описание PR
Добавлена лазерная турель, у которой есть разновидности такие же как и у баллистической.

**Медиа**
https://github.com/user-attachments/assets/5c2bef80-b5d4-4d1d-934c-a418aba6fe44

**Проверки**
- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
- add: Добавлена лазерная турель.
- add: Добавлены разновидности турели (NT, Syndicate, Hostile)

2024-08-29 18:57 UTC, Ady4ik commented
@EstKemran жду аппрув

2024-08-29 20:45 UTC, EstKemran approved these changes

2024-08-29 20:47 UTC, EstKemran commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Guns/turrets.yml
> +  name: Лазерная турель
`name` всегда начинается с маленькой буквы.

2024-08-29 20:47 UTC, EstKemran commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Guns/turrets.yml
> +  name: Одноразовая лазерная турель
`name` всегда начинается с маленькой буквы.

2024-08-29 20:48 UTC, DexlerXD requested changes

2024-08-29 20:48 UTC, DexlerXD commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Guns/turrets.yml
> +  name: Лазерная турель
```suggestion
  name: лазерная турель
```

2024-08-29 20:48 UTC, DexlerXD commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Guns/turrets.yml
> +  name: Одноразовая лазерная турель
```suggestion
  name: одноразовая лазерная турель
```

2024-08-29 21:44 UTC, DexlerXD commented
@yulilok у тебя с ценами у турелей беда, смотри подробности упавших чеков

2024-08-30 08:47 UTC, Ady4ik requested changes
Исправить чеки. Если не получится самостоятельно - обращайтесь к @EstKemran

2024-08-30 10:53 UTC, DexlerXD commented
@yulilok 
![image](https://github.com/user-attachments/assets/f7f3d2c3-7a60-41e7-8837-2f76a596d3f4)
упупу

2024-08-30 12:05 UTC, yulilok commented
> @yulilok ![image](https://private-user-images.githubusercontent.com/69513582/363145112-f7f3d2c3-7a60-41e7-8837-2f76a596d3f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTk3ODUsIm5iZiI6MTcyNTAxOTQ4NSwicGF0aCI6Ii82OTUxMzU4Mi8zNjMxNDUxMTItZjdmM2QyYzMtN2E2MC00MWU3LTg4MzctMmY3NmE1OTZkM2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDEyMDQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiM2MyODgwZDk1MzRkMWRlMWE1ZTdlZTBjODYwODVmYzAyN2JjYmY2ZDJiZGVjM2ZmMTQyYjJmNDgyYmMyM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b4FUikfQ3PVbpxCO60HwaDBZT3P2-DpQiEOlR8NdgxI) упупу

Да я в душе не понимаю что он хочет

2024-08-30 14:25 UTC, yulilok commented
Урааааа

2024-08-30 14:32 UTC, DexlerXD approved these changes

2024-08-30 14:35 UTC, DexlerXD commented
@Ady4ik апрув нажми и замержи

2024-08-30 14:37 UTC, Ady4ik approved these changes

2024-08-30 14:37 UTC, merged