Вторая шлёпская итерация
SerbiaStrong-220/space-station-14 pull request #1742
Opened 2024-09-04 11:25 UTC by EstKemran

## Описание PR
- [ ] **Анимированные плащи для игроков**
- [ ] Трубка и сигары + зиппо (по аналогии с Шлёпскими сигаретами)
> - [ ] Трубка
> - [x] Сигары
> - [x] Зиппо
- [ ] Упаковка пива "Tracker"
- [ ] Костюмы из деревни дураков для клоуна и мима.**
> - [ ] Костюм для клоуна "Мужик" из деревни дураков (респрайт)
> - [ ] Костюм для мима "Морячок" из деревни дураков (респрайт)
- [ ] Куртка ГГ из Cybеrpunk 2077
- [x] Игрушка курящей рыбы
- [ ] Шлёпское шампанское
- [x] Плюшевый шлёпа
- [ ] Футболка "Пивозавр"
- [ ] Куртка "1984" 
- [x] Крокс на голову
- [x] Рожки
- [ ] Нимб
- [ ] Замена спрайта аварийного набора
- [ ] Вишнёвая куртка (респрайт)
- [ ] Куртка мыловара (респрайт)
- [ ] Сет розового мафиозника (респрайт)
- [ ] Сет золотого клоуна (респрайт)
- [ ] Чёрное пальто (респрайт)
- [ ] Мозаичный комбинезон из сета мыловара (респрайт)
- [ ] Фирменная белая куртка (респрайт)

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl:
- add: Добавлена Вторая Шлёпская Итерация!

2024-09-04 11:34 UTC, DexlerXD commented
а где костюм Кенто? :XyliPizdish:

2024-09-21 07:56 UTC, Qwerlink commented on Resources/Textures/SS220/Clothing/Sponsor/Cyberpunk/Coats/cybermedsuit.rsi/equipped-OUTERCLOTHING.png
Мой скилл ишью в виде перекрытых рук остался :\

2024-09-23 19:42 UTC, Ady4ik requested changes

2024-09-23 19:42 UTC, Ady4ik commented on Resources/Prototypes/Loadouts/Miscellaneous/glasses.yml
> +# Sponsor / Cyber
```suggestion
# SS220 Second flopa iteration / Cyber
```

2024-09-23 19:42 UTC, Ady4ik commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - MaskClown
```suggestion
  - MaskClown #SS220-Two Floppa Iteration
```

2024-09-23 19:42 UTC, Ady4ik commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - MaskMuzhik
```suggestion
  - MaskMuzhik #SS220-Two Floppa Iteration
```

2024-09-23 19:42 UTC, Ady4ik commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - MaskGold
```suggestion
  - MaskGold #SS220-Two Floppa Iteration
```

2024-09-24 04:31 UTC, Ady4ik approved these changes

2024-09-24 17:21 UTC, EstKemran commented on Resources/Prototypes/SS220/Loadouts/sponsor_loadouts.yml
> +  id: HeadDeveloperNeck
С обоих серверов берутся

2024-09-24 17:24 UTC, EstKemran commented on Resources/Prototypes/SS220/Loadouts/sponsor_loadouts.yml
> +    proto: DeveloperSponsorTier #Нет тира для мапперов
Неделю назад добавили :3

2024-09-24 21:32 UTC, EstKemran commented
@DexlerXD @Surani1 @Kit0vras 
![BITrisereview](https://github.com/user-attachments/assets/5cd8a4fc-1d7d-4424-bded-ce622c628906)

Чекеры упали из-за мапы. Не знаю, по приколу они или я где-то накосячил. _(Возможно из-за замапленных шмоток морячка и мужичка)_
Удачи вам в ревью, гагага

2024-09-25 19:18 UTC, DexlerXD commented on Resources/Prototypes/SS220/Loadouts/sponsor_loadouts.yml
> +  id: HeadDeveloperNeck
> С обоих серверов берутся

а думаешь общая плашка ведущих подвязана к боту?

2024-09-25 19:19 UTC, EstKemran commented on Resources/Prototypes/SS220/Loadouts/sponsor_loadouts.yml
> +  id: HeadDeveloperNeck
> > С обоих серверов берутся
> 
> а думаешь общая плашка ведущих подвязана к боту?

Вер сказал, что тиры и отсюда и оттуда берутся

2024-09-25 19:22 UTC, EstKemran commented
@DexlerXD Раз ты тут, хелпани немного. Он говорит, что не загружается обломок, по причине, как я понял, `Тест был утилизирован грязным способом`.

На что он жалуется и как это исправить? Мапы я вроде не трогал

2024-09-25 20:40 UTC, DexlerXD commented
ебать заработало

2024-09-25 20:40 UTC, DexlerXD approved these changes

2024-09-25 20:41 UTC, merged