Add Quartermaster goggles
SerbiaStrong-220/space-station-14 pull request #1751
Opened 2024-09-04 22:11 UTC by Bomjojuk

## Описание PR
Добавление КМу собственных очков на основе нового карго худа. Совмещают в себе свойства обычных солнцезащитных очков и отображение цены карго худа.

**Медиа**
![image](https://github.com/user-attachments/assets/7da3a5dd-6948-49a6-9467-bc1e766baa69)
![image](https://github.com/user-attachments/assets/dda4950e-2013-4152-8c48-9930008ccd78)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены личные очки Квартирмейстера

2024-09-05 04:31 UTC, Bomjojuk commented
Чеки попробую пофиксить позже сегодня

2024-09-05 07:30 UTC, Ady4ik requested changes

2024-09-05 07:30 UTC, Ady4ik commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
> +    - id: ClothingEyesQuartermasterGlasses
```suggestion
     # SS220 Add goggles for QM
    - id: ClothingEyesQuartermasterGlasses
```

2024-09-05 07:30 UTC, Ady4ik commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +
Убрать пустые изменения
```suggestion
```

2024-09-05 07:43 UTC, Bomjojuk commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
> +    - id: ClothingEyesQuartermasterGlasses
Да, точно, забыл сделать комент в ящике главы

2024-09-05 07:44 UTC, Bomjojuk commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +
Кхм... Это видимо мискликнул...

2024-09-05 07:46 UTC, Bomjojuk commented
@Ady4ik я тут подумал, может сделать более понятным описание айтема? В двух словах сказать, в чем фишка

2024-09-05 08:19 UTC, Ady4ik requested changes

2024-09-05 08:19 UTC, Ady4ik commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +
Это также убрать надо
```suggestion
```

2024-09-05 08:19 UTC, Ady4ik commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +  description: Эксклюзивные очки квартирмейстера, совмещающие в себе защиту ваших, зрящих в корень, глаз от ярких лучей, встроенный интерфейс оценивания груза и выдержанный стиль отдела снабжения.
```suggestion
  description: Эксклюзивные очки квартирмейстера, совмещающие в себе защиту ваших, зрящих в корень, глаз от ярких лучей в совокупности со встроенным интерфейсом оценивания груза. Выдержанный стиль отдела снабжения для своего лучшего сотрудника. 
```

2024-09-05 08:47 UTC, Bomjojuk commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +
Да как.. Откуда... Я просто с мобильника редачу, из за этого возможно

2024-09-05 10:28 UTC, Ady4ik approved these changes

2024-09-05 17:02 UTC, DexlerXD requested changes

2024-09-05 17:02 UTC, DexlerXD commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
перенести в 220

2024-09-05 20:00 UTC, Bomjojuk commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
Уе... Пон

2024-09-06 09:20 UTC, DexlerXD approved these changes

2024-09-06 18:49 UTC, merged