Fix #1729
SerbiaStrong-220/space-station-14 pull request #1758
Opened 2024-09-05 18:51 UTC by Ady4ik

## Описание PR
Исправлено отображение юбки-комбинезона безопасности в руках.

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

 
:cl: Ady4
- fix: Исправлено отображение юбки-комбинезона в руках.

2024-09-05 18:56 UTC, EstKemran approved these changes

2024-09-05 18:57 UTC, EstKemran commented
:jokerge:

2024-09-05 19:09 UTC, DexlerXD requested changes

2024-09-05 19:09 UTC, DexlerXD commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +     - WhitelistChameleon #SS220-pr: FIX CLOTHING TAGS
ну емае

2024-09-09 15:09 UTC, DexlerXD approved these changes
лан похуй

2024-09-09 15:09 UTC, merged