Cleaned up SS220\Entities\Clothing
SerbiaStrong-220/space-station-14 pull request #1771
Opened 2024-09-06 12:50 UTC by chell4592

## Описание PR

Навёл порядок в прототипах SS220\Entities\Clothing

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up. Changelog must have a :cl: symbol, so the bot recognizes the changes and adds them to the game's changelog.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-09-06 18:59 UTC, DexlerXD approved these changes
lgtm

2024-09-06 19:03 UTC, Surani1 requested changes
В целом, внести лицензии для красоты. FTL нужен будет, но можно позже.

2024-09-06 19:03 UTC, Surani1 commented on Resources/Prototypes/SS220/Entities/Clothing/Head/hardsuit_helmets.yml
> +- type: entity
Лицензия

2024-09-06 19:03 UTC, Surani1 commented on Resources/Prototypes/SS220/Entities/Clothing/Shoes/boots.yml
> +# secboots
Лицензия

2024-09-06 19:03 UTC, Surani1 commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/jumpskirts.yml
> +# Сервис
Лицензия

2024-09-06 19:17 UTC, Ady4ik requested changes
Просьба добавить лицензии в начале каждого файла.

2024-09-09 07:19 UTC, chell4592 commented
добавил везде лицензию

2024-09-09 07:34 UTC, Kirus59 commented
Конфликтики

2024-09-09 11:20 UTC, chell4592 commented
Я добавил все изменения из конфликтующих файлов. Ругается из-за того, что файлы по-другому названы

2024-09-10 17:10 UTC, chell4592 commented
@Ady4ik лицензии добавлены

2024-09-11 08:12 UTC, Surani1 approved these changes
@Ady4ik @DexlerXD как только пофиксит мерж конфликты - залить первым делом. Очень важный PR

2024-09-11 08:32 UTC, closed without merging

2024-09-11 09:36 UTC, DexlerXD commented
да зачем пры-то при любом конфликте закрывать?