ReactiveTeleportArmorRD
SerbiaStrong-220/space-station-14 pull request #1802
Opened 2024-09-08 06:23 UTC by 21Melkuu

## Описание PR

Узнайте РП путем :tuh: 
Требуется помощь в виде спрайтеров, которые переделают оригинальные спрайты с ыы13. 

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up. Changelog must have a :cl: symbol, so the bot recognizes the changes and adds them to the game's changelog.
:cl: 21Gnomkuu"
- add: Добавлена экспериментальная реактивная броня

2024-09-08 06:24 UTC, 21Melkuu commented
ладно уговорили
![image](https://github.com/user-attachments/assets/44ae4edf-683c-4976-ae8a-5666e76a62c3)

2024-09-08 23:59 UTC, DexlerXD reviewed
https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/
ознакомься допом

2024-09-08 23:59 UTC, DexlerXD commented on Content.Server/SS220/ReactiveTeleportArmor/ReactiveTeleportArmorOnUristComponent.cs
> +    public bool OnCoolDown = false;
не думаю, что тут нужен `DataField`

2024-09-08 23:59 UTC, DexlerXD commented on Content.Server/SS220/ReactiveTeleportArmor/ReactiveTeleportArmorSystem.cs
> +        }
а обнулить `ArmorUid`?

2024-09-08 23:59 UTC, DexlerXD commented on Content.Server/SS220/ReactiveTeleportArmor/ReactiveTeleportArmorSystem.cs
как много и откуда ты *позаимствовал*? со скрама вижу, а еще откуда?

2024-09-10 09:41 UTC, DexlerXD submitted a review, later dismissed

2024-09-10 09:41 UTC, DexlerXD commented on Resources/Prototypes/Objectives/stealTargetGroups.yml
> +# SS220 - ReactiveArmor-end
перенести в 220

2024-09-10 09:41 UTC, DexlerXD commented on Resources/Prototypes/SS220/Entities/Clothing/OuterClothing/reactive_armor_rd.yml
> +  description: "Desc2." # да............ точно сделаю, кстати всем ревьюевирам дарова
переделать через локализацию и придмать нормальное название/описание

2024-09-10 09:41 UTC, DexlerXD commented on Content.Server/SS220/ReactiveTeleportArmor/TeleportOnDamageComponent.cs
> +    [ViewVariables, AutoNetworkedField]
а нетворкинг зачем? у тебя все равно все на одной стороне написано

2024-09-10 09:41 UTC, DexlerXD commented on Content.Server/SS220/ReactiveTeleportArmor/ReactiveTeleportArmorComponent.cs
неиспользуемые юзинги убрать и лицензию добавить

2024-09-10 09:41 UTC, DexlerXD commented on Content.Server/SS220/ReactiveTeleportArmor/ReactiveTeleportArmorSystem.cs
неиспользуемые юзинги убрать

2024-09-10 09:41 UTC, DexlerXD commented on Content.Server/SS220/ReactiveTeleportArmor/ReactiveTeleportArmorSystem.cs
> +        private void OnUnequip(Entity<ReactiveTeleportArmorComponent> ent, ref ClothingGotUnequippedEvent args)
эх вот бе спейсинг нормальный

2024-09-10 09:41 UTC, DexlerXD commented on Content.Server/SS220/ReactiveTeleportArmor/ReactiveTeleportArmorComponent.cs
неиспользуемые юзинги убрать

2024-09-10 09:41 UTC, DexlerXD commented on Content.Server/SS220/ReactiveTeleportArmor/ReactiveTeleportArmorSystem.cs
> +            } while (true);
страшилка
ограничить бы каким-нибудь числом кол-во циклов...
а смысл вообще от этого изначального цикла?

2024-09-10 09:41 UTC, DexlerXD commented on Content.Server/SS220/ReactiveTeleportArmor/ReactiveTeleportArmorSystem.cs
> +                switch (_random.Prob(ent.Comp.TeleportChance))
ща бы switch case на true/false делать...

2024-09-10 12:13 UTC, 21Melkuu commented on Content.Server/SS220/ReactiveTeleportArmor/ReactiveTeleportArmorSystem.cs
В System нет лишних юзингов
![image](https://github.com/user-attachments/assets/d7e7824d-269c-43b0-bff6-0e2d5cdc59a3)

2024-09-10 12:14 UTC, 21Melkuu commented on Content.Server/SS220/ReactiveTeleportArmor/ReactiveTeleportArmorSystem.cs
> +            } while (true);
Вообще как я понял, это перенесенный костыль со OnScramImplant, требуется для того чтобы всегда возвращалось какой-либо значение, если на этапах проверки приходят кривые данные, то do завершается через break; 
Могу ебануть while(false), чтобы не было никаких страшилок. :)

Не уверен, что будет хорошим решением мне реафкторить чужую систему 🥺

2024-09-10 21:49 UTC, DexlerXD commented on Content.Server/SS220/ReactiveTeleportArmor/ReactiveTeleportArmorSystem.cs
> +            } while (true);
> Вообще как я понял, это перенесенный костыль со OnScramImplant, требуется для того чтобы всегда возвращалось какой-либо значение, если на этапах проверки приходят кривые данные, то do завершается через break; Могу ебануть while(false), чтобы не было никаких страшилок. :)
> 
> Не уверен, что будет хорошим решением мне реафкторить чужую систему 🥺

если ты сделаешь while(false), то от цикла вообще никакого смысла не будет
легче тогда вообще этот цикл do while убрать

2024-09-11 20:00 UTC, DexlerXD commented on Content.Server/SS220/ReactiveTeleportArmor/TeleportOnDamageComponent.cs
> +    public EntityUid SavedUid;
написать бы summary, а то так не понятно, зачем нужно это поле

2024-10-02 16:17 UTC, 21Melkuu commented
@DexlerXD я накакал

2024-10-02 16:50 UTC, DexlerXD commented
конфликты

2024-10-02 17:48 UTC, 21Melkuu commented
> конфликты

НЕ МОГУ ЗАКРЫТЬ, кнопка не доступнка, я хз почему

2024-10-02 20:03 UTC, 21Melkuu commented
ура победа @DexlerXD

2024-10-02 22:25 UTC, Ady4ik requested changes

2024-10-02 22:25 UTC, Ady4ik commented on Resources/Locale/ru-RU/ss220/prototypes/entities/clothing/outerclothing/reactivearmor.ftl
> +    .desc = Включает или выключает реактивную брони.
```suggestion
    .desc = Включает или выключает реактивную броню.
```

2024-10-02 22:25 UTC, Ady4ik commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Это что?

2024-10-02 22:25 UTC, Ady4ik commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
> +
```suggestion
```

2024-10-03 09:19 UTC, 21Melkuu commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Кто

2024-10-03 09:55 UTC, Ady4ik commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Изменение лодаутов шкафов зачем?

2024-10-03 09:57 UTC, 21Melkuu commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
а куда мне запихнуть реактивку хайриск рд, кроме как в шкаф рд?

2024-10-03 11:13 UTC, Ady4ik commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
![image](https://github.com/user-attachments/assets/46836554-ea32-4adf-ab00-3d4cbf6376e8)
Эти инсерты в его шкаф зачем?
А тут ты вообще пихнул реактивку в шкаф к ГВ
![image](https://github.com/user-attachments/assets/51051165-131a-4b41-9100-f146886f61f1)

2024-10-03 11:24 UTC, 21Melkuu commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
>>> Эти инсерты в его шкаф зачем? 
вот это я нихуя не понял

>>> А тут ты вообще пихнул состав шкафа РД в шкаф ГВ + реактивку
вот это поправлю, немного криво решил мердж конлфикты

2024-10-03 11:24 UTC, 21Melkuu commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
> Эти инсерты в его шкаф зачем?
вот это я нихуя не понял

> А тут ты вообще пихнул состав шкафа РД в шкаф ГВ + реактивку
вот это поправлю, немного криво решил мердж конлфикты

2024-10-03 11:25 UTC, 21Melkuu commented on Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
>Эти инсерты в его шкаф зачем?

вот это я нихуя не понял

>А тут ты вообще пихнул состав шкафа РД в шкаф ГВ + реактивку

вот это поправлю, немного криво решил мердж конлфикты

2024-10-03 19:41 UTC, Ady4ik approved these changes

2024-10-04 06:58 UTC, Ady4ik approved these changes

2024-10-04 07:04 UTC, merged