Add Envelope craft
SerbiaStrong-220/space-station-14 pull request #1815
Opened 2024-09-08 20:01 UTC by Ady4ik

## Описание PR
Добавлена возможность скрафтить конверт. Выполнено в рамках задачи: [Тык](https://discord.com/channels/1158128815311171638/1282060865742311517)

**Медиа**
![image](https://github.com/user-attachments/assets/fd484a49-d561-4138-95b3-bbe1e5004e60)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлен крафт конверта.

2024-09-08 20:14 UTC, DexlerXD requested changes

2024-09-08 20:14 UTC, DexlerXD commented on Resources/Prototypes/SS220/Recipes/Crafting/paper.yml
> +  description: "Простой конверт для отправки писем."
а переводики мы нынче в локализации пишем

2024-09-09 09:52 UTC, Ady4ik commented
@DexlerXD Всю локализацию на крафты сделали там же, где сделал я. Локалей для крафтов не существует.
![image](https://github.com/user-attachments/assets/ff49c49a-be17-43b7-b840-b4741fcb76a8)

2024-09-09 10:04 UTC, DexlerXD approved these changes

2024-09-09 10:04 UTC, merged