Donuts Fix 0.2.1
SerbiaStrong-220/space-station-14 pull request #1823
Opened 2024-09-09 14:25 UTC by spo9k

## Описание PR
Изменение:
**1.** Изменён коридор РнД, и робототехника ( стало компактней и удобней )
**2.** прибытие было изменено чу-чуть продвинул, чтоб не ломал шаттл защитку.
**3.** Добавлены корзинка с бумагами
**4.** Убрана маска которая ебанутая (незнал) 
**5.** Цветок на Мостик вернулся.
**6.** Починил сервер мониторинг серверов.
**7.** Убраны некоторые вещи на обломке Вирусологии
**8.** Теперь свет не пропадает, в ИИ.

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
🆑 spo9k, Persia
- fix: Исправлена карта Donuts.

2024-09-09 15:25 UTC, UrPrice requested changes
Обновления без учёта следующего PR: https://github.com/SerbiaStrong-220/space-station-14/pull/1817
Вырезаешь контент из апдейта 0.25 таким способом + проделываешь повторную работу.

Отклонено по первому закону Ньютона - сначала пулим, а только потом пушим.
Соответственно тебе надо стянуть актуальную версию Донатса и вносить изменения уже на неё.

2024-09-28 09:22 UTC, UrPrice approved these changes

2024-09-28 09:23 UTC, UrPrice commented
Вероятно, когда этот https://github.com/SerbiaStrong-220/space-station-14/pull/1938 PR выйдет то карта уже будет готова под него, поэтому можно мёрджить @DexlerXD

2024-09-28 09:43 UTC, DexlerXD approved these changes

2024-09-28 09:44 UTC, merged