Paramedic&Pilot Hardsuit Vox
SerbiaStrong-220/space-station-14 pull request #1832
Opened 2024-09-10 14:10 UTC by EstKemran

## Описание PR
Ужасно перерисовывать хуёвые спрайты, чтобы они оставались хуёвыми :С

**Медиа**
![изображение](https://github.com/user-attachments/assets/2b7a3543-d706-45b6-b499-99ebb4af2cbc)
![изображение](https://github.com/user-attachments/assets/cafddf15-151d-42e3-bd32-b7934db003b9)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Kemran
- add: Добавлены спрайты скафандра парамедика и пилота для воксов

2024-09-10 21:08 UTC, DexlerXD requested changes
а копирайт не надо указать на респрайт?

2024-09-10 21:18 UTC, EstKemran commented
> а копирайт не надо указать на респрайт?

Баля, это настолько ужасные спрайты (оригинальные), что мне не хочется оставлять в них свой след :disintegrate:

2024-09-10 21:22 UTC, DexlerXD commented
> > а копирайт не надо указать на респрайт?
> 
> Баля, это настолько ужасные спрайты (оригинальные), что мне не хочется оставлять в них свой след :disintegrate:

а вот законы копирайта думают иначе

2024-09-11 19:54 UTC, DexlerXD approved these changes

2024-09-11 19:55 UTC, merged