Syndie jaws of life fix of speed modifier
SerbiaStrong-220/space-station-14 pull request #1842
Opened 2024-09-11 16:06 UTC by lexaSvarshik

## Описание PR

Фикс того, что челюсти жизни синдиката медленнее обычных челюстей. Теперь челюсти синдиката открывают запитанные двери в три раза быстрее. Скорость обычных челюстей снова нормальная.

**Проверки**

- [+ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [+ ] Я **ознакомился** с [наставлением по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [+ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [+ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ +] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

https://github.com/user-attachments/assets/e042a896-5638-4851-8899-eb19cfa6a6cd

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up. Changelog must have a :cl: symbol, so the bot recognizes the changes and adds them to the game's changelog.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-09-11 16:10 UTC, Kirus59 commented
В проверках нужно так ставить `[X]` (ну или `[x]`) чтобы галочка была.

2024-09-11 19:01 UTC, DexlerXD commented
исправить бы описание пра, а именно:
1. видео перенести в медиа
2. написать галочки, как отметил Кирус
3. написать чейнджлог по форме (в комментариях пример есть)

2024-09-11 20:36 UTC, gogenych requested changes
Спасибо что попросили ревью, потому что тут явно что-то не так. Я порылся в комитах и обнаружил, что наш пр #624 наложился на пару апстримов.

Что нужно сделать: 

1. Все челюсти должны быть с модификатором скорости "3" т.к. им изначально задавалась такая скорость если у них появится возможность взламывать пол. Она у них появилась, но обычным скорость вернуть забыли. 

2. Поправить комментарии к изменениям. Каждое новое изменение должно идти под своим комментарием, а тут три история из минимум трех правок под комментарием Адуча полугодичной давности.

2024-09-11 23:51 UTC, lexaSvarshik commented
То есть  у нас синди-челюсти будут идентичны обычным? ПР поправлю на досуге

2024-09-12 09:33 UTC, gogenych commented
> То есть у нас синди-челюсти будут идентичны обычным? ПР поправлю на досуге

сейчас у синди челюстей 11 секунд скорость. Она такая потому, что когда-то им дали возможность ломать пол и таким образом забалансили. Чуть позже оффы дали обычным челюстям возможность ломать пол тоже и мы должны забалалансить обычные до 11 секунд

2024-09-12 16:09 UTC, lexaSvarshik commented
Тогда, если делать обеим челюстям 11 секунд на открытие запитанной двери, модификатор скорости нужно будет поставить на единицу. И тогда у нас будут синди-челюсти абсолютно идентичны обычным. Так и задумано, что предмет из аплинка за 2тк абсолютно идентичен предмету, который изучается в рнд через 40 минут с начала смены?

2024-09-13 19:09 UTC, gogenych commented
>  Так и задумано, что предмет из аплинка за 2тк абсолютно идентичен предмету, который изучается в рнд через 40 минут с начала смены?

да

2024-09-15 16:26 UTC, lexaSvarshik commented
Довёл до ума описание ПР'а, фикс в коммите. Модификатор я поставил на 1, т.к. именно при нём скорость открытия будет составлять 11 секунд

2024-09-15 18:29 UTC, DexlerXD approved these changes
технически норм

2024-09-15 19:33 UTC, gogenych approved these changes

2024-09-16 11:20 UTC, Ady4ik approved these changes

2024-09-16 11:20 UTC, merged