TTK Update №1
SerbiaStrong-220/space-station-14 pull request #1862
Opened 2024-09-13 16:39 UTC by Gnomeev

## Описание PR

//// **экспериментальный апдейт, нужно посмотреть как это играется на сервере** ////
По трекеру: https://discord.com/channels/1097181193939730453/1282093984717475900 (Был одобрен)
- Был повышен урон всему огнестрельному оружию.

**Ниже представлены цифры по основным калибрам:**
- .35 (20 урона)
Без брони ->  5 на крит 
Снаряжение офицера -> 8 на крит
Ядерный оперативник -> 14 на крит

- .25 (24 урона)
Без брони ->  5 на крит 
Снаряжение офицера -> 7 на крит
Ядерный оперативник -> 11 на крит

- .20 (29 урона)
Без брони ->  4 на крит 
Снаряжение офицера -> 6 на крит
Ядерный оперативник -> 10 на крит

- .30  (33 урона)
Без брони -> 3 на крит 
Снаряжение офицера -> 5 на крит
Ядерный оперативник -> 8 на крит

- .45 / .50 Картечь (40 урона)
Без брони -> 3 на крит 
Снаряжение офицера -> 4 на крит
Ядерный оперативник -> 7 на крит

- .50 дробь (15/6)
Без брони -> 2 на крит 
Снаряжение офицера -> 2 на крит
Ядерный оперативник -> 3 на крит

- .60 (60 AP)
2 выстрела на крит любой цели

**Дополнительно:**
- Был повышен урон хитскан оружию (Лазеры и тд)
- L6 SAW было добавлено 20% замедление при носке в руках
- Увеличен разброс у некоторых видов оружия
- Крупной фауне (Дракону, Жнецу, Королю крыс) был дан резист к пулям

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлением по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Gnomeev
- tweak: Повышен урон ВСЕМУ огнестрельному оружию!

2024-09-13 16:48 UTC, 21Melkuu commented
прочитал, все хуйня, переделывай.

2024-09-13 16:48 UTC, DexlerXD requested changes

2024-09-13 16:48 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml
> +  components:
пустое изменение пупу

2024-09-13 17:15 UTC, FriedrichStrassen commented
![image](https://github.com/user-attachments/assets/ecec2807-a1af-4143-89e0-fe3b061be1e2)

2024-09-13 19:08 UTC, gogenych requested changes
Убрать повышение урона по стамине. В трекере обговаривалось повышение летальности, а не ап стаминометы от которой мы пытаемся избавится.

2024-09-14 14:10 UTC, gogenych approved these changes

2024-09-14 14:27 UTC, DexlerXD approved these changes

2024-09-15 07:22 UTC, FriedrichStrassen commented
ревёрт стаминадамаге резко делает резиновые патроны ещё бесполезнее в сравнении с леталом

2024-09-15 07:46 UTC, Bomjojuk commented
Согласен с доводом чая выше

2024-09-15 10:43 UTC, UrPrice commented
> прочитал, все хуйня, переделывай.

This comment was marked as abuse

2024-09-15 16:32 UTC, lexaSvarshik commented
Вставлю своё имхо. .45 калибр слишком слабо баффнут, у него урон вырос только на 5 единиц, тогда как у прочих калибров он вырос в среднем на 17.
Второе: нерф L6 - зачем?.. Оружие не то что бы метовое, особенно учитывая то, что стоит оно дороже прочих, но в эффективности не сильно выигрывающее из-за своего разброса, размеров и невозможности повесить на спину, что заставляет либо тратить место 4*4 в сумке, либо вовсе из рук не выпускать. Предложу либо вовсе не давать понижения скорости при ношении пилы, либо сделать его около 5%, либо сделать замедление только при двуручном хвате (и всё равно не такое большое, почему пулемет весит как тяжелый бронекостюм?).

2024-09-15 19:31 UTC, gogenych commented
> ревёрт стаминадамаге резко делает резиновые патроны ещё бесполезнее в сравнении с леталом

делайте трекер

2024-09-16 01:04 UTC, lexaSvarshik commented
> Страшно представить как быстро будут вайпать станцию командиры нюки под метом, если не нерфить скорость с пилой. С повышенным уроном оружие чересчур OP

У нюки всё ещё есть более часто используемые ср-ки, которые убивают лишь на пару пуль больше, но при этом занимают 2*4 слота, вешаются на спину, по скорострельности находящиеся примерно на одном уровне, по точности выигрывающие. Про разницу в цене (17тк против 30тк) и говорить нечего. 
Лучше не трогать L6 и скорость передвижения с ней, разве что только после теста на сервере, иначе это сразу убьет оружие, его брать никто не будет и понять, мета оно или нет - не выйдет.

2024-09-16 01:08 UTC, lexaSvarshik commented
И, ради чего-то нерфя L6, мы имеем **3** выстрела с любого дробовика **обычной** дробью, чтобы убить человека **(даже нюку)**. 1 магазин силовика в коридоре просто не оставит шансов, я вижу тут большую мету дробовиков, но опять же, лишь в теории.

2024-09-16 11:22 UTC, Ady4ik requested changes
запулить на дев ветку, в ближайшее время проведем клоузтесты и посмотрим, как играется

2024-10-13 16:50 UTC, 21Melkuu commented
@Ady4ik дарова мне сказали написать крутое мнение о прекрасном пре. 
Для задротов пр дает новый майндсет, что любое попадание может стать ошибкой года, ты больше сидишь играешь от префов, чем бездумно бежишь в цель -> убить, потому что ты на квасе и твои статы лучше. Условно раньше, нюка могла вбежать в бедного сбшника и убить его, не получив критического урона. ПР же уравнивает шансы(имхо), да сбуха все еще остается слабым по сравнению с нюкой, но это уже не безшансовое вбежал-выбежал-захилил одной ниткой фулл хп, побежал дальше. С каждым врагом( не важно с чем он) тебе нужно считаться и не бежать на бреиндедичах в цель.

Хоть я и раньше говорил, что дробвики с новым уроном станут бесполезными, я ошибался. Дробвики все еще сильные, дают сверх превосходство в близи цели, но платить придется разъебанным ебалом, пока ты пытаешься добежать до жертвы. Хотя я бы все же еще бы поднял чуть чуть урон дроби.

Для анробиков, которые не потратили в этой  блядской игре тысячу и миллионов часов игра не будет ничем отличатся, их как убивали/они убивали непонятно как для них, так и будут убивать/умирать. 

ПР дает больше динамики в перестрелке, больше наказывают за ошибки. Это нам надо, думать не надо, хуй знает, зачем эти тесты вообще нужны были, гнома гений, красава, люблю его.

2024-10-13 22:08 UTC, Surani1 approved these changes
Тесты проведены, в целом интересное нововведение, но всё же

- Далее требуется провести полный рефактор мили оружия в Т.Ч

- С броней тоже что-то требуется сделать, бронепластины от зонеса когда-то звучали, в целом как будто можно такое сделать

- Субъективно на тестах посмотрели, показало себя +- адекватно, но на серверах оно должно быть на испытательном сроке с сроком около 2х недель

Даю аппрув, но с условием дальнейшей работы с ТТК как огромного ребаланса, а не как единичного изменения.

2024-10-15 20:48 UTC, Ady4ik approved these changes
мерджим с делеем?

2024-10-16 10:39 UTC, UrPrice commented
Тут так много аппрувов, дополню

2024-10-16 11:04 UTC, stalengd requested changes

2024-10-16 11:04 UTC, stalengd commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/e_sword.yml
> +    spreadProjectile: 180
Меточки на весь блок, даже если остальное унаследовали

2024-10-16 11:04 UTC, stalengd commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/magnum.yml
> +        Blunt: 38 #weaponBalance
хз что за weaponBalance тут стоял, надо вставить что это именно наше изменение

2024-10-16 11:04 UTC, stalengd commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/pistol.yml
> +        Blunt: 16 #weaponBalance
хз что за weaponBalance тут стоял, надо вставить что это именно наше изменение

2024-10-16 11:04 UTC, stalengd commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/shotgun.yml
> +        Heat: 5 #weaponBalance
хз что за weaponBalance тут стоял, надо вставить что это именно наше изменение

2024-10-16 11:30 UTC, EstKemran approved these changes

2024-10-16 15:47 UTC, stalengd approved these changes

2024-10-16 16:31 UTC, merged