Death squad
SerbiaStrong-220/space-station-14 pull request #1887
Opened 2024-09-18 14:37 UTC by EstKemran

## Описание PR

### Оружие
- [x] Цепной меч
- [x] Пульсовая винтовка
- [ ] Пульсовый дробовик
- [x] SP-91-RC
### Снаряжение
- [x] Скафандр Командира
- [x] Скафандр Специалиста
- [x] Изменить стандартный скафандр ЭС
- [x] Магнитные ботинки
- [ ] Боевые перчатки ЭС
- [x] Омни-визор
- [ ] Боевой гипоспрей
### Эскадрон смерти
- [ ] Раса ЭС
- [ ] Должности командира и специалиста
- [ ] Спавнеры
### Разное
- [x] Божественный медипен
- [ ] Турель
- [ ] Частота
- [ ] Шкафчики командитра и специалиста

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я **ознакомился** с [наставлением по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up. Changelog must have a :cl: symbol, so the bot recognizes the changes and adds them to the game's changelog.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-10-20 16:16 UTC, EstKemran commented
Как же ты заебал

2024-10-20 19:41 UTC, EstKemran commented
Ну и насрал я коммитами

@stalengd @Kirus59 ревью

@Ady4ik Одобрено/Отказано

2024-10-21 14:43 UTC, Ady4ik approved these changes
апрув+поверхностное ревью

2024-10-21 14:43 UTC, Ady4ik commented on Resources/Locale/ru-RU/ss220/clothing/Hands/gloves.ftl
> +    .desc = Силовые перчатки, многократно усиливающие механическую силу удара.
```suggestion
    .desc = Силовые перчатки, значительно усиливающие силу удара.
```

2024-10-21 14:43 UTC, Ady4ik commented on Resources/Locale/ru-RU/ss220/clothing/Hands/gloves.ftl
> +ent-ClothingHandsGlovesDQ = боевые перчатки Эскадрона Смерти
```suggestion
ent-ClothingHandsGlovesDQ = боевые перчатки специалиста Эскадрона Смерти
```

2024-10-21 14:43 UTC, Ady4ik commented on Resources/Locale/ru-RU/ss220/clothing/Shoes/boots.ftl
> +    .desc = Самые современные магнитные ботинки в узнаваемых цветах.
```suggestion
    .desc = Самые современные магнитные ботинки в незабываемых цветах.
```

2024-10-21 14:43 UTC, Ady4ik commented on Resources/Locale/ru-RU/ss220/job/job-name.ftl
> +job-name-deathsquad = оперативник Эскадрона Смерти
```suggestion
job-name-dq-operative = оперативник Эскадрона Смерти
```

2024-10-21 14:43 UTC, Ady4ik commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/specific/medical/hypospray.ftl
> +    .desc = Экстренный медипен, который в кратчайшие сроки ставит на ноги даже при самых тяжелых травмах. Из-за дороговизны и трудности производства применяется элитными отрядами.
```suggestion
    .desc = Экстренный медипен, который в кратчайшие сроки ставит на ноги даже при самых тяжелых травмах. Из-за дороговизны производства применяется только элитными отрядами.
```

2024-10-21 14:43 UTC, Ady4ik commented on Resources/Prototypes/SS220/Catalog/Fills/Backpacks/backpack.yml
> +        - id: ToolDebug
```suggestion
        - id: ToolDebug
```
Это как понимать?

2024-10-21 14:43 UTC, Ady4ik commented on Resources/Prototypes/SS220/Catalog/Fills/Backpacks/backpack.yml
> +        - id: ToolDebug
```suggestion
        - id: ToolDebug
```
???

2024-10-21 14:43 UTC, Ady4ik commented on Resources/Prototypes/SS220/Entities/Objects/Misc/identification_cards.yml
> +    jobTitle: job-name-deathsquad
```suggestion
    jobTitle: job-name-dq-operative
```

2024-10-21 14:43 UTC, Ady4ik commented on Resources/Prototypes/SS220/Roles/play_time_trackers.yml
А обычному оперативнику каунт часов почему не добавил?

2024-10-21 14:43 UTC, Ady4ik commented on Resources/Prototypes/SS220/StatusIcons/centcom.yml
> +  jobName: job-name-deathsquad
```suggestion
  jobName: job-name-dq-operative
```

2024-10-21 14:48 UTC, lexaSvarshik reviewed
Исправления локализации и пара других вещей

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/specific/medical/hypospray.ftl
> +    .desc = Экстренный медипен, который в кратчайшие сроки ставит на ноги даже при самых тяжелых травмах. Из-за дороговизны и трудности производства применяется элитными отрядами.
```suggestion
    .desc = Экстренный медипен, который в кратчайшие сроки ставит на ноги даже при самых тяжелых травмах. Из-за дороговизны и трудности производства применяется только самыми элитными отрядами.
```

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/weapons/gun/battery.ftl
> +    .desc = Энергетическая дробовик с новейшей техников лечения.
```suggestion
    .desc = Энергетическая дробовик с новейшей технологией лечения.
```

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/weapons/gun/battery.ftl
> +    .desc = Энергетическая винтовка тяжелого типа, способна разрушать структуры.
```suggestion
    .desc = Энергетическая винтовка тяжелого типа, способна аннигилировать любые структуры.
```

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Objects/Devices/pda.yml
> +
пробел в нигде

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
> +  description: A large submachine gun using caliber cartridges.45 magnum.
```suggestion
  description: A large submachine gun using caliber cartridges .45 magnum.
```

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Objects/Specific/Medical/hypospray.yml
> +  description: Emergency honey and foam, which puts you back on your feet in the shortest possible time, even with the most severe injuries. Due to the high cost and difficulty of production, it is u
```suggestion
  description: Emergency medipen, which puts you back on your feet in the shortest possible time, even with the most severe injuries. Due to the high cost and difficulty of production, it is used only by the most elite units.
```

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  description: A heavy-duty energy rifle capable of destroying structures.
```suggestion
  description: A heavy-duty energy rifle capable of annihilating any structures.
```

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
> +  description: A large submachine gun using caliber cartridges.45 magnum.
```suggestion
  description: A large submachine gun using caliber cartridges .45 magnum.
```

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Clothing/OuterClothing/hardsuits.yml
> +  name: the hardsuit of the commander of the DQ
```suggestion
  name: the hardsuit of the DQ commander
```

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Clothing/OuterClothing/hardsuits.yml
> +  name: the hardsuit of the specialist of the DQ
```suggestion
  name: the hardsuit of the DQ specialist
```

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Objects/Devices/pda.yml
> +
пробел в нигде

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Objects/Specific/Medical/hypospray.yml
> +  description: Emergency honey and foam, which puts you back on your feet in the shortest possible time, even with the most severe injuries. Due to the high cost and difficulty of production, it is u
```suggestion
  description: Emergency medipen, which puts you back on your feet in the shortest possible time, even with the most severe injuries. Due to the high cost and difficulty of production, it is used only by the most elite units.
```

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  description: An energy shotgun with the latest treatment technique.
```suggestion
  description: An energy shotgun with the latest treatment technology.
```

2024-10-21 14:48 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Melee/sword.yml
> +  - type: Reflect
Тут вроде не прописаны типы рефлекта, могу ошибаться

2024-10-21 14:51 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Catalog/Fills/Backpacks/backpack.yml
> +        - id: ToolDebug
![изображение](https://github.com/user-attachments/assets/eebb15f7-b7ac-4656-88a0-b1ed13cf9e14)
Это испанский нож, по сути - лом, гаечный, отвертка, кусачки в одном предмете

2024-10-21 17:07 UTC, EstKemran commented on Resources/Prototypes/SS220/Entities/Clothing/OuterClothing/hardsuits.yml
> +  name: the hardsuit of the specialist of the DQ
Фу, английский

2024-10-21 17:07 UTC, EstKemran commented on Resources/Locale/ru-RU/ss220/clothing/Hands/gloves.ftl
> +ent-ClothingHandsGlovesDQ = боевые перчатки Эскадрона Смерти
Перчатки для всех ЭС, не только для специалиста

2024-10-21 17:11 UTC, EstKemran commented on Resources/Prototypes/SS220/Roles/play_time_trackers.yml
В офф репе есть

2024-10-21 18:32 UTC, stalengd requested changes

2024-10-21 18:32 UTC, stalengd commented on Resources/Prototypes/SS220/Entities/Objects/Devices/pda.yml
> +
пробел в нигде
```suggestion

```

2024-10-21 18:32 UTC, stalengd commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Melee/sword.yml
> +  #   - suitStorage
Какой ещё туду?

2024-10-21 18:32 UTC, stalengd commented on Resources/Textures/SS220/Clothing/Head/Hardsuits/dq_alpha_helmet.rsi/meta.json
> +  "copyright": "Created by discord:IAmRasputin#5242",
Ссылку на источник может если где-то опубликовано?

2024-10-21 18:33 UTC, stalengd commented on Resources/Prototypes/SS220/Entities/Objects/Devices/pda.yml
> +
А хотя похрен, забудь

2024-10-21 18:35 UTC, EstKemran commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Melee/sword.yml
> +  #   - suitStorage
Его переделать надо, но если я отложу пр до его переработки, пр снова начнёт гнить

2024-10-21 18:38 UTC, EstKemran commented on Resources/Locale/ru-RU/ss220/prototypes/catalog/fills/backpacks.ftl
> +    .suffix = Рюкзак оперативника ЭС, Эскадрон Смерти, Death Squad, ЭС, DQ
> "Рюкзак оперативника ЭС" это чуть ли не название предмета

В названии нет принадлежности к роли. Сокращу

2024-10-24 21:07 UTC, stalengd requested changes
Ещё не все суффиксы

2024-10-24 21:07 UTC, stalengd commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/specific/medical/hypospray.ftl
> +    .suffix = Эскадрон Смерти, Death Squad, ЭС, DQ
И тут

2024-10-24 21:07 UTC, stalengd commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/weapons/gun/battery.ftl
> +    .suffix = Винтовка, Эскадрон Смерти, Death Squad, ЭС, DQ
И тут

2024-10-24 21:07 UTC, stalengd commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/weapons/gun/battery.ftl
> +    .suffix = Дробовик, Эскадрон Смерти, Death Squad, ЭС, DQ
И тут

2024-11-04 16:57 UTC, EstKemran commented
Осталась одна проблема. ID карта дедов не открывает их ящика по доступу `CentralCommandDeathSquad`. Потыкал, повтыкал, не понял в чём проблема

2024-11-10 15:19 UTC, EstKemran commented
@stalengd ![изображение](https://github.com/user-attachments/assets/df0658e9-3889-4959-b1c4-e4546fb935c9)

2024-11-10 21:42 UTC, stalengd approved these changes

2024-11-10 21:46 UTC, merged