Stamina armor
SerbiaStrong-220/space-station-14 pull request #189
Opened 2023-08-07 22:11 UTC by ZoNeSRuS

## Описание PR

Стамина была внедрена в систему брони. 

Теперь стамина считается как урон, и наносимый урон по стамине отображается на оружии при осмотре. 
Резисты стамины добавлены на все риги, отображается уровень защиты.
Ригам добавлялись резисты исходя из их предназначения и статуса носителя. Самый высокий резист доступный на станции у капитана и ГСБ.
У синдиката, обр и дедсквада резист стамины составляет 90%

Были переработаны все предметы связанные со стаминой что бы соответствовать текущей системе.

ИСКЛЮЧЕНИЕ составляют станбатон и телескопическая дубинка. Так как они задействуют отдельные системы в которых я не успел разобраться. 

Не были обработаны случайные события, возможны ошибки. Локально тесты проведены были.

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: ZoNeSRuS
- add: Теперь хардсьюты защищают от самина урона.

2023-08-08 07:20 UTC, aw-c requested changes
Да кстати ПР не трогать, доделывается

2023-08-08 20:12 UTC, TheArturZh submitted a review, later dismissed

2023-08-08 20:12 UTC, TheArturZh commented on Content.Shared/Damage/Systems/DamageableSystem.cs
> +        [Dependency] private readonly StaminaSystem _staminaSystem = default!;
_staminaSystem переименовать в _stamina, оффы душатся

2023-08-09 09:35 UTC, aw-c approved these changes

2023-08-09 09:36 UTC, merged

2023-08-09 09:45 UTC, TheArturZh commented
Ну и чего ради вы замержили это если тесты падают
чините