Magistrate Foundation
SerbiaStrong-220/space-station-14 pull request #1890
Opened 2024-09-18 18:14 UTC by EstKemran

## Описание PR
Базовые прототипы, дабы мапперы могли начать работу

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлением по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
No cl

2024-09-18 18:37 UTC, Surani1 commented on Resources/Prototypes/SS220/Entities/Objects/Devices/pda.yml
> +    - type: PdaBorderColor
табуляция, из-за этого чек бадает

2024-09-18 18:41 UTC, DexlerXD requested changes

2024-09-18 18:41 UTC, DexlerXD commented on Resources/Prototypes/SS220/Entities/Objects/Devices/pda.yml
> +    - type: PdaBorderColor
уээээ

2024-09-18 18:41 UTC, DexlerXD commented on Resources/Prototypes/SS220/Roles/Jobs/Internal Affairs/magistrate.yml
> +      department: InternalAffairs
а разве этот департамент есть в игре?

2024-09-18 19:31 UTC, EstKemran commented on Resources/Prototypes/SS220/Roles/Jobs/Internal Affairs/magistrate.yml
> +      department: InternalAffairs
Баля xd

2024-09-19 13:38 UTC, DexlerXD approved these changes

2024-09-19 13:39 UTC, merged