New upgrade system for directional windows 220
SerbiaStrong-220/space-station-14 pull request #1891
Opened 2024-09-18 18:16 UTC by NightmareStalker

## Описание PR

Добавил оффовскую систему с апгрейдом окон для других направленных окон разных форм, которые добавлял до нее.
Убрал ишуй с урановым окном(ранее у оффов не было крафта урановых окон в принципе, потому его добавлял я - теперь она есть - лишнюю часть стер).

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлением по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлена оффовская система апгрейда других направленных окон

2024-09-18 18:42 UTC, DexlerXD requested changes

2024-09-18 18:42 UTC, DexlerXD commented on Resources/Prototypes/Recipes/Construction/Graphs/structures/windowdirectional.yml
удаление оффовских строк делается через комментирование

2024-09-18 20:08 UTC, NightmareStalker commented on Resources/Prototypes/Recipes/Construction/Graphs/structures/windowdirectional.yml
исправил
![image](https://github.com/user-attachments/assets/ea09d5e0-1bd5-4819-a870-7f4fb39aef6a)

2024-09-19 13:41 UTC, DexlerXD approved these changes

2024-09-19 13:42 UTC, merged