Cigrettes rework
SerbiaStrong-220/space-station-14 pull request #1919
Opened 2024-09-23 16:02 UTC by TryHardo7

Создал несколько новых уникальных для некоторых отделов и не только сигарет со стилизованными пачками и блоками.
Создал новую базу для визуалайзера сигарет внутри пачки для новых пачек в перспективе 3х4 а не кабинета.
Старые остались как были, мне лень их перерисовывать и вообще я не спрайтер.   

![image](https://github.com/user-attachments/assets/3df27175-5a55-42b7-a00a-12833825b4db)

Был добавлен новый химикат - Неоникатинойд, менее вредный для гуманоидов при курении.
Этот химикат лежит в основе не-лечащих сигарет, нужен для баланса генетического урона, потому что в лечащих 
сигаретах меньше вещества, а в оказывающих эффект больше. 

Разделил все сигареты в игре на 2 фундаментальные базы - лечащие и оказывающие эффект, в лечащих сигаретах никотин, в оказывающих эффект - неоникатиноид.
Курение переделано так, что теперь оно заносит в организм вещества из сигарет со скоростью более близкой к скорости метаболизма, так реагенты не успевают копиться внутри куклы, но успевают усвоиться и оказать эффект. 

Теперь курение вызывает рак, приблизительно 1 сигарета наносит 1-1.3 клеточного урона

Время курения сигарет до реворка и после примерно сровнял, для игрока разницы не заметно.

Добавил локализацию для всех сигарет. 
Добавил новые сигареты, посвященные отделам в вендоры соответствующих отделов. 

Никотин в шлёпских сигаретах заменён на неоникатинойд, чтобы шлёпстеры поменьше травились. 

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот демонстрации PR в игре.

:cl: Lancevrot
- add: Добавлены новые виды сигарет!
- add: Курение вызывает рак! Ура!
- tweak: Старым сигаретам добавлены новые эффекты!
- fix: Исправлено - эффекты химии в сигаретах не срабатывали при курении!

2024-09-23 16:15 UTC, gogenych approved these changes
Всё гуд. Спрайты бы Кемрану показать

2024-09-23 19:29 UTC, Ady4ik requested changes
Посмотрел только поверхностно, увынск

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
> +  - type: StorageFill
Комментарий бы
```suggestion
  - type: StorageFill
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
> +  - type: StorageFill
Здесь тоже бы
```suggestion
  - type: StorageFill
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
> +  - type: StorageFill
Ну и здесь уже, раз речь пошла
```suggestion
  - type: StorageFill
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/SS220Cigarettes/cartons.yml
> +- type: entity
```suggestion
# © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

- type: entity
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/SS220Cigarettes/cigarette.yml
> +- type: entity
```suggestion
# © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

- type: entity
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/SS220Cigarettes/packs.yml
> +- type: entity
```suggestion
# © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

- type: entity
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/base_smokeables.yml
> +    inhaleAmount: 0.35 # SS220 Cigarettes rework
По хорошему тут бы тоже все пометить за один комментарий, чтобы потом если что можно было разобраться
```suggestion
    inhaleAmount: 0.35 # SS220 Cigarettes rework
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Prototypes/Reagents/narcotics.yml
> +  metabolisms: # SS220 Cigarettes rework
Аналогично с комментарием выше
```suggestion
  metabolisms: # SS220 Cigarettes rework
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Prototypes/Reagents/narcotics.yml
> +
```suggestion
#SS220 Cigarettes begin
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Prototypes/Reagents/narcotics.yml
```suggestion
#SS220 Cigarettes end
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Locale/en-US/reagents/meta/narcotics.ftl
```suggestion
#SS220 Cigarettes begin
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Locale/en-US/reagents/meta/narcotics.ftl
> +
```suggestion
#SS220 Cigarettes end
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Locale/ru-RU/reagents/meta/narcotics.ftl
> +reagent-name-neonicotinoid = неоникатиноид
А вообще, по хорошему к нам перенести и сделать ftl файлик
```suggestion
#SS220 Cigarettes begin
reagent-name-neonicotinoid = неоникатиноид
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Locale/ru-RU/reagents/meta/narcotics.ftl
> +reagent-desc-neonicotinoid = Менее опасная форма никотина, всё равно убивает растения.
```suggestion
reagent-desc-neonicotinoid = Менее опасная форма никотина, всё равно убивает растения.
#SS220 Cigarettes
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/cigs.yml
> +    CigPackGreen: 3
```suggestion
#SS220 Cigarettes begin
    CigPackGreen: 3
```

2024-09-23 19:29 UTC, Ady4ik commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/cigs.yml
> +    CigPackMixed: 3
```suggestion
    CigPackMixed: 3
#SS220 Cigarettes end
```

2024-09-23 20:27 UTC, TryHardo7 commented
Комментарии в код добавил, но надо спрайты получше сделать, пока к мержу не готово

2024-09-28 21:40 UTC, TryHardo7 commented
Пройдены все круги ревьюверского ада, перерисовал все спрайты, удалил блоки за ненадобностью, сделал новый визуализатор сигарет внутри пачки, под новые спрайты.

2024-09-28 22:09 UTC, EstKemran approved these changes

2024-09-28 22:10 UTC, EstKemran commented
> Пройдены все круги ревьюверского ада, перерисовал все спрайты, удалил блоки за ненадобностью, сделал новый визуализатор сигарет внутри пачки, под новые спрайты. Новые пачки (на серую не обращайте внимания, её нет в файлах): ![image](https://private-user-images.githubusercontent.com/166473301/371809686-77132f16-2ee4-44ef-b0d4-1b940c5ab923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NjE2NzYsIm5iZiI6MTcyNzU2MTM3NiwicGF0aCI6Ii8xNjY0NzMzMDEvMzcxODA5Njg2LTc3MTMyZjE2LTJlZTQtNDRlZi1iMGQ0LTFiOTQwYzVhYjkyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQyMjA5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjQ4YWRlOTFmZDg3Y2U1NGEzMTRlMzIxNDYyZGM4YzI1MzkxOWI3NzlkYTg1YzcxMzQzODc4MmE4NTdhMDEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YG_89B7iV9Slf1VYnlzRkhkeH_KMc0k3ltkJhlClo18)

Добавь эту картинку в описание ПРа

2024-09-29 09:32 UTC, DexlerXD requested changes

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +- type: entity
новый прототип перенести в 220

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
пометки на изменениях добавить бы

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +- type: entity
новый прототип - в 220

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +- type: entity
новый прототип - в 220

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +- type: entity
пометки?

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  - type: SolutionContainerManager
пометки?

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/base_smokeables.yml
пометки бы добавить

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Prototypes/Reagents/narcotics.yml
> +- type: reagent
новый прототип - в 220

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/SS220Cigaretts/Packs/ENG.rsi/meta.json
у нас для спрайтов своя папка есть...

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/SS220Cigaretts/Packs/MED.rsi/meta.json
перенести новые спрайты в нашу папку

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/SS220Cigaretts/Packs/RnD.rsi/meta.json
перенести новые спрайты в нашу папку

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/SS220Cigaretts/Packs/SEC.rsi/meta.json
перенести новые спрайты в нашу папку

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/SS220Cigaretts/Packs/WEH.rsi/meta.json
перенести новые спрайты в нашу папку

2024-09-29 09:32 UTC, DexlerXD commented on Resources/Textures/Objects/Consumable/Smokeables/Cigarettes/SS220Cigaretts/Packs/visualizer.rsi/meta.json
перенести новые спрайты в нашу папку

2024-09-29 11:17 UTC, DexlerXD approved these changes

2024-09-29 11:17 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/base_smokeables.yml
> +            Quantity: 50
```suggestion
    # SS220 Cigarettes rework begin
    inhaleAmount: 0.35
  - type: Cigar
  - type: Tag
    tags:
    - Trash
  - type: SolutionContainerManager
    solutions:
      smokable:
        maxVol: 100
        reagents:
          - ReagentId: NeoNicotinoid
            Quantity: 50
    # SS220 Cigarettes rework end
```

2024-09-29 11:17 UTC, DexlerXD commented on Resources/Prototypes/Reagents/narcotics.yml
> +            Cellular: 0.05 # Smoking causes cancer.
```suggestion
  # SS220 Cigarettes rework begin
  metabolisms:
    Narcotic:
      effects:
      - !type:HealthChange
        damage:
          types:
            Cellular: 0.05 # Smoking causes cancer.
  # SS220 Cigarettes rework end
```

2024-10-01 12:12 UTC, Ady4ik requested changes
after requested changes rfm

2024-10-01 12:12 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  parent: SoakedHealCigarette
```suggestion
  parent: SoakedHealCigarette # SS220 Cigarettes
```

2024-10-01 12:12 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  parent: SoakedHealCigarette
```suggestion
  parent: SoakedHealCigarette # SS220 Cigarettes
```

2024-10-01 12:12 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  parent: SoakedHealCigarette
```suggestion
  parent: SoakedHealCigarette # SS220 Cigarettes
```

2024-10-01 12:12 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  parent: SoakedHealCigarette
```suggestion
  parent: SoakedHealCigarette # SS220 Cigarettes
```

2024-10-01 12:12 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  parent: SoakedHealCigarette
```suggestion
  parent: SoakedHealCigarette # SS220 Cigarettes
```

2024-10-01 12:12 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  parent: SoakedHealCigarette
```suggestion
  parent: SoakedHealCigarette # SS220 Cigarettes
```

2024-10-01 12:12 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  parent: SoakedHealCigarette
```suggestion
  parent: SoakedHealCigarette #  SS220 Cigarettes
```

2024-10-01 12:12 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  parent: SoakedHealCigarette
```suggestion
  parent: SoakedHealCigarette #  SS220 Cigarettes
```

2024-10-01 12:12 UTC, Ady4ik commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  parent: SoakedHealCigarette
```suggestion
  parent: SoakedHealCigarette #  SS220 Cigarettes
```

2024-10-01 14:16 UTC, Ady4ik approved these changes

2024-10-01 15:53 UTC, DexlerXD commented
чекам всё ещё плохо...

2024-10-02 15:07 UTC, Ady4ik requested changes

2024-10-02 15:07 UTC, Ady4ik commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
> +    sprite: SS220/Objects/Consumable/Smokeables/Cigarettes/Packs/ENG.rsi
```suggestion
    sprite: SS220/Objects/Consumable/Smokeables/Cigaretts/Packs/ENG.rsi
```
Везде где есть подобный путь изменить на указанный. Сама по себе папка называется Cigaretts

2024-10-02 15:25 UTC, Ady4ik approved these changes

2024-10-02 15:25 UTC, merged