Syndie visor buff
SerbiaStrong-220/space-station-14 pull request #1920
Opened 2024-09-23 17:27 UTC by lexaSvarshik

## Описание PR

На основе [трекера](https://discord.com/channels/1097181193939730453/1287076957242130533)
Улучшены визор синдиката и визор агента синдиката! Теперь они защищают от сварки и вспышек, а так же визор агента синдиката имеет встроенные очки хим. анализа и отображает уровень здоровья киборгов!

## Почему/баланс
На данный момент смысла покупки визора нет, по тем причинам, что он: является контрабандой, по функционалу идентичен визору СБ, стоит несоразмеримо дорого за свой функционал (функционал - сб худ, отображение иконок ЯО).

После правок, базовый визор будет иметь: защиту от вспышек, защиту от сварки. Визор агента будет иметь, в добавок ко всему прочему: робо-худ _(отображение здоровья киборгов. Полезно для ЯО - чинить своего штурмового борга)_, очки хим. анализа для определения жидкостей в мензурке. 
Цена в аплинке - 1 ТК. Так же, визор добавлен в аплинк ЯО.

**TODO:**
- [ ] Обсудить баланс

**Медиа**

https://github.com/user-attachments/assets/489f94ed-de6a-4695-9be8-b67281c0feb5

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Svarshik

- tweak: Улучшены визор синдиката и визор агента синдиката!

2024-09-23 19:07 UTC, DexlerXD requested changes
перевод перенести в 220

2024-09-23 20:52 UTC, DexlerXD approved these changes

2024-09-23 20:52 UTC, DexlerXD commented
@lexaSvarshik еще в работе?

2024-09-23 20:54 UTC, lexaSvarshik commented
> @lexaSvarshik еще в работе?

Мне нужен фидбек по балансу, разве что. Насчёт цены в аплинк в 1/2 ТК. Всё остальное сделано.

2024-09-23 21:04 UTC, lexaSvarshik commented
@gogenych нужно мнение насчёт баланса и цены. Свои аргументы за такую цену - я привел в шапке

2024-09-24 04:21 UTC, Surani1 commented
А в чём их смысл агенту вообще, когда есть точно такая же маска

2024-09-24 08:04 UTC, lexaSvarshik commented
> А в чём их смысл агенту вообще, когда есть точно такая же маска

Медхуд + сб худ. Для отслеживания уровня здоровья союзников и противников, для распознавания свой/чужой.

2024-09-24 08:15 UTC, gogenych requested changes

2024-09-24 08:15 UTC, gogenych commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +    Telecrystal: 1 #price is lower because that is basically enemy equipment and in-game perma
Вернуть как было

2024-09-24 18:43 UTC, gogenych approved these changes

2024-09-25 12:49 UTC, merged