Docs tweak
SerbiaStrong-220/space-station-14 pull request #194
Opened 2023-08-08 19:29 UTC by yatebyaeby

## Описание PR
Новые цели для станции и новые бланки

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: enJey Ady4
- add: Добавил новые цели станции
- add: Добавил бланки для выполнения целей

2023-08-08 20:01 UTC, aw-c requested changes
Почему ты решил использовать папки корвакса для текстов наших целей?

2023-08-08 20:18 UTC, yatebyaeby commented
> Почему ты решил использовать папки корвакса для текстов наших целей?
> Наш контент идёт в папку ss220 в ru-RU, корвакс мы не трогаем, нам ещё ребейз от них делать :trollface:

где были цели, там их и добавил, когда будем делать ребейз, тогда и перенем

2023-08-08 22:10 UTC, aw-c commented
> > Почему ты решил использовать папки корвакса для текстов наших целей?
> > Наш контент идёт в папку ss220 в ru-RU, корвакс мы не трогаем, нам ещё ребейз от них делать :trollface:
> 
> где были цели, там их и добавил, когда будем делать ребейз, тогда и перенесем

Нет, переноси сейчас.

2023-08-08 22:13 UTC, TheArturZh commented
Наш контент идёт в соответствующую папку.

2023-08-08 22:16 UTC, TheArturZh commented
Если что тебя не просят переносить код, но прототипы и локалы должны быть перенесены.

2023-08-08 23:23 UTC, TheArturZh commented
Так же формы очень нишевые, для них нужно сделать отдельную группу. В командных формах и так уже куча всего.

2023-08-09 12:05 UTC, Ady4ik commented
Можем сделать новый отдел для отчетов о выполнении цели, т.к хотелось бы не ограничиться добавлением только трех целей, а так будет понятно, где они будут расположены.

2023-08-10 19:40 UTC, TheArturZh commented
Локи целей всё еще нужно перенести в `ru-RU/ss220/station-goals.ftl` остальное гуд.

2023-08-18 10:44 UTC, TheArturZh commented
Не совсем то, поправил сам

2023-08-18 10:44 UTC, merged