TwoOne floppa iteration
SerbiaStrong-220/space-station-14 pull request #1948
Opened 2024-09-27 21:40 UTC by EstKemran

## Описание PR
- Плащи добавлены для стандартных ролей и выше
  - Парадизовский плащ перенесен в лодауты
  - Плащи спонсорские в отдельной вкладе от игровых плащей
- Киберпанк вещи добавлены для стандартных ролей и выше
- Почистил немного прототипы и спрайты
- Убрал шлёпские аварийные наборы

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
No cl

2024-09-27 21:42 UTC, EstKemran commented
@Ady4ik @Surani1 @UrPrice @DexlerXD 

Завтра всё дополнительно протестирую, пока вот так

2024-09-27 21:47 UTC, EstKemran commented
Упали. Завтра починю

2024-09-27 21:53 UTC, DexlerXD requested changes

2024-09-27 21:53 UTC, DexlerXD commented on ToolsSS220/UserInfoImitator/Controllers/UserInfoController.cs
откатить

2024-09-28 00:12 UTC, UrPrice commented
> @Ady4ik @Surani1 @UrPrice @DexlerXD
> 
> Завтра всё дополнительно протестирую, пока вот так

Ночью накачу потещу

2024-09-28 00:45 UTC, UrPrice commented
- У шеф-повара надо убрать спонсорские плащи
- У бармена тоже надо бы убрать спонсорские плащи
- У библиотекаря 50/50, у него вроде тоже плащ как для ГМа мог бы использоваться, вроде не вычурно
- Клоуну дать спонсорские плащи 
- Миму дать спонскорские плащи

2024-09-28 18:44 UTC, EstKemran commented
@Ady4ik @DexlerXD Заревьювте и замёрджите кто-то. Мне этот ПР нужен для юристов, которые должны быть сделаны уже завтра, до релиза Астро и апдейта картов

2024-09-29 08:55 UTC, DexlerXD approved these changes

2024-09-29 08:56 UTC, merged