Add lying down
SerbiaStrong-220/space-station-14 pull request #1960
Opened 2024-09-29 14:11 UTC by Kirus59

## Описание PR

Добавлен компонент и экшн, позволяющий энтити лечь на пол.

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: kirus59

2024-09-29 16:24 UTC, Kirus59 commented
Заранее отмечу что это делается для питомцев глав, а не для кукол игроков.

2024-10-09 20:40 UTC, Kirus59 commented
need review

2024-10-10 20:28 UTC, stalengd requested changes

2024-10-10 20:28 UTC, stalengd commented on Content.Shared/SS220/LyingDownOnBuckledEntity/Systems/LyingDownOnBuckledEntitySystem.cs
> +        SubscribeLocalEvent<HumanoidAppearanceComponent, GetVerbsEvent<AlternativeVerb>>(OnHumanoidAlternativeVerb);
Подписка на компонент оффов это нехорошо, может всё сломать в будущем

2024-10-10 20:28 UTC, stalengd commented on Content.Shared/SS220/LyingDownOnBuckledEntity/Components/LyingPetComponent.cs
> +public sealed partial class LyingPetComponent : Component
Судя по функционалу, название компонента неудачное

2024-10-10 20:28 UTC, stalengd commented on Content.Shared/SS220/LyingDownOnBuckledEntity/Components/LyingDownOnBuckledEntityComponent.cs
> +    /// The damage that the entity gain in second
```suggestion
    /// The damage that the entity gain per second
```

2024-10-10 20:28 UTC, stalengd commented on Content.Shared/SS220/LyingDownOnBuckledEntity/Systems/LyingDownOnBuckledEntitySystem.cs
> +    private void OnCanMoveUpdate(Entity<LyingDownOnBuckledEntityComponent> entity, ref UpdateCanMoveEvent args)
Заодно пустую строку закинь тут

```suggestion
    }
    
    private void OnCanMoveUpdate(Entity<LyingDownOnBuckledEntityComponent> entity, ref UpdateCanMoveEvent args)
```

2024-10-10 20:28 UTC, stalengd commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +  #SS220 Add lying down on entity end
И заодно табуляцию этих комментариев как-то уровнять

2024-10-11 16:13 UTC, stalengd approved these changes

2024-10-11 16:18 UTC, merged