Tajaran Race
SerbiaStrong-220/space-station-14 pull request #1961
Opened 2024-09-29 14:53 UTC by Alwayswannahunt

## Описание PR

Добавлена играбельная раса таяран, лор можете найти тут: https://wiki.ss220.club/index.php/%D0%A2%D0%B0%D1%8F%D1%80%D0%B0%D0%BD.
Добавлена уникальная особенность таяр - острый слух. Раз в 2 минуты они могут слышать сердцебиение живых существ рядом в течение 5 секунд.
Аналогичное получил и ниндзя, но эффект постоянный.

**Медиа**

![Снимок экрана 2024-09-29 173134](https://github.com/user-attachments/assets/411945d7-ae07-40b7-b496-297bd9edf798)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Sprited by Kemran, speachbuble by Gabka, code by AlwyAnri
- add: Добавлена новая играбельная раса таяр!
- tweak: Добавлена система чуткого слуха!

2024-09-29 16:16 UTC, DexlerXD commented
ЭТО ТАКОЙ КОНЕЦ

2024-09-29 17:55 UTC, FriedrichStrassen commented
ЭТО ТАКОЙ ПИЗДЕЦ

2024-09-30 03:01 UTC, Tris0r commented
ЭТО ТАКОЕ НАЧАЛО

2024-10-02 04:10 UTC, TryHardo7 commented
Вырезание феленидов в этот же ПР пожалуйста

2024-10-06 14:35 UTC, Alwayswannahunt commented
@DexlerXD Тесты тут победил. Вроде ничего, что затронет апстрим не делал, но глянь

2024-10-06 15:00 UTC, DexlerXD requested changes

2024-10-06 15:00 UTC, DexlerXD commented on Content.Client/SS220/Overlays/KeenHearingOverlay.cs
> +        // Tajaran_TODO check if it works okay
?

2024-10-06 15:00 UTC, DexlerXD commented on Content.Server/SS220/Speech/Components/TajaranAccentComponent.cs
тоже на всякий ебани копирайт ноутис

2024-10-06 15:00 UTC, DexlerXD commented on Content.Server/SS220/IgnoreLightVision/KeenHearing/KeenHearingSystem.cs
> +/// //Tajaran_TODO: make it work
?

2024-10-06 15:03 UTC, Alwayswannahunt commented on Content.Server/SS220/IgnoreLightVision/KeenHearing/KeenHearingSystem.cs
> +/// //Tajaran_TODO: make it work
– Лёжанный таярин этого комента! Какого таярина слова в другом порядке написаны? Я же сам печатал их на своих глазах, врон! Как они могут быть там написаны в другом порядке?!
– В другом! Вот смотрите!

Ща гляну, скорее всего рудимент.

2024-10-06 18:28 UTC, DexlerXD approved these changes
lgtm

2024-10-07 06:14 UTC, merged