Calculator
SerbiaStrong-220/space-station-14 pull request #1962
Opened 2024-09-29 17:47 UTC by stalengd

## Описание PR
Калькулятор. Он считает.

Todo висит в ветке в канале идей.

**Медиа**

![image](https://github.com/user-attachments/assets/1f477f07-e021-4855-8c42-c069c89c81fa)

**Проверки**
- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлен калькулятор.

2024-09-29 17:48 UTC, DexlerXD commented
ЭТО ТАКОЕ НАЧАЛО

2024-09-29 17:59 UTC, stalengd commented
Чтобы закончить фичу, нужен этот коммит движка у нас https://github.com/space-wizards/RobustToolbox/commit/f467a7027b66928480b3b6c81e62e4c9780cf2c3

2024-09-29 23:07 UTC, UrPrice commented
А можем попросить @MIXnikita сделать калькулятору антуражно подходящие звуки клавиш нажатия?

2024-09-30 07:11 UTC, stalengd commented
> А можем попросить @MIXnikita сделать калькулятору антуражно подходящие звуки клавиш нажатия?

Я уже сделал звуки, позже будет видео, мне кажется они подходят.

2024-10-03 22:55 UTC, stalengd commented
Всё готово, ждём только обновления движка, после чего будет небольшое изменение и всё

2024-10-17 19:06 UTC, stalengd commented
ГОООООЛ

2024-10-17 19:09 UTC, stalengd commented
@Kirus59 осилишь ревью этого? В целом контент плюс-минус декоративный и не должен сломать ничего существующего, поэтому большой ответственности нет

2024-10-17 20:03 UTC, Kirus59 commented
> @Kirus59 осилишь ревью этого? В целом контент плюс-минус декоративный и не должен сломать ничего существующего, поэтому большой ответственности нет

Завтра гляну

2024-10-19 19:03 UTC, Kirus59 requested changes

2024-10-19 20:57 UTC, Kirus59 approved these changes

2024-10-19 20:57 UTC, merged