Ss220 uplink minor fixes and discounts
SerbiaStrong-220/space-station-14 pull request #1968
Opened 2024-09-29 20:28 UTC by lexaSvarshik

## Описание PR

Предметам, добавленных нами, добавлена система оффовских скидок. Малые исправления локализации. Несколько скидок исправленно ввиду изменений цены.

- Изменен нижний порог скидки метательных ножей
- Изменен нижний порог скидки импланта "свобода"
- Добавлены скидки для: миниарбалета, двойного энергомеча, майндслейва, термалов, импланта термалов, сегвея, набора улучшения мима. Скидки сделаны аналогично оффовским. _Нижний порог скидок на даблу и арбалет сделан нескольким выше ввиду баланса._

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

no cl no fun

2024-09-30 07:16 UTC, gogenych requested changes
Первый раз слышу о этих изменениях. Баланс должен обсуждаться, а не просто заливаться на гит "потому что логично". У нас уже есть опыт подобных правок, пол года разгребаем

2024-09-30 14:14 UTC, lexaSvarshik commented
> Первый раз слышу о этих изменениях. 

Порог скидок изменен для предметов из обновы #SS220-underused-uplinks-stuff. Им цену скинули, но у оффов другая цена и в итоге там скидка могла составлять 0%.

2024-09-30 14:15 UTC, lexaSvarshik commented
Ну а скидки нашим предметам по типу термалов сделаны, потому что скидок нет... А должны быть...

2024-10-01 12:18 UTC, Ady4ik requested changes
Dnm, требует обсуждения.

2024-10-05 14:26 UTC, Surani1 commented
> Dnm, требует обсуждения.

Завтра на планёрке?

2024-10-06 13:31 UTC, Ady4ik approved these changes

2024-10-06 13:31 UTC, DexlerXD approved these changes

2024-10-06 13:33 UTC, merged