Head antag
SerbiaStrong-220/space-station-14 pull request #198
Opened 2023-08-10 14:01 UTC by ZoNeSRuS

## Описание PR

Теперь главы могут быть антагонистами.
Главы настроены таким образом что они не могут украсть сами у себя. Введены impossibleGoals для каждой "работы".
Вероятность выпадение цели на диск уменьшена, так как это самая сложная цель в игре, и она имела вероятность упасть равна мясу корги. Скорее всего это банальная ошибка. Обговорено с WER.

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: ZoNeSRuS
- add: Главы могут быть предателями.
- tweak: Цель на кражу диска теперь падает реже.
- tweak: Главам не может упасть цель воровать самим у себя.

2023-08-10 22:08 UTC, ZoNeSRuS commented
Сорян, пока только учуть вашим гитам. Пописал в консольке  git rebase master.

2023-08-10 22:24 UTC, aw-c requested changes
Необходимо исправить историю коммитов

2023-08-10 22:27 UTC, TheArturZh commented
Ты кажется не запушил после ребейза, здесь снизу всё еще конфликты весят
Или ветку сменить забыл? Оно должно будет попросить тебя решить конфликты

2023-08-10 22:28 UTC, TheArturZh commented
Хотя я тут посмотрел, тут оно отстаёт на 527, может немного запарно быть
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/16546901/293fc01f-3075-4419-96c7-5d33f52df5cd)
Могу сам поправить если ты не против

2023-08-10 22:38 UTC, ZoNeSRuS commented
Я не против если ты сам исправишь.

2023-08-11 10:32 UTC, Spase338 commented
В аплинк главам не добавлены предметы из вайтлиста профессий.

2023-08-11 10:53 UTC, aw-c approved these changes

2023-08-11 10:55 UTC, TheArturZh commented
Не проходит тесты линтера, похоже ID обжективов сменились

2023-08-11 10:56 UTC, aw-c commented
> Не проходит тесты линтера, похоже ID обжективов сменились

пох мёржим

2023-08-11 11:04 UTC, TheArturZh requested changes
``` 
- !type:NotRoleRequirement
  roleId: ResearchDirector
```
Блэклисты ролей уже указаны в прототипах целей, нет смысла дублировать

2023-08-11 11:04 UTC, TheArturZh commented on Content.Shared/Roles/JobPrototype.cs
> +        [DataField("impossibleGoals", customTypeSerializer: typeof(PrototypeIdListSerializer<AccessGroupPrototype>))]
не будет работать, неверно указан тип прототипа. Должен быть ObjectivePrototype

2023-08-11 11:28 UTC, TheArturZh commented
Перед внесением в ветку нужно будет убедиться что подтянулись изменения с гитхаба т.к. я делал rebase
Т.е. находясь на ветке head_antag нужно будет сделать git reset --hard origin/head_antag
Делать это нужно до внесения изменений иначе они будут потеряны

2023-08-11 13:49 UTC, AndreyKostenkoS commented
А как это по лору будет объяснено? Просто сейчас же по дефолту у глав по рп майндшилд установлен?

2023-08-11 14:22 UTC, aw-c commented
> А как это по лору будет объяснено? Просто сейчас же по дефолту у глав по рп майндшилд установлен?

как мне пояснили майндшилд есть у капитана и хоса

2023-08-12 03:19 UTC, ZoNeSRuS commented
> > А как это по лору будет объяснено? Просто сейчас же по дефолту у глав по рп майндшилд установлен?
> 
> как мне пояснили майндшилд есть у капитана и хоса

И у всего СБ

2023-08-12 06:21 UTC, Izergaer commented
> А как это по лору будет объяснено? Просто сейчас же по дефолту у глав по рп майндшилд установлен?

майндщит защищает от конвертации в культ и революцию

2023-08-15 12:29 UTC, closed without merging