Dallas mask fix
SerbiaStrong-220/space-station-14 pull request #1988
Opened 2024-10-01 21:18 UTC by EstKemran

## Описание PR

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Kemran
- fix: Исправлена демократическая маска.

2024-10-01 21:19 UTC, DexlerXD requested changes
изменения построек?

2024-10-01 21:20 UTC, EstKemran commented
> изменения построек?

huy знает, почему они подтянулись. Уберу

2024-10-01 21:43 UTC, EstKemran commented
Рофлопадение

2024-10-02 16:23 UTC, DexlerXD approved these changes

2024-10-02 16:25 UTC, merged