add headsets for heads by OIegsandr [WIP] [DO NOT MERGE]
SerbiaStrong-220/space-station-14 pull request #2006
Opened 2024-10-03 15:26 UTC by OIegsandr

## Описание PR

Добавляет в лодауты глав выбор между полной и обычной гарнитурой.
**Медиа**

![image](https://github.com/user-attachments/assets/c3672aaf-59a0-4627-867a-c9613b36668c)
![image](https://github.com/user-attachments/assets/e1508ca4-babf-45a3-a151-90a0a274753f)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: OIegsandr
- add: Добавлен выбор гарнитуры в лодаутах глав.

2024-10-04 08:39 UTC, Surani1 requested changes
Там где требуется создать новые прототипы, навести порядок и чистоту. Лишние изменения убрать

2024-10-04 08:39 UTC, Surani1 commented on Resources/Locale/ru-RU/preferences/loadout-groups.ftl
> +loadout-group-hop-headset = Глава персонала, гарнитура
перенести в 220

2024-10-04 08:39 UTC, Surani1 commented on Resources/Prototypes/Loadouts/Jobs/Medical/chief_medical_officer.yml
> +# Headset
в 220 перенести

2024-10-04 08:39 UTC, Surani1 commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - Cello`
was????

2024-10-04 08:39 UTC, Surani1 commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +- type: loadoutGroup
220

2024-10-04 08:39 UTC, Surani1 commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +- type: loadoutGroup
220

2024-10-04 08:39 UTC, Surani1 commented on Resources/Prototypes/Loadouts/role_loadouts.yml
> +  - BartenderJumpsuit
Это зачем

2024-10-04 08:39 UTC, Surani1 commented on Resources/Prototypes/SS220/Loadouts/loadout_groups.yml
> - # Сервисный работник (Начало)
????

2024-10-04 08:39 UTC, Surani1 commented on Resources/Prototypes/SS220/Loadouts/role_loadouts.yml
> +  - IAABackpacks #ss220 iaa loadout fix\
у fix/ черточку убрать, для красоты.

2024-10-05 17:48 UTC, EstKemran commented
Надо будет ещё и у ролей с startingGear убрать гарнитуры

2024-10-13 12:34 UTC, Surani1 commented
@stalengd закрывай

2024-10-13 12:37 UTC, closed without merging