Minor things
SerbiaStrong-220/space-station-14 pull request #2024
Opened 2024-10-07 01:49 UTC by TryHardo7

1) Исправлена сигарета Nomad's - теперь курящий не будет орать, его не будет трясти и выводить на экран сообщения. Задуманный функционал сохранён (для этого создан новый реагент, который не синтезируется и есть только в этой сигарете)

2) Новая крайне эффективная мета борьбы с сухожилиями: просто их жрать...будучи человеком...теперь они острые и колючие не только когда снаружи, но и когда внутри. Приятного аппетита!
![image](https://github.com/user-attachments/assets/05a74d7c-7f04-414a-a0df-d3ec71a340b3)

3) Добавлено наше отечественное мыло! из соплей...зато наше.

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

:cl: Lancevrot
- tweak: Исправлен эффект сигарет Номадс!
- tweak: Для любителей поедать сухожилия добавлены особые специи!

2024-10-07 13:55 UTC, Surani1 requested changes
Основные моменты подметил, по прототипу мыла - не проверял, но верю что он хороший. Проверить Parent только надо и лишнее делитнуть если это уже указано в наследовании

2024-10-07 13:55 UTC, Surani1 commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/janitorial/soap.ftl
> +ent-SnotSoap = соплемыло
перенести FTL в нашу папку

2024-10-07 13:55 UTC, Surani1 commented on Resources/Locale/ru-RU/reagents/meta/medicine.ftl
> +reagent-name-nicotizine = Никотизин
FTL в нашу папку

2024-10-07 13:55 UTC, Surani1 commented on Resources/Locale/en-US/reagents/meta/medicine.ftl
> +reagent-name-nicotizine = nicotizine
FTL в нашу папку

2024-10-07 13:55 UTC, Surani1 commented on Resources/Prototypes/SS220/Entities/Objects/Specific/Janitorial/soap.yml
> +    fixtures:
у тебя разве в parent это всё не наследуется?

2024-10-07 13:55 UTC, Surani1 commented on Resources/Prototypes/Entities/Objects/Misc/kudzu.yml
> +          - ReagentId: Razorium #SS220 bon appétit
лучше красиво сделай
```
#SS220 bon appétit begin
 - ReagentId: Razorium
            Quantity: 7
#SS220 bon appétit end
```

2024-10-07 13:55 UTC, Surani1 commented on Resources/Prototypes/SS220/Entities/Objects/Specific/Janitorial/soap.yml
> +  - type: ClusterGrenade
какую задачу несёт этот компонент? Типо когда мыло на полу, оно может развалиться?

2024-10-07 14:15 UTC, TryHardo7 commented on Resources/Prototypes/SS220/Entities/Objects/Specific/Janitorial/soap.yml
> +  - type: ClusterGrenade
да, оно разлетается на мелкие как кластерное синди

2024-10-07 14:17 UTC, TryHardo7 commented on Resources/Prototypes/SS220/Entities/Objects/Specific/Janitorial/soap.yml
> +    fixtures:
с этим наследованием и проблема...

2024-10-07 15:38 UTC, EstKemran commented
Надо будет нам опять помучить друг друг :)

2024-10-07 15:45 UTC, TryHardo7 commented
кто бы мог подумать что добавить простое мыло может быть так сложно. 

> Надо будет нам опять помучить друг друг :)

я как раз планирую ещё партию пачек сигарет сбахать

2024-10-09 19:54 UTC, DexlerXD approved these changes

2024-10-10 16:04 UTC, merged