Fract war ebent update v0.7
SerbiaStrong-220/space-station-14 pull request #2034
Opened 2024-10-08 16:09 UTC by Kirus59

## Описание PR

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

no cl.

2025-01-21 17:41 UTC, stalengd requested changes

2025-01-21 17:41 UTC, stalengd commented on Content.Shared/SS220/EventCapturePoint/EventCapturePointComponent.cs
> +    public float RetentionTimeForWP = 15;
1. тип должен быть TimeSpan
2. не нужно сокращать в названиях

2025-01-21 17:41 UTC, stalengd commented on Content.Shared/SS220/PlacerItem/PlacerItemComponent.cs
> +    public float DoAfter = 0;
TimeSpan

2025-01-22 17:26 UTC, stalengd approved these changes

2025-01-22 18:15 UTC, stalengd requested changes

2025-01-22 18:15 UTC, stalengd commented on Content.Server/Weapons/Ranged/Systems/GunSystem.cs
> +                                rayCastResults.RemoveAll(r => resultsToRemove.Contains(r));
```suggestion
                                for (var i = 0; i < rayCastResults.Count; i++)
                                {
                                    var attemptEv = new HitscanAttempt(lastUser);
                                    RaiseLocalEvent(rayCastResults[i].HitEntity, ref attemptEv);

                                    if (attemptEv.Cancelled)
                                    {
                                        rayCastResults.RemoveAt(i);
                                        i--;
                                    }
                                }
```

2025-01-22 23:24 UTC, stalengd approved these changes

2025-01-23 17:03 UTC, Kirus59 commented
@stalengd 
![image](https://github.com/user-attachments/assets/59d752da-7a2b-4957-8d71-ca51196292e8)

2025-01-23 18:23 UTC, merged