PrisonerIDCard
SerbiaStrong-220/space-station-14 pull request #2037
Opened 2024-10-08 19:45 UTC by EstKemran

## Описание PR
Чтобы карта отображала иконку, пришлось добавить джобку

**Медиа**
![изображение](https://github.com/user-attachments/assets/cee49ecb-05d4-47ee-9ac3-51e6c66259eb)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Kemran
- add: Добавлена ID карта заключённого. Можно найти в гардеробе заключённого в количестве двух штук.

2024-10-08 20:03 UTC, EstKemran commented
Опять эти гномы кладут чекер

2024-10-09 06:35 UTC, Alwayswannahunt commented
Плавающая ошибка, перезапустить бы тесты.

2024-10-09 06:43 UTC, Alwayswannahunt requested changes
Небольшие очепятки

2024-10-09 06:43 UTC, Alwayswannahunt commented on Resources/Locale/ru-RU/ss220/job/job-description.ftl
> +job-description-magistrate = Магистрат обязан Быть гарантом корпоративного закона, координировать юридический отдел.
"Быть" либо уж всё слово заглавными, либо очепятка.

2024-10-09 06:43 UTC, Alwayswannahunt commented on Resources/Locale/ru-RU/ss220/job/job-description.ftl
> +job-description-prisoner = Заключённый космической станции.. Что может быть лучше?
Либо точка, либо многоточие.

2024-10-09 20:04 UTC, DexlerXD approved these changes

2024-10-09 20:04 UTC, DexlerXD commented
мои последние мерджи

2024-10-09 20:07 UTC, merged