FIX the tourniquet and the medic's belt
SerbiaStrong-220/space-station-14 pull request #2047
Opened 2024-10-10 17:26 UTC by Tris0r

## Описание PR
Теперь жгут можно будет положить в пояс медика.

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
🆑 Cortez
- add: Теперь жгут можно класть в пояс медика

2024-10-10 19:34 UTC, Kirus59 requested changes

2024-10-10 19:34 UTC, Kirus59 commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        - Tourniquet #SS220 Fix
В комменте допиши какой конкретно фикс (либо ссылку на ишуе)

2024-10-10 19:34 UTC, Kirus59 commented on Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
> +        - Tourniquet #SS220 FIX
И тут

2024-10-10 19:34 UTC, Kirus59 commented on Resources/Prototypes/tags.yml
> +#SS220 FIX End
И тут

2024-10-10 19:49 UTC, Tris0r commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        - Tourniquet #SS220 Fix
Я до этого всегда писал просто сс220 фикс и принимали

2024-10-10 20:36 UTC, Kirus59 commented on Resources/Prototypes/tags.yml
> +#SS220 FIX End
А и кстати, этот тег перенести в `Prototypes/SS220/tags.yml`

2024-10-11 05:16 UTC, Kirus59 approved these changes

2024-10-11 05:19 UTC, merged

2024-10-11 05:27 UTC, Tris0r commented
Победа!!