No vocal when muzzled
SerbiaStrong-220/space-station-14 pull request #2053
Opened 2024-10-12 07:01 UTC by SkaldetSkaeg

## Описание PR
Очень старая проблема, которая не решается оффами, сделал так. Хз, стоит ли им такое загонять?
Давно хотел сесть за это PR, но никак не находил сил. 

**Медиа**

**Проверки**
- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl:
- add: Добавлен компонент позволяющий надетой вещи блокировать звуковые эмоции
- tweak: Намордник теперь блокирует звуковые эмоции

2024-10-12 14:50 UTC, Kirus59 requested changes

2024-10-12 14:50 UTC, Kirus59 commented on Content.Server/SS220/Speech/EntitySystems/AddMutedClothingSystem.cs
> +        ent.Comp.IsActive = true;
Можно сократить
```
if (EnsureComp<MutedComponent>(args.Wearer, out _))
    ent.Comp.IsActive = false;
else
    ent.Comp.IsActive = true;
```
Одна из перегрузок `EnsureComp` возвращает true если компонент уже существует, в ином случае добавляет компонент и возвращает false

2024-10-12 14:50 UTC, Kirus59 commented on Content.Server/SS220/Speech/EntitySystems/AddMutedClothingSystem.cs
> +        }
`HasComp` лишний, ибо в `RemComp` также есть проверка на его наличие перед удалением

2024-10-12 14:57 UTC, Kirus59 commented on Content.Server/SS220/Speech/EntitySystems/AddMutedClothingSystem.cs
> +        ent.Comp.IsActive = true;
Также `MutedComponent` блокирует не только эмоуты, а еще и обычную речь, что в контексте кляпа не является хорошим решением, т.к. у него речь должна заменяться на Ммпмв!

Ну и еще этот компонент же будет блокировать все эмоуты, но по идее человек с кляпом может же например моргать, исполнять какие-либо жесты и т.д.

2024-10-12 15:55 UTC, SkaldetSkaeg commented on Content.Server/SS220/Speech/EntitySystems/AddMutedClothingSystem.cs
> +        ent.Comp.IsActive = true;
ну, эмоции он не блокирует, а просто их звук убирает.
Насчет сокращения, тут у тебя пиво...

2024-10-12 15:57 UTC, SkaldetSkaeg commented on Content.Server/SS220/Speech/EntitySystems/AddMutedClothingSystem.cs
> +        }
тут согласен, тут пиво мое

2024-10-12 15:58 UTC, SkaldetSkaeg commented on Content.Server/SS220/Speech/EntitySystems/AddMutedClothingSystem.cs
> +        ent.Comp.IsActive = true;
если человек был замучен, и наденет/снимет, то будет прикол

2024-10-12 16:22 UTC, Kirus59 commented on Content.Server/SS220/Speech/EntitySystems/AddMutedClothingSystem.cs
> +        ent.Comp.IsActive = true;
> ну, эмоции он не блокирует, а просто их звук убирает. Насчет сокращения, тут у тебя пиво...

Насчет пива не понял, а по компоненту - да сорян ошибся, но говорить он все же не позволяет....

2024-10-14 19:36 UTC, UrPrice commented
Ну закрыто типа: https://github.com/space-wizards/space-station-14/pull/32779 ?

2024-10-14 19:37 UTC, UrPrice commented
Или где? Куда, как? У нас продолжаем или офам уйдёт?

2024-10-15 03:45 UTC, SkaldetSkaeg commented
> Ну закрыто типа: [space-wizards#32779](https://github.com/space-wizards/space-station-14/pull/32779) ?

это другое

2024-10-15 03:45 UTC, SkaldetSkaeg commented
> Или где? Куда, как? У нас продолжаем или офам уйдёт?

я думаю, там система достаточно говняная.
Либо костыль делать свой, либо рефактор офам делать, вот я думаю

2024-11-06 03:59 UTC, closed without merging

2024-11-06 08:16 UTC, UrPrice commented
:catdespair: