add suffix for time loadout clothing
SerbiaStrong-220/space-station-14 pull request #2071
Opened 2024-10-13 17:30 UTC by Theywod

## Описание PR
- Добавлен суффикс в прототипы вещей, доступных для выбора в лодауте после определенной продолжительности игры на сервере. Суффикс - За время в игре.
- Теперь весь сет мужика для клоуна доступен по подписке Большой Шлёпа. Ранее была ошибка, при которой часть сета доступна при Большом Шлёпе, а часть - при Золотом.

**Медиа**
![изображение](https://github.com/user-attachments/assets/f6d4b212-3d50-4c70-9521-65c48f9f2bd6)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Theywod
- fix: Теперь вся одежда набора "Мужик" для клоуна доступна по подписке "Большой Шлёпа"

2024-10-13 18:28 UTC, stalengd commented
Во-первых, ты зря два изменения в один PR запихал, ну ладно
Во-вторых, @EstKemran есть апрув на изменение лодаута?

2024-10-13 19:02 UTC, stalengd approved these changes

2024-10-13 21:48 UTC, stalengd requested changes

2024-10-13 21:48 UTC, stalengd commented on Resources/Prototypes/SS220/Entities/Clothing/Head/hats.yml
> +    sprite: SS220/Clothing/Head/Hats/whitecapcap.rsi
Это почему изменено?

2024-10-13 21:50 UTC, Surani1 requested changes
Нужно сделать FTL с локализацией, и заменить ```Время в игре``` на ссылку FTL'a. Соблюдаем правило - прототипы пишем на английском, а локализацию делаем на русском.

2024-10-13 21:50 UTC, Surani1 commented on Resources/Prototypes/SS220/Entities/Clothing/Head/hats.yml
> +    sprite: SS220/Clothing/Head/Hats/whitecapcap.rsi
???

2024-10-13 21:50 UTC, Surani1 commented on Resources/Prototypes/SS220/Loadouts/Jobs/Civilian/clown.yml
> +    proto: BigShlopaSponsorTier
???

2024-10-13 22:12 UTC, Surani1 commented
уточнение - отмена по полному FTL, для её реализации нужно каждому прототипу прописывать локализацию. Пропиши только для тех, у которых она есть ( прототипы с неймом на английском )

2024-10-14 05:13 UTC, Theywod commented on Resources/Prototypes/SS220/Entities/Clothing/Head/hats.yml
> +    sprite: SS220/Clothing/Head/Hats/whitecapcap.rsi
Обычная фуражка не является предметом за время. При этом она наследуется от белой фуражки капитана, имеет ее спрайт. Наследование суффикса для нее не нужно, поэтому я просто установил в качестве родителя базу и поставил спрайты фуражки капитана.

2024-10-14 17:15 UTC, stalengd commented on Resources/Prototypes/SS220/Entities/Clothing/Head/hats.yml
> +    sprite: SS220/Clothing/Head/Hats/whitecapcap.rsi
Окей

2024-10-14 17:16 UTC, stalengd commented
@Theywod внеси изменения, которые запросил Сурани, и всё

2024-10-14 17:17 UTC, EstKemran approved these changes

2024-10-20 09:46 UTC, stalengd requested changes
Поправить метки

2024-10-20 09:46 UTC, stalengd commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigars/case.yml
> +  parent: [ BaseStorageItem, BaseBagOpenClose ]
Метки на изменения SS220

2024-10-20 09:46 UTC, stalengd commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigars/case.yml
> +    storedRotation: 90
Метки на изменения SS220 на весь этот блок

2024-10-20 09:46 UTC, stalengd commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigars/case.yml
> +#SS220-add-time-suffix-loadout-begin
Почему метка здесь?

2024-10-20 09:46 UTC, stalengd commented on Resources/Prototypes/Entities/Objects/Consumable/Smokeables/Cigars/case.yml
> +  - type: Appearance
Метки на изменения SS220 на весь этот блок

2024-10-20 09:46 UTC, stalengd commented on Resources/Prototypes/Entities/Clothing/Masks/masks.yml
> +#SS220-add-time-suffix-loadout-end
Нельзя просто взять и поставить метки где-то, они должны быть только у/вокруг непосредственно изменений и не захватывать неизменённые части

2024-10-20 17:26 UTC, EstKemran approved these changes

2024-10-24 13:42 UTC, Theywod commented
Это ужас

2024-10-24 20:53 UTC, stalengd approved these changes
Ну вот теперь вроде всё как надо, молодец

2024-10-24 20:53 UTC, merged