Fix Airlocks on NukeOps Outpost
SerbiaStrong-220/space-station-14 pull request #2076
Opened 2024-10-13 22:57 UTC by NightmareStalker

## Описание PR

Все шлюзы со станционными доступами изменены на аналоги без доступов из-за рефактора шлюзов от оффов, отчего дополнительных доступов для Оперативников на их же базе не было.

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- fix: Исправлена проблема с доступами шлюзов на аванпосте Ядерных Оперативников

2024-10-13 22:59 UTC, Surani1 commented
Ща будем смотреть на чеки

2024-10-13 23:13 UTC, NightmareStalker commented
это такой конец
![image](https://github.com/user-attachments/assets/7c7c07fe-f1a3-44ba-b0b1-c729bb6a473f)

2024-10-13 23:15 UTC, Surani1 commented
чеки упали 
![itpedia-hot-tubs-hot-tubs](https://github.com/user-attachments/assets/c6c1ee7f-0ff6-485a-a3a1-3baf491d1b9c)

2024-10-13 23:15 UTC, NightmareStalker commented
> чеки упали ![itpedia-hot-tubs-hot-tubs](https://private-user-images.githubusercontent.com/154987464/376075864-c6c1ee7f-0ff6-485a-a3a1-3baf491d1b9c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NjE2MTAsIm5iZiI6MTcyODg2MTMxMCwicGF0aCI6Ii8xNTQ5ODc0NjQvMzc2MDc1ODY0LWM2YzFlZTdmLTBmZjYtNDg1YS1hM2ExLTNiYWY0OTFkMWI5Yy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QyMzE1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDIxMTY1YjY5NzdjMGNlMzI4ODZiY2FjMmQzNzg3MjI5NzYzOGExNmIyODFmNWQwZmVlY2Q4M2QwMjVkYmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DMZZMhiYgScHmC7hHOzupfWD8jMQ2pxKSpyBu0VDRMI) [ ![itpedia-hot-tubs-hot-tubs](https://private-user-images.githubusercontent.com/154987464/376075864-c6c1ee7f-0ff6-485a-a3a1-3baf491d1b9c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NjE2MTAsIm5iZiI6MTcyODg2MTMxMCwicGF0aCI6Ii8xNTQ5ODc0NjQvMzc2MDc1ODY0LWM2YzFlZTdmLTBmZjYtNDg1YS1hM2ExLTNiYWY0OTFkMWI5Yy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QyMzE1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDIxMTY1YjY5NzdjMGNlMzI4ODZiY2FjMmQzNzg3MjI5NzYzOGExNmIyODFmNWQwZmVlY2Q4M2QwMjVkYmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DMZZMhiYgScHmC7hHOzupfWD8jMQ2pxKSpyBu0VDRMI) ](https://private-user-images.githubusercontent.com/154987464/376075864-c6c1ee7f-0ff6-485a-a3a1-3baf491d1b9c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NjE2MTAsIm5iZiI6MTcyODg2MTMxMCwicGF0aCI6Ii8xNTQ5ODc0NjQvMzc2MDc1ODY0LWM2YzFlZTdmLTBmZjYtNDg1YS1hM2ExLTNiYWY0OTFkMWI5Yy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QyMzE1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDIxMTY1YjY5NzdjMGNlMzI4ODZiY2FjMmQzNzg3MjI5NzYzOGExNmIyODFmNWQwZmVlY2Q4M2QwMjVkYmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DMZZMhiYgScHmC7hHOzupfWD8jMQ2pxKSpyBu0VDRMI) [ ](https://private-user-images.githubusercontent.com/154987464/376075864-c6c1ee7f-0ff6-485a-a3a1-3baf491d1b9c.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NjE2MTAsIm5iZiI6MTcyODg2MTMxMCwicGF0aCI6Ii8xNTQ5ODc0NjQvMzc2MDc1ODY0LWM2YzFlZTdmLTBmZjYtNDg1YS1hM2ExLTNiYWY0OTFkMWI5Yy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QyMzE1MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDIxMTY1YjY5NzdjMGNlMzI4ODZiY2FjMmQzNzg3MjI5NzYzOGExNmIyODFmNWQwZmVlY2Q4M2QwMjVkYmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DMZZMhiYgScHmC7hHOzupfWD8jMQ2pxKSpyBu0VDRMI)

получается не ты проклят, а аутпост

2024-10-13 23:22 UTC, stalengd commented
Может позже посмотрю что с этим тестом

2024-10-16 17:04 UTC, stalengd commented on Resources/Maps/SS220/ss220-nukeoutpost.yml
> +      mapPaused: True
@UrPrice так и должно быть?

2024-10-16 18:58 UTC, UrPrice commented on Resources/Maps/SS220/ss220-nukeoutpost.yml
> +      mapPaused: True
@NightmareStalker убери конкретно строку `mapPaused: True` - должно помочь. Сам `- type: Map` можно оставить.

2024-10-16 18:59 UTC, UrPrice requested changes
Пометил место в файле выше

2024-10-16 20:00 UTC, NightmareStalker commented
только сейчас добрался...
ну
смотрим...

2024-10-16 20:25 UTC, NightmareStalker commented
победа

2024-10-17 06:09 UTC, stalengd commented
@UrPrice по мапперской части одобрено?

2024-10-17 06:19 UTC, UrPrice requested changes
Поправь остальные шлюзы тут и можно мерджить

2024-10-17 06:19 UTC, UrPrice commented on Resources/Maps/SS220/ss220-nukeoutpost.yml
>  - proto: AirlockScienceLocked
AirlockScienceLocked - здесь чего забыл заменить

2024-10-17 06:19 UTC, UrPrice commented on Resources/Maps/SS220/ss220-nukeoutpost.yml
>  - proto: AirlockMedicalLocked
Аналогично и тут

2024-10-17 10:45 UTC, NightmareStalker commented
> Поправь остальные шлюзы тут и можно мерджить

проебался слегка, да...
исправил

2024-10-17 11:02 UTC, UrPrice requested changes

2024-10-17 11:02 UTC, UrPrice commented on Resources/Maps/SS220/ss220-nukeoutpost.yml
> -    - type: Reflect
При пересохранении удалилась настройка компоненты. Надо вернуть её в отключённом состоянии либо перекинуть в MissingComponent (удалить через VV)

2024-10-17 11:56 UTC, UrPrice approved these changes
Можно мёрджить

2024-10-17 17:05 UTC, merged