Emagged SecTech
SerbiaStrong-220/space-station-14 pull request #2080
Opened 2024-10-14 11:35 UTC by lexaSvarshik

## Описание PR

Появилась возможность емага СБтех'а. Ассортимент: 
- 1 ед. свисток ЯО
- 1 ед. боевые перчатки
- 1 ед. разрывная граната
- 1 ед. дымовая граната
- 1 ед. ЭМИ граната
- 1 ед. стальной дубинка
- 2 ед. метательные ножи

**Медиа**

![изображение](https://github.com/user-attachments/assets/31194a1b-226e-46fa-8893-560d9160b2a4)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлена возможность ЕМАГ'а СБтех!

2024-10-14 16:31 UTC, UrPrice requested changes
Протестируй, пожалуйста, пополнение емагнутого СБтеха набором для пополнения и сообщи, пополняет ли он те товары, что появились от ЕМАГа.

2024-10-14 18:53 UTC, lexaSvarshik commented
@UrPrice Да, пополняет. Но это в целом проблема с любым пополнением автоматов (скажем, если емагнуть химкомат, а потом пополнить, то токсин тоже пополнится). Из самого пополнения вещи из емагнутого инвентаря не выпадают.

2024-10-14 19:29 UTC, UrPrice commented
> @UrPrice Да, пополняет. Но это в целом проблема с любым пополнением автоматов (скажем, если емагнуть химкомат, а потом пополнить, то токсин тоже пополнится). Из самого пополнения вещи из емагнутого инвентаря не выпадают.

Понял, спасибо. Тогда на основе этого дополнительно запросим апрув Адуча.

2024-10-14 19:30 UTC, UrPrice commented
@Ady4ik Посмотри, пожалуйста, и согласуй, при учёте, что это можно пополнить при помощи набора пополнения. Возможно его бы в ишуе записать.

2024-10-17 05:55 UTC, Ady4ik approved these changes
Посмотрим по наполнению после мерджа

2024-10-17 05:58 UTC, UrPrice approved these changes

2024-10-18 21:28 UTC, stalengd approved these changes

2024-10-18 21:29 UTC, merged