Meat crates
SerbiaStrong-220/space-station-14 pull request #2089
Opened 2024-10-14 20:43 UTC by lexaSvarshik

## Описание PR

wip 

todo:
- [x] Контейнер экзотического мяса
- [ ] Контейнер обычного мяса
- [ ] Заказ контейнеров в карго
- [ ] Добавить контейнер мяса в рандомное событие подарков от НТ
- [ ] Установить точное наполнение

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: В заказы карго добавлены ящики мяса и экзотического мяса!

2024-10-16 07:24 UTC, lexaSvarshik commented
![изображение](https://github.com/user-attachments/assets/2de00cde-8cb3-495e-abbd-bc8f3aaf733e)
я в ахуе

2024-10-16 18:19 UTC, Kirus59 requested changes

2024-10-16 18:19 UTC, Kirus59 commented on Resources/Prototypes/GameRules/cargo_gifts.yml
> +
?

2024-10-16 18:19 UTC, Kirus59 commented on Resources/Prototypes/SS220/Catalog/Fills/Crates/food.yml
> +  description: Contains over 10 of unusual meat from all corners of the galaxy.
```suggestion
  description: Contains over 10 pieces of unusual meat from all corners of the galaxy.
```

2024-10-16 19:01 UTC, lexaSvarshik commented on Resources/Prototypes/GameRules/cargo_gifts.yml
> +
Ну там была какая-то табуляция лишняя, я её убрал видать, яхз

2024-10-17 05:52 UTC, Ady4ik approved these changes
По ценам посмотрим после мерджа

2024-10-17 06:02 UTC, Kirus59 commented on Resources/Prototypes/GameRules/cargo_gifts.yml
> +
> Ну там была какая-то табуляция лишняя, я её убрал видать, яхз

В оффовских файлах лучше так не делать, т.к. это может вызвать конфликты при апстриме

2024-10-18 11:56 UTC, Kirus59 commented on Resources/Prototypes/SS220/Catalog/Fills/Crates/food.yml
> +      prob: 0.0001 # never. 0.01%
@Ady4ik Тут хоть и очень низкий, но все же шанс на спавн мяса корги, что является хайриском, оставляем?

2024-10-19 18:31 UTC, Ady4ik commented on Resources/Prototypes/SS220/Catalog/Fills/Crates/food.yml
> +      prob: 0.0001 # never. 0.01%
Пусть будет, fo rofl

2024-10-19 19:16 UTC, Kirus59 approved these changes

2024-10-19 19:16 UTC, merged