[WIP]
SerbiaStrong-220/space-station-14 pull request #2090
Opened 2024-10-14 20:52 UTC by Surani1

## Описание PR
Рефактор гайдбуков, пока PR заброшен, как только руки дойдут пойду делать

- [ ] полный перевод гайдбуков
- [ ] перенос КЗ
- [ ] Перенос СРП СБ
- [ ] Добавление антагов 220
- [ ] Добавление рас 220
- [ ] Добавление дополнительных гайдов
- [ ] Расширение информации по игре

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Surani
- tweak: Изменены гайдбуки в игре.

2024-10-16 08:34 UTC, Surani1 commented
А почему китовраса ревью?

2024-10-16 14:34 UTC, Kit0vras requested changes
Просмотрел только часть, пока было время

2024-10-16 15:02 UTC, Surani1 commented on Resources/ServerInfo/SS220/Guidebook/Security/Forensics.xml
> +  Также можно снять чьи-то отпечатки пальцев на месте происшествия, если заставить их снять перчатки и приложить к пальцам пластинку для криминалистики. Не нужно бежать возвращаться к [color=#a4885c]
нах ты это ревьюишь

2024-10-16 15:03 UTC, Surani1 commented
> Просмотрел только часть, пока было время

Я хуй знает зачем прайс запросил ревью, ибо это паста старых гайдбуков, а не создание новых. Я ничего еще пока не сделал, не считая переноса и разбора работы XML. Драфт висит же епта

2024-10-16 16:29 UTC, Kit0vras commented
https://cdn.discordapp.com/attachments/1180626739005767751/1293281987515256953/rendered.gif?ex=6710b175&is=670f5ff5&hm=f01ee2a74619781d748287ba95b26738694cc394ec075be29f59d2a3e146f483&

2024-10-17 15:07 UTC, UrPrice commented
> > Просмотрел только часть, пока было время
> 
> Я хуй знает зачем прайс запросил ревью, ибо это паста старых гайдбуков, а не создание новых. Я ничего еще пока не сделал, не считая переноса и разбора работы XML. Драфт висит же епта

Из-за большого количества текстов, запросил его как редактора на логические, синтаксические, орфографические ошибки конкретно в тексте, чтобы потом поправлять всё это, несмотря на то, что это копипаста

2024-10-17 18:48 UTC, Surani1 commented
> ## Описание PR
> Рефактор гайдбуков, пока PR заброшен, как только руки дойдут пойду делать
> 
> * [ ]  перенос КЗ
> 
> **Медиа**
> 
> **Проверки**
> 
> * [ ]  PR полностью завершён и мне не нужна помощь чтобы его закончить.
> * [ ]  Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
> * [ ]  Я внимательно просмотрел все свои изменения и багов в них не нашёл.
> * [ ]  Я запускал локальный сервер со своими изменениями и всё протестировал.
> * [ ]  Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.
> 
> **Изменения** 🆑 Surani
> 
> * tweak: Изменены гайдбуки в игре.

2024-10-23 19:25 UTC, lexaSvarshik commented
https://github.com/space-wizards/space-station-14/pull/32894
Оффы переделывают инженерный гайдбук

2024-11-01 17:25 UTC, ArtisticRoomba commented
Hey y'all, I saw that you referenced my PR for your fork's guidebook update. Just wanted to make it known that I fucked up Git and reopened my PR, space-wizards#33062. 

It'll probably be a while before it's finished but just know I'm still working on it. 

Cheers :)

2024-11-02 19:47 UTC, UrPrice commented
> Hey y'all, I saw that you referenced my PR for your fork's guidebook update. Just wanted to make it known that I fucked up Git and reopened my PR, [space-wizards#33062](https://github.com/space-wizards/space-station-14/pull/33062).
> 
> It'll probably be a while before it's finished but just know I'm still working on it.
> 
> Cheers :)

Ty for info, mate
We'll keep this changes in mind

2024-11-05 21:44 UTC, UrPrice commented
@Surani1 А чего тут осталось доделать? Помочь мб?

2024-11-20 13:42 UTC, Surani1 commented
> @Surani1 А чего тут осталось доделать? Помочь мб?

Уже не помню, я забил и продвижения не будет. Можете посмотреть, да доделать

2024-12-10 15:45 UTC, UrPrice commented
Доделал гайдбук, добавил гиф в медиа. Вроде из КЗ это всё.

2024-12-10 15:45 UTC, UrPrice commented
@Kit0vras посмотришь на орфографию? Я хоть и из Вики копировал, но всё равно.

2024-12-10 19:00 UTC, stalengd commented
> @Kit0vras посмотришь на орфографию? Я хоть и из Вики копировал, но всё равно.

Можешь spellcheck на vs code поставить

2024-12-23 06:12 UTC, merged