Vox not rotting
SerbiaStrong-220/space-station-14 pull request #2096
Opened 2024-10-15 20:09 UTC by EstKemran

## Описание PR
Так как я не знаю как убрать наследуемый компонент из прототипа, пришлось создать новый base прототип без компонента, который мне не нужен

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Kemran
- tweak: Теперь воксы не гниют!

2024-10-16 11:44 UTC, UrPrice commented
Попробовал пересобрать с `missingComponent`, но он работает только для карт. Вероятно наследуемый компонент всё же не убрать.

2024-10-16 12:01 UTC, Kirus59 requested changes

2024-10-16 12:01 UTC, Kirus59 commented on Resources/Prototypes/Entities/Mobs/Species/vox.yml
> +  parent: BaseMobSpeciesOrganicNotPerishable #SS220-Vox not rotting
Попробуй вместо изменения наследования написать так:
```
- type: Rotting
  dealDamage: false
```

2024-10-16 12:01 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Mobs/Species/base.yml
Соответственно и это не нужно будет

2024-10-16 18:21 UTC, EstKemran commented on Resources/Prototypes/Entities/Mobs/Species/vox.yml
> +  parent: BaseMobSpeciesOrganicNotPerishable #SS220-Vox not rotting
Добавил компонент в `Species\vox.yml`:
![изображение](https://github.com/user-attachments/assets/bbf8f2bf-0180-43cd-80dc-b4d4aa15cbb5)

Вокс гниёт, получает клеточный урон:
![изображение](https://github.com/user-attachments/assets/4a7330f4-d374-4c22-9fdd-cbee2a74f4bb)

2024-10-16 19:00 UTC, Kirus59 commented on Resources/Prototypes/Entities/Mobs/Species/vox.yml
> +  parent: BaseMobSpeciesOrganicNotPerishable #SS220-Vox not rotting
Аааа, я компонентом ошибся, сорри.
Попробуй написать
```
- type: Perishable
  forceRotProgression: false
```

2024-10-16 20:31 UTC, EstKemran commented on Resources/Prototypes/Entities/Mobs/Species/vox.yml
> +  parent: BaseMobSpeciesOrganicNotPerishable #SS220-Vox not rotting
> Аааа, я компонентом ошибся, сорри. Попробуй написать
> 
> ```
> - type: Perishable
>   forceRotProgression: false
> ```

:hampster:

```- type: entity
  parent: BaseMobSpeciesOrganic
  id: BaseMobVox
  abstract: true
  components:
  - type: Perishable
    forceRotProgression: false 
```
    
Результат:
![изображение](https://github.com/user-attachments/assets/3fce3bdb-8cd8-428a-9ae8-bc74e6fe1ac9)

2024-10-16 21:14 UTC, EstKemran commented on Resources/Prototypes/Entities/Mobs/Species/vox.yml
> +  parent: BaseMobSpeciesOrganicNotPerishable #SS220-Vox not rotting
Ещё раз проверил, всё так же
![изображение](https://github.com/user-attachments/assets/186474e2-06f0-42bf-8218-74ce58e946ba)

2024-10-17 06:10 UTC, Kirus59 approved these changes

2024-10-18 07:28 UTC, Ady4ik approved these changes
Буренке отдал, добавит на вики

2024-10-18 07:28 UTC, merged