Nukies can recall evac via syndicate comms
SerbiaStrong-220/space-station-14 pull request #2100
Opened 2024-10-16 12:18 UTC by lexaSvarshik

## Описание PR

Консоль связи ядерных оперативников теперь может вызвать/отозвать эвак. Для пресечения сценария, когда опера прибывают на станцию, а шаттл эвакуации стыкуется через три минуты. Согласно [обсуждению ](https://discord.com/channels/1158128815311171638/1267573532003532961)в qa

**_DNM до момента аппрува._**

**Медиа**

![изображение](https://github.com/user-attachments/assets/da8184cb-d634-4af5-b7b6-80e62dca9dbb)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Svarshik
- tweak: Ядерные оперативники могут отзывать шаттл эвакуации!

2024-10-16 15:46 UTC, Surani1 commented
она раньше могла это делать же, не? Я по этой причине замаппил 2 консоли отзыва связи. Одна на шаттле, вторая на аванпосте. Ибо админы сами отзывали

2024-10-16 16:09 UTC, lexaSvarshik commented
> она раньше могла это делать же, не? 

Я тоже так думал. Видать, когда-то изменили, хотя по истории правок, эту строчку не трогали два года. Потестив, оказалось, что у них этой возможности почему-то нет. Я поменял, теперь она будет.

2024-10-17 05:56 UTC, Ady4ik requested changes
Отказано, так как решение вопроса вызова эвака при ЯО будет решено по другому.

2024-10-17 06:57 UTC, UrPrice commented
> Отказано, так как решение вопроса вызова эвака при ЯО будет решено по другому.

Тут скорее вопрос в том, что если оперативники после объявления войны промедлят. То при вызове эвакуации экипажем после срока ограничения, оперативники не смогут никак его прервать. В этом же случае нужно будет давать больший таймаут связи, не 20, а 30 минут.

2024-10-27 12:42 UTC, closed without merging