Janitor new loadout
SerbiaStrong-220/space-station-14 pull request #2101
Opened 2024-10-16 15:17 UTC by Tris0r

## Описание PR
Одежда JR для лодаута уборщика. Время - 70ч

**Медиа**
![JanitorJR](https://github.com/user-attachments/assets/4028d117-7bf3-40e1-acdf-8cf0f90d86ba)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
🆑 Cortez, Лорд Розовая Тень
- add: Добавлена одежда JR в лодаут уборщика

2024-10-16 15:45 UTC, Surani1 requested changes
Перенести FTL в 220 и аппрув

2024-10-16 15:45 UTC, Surani1 commented on Resources/Locale/en-US/preferences/loadout-groups.ftl
> +loadout-group-janitor-belt = Janitor belt
220

2024-10-16 16:04 UTC, Tris0r commented
Пока не аппрувайте

2024-10-16 16:21 UTC, Tris0r commented
Теперь можно

2024-10-16 17:44 UTC, stalengd requested changes
Добавь суффикс "За время в игре" этим шмоткам в .ftl, проверь что работает

2024-10-16 19:27 UTC, stalengd requested changes

2024-10-16 19:27 UTC, stalengd commented on Resources/Locale/ru-RU/ss220/clothing/Belt/belts.ftl
> +    .desc = JR, За время в игре
```suggestion
    .suffix = JR, За время в игре
```

2024-10-16 19:27 UTC, stalengd commented on Resources/Locale/ru-RU/ss220/clothing/Hands/gloves.ftl
> +    .desc = JR, За время в игре
```suggestion
    .suffix = JR, За время в игре
```

2024-10-16 19:27 UTC, stalengd commented on Resources/Locale/ru-RU/ss220/clothing/Head/hardhats.ftl
> +    .desc = JR, За время в игре
```suggestion
    .suffix = JR, За время в игре
```

2024-10-16 19:27 UTC, stalengd commented on Resources/Locale/ru-RU/ss220/clothing/Head/hats.ftl
> +    .desc = JR, За время в игре
```suggestion
    .suffix = JR, За время в игре
```

2024-10-16 19:27 UTC, stalengd commented on Resources/Locale/ru-RU/ss220/clothing/Head/hats.ftl
> +    .desc = JR, За время в игре
```suggestion
    .suffix = JR, За время в игре
```

2024-10-16 19:27 UTC, stalengd commented on Resources/Locale/ru-RU/ss220/clothing/Shoes/shoes.ftl
> +        .desc = JR, За время в игре
```suggestion
    .suffix = JR, За время в игре
```

2024-10-16 23:44 UTC, SmilMolch commented
только открыл золотой вантуз, придётся опять ебашить на новый прикид

2024-10-17 05:59 UTC, stalengd approved these changes

2024-10-17 06:00 UTC, merged