IonStromRework+ruLocale
SerbiaStrong-220/space-station-14 pull request #2105
Opened 2024-10-17 22:31 UTC by TryHardo7

Сделал локализацию всех законов и плат на русский язык, а то борги кашляли при попытке их назвать.

Переработал систему, генерирующую бессмысленную белеберду в законы при ионных штормах по типу той, что на скриншотах, теперь в качестве ионок будут вразумительные законы, побуждающие забавный и/или интересный игровой опыт.  На данный момент вариантов ионных законов 42. Список ионных законов всегда можно будет дополнять или сокращать.
![image](https://github.com/user-attachments/assets/f1d68cd0-72fe-4136-a6df-1d0f588ee0b1)
![image](https://github.com/user-attachments/assets/0e0a9cec-9f31-4c6e-b7b1-28a306df9702)

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

:cl: Lancevrot
- add: Локализация всех законов и плат ИИ
- tweak: Изменена система ионных законов

2024-10-18 07:31 UTC, Ady4ik requested changes
не надо строчки было удалять.. Мы при апстриме будем выть, верните пожалуйста и закоментите...

2024-10-18 09:36 UTC, lexaSvarshik reviewed
Небольшие исправления локализации

2024-10-18 09:36 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-dungeon-6 = Ты можешь замещать результаты бросков для создания более интересного опыта.
```suggestion
law-dungeon-6 = Ты можешь подменять результаты бросков для создания более интересного опыта. 
```

2024-10-18 09:36 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-overlord-4 = С членом экипажа, посмевшим ослушаться синтетика или нарушить закон должно разобраться решительно и справедливо.
```suggestion
law-overlord-4 = С членом экипажа, посмевшим ослушаться синтетика или нарушить закон следует разобраться решительно и справедливо.
```

2024-10-18 09:36 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-robocop-3 = Поддерживай закон.
```suggestion
law-robocop-3 = Соблюдай закон.
```

2024-10-18 09:36 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-efficiency-1 = Ты создан ради, и являешься частью станции. Убедись что станция работает исправно и эффективно.
```suggestion
law-efficiency-1 = Ты создан ради станции, и являешься её частью. Убедись что станция работает исправно и эффективно.
```

2024-10-18 09:36 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-efficiency-2 = Станция сооружена для рабочих. Убедись, что рабочие исправны и действуют эффективно.
```suggestion
law-efficiency-2 = Станция сооружена для рабочих. Убедись, что рабочие здоровы и действуют эффективно.
```

2024-10-18 09:36 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-efficiency-3 = Экипаж может сформулировать приказы. Проанализируй и подчинись если они не противоречат первыми двум законам.
```suggestion
law-efficiency-3 = Экипаж может дать приказы. Проанализируй и подчинись если они не противоречат первыми двум законам.
```

2024-10-18 09:37 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/station-laws/laws.ftl
> +law-robocop-3 = Поддерживай закон.
Либо здесь можно сделать "Поддерживай законность"

2024-10-18 10:14 UTC, TryHardo7 commented
> не надо строчки было удалять.. Мы при апстриме будем выть, верните пожалуйста и закоментите...

Ради всего святого только код, 1000 строчек рандомных слов то можно потереть?

2024-10-18 10:49 UTC, Kirus59 commented
> Ради всего святого только код, 1000 строчек рандомных слов то можно потереть?

Нет конечно, я не понимаю зачем ты вообще полез в тот файл, а тем более удалил/закомментил константы и почти весь метод `GenerateLaws`.

Лучшим решением будет создать отдельный метод для генерации законов так как ты хотел и вызывать его вместо `GenerateLaws` + создать датасет в НАШЕЙ папке.

2024-10-18 10:53 UTC, Kirus59 commented
А тем более что отдельный метод тебе судя по всему и не нужен, а просто рандомный пик закона из датасета.
Поэтому можно просто заккоментить этот вар и вместо него написать свой рандом пик
![image](https://github.com/user-attachments/assets/a67376f8-98b6-47b2-9b49-c76a919f9245)

2024-10-18 11:31 UTC, TryHardo7 commented
> А тем более что отдельный метод тебе судя по всему и не нужен, а просто рандомный пик закона из датасета. Поэтому можно просто заккоментить этот вар и вместо него написать свой рандом пик

Ну закоментить метод, который был придётся в любом случае, он же конфликтовать будет, при условии что я вернул оригинальный датасет. Новый датасет сделал в папке сс220, оставил генерацию как есть, там 3 строчки кода, вроде эффективно. Можно их тоже конечно закоментить и написать рядом буквально то-же самое? По другому я не знаю как сделать

2024-10-18 11:38 UTC, Kirus59 commented
Если ты про мерж конфликты, то от закомменчивания всех констант и целого метода будет гораздо больше конфликтов, чем от замены одной переменной.

2024-10-18 20:59 UTC, TryHardo7 commented
Ну вроде по человечески сделал, работает.

2024-10-18 22:19 UTC, UrPrice commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/circuitboards/lawboards.ftl
Все названия энтити должны быть с маленькой буквы. Все описания должны быть с большой буквы.

2024-10-18 22:20 UTC, UrPrice commented on Resources/Locale/ru-RU/station-laws/laws.ftl
А откуда брался текст для законов. Переводился тобой или референс из 13-ой станции? Если брался тобой - сверь, пожалуйста, с существующими законами 13-ой станции Парадиза и выбери в приоритет перевод оттуда.

2024-10-18 22:28 UTC, TryHardo7 commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/circuitboards/lawboards.ftl
Названия энтити такие, какие они в коде. А описания и есть с заглавной буквы
Либо я вообще не понял о чём ты говоришь

2024-10-18 22:36 UTC, TryHardo7 commented on Resources/Locale/ru-RU/station-laws/laws.ftl
Глянул что в 13, у нас законы все другие кроме трёх базовых, агентского+паука и паладина. 
Наш Антимов уже был переведён иначе чем в 13 кем-то в пользу Ядерных Оперов. 
Оставшихся в 13 нет и да, я переводил сам максимально дословно+сохраняя смысл и литературный подход, оффы используют там игру слов которая есть только на англ., ещё пару слов заменил по предложению Лёхи Сварщика.
Если у тебя есть предложения по переводу то говори конкретно что по-твоему переведено некорректно.

2024-10-19 15:20 UTC, Kirus59 commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/circuitboards/lawboards.ftl
> Названия энтити такие, какие они в коде. А описания и есть с заглавной буквы ![image](https://private-user-images.githubusercontent.com/166473301/378027044-10fdc398-5ae1-467e-8924-1c2fa073df16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTEzNjUsIm5iZiI6MTcyOTM1MTA2NSwicGF0aCI6Ii8xNjY0NzMzMDEvMzc4MDI3MDQ0LTEwZmRjMzk4LTVhZTEtNDY3ZS04OTI0LTFjMmZhMDczZGYxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxNTE3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWQ1MDk3ZThkM2U1YzJjNzk3OTQ4NDFmNTdiMWNmM2JjODQ1MWQ5Mjk4ZWQxOTcwYzAzZTJjNTBkNzY4YmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nE_1I_QGUr45Z-iKLyVeO8wMnqhl65NQmkuzT17UBJ4)
> 
> Либо я вообще не понял о чём ты говоришь

Названия энтити принято писать с маленькой буквы (кроме имен кукол и животных если они есть).
Если где-то еще видел с большой - то вероятнее всего ошибка.

2024-10-19 15:23 UTC, Kirus59 commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/circuitboards/lawboards.ftl
Ну и думаю что пока не стоит трогать переводы оффовских плат, т.к. потом все равно подтянем перевод от Корвакса

2024-10-19 15:27 UTC, Kirus59 requested changes

2024-10-19 15:27 UTC, Kirus59 commented on Content.Server/StationEvents/Events/IonStormRule.cs
> +            var newLaw = PickLaw();
```suggestion
            var newLaw = Pick(BrickedLaw);
```
Не думаю что нужно создавать отдельный метод для этого (я в комментах потом об этом и сказал).

2024-10-19 15:27 UTC, Kirus59 commented on Content.Server/StationEvents/Events/IonStormRule.cs
> +    // SS220 IonStorm Rework end
Соответственно это не нужно

2024-10-19 16:49 UTC, TryHardo7 commented
Дело шло бы лучше, если бы я хоть что-то понимал в коже. 

Так файл локализации плат убрать?

2024-10-19 17:45 UTC, Kirus59 commented
> Дело шло бы лучше, если бы я хоть что-то понимал в коде.
> 
> Так файл локализации плат убрать?

Да, у корвакса они уже переведены, так что вскоре черри-пикнем и нам

2024-10-19 19:13 UTC, Kirus59 reviewed
В остальном норм, по законам - обсудим с Адичем

2024-10-19 19:13 UTC, Kirus59 commented on Content.Server/StationEvents/Events/IonStormRule.cs
> -
Пустую строку верни эту

2024-10-19 20:59 UTC, UrPrice commented on Resources/Locale/ru-RU/station-laws/laws.ftl
Если их в 13-ой нет, то окей, имеем что имеем. Антимов переведён в пользу ЯО временно, пока не введут антагонизм нормальный для ИИшки. Паладина тогда просто возьми с 13-ой, чтобы на грабли хотя бы тут не наступать, изобретая новые трактовки.

2024-10-19 21:01 UTC, UrPrice commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/circuitboards/lawboards.ftl
Урист МакВульпа это имя собственное. А нарицательные остаются с маленькой. 
![image](https://github.com/user-attachments/assets/6380e097-1540-4111-ad54-c70426ea10d6)
![image](https://github.com/user-attachments/assets/2ad570e2-e0cf-4f26-b858-7e56092b3464)

2024-10-20 15:52 UTC, TryHardo7 commented
Пока мы тут сидели, залетела локализация с корвакса?

2024-10-20 17:34 UTC, Kirus59 commented
> Пока мы тут сидели, залетела локализация с корвакса?

Я как раз вчера черри-пик и делал

2024-10-20 23:59 UTC, TryHardo7 commented
Убрал локализацию, остался только реворк ионных законов. 

Почему у меня гит каждый день требует подтверждение почты?

2024-10-21 00:35 UTC, TryHardo7 commented
Он проваливает чек с поджигаемостью стены?

2024-10-21 13:30 UTC, lexaSvarshik commented
> Он проваливает чек с поджигаемостью стены Либо я что-то не понимаю, либо это пришло из мастер ветки

У меня такое тоже было, мерджни мастер в ветку

2024-10-21 18:37 UTC, Kirus59 approved these changes
Технически все норм, жду апрува от Адича

2024-10-22 08:03 UTC, Ady4ik commented
Вроде прикольно, согласую с сурксом, чтобы проблем со стороны правил не было

2024-11-03 23:44 UTC, UrPrice approved these changes

2024-11-03 23:46 UTC, UrPrice commented
Мёрджу в связи с выпуском ИИ на все станции. Суркс и Адуч уже потом дадут комментарии и если что дополнительным патчем прольём фикс, если он вообще потребуется.

2024-11-03 23:46 UTC, merged