Fireaxe cyborg module
SerbiaStrong-220/space-station-14 pull request #2111
Opened 2024-10-18 18:32 UTC by lexaSvarshik

## Описание PR

В игру добавлены два модуля для киборгов - модуль с пожарным топором и его синди-версия: модуль с огнетопором.
![изображение](https://github.com/user-attachments/assets/f45e4748-de19-4022-925b-ee56e7e07224)

Модуль с топором изучается в Т2 технологии РНД "Продвинутые инструменты", устанавливается исключительно на инженерное шасси.

### **Причины**
Инженерные киборги и инженеры в целом сталкиваются с проблемой необходимости сноса большого кол-ва обычных/укрепленных стен; тогда как разборка усиленных невозможна посредством РСУ, а разбирать каждую стену вручную - занятие неблагодарное (разборка одной стены проходит в ~10 этапов, на это уходит около минуты или двух).
![изображение](https://github.com/user-attachments/assets/09592ad5-863c-479a-a7e4-a271f1238d55)
Имея же пожарный топор в распоряжении киборга - демонтаж проходит гораздо быстрее, без лишних заморочек.

### **Дополнительно**
Альтернативное применение топора - оборона от аггрессивной фауны. 

### **Про емагнутых киборгов**
На данный момент в игре у ЕМАГнутых киборгов очень скудный арсенал. Обычный лом, челюсти/швабра (10 урона), лопата (14 урона) из шахтерского модуля, протокинетик (единственное достойное оружие). 
Модуль с топором отчасти заполняет нишу оружия для киборгов.

## Модуль с огнетопором
Ещё, был добавлен модуль с огнетопором в аплинк. Модуль универсальный, подойдёт для любого типа шасси. Огнетопор качественно от обычного отличается тем, что при ударе накладывает 1 стак огня. 

Стоимость - 3 ТК _(может измениться)_. Стоимость аргументирована там, что за свою цену ничего особенного (кроме поджога) вы не получаете. Модуль с обычным топором и без того изучается в РНД довольно быстро, печатается в любых требуемых количествах. По урону топоры идентичны.
![изображение](https://github.com/user-attachments/assets/09a2b997-d040-4bec-a875-f656b1bd254e)

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлены модули с пожарным топором и огнетопором для киборгов!

2024-10-18 21:34 UTC, TryHardo7 commented
Это что, ОПГ "синтетики"? Слишком сильно, у нас топор имба по части сравнивания станции с плиткой грида. Один борг с приказом за 10 минут сможет убрать стены всех отделов. Да и базовый топор просто как оружие очень сильный 25 - дамаги с тычки, есворд борговский зачем нужен? Если ты можешь емагать боргов и давать им бесплатно топоры которыми они зарубят кого угодно и ГДЕ угодно, препятствий для них не будет. 
Я бы осторожнее относился к бафам силы боргов, лучше дать им сильное РСУ которое может убирать укреп, но будет жрать много заряда, типа 200-250кВт за применение.

2024-10-19 08:41 UTC, lexaSvarshik commented
Я думал насчет баланса - урон топору можно урезать ввиду его легкодоступности. Как режущий, так и структурный. Скажем, 10-15 режущего, структурный до 80-100.

2024-10-23 19:08 UTC, lexaSvarshik commented
После нерфа:
- Обычная стена - 5 ударов
- Усиленное стекло - 2 удара
- Усиленная стена - 20 ударов

Урон топором снижен до 15 (было 25)

2024-10-24 20:11 UTC, Ady4ik approved these changes
В целом все, только дискаунт подрезать, а в остальном не имею ничего против.

2024-10-24 20:11 UTC, Ady4ik commented on Resources/Prototypes/SS220/Catalog/uplink_catalog.yml
> +    Telecrystal: 3
```suggestion
    Telecrystal: 2
  cost:
    Telecrystal: 3
```

Слишком сильная штука, можно реально личико человечку поломать, дискаунт до 1 неоправдан.

2024-10-27 02:32 UTC, UrPrice submitted a review, later dismissed
![dotnet_5l6PiIhZDR](https://github.com/user-attachments/assets/5ea52283-f464-4bd8-94b1-6c9f0a1127be)
А где?

2024-10-27 09:39 UTC, lexaSvarshik commented
> ![dotnet_5l6PiIhZDR](https://private-user-images.githubusercontent.com/107646133/380463615-5ea52283-f464-4bd8-94b1-6c9f0a1127be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMjIyMTYsIm5iZiI6MTczMDAyMTkxNiwicGF0aCI6Ii8xMDc2NDYxMzMvMzgwNDYzNjE1LTVlYTUyMjgzLWY0NjQtNGJkOC05NGIxLTZjOWYwYTExMjdiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwOTM4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGUzMjQ0NzkzMmZiZWQyN2MxZGVmMjI4MTY0MGZmNjVhYmUyMDM5ZWJlM2MzN2ZjZDZjMjQyYjhmNjA2MTJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ygmvQna1lYznkmmZWRpd8etGB6vmPfAeFhp-5lLFXNA) А где?

С новой обновой от оффов, видать, пришло. Выходит, нужны будут спрайты под топоры и ещё под наш модуль с протокинетиком, т.к. под него тоже ничего не рисовалось

2024-10-27 12:36 UTC, UrPrice commented
> > А где?
> 
> С новой обновой от оффов, видать, пришло. Выходит, нужны будут спрайты под топоры и ещё под наш модуль с протокинетиком, т.к. под него тоже ничего не рисовалось

Агаа, запроси у спрайтеров, пж

2024-10-28 00:12 UTC, lexaSvarshik commented
> Агаа, запроси у спрайтеров, пж

Я запросил, но неясно, когда оно будет. Можно залить как есть, я потом отдельно иконки закину.

2024-11-03 01:57 UTC, lexaSvarshik commented
Блин хоть самому иконки рисуй яхз

2024-11-03 04:06 UTC, UrPrice commented
> Блин хоть самому иконки рисуй яхз

Ну можешь попробовать, на основе офовской просто вырезать объект внутри и подставить спрайт другого объекта, чуть цветовую палитру изменив.

2024-12-20 17:32 UTC, lexaSvarshik commented
![изображение](https://github.com/user-attachments/assets/61a02e19-1242-4f7e-8cd4-bdc47ef41b76)
![изображение](https://github.com/user-attachments/assets/d9c09c4b-86f9-4aca-80a4-5dbc7d6d5b9c)

Лежало у спрайтеров больше месяца, поэтому взял и нарисовал сам

2024-12-21 05:21 UTC, Kirus59 requested changes

2024-12-21 05:21 UTC, Kirus59 commented on Resources/Locale/ru-RU/ss220/prototypes/entities/specific/robotics/borg_modules.ftl
> +    .desc = Техническая деталь, дающая киборгам пожарный топор, поджигающий жертв!
мб про поджигание через скрытое описание лучше писать?

2024-12-21 05:21 UTC, Kirus59 commented on Resources/Locale/ru-RU/ss220/weapons/borg_fireaxe.ftl
> +    .desc = Модифицированный компанией Cybersun пожарный топор, подходящий для любых типов шасси! При ударе поджигает жертв.
и тут

2024-12-21 05:21 UTC, Kirus59 commented on Resources/Textures/Interface/Actions/actions_borg.rsi/meta.json
Спрайты перенести в нашу директорию

2024-12-21 05:21 UTC, Kirus59 commented on Resources/Textures/Objects/Specific/Robotics/borgmodule.rsi/meta.json
Перенести в нашу директорию

2024-12-21 16:58 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/weapons/borg_fireaxe.ftl
> +    .desc = Модифицированный компанией Cybersun пожарный топор, подходящий для любых типов шасси! При ударе поджигает жертв.
Это не надо в скрытом описании писать, этот топор только самому киборгу видно, никому другому.

2024-12-21 16:58 UTC, lexaSvarshik commented on Resources/Textures/Interface/Actions/actions_borg.rsi/meta.json
ladno

2024-12-21 16:59 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/prototypes/entities/specific/robotics/borg_modules.ftl
> +    .desc = Техническая деталь, дающая киборгам пожарный топор, поджигающий жертв!
Казалось бы, модуль очевидно синдикатовский, но, в целом, как анти-мета, можно сделать и так.

2024-12-21 17:05 UTC, Kirus59 commented on Resources/Locale/ru-RU/ss220/weapons/borg_fireaxe.ftl
> +    .desc = Модифицированный компанией Cybersun пожарный топор, подходящий для любых типов шасси! При ударе поджигает жертв.
> Это не надо в скрытом описании писать, этот топор только самому киборгу видно, никому другому.

При обыске боргов разве нельзя посмотреть его "руки" (текущие предметы из активного модуля)?

2024-12-21 17:10 UTC, lexaSvarshik commented on Resources/Textures/Objects/Specific/Robotics/borgmodule.rsi/meta.json
Там вряд ли выйдет, т.к. у спрайта одновременно два стейта - база и иконка. При переносе иконок придётся переносить и оффовскую базу, что не сильно круто

2024-12-21 17:47 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/weapons/borg_fireaxe.ftl
> +    .desc = Модифицированный компанией Cybersun пожарный топор, подходящий для любых типов шасси! При ударе поджигает жертв.
> > Это не надо в скрытом описании писать, этот топор только самому киборгу видно, никому другому.
> 
> При обыске боргов разве нельзя посмотреть его "руки" (текущие предметы из активного модуля)?

![изображение](https://github.com/user-attachments/assets/2b5a7482-aa80-4be3-ac78-6645e62d5e7b)

2024-12-21 17:50 UTC, Kirus59 commented on Resources/Textures/Objects/Specific/Robotics/borgmodule.rsi/meta.json
> Там вряд ли выйдет, т.к. у спрайта одновременно два стейта - база и иконка. При переносе иконок придётся переносить и оффовскую базу, что не сильно круто

``` .yml
- type: Sprite
  layers:
    - state: syndicate
      sprite: Objects/Specific/Robotics/borgmodule.rsi
    - state: icon-fireaxe-flaming
      sprite: SS220/Objects/Specific/Robotics/borgmodule.rsi
```
Для лейеров можно отдельно указывать путь

2024-12-21 22:04 UTC, Kirus59 approved these changes

2024-12-21 22:05 UTC, merged

2024-12-21 22:10 UTC, EstKemran commented
Дождались бы хоть ревью :shock:

2024-12-21 22:13 UTC, lexaSvarshik commented
> Дождались бы хоть ревью :shock:

![386872321-0d9c580e-a9b7-4b4a-b092-7caa9c8e7736(1)](https://github.com/user-attachments/assets/265eb523-a294-4fdd-b6f6-2515d4e97cc6)

2024-12-21 22:14 UTC, Kirus59 commented
> Дождались бы хоть ревью :shock:

А, я забыл....