Incendary ammo rebalance
SerbiaStrong-220/space-station-14 pull request #2112
Opened 2024-10-18 20:29 UTC by lexaSvarshik

## Описание PR

Баланс зажигательных патронов, изенение групп урона в соответствии с остальными типами патронов.

Если раньше у них был урон тупой (blunt), сейчас урон уколами (piercing), как и у прочих летальных патронов, имеет смысл.

Дробовым патроны отдельно урезан урон, поскольку даже после именения типа урона, они наносили в 1,5 раза больше урона, нежели простые, летальные.

**Проблема тупого (blunt) урона** - это не тот тип урона, от которого защищает специальная пуленепробиваемая броня, в связи с чем, патроны тупо игнорировали наличие крутого пуленепробиваемого бронежилета и наносили большой урон. При этом, кукле в противоударной броне (броне от ударов тупыми предметами, типа тулбокса или биты), наносилось куда меньше урона, что совсем не соответствует логике. 

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Svarshik
- tweak: Изменены параметры урона зажигательных патронов

2024-10-18 21:26 UTC, TryHardo7 commented
Давно пора, это вообще ошибка разработки, летальные дробинки наносят дробящий урон вместо колющего, логика нарушена.

2024-10-19 11:20 UTC, Surani1 requested changes
Прикрепи фотографии тестов.

2024-10-19 11:44 UTC, lexaSvarshik commented
> Прикрепи фотографии тестов.

Готово. Тесты были до ТТК апдейта и после, картина одинаковая. Сейчас в шапке скрины тестов уже после ТТК апдейта.

2024-10-26 12:31 UTC, lexaSvarshik commented
https://discord.com/channels/1097181193939730453/1299411509893402694
Вот в трекере подняли проблему зажиг

2024-10-27 12:43 UTC, Kirus59 approved these changes

2024-10-27 12:46 UTC, merged