Tweak: Sort ChemWindow buffer by Name
SerbiaStrong-220/space-station-14 pull request #2114
Opened 2024-10-19 05:27 UTC by ReeZer2

## Описание PR
Сортировка реагентов в буффере ХимМастера

**Медиа**
![image](https://github.com/user-attachments/assets/1634778d-a862-4da9-b4bd-5fa9121249cf)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: ReeZii
- tweak: Теперь реагенты в ХимМастере сортируются по имени

2024-10-19 05:45 UTC, ReeZer2 commented
Не было, не было, и на тебе. Рандом падение чеков 
![image](https://github.com/user-attachments/assets/5a2f547d-054a-44fd-bba8-b3c8a6a989d9)

2024-10-19 09:46 UTC, lexaSvarshik commented
А разве сортировка не должна происходить, скажем, по нажатию кнопки? Ибо если оно по дефолту будет по алфавиту, будет либо просто непривычно, либо вовсе невозможно варить (220 часов химики, вероятно, уже механически занимаются варкой)

2024-10-19 13:01 UTC, stalengd commented
@ReeZer2 а в каком порядке они были раньше?

2024-10-19 13:03 UTC, Alwayswannahunt commented
> @ReeZer2 а в каком порядке они были раньше?

В каком вливали. Порядок был только в химраздатчике, в химмастере была "сортировка" по времени первого добавления, если умничать.

2024-10-19 13:08 UTC, stalengd commented
> > @ReeZer2 а в каком порядке они были раньше?
> 
> В каком вливали. Порядок был только в химраздатчике, в химмастере была "сортировка" по времени первого добавления, если умничать.

Есть уверенность что сортировка по имени будет удобнее/логичнее?

2024-10-19 13:13 UTC, Alwayswannahunt commented
> > > @ReeZer2 а в каком порядке они были раньше?
> > 
> > 
> > В каком вливали. Порядок был только в химраздатчике, в химмастере была "сортировка" по времени первого добавления, если умничать.
> 
> Есть уверенность что сортировка по имени будет удобнее/логичнее?

Без понятия, уверен есть те кто привыкли.
Вот бы лучше кнопку сделали по которой сортируют, так хоть могли бы позже у игроков спросить удобно ли...

2024-10-19 13:20 UTC, stalengd requested changes
Добавить кнопку, которая переключает сортировку

2024-10-20 05:05 UTC, Ady4ik approved these changes

2024-10-26 16:29 UTC, stalengd requested changes
Не согласен с реализацией, зачем на сервер лезть? Можно сделать сортировку по кнопке просто на клиенте. Да, состояние сортировки будет сбрасываться при закрытии окна, хотя для этого можно наверное в компонент добавить поле режима сортировки.

2024-10-26 16:38 UTC, ReeZer2 commented
> Не согласен с реализацией, зачем на сервер лезть? Можно сделать сортировку по кнопке просто на клиенте. Да, состояние сортировки будет сбрасываться при закрытии окна, хотя для этого можно наверное в компонент добавить поле режима сортировки.

Если делать на клиенте, то кода выходит намного больше, да и сам List state.BufferReagents readonly. Еще, я подхожу под код оффов, тем, что буквально все кнопки через сервер обрабатываются, а не через клиент.

2024-10-26 16:41 UTC, stalengd commented
> Если делать на клиенте, то кода выходит намного больше, да и сам List state.BufferReagents readonly. 

У тебя буквально в первом коммите всё было реализовано на клиенте, зачем было менять?

2024-10-26 17:46 UTC, ReeZer2 commented
> > Если делать на клиенте, то кода выходит намного больше, да и сам List state.BufferReagents readonly.
> 
> У тебя буквально в первом коммите всё было реализовано на клиенте, зачем было менять?
![image](https://github.com/user-attachments/assets/af11ed7c-8071-4261-9d2b-6967ea04e2ad)

2024-10-26 19:39 UTC, stalengd requested changes
Можно лучше

2024-10-26 19:39 UTC, stalengd commented on Content.Shared/Chemistry/SharedChemMaster.cs
> +        public List<ReagentQuantity> BufferReagents; //ss220 tweak sort
Ещё раз посмотри как у тебя работала сортировка в первом коммите, там для этого не нужно было модифицировать данный класс

2024-10-26 19:39 UTC, stalengd commented on Content.Client/Chemistry/UI/ChemMasterWindow.xaml.cs
> +
Подсказка

```suggestion
        private ChemMasterBoundUserInterfaceState? _chemState;
        private bool _isSortingEnabled;
```

2024-10-26 19:39 UTC, stalengd commented on Content.Client/Chemistry/UI/ChemMasterWindow.xaml.cs
> +            };
А здесь

```suggestion
            BufferSortButton.OnPressed += _ =>
            {
                _isSortingEnabled = !_isSortingEnabled;
                if (_chemState != null)
                {
                    UpdatePanelInfo(_chemState);
                }
            };
```

В `UpdatePanelInfo()` логику как в первом коммите, но с учётом `_isSortingEnabled`

2024-10-27 17:50 UTC, stalengd requested changes

2024-10-27 17:50 UTC, stalengd commented on Content.Shared/Chemistry/SharedChemMaster.cs
> +            IReadOnlyList<ReagentQuantity> bufferReagents, FixedPoint2 bufferCurrentVolume, //ss220 tweak sort
Тут пометка не нужна
```suggestion
            IReadOnlyList<ReagentQuantity> bufferReagents, FixedPoint2 bufferCurrentVolume,
```

2024-10-27 17:50 UTC, stalengd commented on Content.Client/Chemistry/UI/ChemMasterWindow.xaml.cs
> +                : state.BufferReagents;
А так не проще?
```suggestion
            var newBuffer = _isSortingEnabled
                ? state.BufferReagents
                .OrderBy(reagent =>
                {
                    _prototypeManager.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? proto);
                    return proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
                })
                .ToList()
                : state.BufferReagents;
```

2024-10-27 20:15 UTC, stalengd approved these changes

2024-10-27 20:15 UTC, merged