FixTrouble's
SerbiaStrong-220/space-station-14 pull request #2120
Opened 2024-10-19 17:12 UTC by Tris0r

## Описание PR
Исправлены недочёты:
1. Обновлен спрайт кепки
2.  В меню лодаута визуально не снимался пояс уборщика
3.  Со старта в РПС не было вещей
4.  Исправлены прорезиненные ботинки, теперь в нельзя подскользнуться и они имеют пониженный мувспид
5.  Исправлено неправильное отображение распылителя уборщика в РПС

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
no cl

2024-10-19 17:41 UTC, Kirus59 requested changes

2024-10-19 17:41 UTC, Kirus59 commented on Resources/Prototypes/Roles/Jobs/Civilian/janitor.yml
> -    belt: ClothingBeltJanitorFilled
Вне нашей папки не удаляешь - а комментишь и оставляешь пометку

2024-10-19 17:41 UTC, Kirus59 commented on Resources/Prototypes/Roles/Jobs/Fun/visitors_startinggear.yml
> -    belt: ClothingBeltJanitorFilled
?

2024-10-19 17:41 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Clothing/Belt/belts.yml
> -  - type: Appearance
??

2024-10-19 18:11 UTC, Tris0r commented on Resources/Prototypes/SS220/Entities/Clothing/Belt/belts.yml
> -  - type: Appearance
> ??

это чтобы не было кривых отображений шмоток внутри этого РПС

2024-10-19 19:11 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Clothing/Belt/belts.yml
> -  - type: Appearance
> это чтобы не было кривых отображений шмоток внутри этого РПС

Ну так а зачем удалил `maxItemSize: Large` и `- type: Appearance`?
первое вообще к спрайтам не относится, а второе - может повлиять и на другие моменты когда меняется спрайт (просто не будет работать).

Если Appearance наследуется - тогда пох

2024-10-19 19:17 UTC, Tris0r commented on Resources/Prototypes/SS220/Entities/Clothing/Belt/belts.yml
> -  - type: Appearance
А я удалил и ничего не поломалось и все заработало. Ну я и подумал, что не так уж оно и надо значит

2024-10-19 19:18 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Clothing/Belt/belts.yml
> -  - type: Appearance
> А я удалил и ничего не поломалось и все заработало. Ну я и подумал, что не так уж оно и надо значит

:Clueless:

2024-10-19 20:26 UTC, Tris0r commented on Resources/Prototypes/SS220/Entities/Clothing/Belt/belts.yml
> -  - type: Appearance
Ну а в чём я не прав

2024-10-20 13:10 UTC, Kirus59 commented
@Tris0r когда писал `maxItemSize: Large` - накосячил с табуляцией, поэтому и чек упал

2024-10-20 13:33 UTC, Tris0r commented
> @Tris0r когда писал `maxItemSize: Large` - накосячил с табуляцией, поэтому и чек упал

Ну, ты оказался прав.

2024-10-20 13:40 UTC, Kirus59 commented on Resources/Prototypes/Roles/Jobs/Fun/visitors_startinggear.yml
> -    belt: ClothingBeltJanitorFilled
@Tris0r Тут еще вопрос остался, это же одежда ролей посетителей (которые мидраундом могут заспавнится на эвакподе вроде), зачем убирать пояс им?

2024-10-20 13:42 UTC, EstKemran approved these changes

2024-10-20 13:44 UTC, Tris0r commented on Resources/Prototypes/Roles/Jobs/Fun/visitors_startinggear.yml
> -    belt: ClothingBeltJanitorFilled
@Kirus59 Я бы вернул, но у меня эта строчка сохранилась, поэтому я хз как вернуть

2024-10-20 13:48 UTC, Tris0r commented
Всё. Никогда в жизни больше не притронусь к добавлению новых шмоток в лодаут.

2024-10-20 14:00 UTC, Kirus59 commented on Resources/Prototypes/Roles/Jobs/Civilian/janitor.yml
> -    belt: ClothingBeltJanitorFilled
@Tris0r это все еще актуально

2024-10-20 15:26 UTC, Kirus59 approved these changes

2024-10-20 15:26 UTC, merged