BonusForFullyDiscovered
SerbiaStrong-220/space-station-14 pull request #2143
Opened 2024-10-22 23:15 UTC by 21Melkuu

## Описание PR

Узнайте РП путем taa
Мое первое изменение по глобальному(?) пересмотру концепции РНД(возможно его стоит зафиксировать текстом, но пока это лишь в голове).

К сути пра: добавляет бонус - выпадаемый предмет, за полное изучение и активации всех узлов.

## Зачем это нужно?
**Первая причина** 
Как основная, в данный момент нет никакой ценности очкам, а придавать значимость очкам изменениями в экономике РНД на мой взгляд плохая идея -> артефакты выступают как "затычкой" для игроков в рнд. Не можешь/не хочешь изучать аномалии, идешь долбить артефакты, которые крайне сильно уступают по сравнению с аномалиями по КПД очков. Помимо большой разницы в получаемых О.И, не стоит забывать о сложности артефактов(держать 3 аномы в 10 раз проще, чем долбить сложный арт на 13 узлов). Как в конечном итоге мы получаем намного меньше очков за N период времени, повышенную сложность, если сравнивать с кругляшками.

**Вторая причина** 
За полное изучение всех узлов нет никаких плюсов, это лишь гладит твое эго, ну и все :(

**Третья причина** 
Не очевидная. Бесполезность автолата, а в следствии гипер версии. Как показано в черновом примере, хорошая идея будет использовать в качестве бонуса - блюпринты, которым так и не нашлось достойного применения в игре. Больше крутых блюпринтов -> больше использование автолата.

**Четвертая причина**
Некоторые вещи НЕ должны получатся гарантом при изучении технологий на сервере. А получить их не ЩИТспавном все еще хочется. Как пример - пояс СИ, большой пояс, удобный, запихнуть большой белт в обычные изучения - не правильно. Поэтому в дополнительный бонус можно запихнуть все что угодно.

К причинам драфта: 
Надо жестко придумать получаемые вещи, подумать, стоит ли изменять пул лута за сложность артефакта(думаю, что нет не надо).

З.ы инженерные очки в автолате с 0 не правильно. wyccTopor.
Не знаю нахуя я это расписывал, но почему бы и нет :)

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: 21Gnomkuu"
- add: Добавлен бонус за полное изучение артефакта!

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up. Changelog must have a :cl: symbol, so the bot recognizes the changes and adds them to the game's changelog.

2024-10-24 00:47 UTC, UrPrice commented
Плиз плиз плиз, опиши свои основные причины, проблематику и весь роадмап изменений по РнД в отдельном документе, иначе не понятно вообще куда ты будешь собираться вести геймплей и будет сложно принимать решение о принятии твоих изменений. А так, сыглы пока под тем, что РнД давно требует к себе пересмотра.

Сюда же можно будет закинуть вот это:
https://discord.com/channels/1158128815311171638/1262226284172415067 - уже одобренная идея по полигону и получению очков при помощи взрывов

2024-10-24 11:58 UTC, UrPrice commented
> > Плиз плиз плиз, опиши свои основные причины, проблематику и весь роадмап изменений по РнД в отдельном документе, иначе не понятно вообще куда ты будешь собираться вести геймплей и будет сложно принимать решение о принятии твоих изменений.
> 
> Net

В таком случае мы просто не будем рассматривать подобное кручение цифр, как ты сам их и назвал, ради непонятно чего.
Это была вежливая просьба, не надо разыгрывать драмму квин, ей богу.

2024-10-24 12:49 UTC, 21Melkuu commented
> > > Плиз плиз плиз, опиши свои основные причины, проблематику и весь роадмап изменений по РнД в отдельном документе, иначе не понятно вообще куда ты будешь собираться вести геймплей и будет сложно принимать решение о принятии твоих изменений.
> > 
> > 
> > Net
> 
> В таком случае мы просто не будем рассматривать подобное кручение цифр, как ты сам их и назвал, ради непонятно чего. Это была вежливая просьба, не надо разыгрывать драмму квин, ей богу.

Тебе дали пр на улучшение артефактов? Тебе основали причины? Расматривай пр в этом ключе, сидит тип "мы тебя не слушаем лялялялля", ты тут вообще? То что я запланировал будущие изменения рнд != они будут в игре, шаришь?

2024-10-24 13:06 UTC, UrPrice commented
Нормально разговаривай, без токсичности.
Больше в твой PR не полезу, раз тебя так задевают любые, абсолютно адекватные, комментарии твоих работ.

2024-10-24 19:58 UTC, Ady4ik commented
ПР интересный, спору нет.
Хотелось бы уйти от роадмапы у тебя в голове и перенести это на бумагу/гуглдокс/задачу/драфт, чтобы в целом можно было понять, чего ты хочешь добиться в последующем, чтобы не было камней преткновения, ну и, как итог, мы могли корректировать изменения на стадии задумки и двигать их в правильном векторе, который будет нравится всем.

2024-10-24 23:51 UTC, SmilMolch commented
Считаю, что нет смысла добавлять плюшки за изучение арта, пока не понизят общее количество очков с аномы. Изучить всё рнд за 40-50 минут при робастах - не ок.

2024-10-28 21:14 UTC, lexaSvarshik requested changes

2024-10-28 21:14 UTC, lexaSvarshik commented on Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/item_artifacts.yml
> +    - ClothingHeadHatCatEarsValid
Валид убрать с ушек 
![s_231c08c280](https://github.com/user-attachments/assets/58c2696e-c398-487d-90a9-f0f0af2ded9f)

2024-11-28 07:47 UTC, Ady4ik commented
@21Melkuu Что еще надо тут сделать? Нужна помощь?

2024-11-28 13:39 UTC, 21Melkuu commented
> @21Melkuu Что еще надо тут сделать? Нужна помощь?

Прототипы и текст и тем и тем пока нет желания заниматься так как есть более интересные задачи, думаю доделаю в течении двух недель

2024-12-17 23:58 UTC, Surani1 commented
> > @21Melkuu Что еще надо тут сделать? Нужна помощь?
> 
> Прототипы и текст и тем и тем пока нет желания заниматься так как есть более интересные задачи, думаю доделаю в течении двух недель

3 недели спустя

![155774f070222683c5730fce24794328](https://github.com/user-attachments/assets/1c0b86d4-42da-4142-891b-d6d3c9eb4027)

2024-12-21 20:19 UTC, 21Melkuu commented
о нет он насрал...

2024-12-21 21:36 UTC, 21Melkuu commented
не смог победить скилл ишью, перезалил

2024-12-21 21:37 UTC, closed without merging