ReaperUpgrade
SerbiaStrong-220/space-station-14 pull request #2144
Opened 2024-10-23 08:25 UTC by TryHardo7

- [x] Жнец может таскать тела пока в материальной форме. 
- [ ] Эффект оглушения (визуальный, схожий с флешкой) на крик
- [ ] Добавить абилку красного дыма на 2+ стадию
- [ ] Увеличить структурный урон на всех стадиях

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

:cl: Lancevrot
- add: Добавлены способности жнецу

2024-10-24 10:03 UTC, Kirus59 requested changes

2024-10-24 10:15 UTC, TryHardo7 commented on Content.Shared/Movement/Pulling/Systems/PullingSystem.cs
>          entity.Comp.NeedsHands = false;
Это единственный способ заставить его прекратить пулл который я нашёл. В иных случаях он продолжал тащить после выхода из материальной формы, хотя и не мог схватить будучи в астрале.

2024-10-24 10:22 UTC, TryHardo7 commented on Content.Shared/SS220/DarkReaper/DarkReaperSharedSystem.cs
> +            return;
а это косяк

2024-10-24 10:26 UTC, TryHardo7 commented on Resources/Textures/SS220/DemonRofler/dark_reaper.rsi/meta.json
> +  "copyright": "Made by MIXnikita and Lanc for SS220, randomgibs is taken from Paradise build of SS13",
Это файлик мета для всех спрайтов сразу. Один из них получается я сделал, остальные Никита. Если там не должно быть такого, можно моё имя просто потереть

2024-10-24 10:29 UTC, TryHardo7 commented on Content.Shared/SS220/DarkReaper/DarkReaperSharedSystem.cs
> +using PullableComponent = Content.Shared.Movement.Pulling.Components.PullableComponent;
упс, хехе

2024-10-24 10:38 UTC, Kirus59 commented on Resources/Textures/SS220/DemonRofler/dark_reaper.rsi/meta.json
> +  "copyright": "Made by MIXnikita and Lanc for SS220, randomgibs is taken from Paradise build of SS13",
> Это файлик мета для всех спрайтов сразу. Один из них получается я сделал, остальные Никита. Если там не должно быть такого, можно моё имя просто потереть

Ну прост тобою же нарисован только 1 стейт из этого файла, обычно так и уазывается по типу `"Made by MIXnikita and for SS220, randomgibs is taken from Paradise build of SS13; icon_bloodmist made by Lanc for SS220"

2024-10-24 10:43 UTC, Kirus59 commented on Content.Shared/Movement/Pulling/Systems/PullingSystem.cs
>          entity.Comp.NeedsHands = false;
Так тут прост при добавлении компонента `NeedsHands` сетается на false, это же можно сделать и тогда, когда добавляешь компонент.
Ща обозначу где

2024-10-24 10:44 UTC, Kirus59 commented on Content.Shared/SS220/DarkReaper/DarkReaperSharedSystem.cs
> +            EnsureComp<PullerComponent>(uid);
Вроде как то так
```suggestion
            EnsureComp<PullerComponent>(uid).NeedHands = false;
```
Если будет писать что нет доступа к этому параметру, то добавь к нему аттрибут `[Access(Other = AccessPermissions.ReadWriteExecute)]`

2024-10-25 11:04 UTC, lexaSvarshik commented
Может, дать жнецу способность видеть в этом тумане? Или эта способность исключительно как метод отхода?

2024-10-25 17:03 UTC, TryHardo7 commented
> Может, дать жнецу способность видеть в этом тумане? Или эта способность исключительно как метод отхода?

После ТТК пострадала выживаемость жнеца, а не атакующий потенциал, задумано как защитная способность.

2024-10-25 18:50 UTC, Kirus59 requested changes

2024-10-25 18:50 UTC, Kirus59 commented on Content.Shared/Movement/Pulling/Components/PullerComponent.cs
> +    ///     Does this entity need hands to be able to pull something? SS220 DarkReaper Access
```suggestion
    ///     Does this entity need hands to be able to pull something?
```

2024-10-25 18:50 UTC, Kirus59 commented on Content.Shared/Movement/Pulling/Components/PullerComponent.cs
> +    [DataField] [Access(Other = AccessPermissions.ReadWriteExecute)]
```suggestion
    [DataField] 
    [Access(Other = AccessPermissions.ReadWriteExecute)] // SS220 DarkReaper Access
```

2024-10-25 18:50 UTC, Kirus59 commented on Content.Shared/Movement/Pulling/Systems/PullingSystem.cs
> +
Это убрать

2024-10-25 18:50 UTC, Kirus59 commented on Content.Shared/SS220/DarkReaper/DarkReaperSharedSystem.cs
>      }
Не думаю что для этого нужен отдельный метод, тем более с указанием ивента как аргумента метода

2024-10-25 18:50 UTC, Kirus59 commented on Content.Shared/SS220/DarkReaper/DarkReaperSharedSystem.cs
> +        var confusedentities = _lookup.GetEntitiesInRange(uid, comp.StunAbilityConfusion);
```suggestion
        }
        
        var confusedentities = _lookup.GetEntitiesInRange(uid, comp.StunAbilityConfusion);
```

2024-10-25 18:50 UTC, Kirus59 commented on Content.Shared/SS220/DarkReaper/DarkReaperComponent.cs
> +    public string ConfusionEffectName = "Flashed";
У тебя весь `summary` будет писаться только у первого параметра.
Поэтому перед каждым параметром напиши отдельное `summary` с его описанием.

Ну и этим параметрам добавить бы аттрибут `[DataField]`

2024-10-25 18:50 UTC, Kirus59 commented on Content.Shared/SS220/DarkReaper/DarkReaperActions.cs
> +    [DataField, AutoNetworkedField]
Лишняя строка
```suggestion
    /// </summary>
    [DataField, AutoNetworkedField]
```

2024-10-25 21:24 UTC, Kirus59 requested changes

2024-10-25 21:24 UTC, Kirus59 commented on Content.Shared/Movement/Pulling/Systems/PullingSystem.cs
> -
Да не строку убрать, а своё изменение....
Короче этот файл должен быть в таком виде, как на мастере (т.к. ты сюда никаких изменений не вносил).

2024-10-25 21:24 UTC, Kirus59 commented on Content.Shared/SS220/DarkReaper/DarkReaperComponent.cs
> +    /// ConfusionDuration - duration of the confusion effect
```suggestion
    /// <summary>
    /// ConfusionDuration - duration of the confusion effect
```

2024-10-26 00:23 UTC, TryHardo7 commented on Content.Shared/Movement/Pulling/Systems/PullingSystem.cs
> -
Я понимаю, но не понимаю где там затерялся этот пробел который является изменением

2024-10-26 00:26 UTC, TryHardo7 commented on Content.Shared/Movement/Pulling/Systems/PullingSystem.cs
> -
Во, получилось

2024-10-27 12:45 UTC, Ady4ik approved these changes

2024-10-27 12:47 UTC, Kirus59 approved these changes

2024-10-27 12:47 UTC, merged