Electrical chair
SerbiaStrong-220/space-station-14 pull request #2147
Opened 2024-10-23 19:45 UTC by Kirus59

## Описание PR

Добавлен эелектрический стул по [трекеру](https://discord.com/channels/1097181193939730453/1293100347056848928)

**Медиа**

https://github.com/user-attachments/assets/18d4f6e3-3488-4264-9c51-b4ff0cd4fb74

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: kirus59
- add: Добавлено веселье!

2024-10-24 09:45 UTC, TryHardo7 commented
Добавлено веселье, которое мы заслужили

2025-04-06 22:28 UTC, stalengd requested changes

2025-04-06 22:28 UTC, stalengd commented on Content.Server/SS220/ElectricalChair/ElectricalChairComponent.cs
> +    [DataField, AutoNetworkedField]
Так, а разве `AutoNetworkedField` работает без `AutoGenerateComponentState`?

2025-04-07 05:09 UTC, Kirus59 commented on Content.Server/SS220/ElectricalChair/ElectricalChairComponent.cs
> +    [DataField, AutoNetworkedField]
А тут чисто серверный компонент, этого атрибута вообще не должно быть

2025-04-15 20:36 UTC, stalengd approved these changes

2025-04-16 18:50 UTC, UrPrice approved these changes

2025-04-16 18:53 UTC, merged