Ninja targets update
SerbiaStrong-220/space-station-14 pull request #2148
Opened 2024-10-24 08:52 UTC by Alwayswannahunt

## Описание PR
дд - https://discord.com/channels/1158128815311171638/1290759428634574931/1297207471030534226

**Цели**
Ниндзя получил три новые цели из двух новых типов целей - "Заказ на устрашение" и "Подставить сотрудника".
Убраны цели на взрыв паучьей бомбы и взлом консоли криминальных записей.

**Инструменты**
Маска ниндзя теперь умеет изменять ТТС и голос носителя.

 **Код**
Добавлены ивенты при изменении криминальных записей.

**Медиа**
TBA

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: AlwyAnri
- add: Добавлены новые цели для ниндзя - "Заказ на устрашение" и "Подставить сотрудника"!
- remove: Убраны цели ниндзя на взрыв бомбы и взлом консоли криминальных записей!
- tweak: Маска ниндзя теперь имеет свойства голосовой маски!

2024-10-24 09:49 UTC, TryHardo7 commented
Для ниндзи крайне легко выполнить заказ на устранение любого на станции, я считаю не нужна ему такая цель. Подставить - отлично, пакостить - ок, воровать - ок.
Может цель на взлом боргов? Они никогда этого не делают
Какое-то рп типа случайному члену экипажа без МЩ прокает цель стать учеником ниндзи и что-то в этом русле сделать?

2024-10-24 12:27 UTC, Alwayswannahunt commented
> Для ниндзи крайне легко выполнить заказ на устранение любого на станции, я считаю не нужна ему такая цель. Подставить - отлично, пакостить - ок, воровать - ок. Может цель на взлом боргов? Они никогда этого не делают Какое-то рп типа случайному члену экипажа без МЩ прокает цель стать учеником ниндзи и что-то в этом русле сделать?

Заказ на **устрашение**

Ниндзя работающий за РНД уже и так стал мемом, он теперь будет и боргов ещё собирать, подрабатывая утилём. Не, пожалуй, не этим он должен заниматься.

РП рпом, но цель засчитывать надо, никто не мешает написать в ахелп и отыграть такое с разрешения/помощи админа. Я уже молчу что ниндзя делать если ученик не хочет учиться? Любой ответ на этот вопрос сведёт на ноль интересность цели.

2024-12-06 20:28 UTC, Alwayswannahunt commented
@stalengd Я открою, но мерджить после тестов

2024-12-26 05:21 UTC, Kirus59 commented
@Alwayswannahunt Тут готово или еще ждем чего-то?

2024-12-26 12:55 UTC, Alwayswannahunt commented
@stalengd помоленьку кури кодинг.

2024-12-26 18:40 UTC, stalengd requested changes

2024-12-26 18:40 UTC, stalengd commented on Content.Server/SS220/Objectives/Components/IntimidatePersonConditionComponent.cs
> +    /// Description will be applied when objective is done. No params in it
Правильный док?

2024-12-26 18:40 UTC, stalengd commented on Resources/Textures/SS220/Objectives/frame.rsi/meta.json
> +    "copyright": "By Estkemran (Github) for SS220 for SS220",
for SS220 for SS220

2024-12-26 18:40 UTC, stalengd commented on Resources/Textures/SS220/Objectives/intimidate.rsi/meta.json
> +    "copyright": "By Estkemran (Github) for SS220 for SS220",
for SS220 for SS220

2025-02-16 13:49 UTC, Alwayswannahunt commented
@stalengd Я разгрёб своё, твой прошлый ревью учёл. Глянь и если рди, то можно мёржить

2025-02-16 18:37 UTC, stalengd approved these changes

2025-02-16 18:38 UTC, stalengd commented
@Alwayswannahunt картинок не добавишь?

2025-02-16 18:40 UTC, Alwayswannahunt commented
> @Alwayswannahunt картинок не добавишь?

А нечего... Ну я черепок кайфовый от Кемрана вкину, чтобы в дискорде тоже кайфанули

2025-02-16 18:43 UTC, merged