InverterGoodBye
SerbiaStrong-220/space-station-14 pull request #2149
Opened 2024-10-24 10:14 UTC by Tris0r

## Описание PR
Убран инвертор, но оставлен только для щитспавна

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
🆑 Cortez
- remove: инвертор квантового спина удалён до лучших времён

2024-10-24 10:26 UTC, Tris0r commented
Вроде правильно, а вроде и нет. Разрешаю душить.

2024-10-24 11:00 UTC, Kirus59 commented
> Разрешаю душить.

Ок

2024-10-24 11:02 UTC, Kirus59 requested changes

2024-10-24 11:02 UTC, Kirus59 commented on Resources/Maps/SS220/Shuttles/lostSoul/honki.yml
Карты лучше не трогать, а сделать через миграцию

2024-10-24 11:13 UTC, Tris0r commented on Resources/Maps/SS220/Shuttles/lostSoul/honki.yml
> Карты лучше не трогать, а сделать через миграцию

Я нинаю про что ты(

2024-10-24 11:29 UTC, Kirus59 commented on Resources/Maps/SS220/Shuttles/lostSoul/honki.yml
> Я нинаю про что ты(

Открываешь файл `Resources/migration.yml` и в конец добавляешь следующее:
```
# 2024-10-24 - SS220 InverterGoodBye
DeviceQuantumSpinInverter: null
```

2024-10-24 12:18 UTC, Tris0r commented on Resources/Maps/SS220/Shuttles/lostSoul/honki.yml
А я чё. Вижу .yml - лезу.
~mrow

2024-10-24 13:52 UTC, Tris0r commented on Resources/Maps/SS220/Shuttles/lostSoul/honki.yml
![BITmeeerge](https://github.com/user-attachments/assets/46f475f4-e2be-4948-92db-56ebacf29e26)

2024-10-24 16:35 UTC, Kirus59 requested changes

2024-10-24 16:35 UTC, Kirus59 commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/swapper.ftl
Почему это переехало в нашу папку?

2024-10-24 16:35 UTC, Kirus59 commented on Resources/Prototypes/Entities/Objects/Devices/swapper.yml
> +  suffix: Shitspawn
Пометку бы

2024-10-24 16:47 UTC, Tris0r commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/swapper.ftl
Я так сделал потому что

2024-10-24 17:13 UTC, Kirus59 commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/swapper.ftl
> Я так сделал потому что

?

2024-10-24 17:54 UTC, Tris0r commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/swapper.ftl
> > Я так сделал потому что
> 
> ?

Ну я взял и перенёс

2024-10-24 18:23 UTC, Kirus59 commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/swapper.ftl
> Ну я взял и перенёс

Вопрос зачем?

2024-10-24 19:30 UTC, Tris0r commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/swapper.ftl
> > Ну я взял и перенёс
> 
> Вопрос зачем?

Чтоб у нас было

2024-10-24 19:36 UTC, Kirus59 commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/swapper.ftl
> Чтоб у нас было

Чтобы что

2024-10-24 19:42 UTC, Tris0r commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/swapper.ftl
Чтобы он хранился в нашей папке

2024-10-24 19:43 UTC, Kirus59 commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/swapper.ftl
> Чтобы он хранился в нашей папке

Возвращай обратно

2024-10-24 20:14 UTC, Tris0r commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/devices/swapper.ftl
Ну так бы сразу и сказал.

2024-10-25 05:10 UTC, Kirus59 approved these changes

2024-10-25 08:23 UTC, merged