Cluwne comm
SerbiaStrong-220/space-station-14 pull request #2153
Opened 2024-10-24 22:21 UTC by SkaldetSkaeg

## Описание PR
Очень старый долг по клувне-коммуникационной консоли, попробую доделать

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up. Changelog must have a :cl: symbol, so the bot recognizes the changes and adds them to the game's changelog.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-10-25 16:30 UTC, stalengd commented
@SkaldetSkaeg Оно готово? Если нет, то лучше перенести в драфт

2025-04-08 12:50 UTC, SkaldetSkaeg commented
@UrPrice дарова, мне с кем время согласовывать между анонсами и кодами?
И добавлять ли больше каких-то сложно добываемых ингредиентов, чтобы получение консоли было равно или даже тяжелее, чем пробирание на мостик для анонсов?
Или это оставить на потом с балансной правкой?

2025-04-08 23:03 UTC, UrPrice commented
> @UrPrice дарова, мне с кем время согласовывать между анонсами и кодами? И добавлять ли больше каких-то сложно добываемых ингредиентов, чтобы получение консоли было равно или даже тяжелее, чем пробирание на мостик для анонсов? Или это оставить на потом с балансной правкой?

Ну, проще всего будет определить со временем конечно тяжесть крафта консоли. Пока звучит и так не просто. Так что посмотрим со временем наверное.

Согласовать надо будет с @Ady4ik через Суркса, вероятнее всего. Либо мы его сейчас и так призовём, либо надо будет его тегнуть. Если не заглянет через сутки сюда, пингану его в телеге.

2025-04-08 23:37 UTC, Ady4ik commented
> @UrPrice дарова, мне с кем время согласовывать между анонсами и кодами?
> И добавлять ли больше каких-то сложно добываемых ингредиентов, чтобы получение консоли было равно или даже тяжелее, чем пробирание на мостик для анонсов?
> Или это оставить на потом с балансной правкой?

Ку привет. Давай объектно опишешь, что как куда мне в ДС: крафт консоли; кд оповещений; кд смены кода и сами коды. Там поболтаем и порешим. 
По балансу стоимости всегда можно переделать.Ну а там с сурксом согласуемся

2025-04-12 05:42 UTC, SkaldetSkaeg commented
> > @UrPrice дарова, мне с кем время согласовывать между анонсами и кодами?
> > И добавлять ли больше каких-то сложно добываемых ингредиентов, чтобы получение консоли было равно или даже тяжелее, чем пробирание на мостик для анонсов?
> > Или это оставить на потом с балансной правкой?
> 
> Ку привет. Давай объектно опишешь, что как куда мне в ДС: крафт консоли; кд оповещений; кд смены кода и сами коды. Там поболтаем и порешим. По балансу стоимости всегда можно переделать.Ну а там с сурксом согласуемся

написал, жду ответов

2025-04-19 13:44 UTC, SkaldetSkaeg commented
@UrPrice Адуч не ознакомился, жду тогда от тебя вердикта

2025-04-19 14:24 UTC, UrPrice commented
> @UrPrice Адуч не ознакомился, жду тогда от тебя вердикта

Я где-то какую-то инфу должен был получить?

2025-04-19 15:20 UTC, SkaldetSkaeg commented
> > @UrPrice Адуч не ознакомился, жду тогда от тебя вердикта
> 
> Я где-то какую-то инфу должен был получить?

Скинул то, что скинул адучу в личку дискорда

2025-04-21 15:39 UTC, SkaldetSkaeg commented on Resources/Textures/SS220/Interface/CluwneComms/cluwne_comms_big_button.rsi/hover.png
@stalengd а это зачем?

2025-04-21 18:15 UTC, stalengd commented on Resources/Textures/SS220/Interface/CluwneComms/cluwne_comms_big_button.rsi/hover.png
Решал сделать такую анимацию кнопки при наведении

2025-04-21 18:52 UTC, stalengd requested changes

2025-04-21 18:52 UTC, stalengd commented on Content.Client/SS220/CluwneComms/UI/CluwneCommsConsoleMenu.xaml.cs
> +        public CluwneCommsConsoleMenu()
```suggestion
        public event Action? OnBoom;
        
        public CluwneCommsConsoleMenu()
```

2025-04-21 18:52 UTC, stalengd commented on Content.Client/SS220/CluwneComms/UI/CluwneCommsConsoleMenu.xaml.cs
> +            #region Announce
Точно ли имеет смысл использовать `#region`? Это довольно сомнительная практика, в данном случае помогло бы просто разделение на методы (например `CreateAnnounce()`)

2025-04-21 18:52 UTC, stalengd commented on Content.Client/SS220/CluwneComms/UI/CluwneCommsConsoleMenu.xaml.cs
> +        #endregion
Уэээ region начинается внутри конструкора, а заканчивается уже после

2025-04-21 18:52 UTC, stalengd commented on Content.Client/SS220/CluwneComms/UI/CluwneCommsConsoleMenu.xaml.cs
> +            // SS220 Text Edit Limits end
Это что-то лишнее

2025-04-21 18:52 UTC, stalengd commented on Content.Server/SS220/CluwneComms/CluwneCommsConsoleSystem.cs
> +        private void OnAnnounceMessage(Entity<CluwneCommsConsoleComponent> ent, ref CluwneCommsConsoleAnnounceMessage args)
```suggestion
        }
        
        private void OnAnnounceMessage(Entity<CluwneCommsConsoleComponent> ent, ref CluwneCommsConsoleAnnounceMessage args)
```

2025-04-21 18:52 UTC, stalengd commented on Content.Server/SS220/CluwneComms/CluwneCommsConsoleSystem.cs
> +            msg += "\n" + Loc.GetString("cluwne-comms-console-announcement-sent-by") + " " + author;
```suggestion
            msg = $"{msg}\n{Loc.GetString("cluwne-comms-console-announcement-sent-by")} {author}";
```

2025-04-21 18:52 UTC, stalengd commented on Content.Server/SS220/CluwneComms/CluwneCommsConsoleSystem.cs
> +        private void OnAlertMessage(Entity<CluwneCommsConsoleComponent> ent, ref CluwneCommsConsoleAlertMessage args)
```suggestion
        }
        
        private void OnAlertMessage(Entity<CluwneCommsConsoleComponent> ent, ref CluwneCommsConsoleAlertMessage args)
```

2025-04-21 18:52 UTC, stalengd commented on Content.Server/SS220/CluwneComms/CluwneCommsConsoleSystem.cs
> +                Title = Loc.GetString("joke-alert-level-" + args.Alert + "-news-title"),
```suggestion
                Title = Loc.GetString($"joke-alert-level-{args.Alert}-news-title"),
```

2025-04-21 18:52 UTC, stalengd commented on Content.Server/SS220/CluwneComms/CluwneCommsConsoleSystem.cs
> +        private void UpdateWriterDevices()
```suggestion
        }
        
        private void UpdateWriterDevices()
```

2025-04-21 18:52 UTC, stalengd commented on Content.Shared/SS220/CluwneComms/CluwneCommsConsoleComponent.cs
> +        public float MaxTileIntensity = 50f;
Если это всё параметры взрыва, то пускай это будет отражено в названии, например `ExplosionTotalIntensity`

2025-04-21 18:52 UTC, stalengd commented on Resources/Audio/SS220/Machines/CluwneComm/ui_cancel.xmp
Этот фай нужен?

2025-04-21 18:52 UTC, stalengd commented on Content.Client/SS220/CluwneComms/UI/CluwneCommsConsoleMenu.xaml
> +                        <OptionButton Name="AlertLevelButton" Access="Public" OptionStyleClasses="button" Margin="0 0 0 6" />
```
Access="Public"
```
Всем этим элементам (он тут не один такой) действительно нужно быть с публичным доступом?

2025-04-21 18:56 UTC, SkaldetSkaeg commented on Content.Server/SS220/CluwneComms/CluwneCommsConsoleSystem.cs
> +                Title = Loc.GetString("joke-alert-level-" + args.Alert + "-news-title"),
Я так пробовал, у меня не заработало

2025-04-21 19:20 UTC, SkaldetSkaeg commented on Content.Client/SS220/CluwneComms/UI/CluwneCommsConsoleMenu.xaml
> +                        <OptionButton Name="AlertLevelButton" Access="Public" OptionStyleClasses="button" Margin="0 0 0 6" />
> ```
> Access="Public"
> ```
> 
> Всем этим элементам (он тут не один такой) действительно нужно быть с публичным доступом?

да, иначе их нельзя дисэйблить в BUI
можно, кончено, это всё пробовать вытаскивать из UpdateState(BoundUserInterfaceState state)

Пробовать?

2025-04-25 19:16 UTC, stalengd requested changes

2025-04-25 19:16 UTC, stalengd commented on Content.Server/SS220/CluwneComms/CluwneCommsConsoleSystem.cs
> +        /// </summary>
Такая документация привязана к следующему за ней члену, здесь же это должен быть обычный комментарий, он не относится к `UpdateWriterUi`

2025-04-25 19:16 UTC, stalengd commented on Content.Client/SS220/CluwneComms/UI/CluwneCommsConsoleMenu.xaml
> +                        <OptionButton Name="AlertLevelButton" Access="Public" OptionStyleClasses="button" Margin="0 0 0 6" />
Я понял, ну если хочешь в принципе можно так оставить, можно сделать методы в `.xaml.cs` на уровне `SetAlertLevelButtonEnabled(bool)`

2025-04-30 09:00 UTC, UrPrice approved these changes

2025-05-04 16:46 UTC, Ady4ik approved these changes

2025-05-11 10:22 UTC, stalengd requested changes

2025-05-11 10:22 UTC, stalengd commented on Content.Client/SS220/CluwneComms/UI/CluwneCommsConsoleBoundUserInterface.cs
> +            if (_random.Prob(boomChance))
1. Почему шанс из меню приходит?
2. Почему шанс вообще на клиенте общитывается, так быть не должно

2025-05-11 10:22 UTC, stalengd commented on Content.Server/SS220/CluwneComms/CluwneCommsConsoleSystem.cs
> +        private void OnAlertMessage(Entity<CluwneCommsConsoleComponent> ent, ref CluwneCommsConsoleAlertMessage args)
Пу-пу-пу

2025-05-11 10:22 UTC, stalengd commented on Content.Server/SS220/CluwneComms/CluwneCommsConsoleSystem.cs
> +        /// </summary>
Пу-пу-пу

2025-05-11 10:24 UTC, stalengd requested changes

2025-05-11 10:24 UTC, stalengd commented on Content.Server/SS220/CluwneComms/CluwneCommsConsoleSystem.cs
> +        ///     Copypaste from NewsSystem because original methods are private
```suggestion
        //     Copypaste from NewsSystem because original methods are private
```

2025-05-11 10:41 UTC, SkaldetSkaeg commented on Content.Client/SS220/CluwneComms/UI/CluwneCommsConsoleBoundUserInterface.cs
> +            if (_random.Prob(boomChance))
> 1. Почему шанс из меню приходит?
> 2. Почему шанс вообще на клиенте общитывается, так быть не должно

1 - в момент взрыва ломается консоль, что приводит к ишшуе с UI, не нашел лучшего выхода, чем закрывать её перед взрывом.
2 - если закрывать после каждого нажатия кнопки, то это превращается в заеб с переоткрытием, а для избегания ишшуе с 1 ошибкой мне пришлось высчитывать вероятность в самом UI консоли

2025-05-11 15:09 UTC, stalengd approved these changes

2025-05-11 15:10 UTC, merged