SpicyPizza ^_^
SerbiaStrong-220/space-station-14 pull request #2163
Opened 2024-10-26 19:38 UTC by jellycrab-sprite

## Описание PR

Данный PR добавляет в игру острую пиццу. Это мясная пицца, которая при бросании разрывается 10 острых кусочков, которые летят подобно метательным ножам. При попадании в цель они наносят 9 колющего урона, игнорируя любую броню и вводят в цель немного флогистона, что поджигает её.
Также её можно разрезать на слайсы и использовать их как метательное орудие. Вещество внутри вводится в человека при первом попадании и более не восполняется. Также в кусочек после попадания не получится ввести какие-либо вещества.
Пиццу можно употребить в пищу. При поедании она наносит термический и slash урон, т.к в её компоненте пищи есть бритвиум и флогистон. 
Способы получения:
- Пицца может случайно появиться на карте как предмет еды с очень маленьким шансом.
- Пицца может с шансом в 3% оказаться в коробке, заказываемой отделом карго
- Пиццу можно приобрести за 4 тк в аплинке повара и мима

Добавлена локализация, уникальный вкус и описание в аплинке.

Цель данного ПР'а - это ввести разнообразие в геймплей как антагонистов, так и экипажа станции.

**Медиа**

![image](https://github.com/user-attachments/assets/70b763a6-2e42-4601-9117-5aeb303a0e34)
![image](https://github.com/user-attachments/assets/93572b2a-f454-443e-a14f-f0c93a57841b)
![image](https://github.com/user-attachments/assets/a7caa785-2c9f-4672-9e43-336b6eb5b2d8)
![image](https://github.com/user-attachments/assets/47566379-ac71-489a-a39f-7c24f4ec432e)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: jellycrab
- add: Добавлена разрывная пицца
- add: Добавлены способы получения разрывной пиццы

2024-10-26 19:46 UTC, lexaSvarshik commented
Имхо цену бы скинуть, ибо за 4ТК можно гранату купить разрывную/осколочную, которая гораздо больнее бахает.
Либо, как вариант - добавить в коробку с пиццей плату от микроволновки Donk Co. и рецепт крафта пиццы в ней

2024-10-27 02:01 UTC, UrPrice commented on Resources/Locale/ru-RU/spicypizza.ftl
Почему неймспейс то не /ss220/ ?

2024-10-27 02:02 UTC, UrPrice commented on Resources/Prototypes/SS220/Catalog/uplink_catalog.yml
> +    - Mime
Честно говоря, так и не понял, почему он должен находиться у мима. Мим же классически французская история, там, а пицца национально итальянское блюдо

2024-10-27 02:06 UTC, UrPrice commented on Resources/Prototypes/Entities/Objects/Consumable/Food/Containers/box.yml
> +      prob: 0.03
Как и появление в спавнере одиночной еды - это плохая практика. Лучше разделить эти две пиццы на две версии - версию из аплинка, и более миролюбивая версия из спавнеров. Вводить синдилут таким образом - не очень хорошо, так как по характеристикам он никак не ослаблен, а случайное появление ещё и обесценивает его необходимость в аплинке.

2024-10-27 02:10 UTC, UrPrice commented on Resources/Locale/ru-RU/spicypizza.ftl
Как мапперу понять, что это синдилут? Добавьте соответствующий суфикс, пока не прошла глобальная реформа по этим делам по таску https://discord.com/channels/1158128815311171638/1282537229193056267

2024-10-27 02:11 UTC, UrPrice requested changes
В общем всё выше

2024-10-27 08:26 UTC, jellycrab-sprite commented
Проблему суффиксом и репозиторием исправлю.
Касаемо остального - в целом тут нет ничего, с чем бы я не был согласен. В ближайшее время добавлю мирную версию этой пиццы. Если уж она будет почти безвредна, то добавлю побольше способов получения именно мирной пиццы. 
А про момент с мимом я тоже не особо вдупляю, видимо на свежую голову надо всё делать

2024-10-27 08:29 UTC, jellycrab-sprite commented
Насчёт самой механики пиццы нет каких-либо замечаний?

2024-10-27 08:31 UTC, jellycrab-sprite commented
Закрою этот PR и создам новый, как доделаю UPD, с моей веткой на форке что-то случилось

2024-10-27 08:51 UTC, closed without merging