FIX: Stunbaton stamina damage toggle
SerbiaStrong-220/space-station-14 pull request #2167
Opened 2024-10-27 16:51 UTC by ReeZer2

## Описание PR
Теперь батон и станпрод не наносит стамина урон, если они выключены

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: ReeZii
- fix: Теперь станбатон не наносит урон стамине, если он выключен

2024-10-27 21:18 UTC, stalengd commented on Content.Server/Damage/Systems/DamageOtherOnHitSystem.cs
> +                if (damageType == "Stamina" && HasComp<StunbatonComponent>(uid) && !_itemToggle.IsActivated(uid))
Хардкод id прототипа "Stamina"

2024-10-27 21:28 UTC, stalengd commented
Зачем добавлять сюда компонент `DamageOtherOnHit` и модифицировать его логику причём хардкодить там тип урона? Не лучше добавить флаг типа `RequireItemEnabled` в `StaminaDamageOnHit` и `StaminaDamageOnCollide`? @Kirus59, я думаю это лучше тебе посмотреть, ты лучше в уроне разбираешься

2024-10-27 21:58 UTC, Kirus59 commented
`StaminaDamageOnHit` считаю что вообще нужно убрать у станпрода и добавить стамина урон в `ItemToggleMeleeWeapon`, чтобы не было игнора резистов у цели.

Также для дамага при броске считаю что нужно либо в `DamageOtherOnHit` добавить флаг `RequireItemEnabled` либо создать отдельный компонент `ItemToggleDamageOtherOnHit`.

Компоненты `StaminaDamage` лучше вообще не использовать, т.к. они игнорируют стамина-резисты у цели (т.к. у оффов нет стамины как `damageType` и соответственно стамина-резистов у чего-либо).

2024-10-29 07:30 UTC, ReeZer2 commented
Так, я мог что-то забыть, но если и забыл, то найти не могу. НО вроде готово

2024-10-29 09:24 UTC, Kirus59 requested changes
В остальном норм

2024-10-29 09:24 UTC, Kirus59 commented on Content.Server/Damage/Components/DamageOtherOnHitComponent.cs
> +    [Access(typeof(DamageOtherOnHitSystem), typeof(ItemToggleOnHitSystem))]
пометку бы

2024-10-29 09:24 UTC, Kirus59 commented on Content.Server/Damage/Systems/DamageOtherOnHitSystem.cs
> +using Content.Server.Stunnable.Components;
лишний using

2024-10-29 09:24 UTC, Kirus59 commented on Content.Server/Damage/Systems/DamageOtherOnHitSystem.cs
> +using Content.Shared.Item.ItemToggle;
и этот

2024-10-29 09:24 UTC, Kirus59 commented on Content.Server/SS220/ItemToggle/ItemToggleOnHitComponent.cs
> +public sealed partial class ItemToggleOnHitComponent : Component
Неудачное название компонента, лучше назвать `ItemToggleDamageOnHitComponent` или `ItemToggleDamageOtherOnHitComponent` чтобы было понятно с чем он связан.

2024-10-29 09:24 UTC, Kirus59 commented on Resources/Prototypes/Entities/Objects/Weapons/Melee/stunprod.yml
Для наших изменений пометки бы

2024-10-29 10:07 UTC, ReeZer2 commented
> В остальном норм

Проверяй, вроде все поставил

2024-10-29 10:20 UTC, ReeZer2 commented
насрал...

2024-10-29 10:21 UTC, Kirus59 approved these changes

2024-10-29 10:32 UTC, merged