BlueShield Rework
SerbiaStrong-220/space-station-14 pull request #2170
Opened 2024-10-27 21:28 UTC by EstKemran

## Описание PR
ХЗ можно ли это назвать реворком, но пихуй

**Медиа**
![изображение](https://github.com/user-attachments/assets/db944e51-d272-4152-841f-184ea055da02)

**Потом будет спрайтшит**

## todo
- [ ] То, что сделано. Потом оформлю как следует
- [ ] Респрайт лазерного пистолета. Два режим с разной скорострельностью. Убрать автозаряд
- [ ] Альтернативу Дрозду. Придумать какую-то уникальность
- [ ] Посох, ждём
- [ ] Защитный шлем. Что-то ближе к гвардии
- [ ] Перерисовать КПК и Гарнитуру (Опционально)
- [ ] Два скафандра (Добавить тяжелый, перерисовать лёгкий). К ним два шлема
- [ ] Перерисовать плащ, добавить наплечный.
- [ ] Что то десятое
- [ ] Помолиться, чтобы это одобрили

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up. Changelog must have a :cl: symbol, so the bot recognizes the changes and adds them to the game's changelog.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-10-28 20:30 UTC, UrPrice commented
Палитра стремная какая-то

2024-10-29 11:46 UTC, FriedrichStrassen commented
Палитра стрёмная. Капец яркий. Думаю от изначального варианта далеко уходить не стоит

2024-10-29 12:42 UTC, EstKemran commented
Эта палитра, которая была в палитре ещё до моего рождения 
![Screenshot_20241029-154134_Discord](https://github.com/user-attachments/assets/039d5cf3-f22e-4899-a278-5cae50737c94)

2024-10-29 14:56 UTC, FriedrichStrassen commented
Это залупа какая-то. Китовразу покажи

2024-10-30 12:41 UTC, Abiergo commented
Какая красота... Ещеб ему конечно лодаут за 100 часов... Но а так пиздец круто
![Cat yells at camera HD REMAKE](https://github.com/user-attachments/assets/32ebef17-13b8-45b8-a70e-55565c63cb53)

2024-11-23 18:17 UTC, EstKemran commented
@Ady4ik По механическим и балансным изменениям всё. Осталась косметика.

Синергетический пистолет имеет два режима стрельбы: лазер на 13 урона, лазер на 45 урона (Скорострельный и сконцентрированный). После того, как кодеры закодят, у режимов будет разная скорострельность, и ДПС будет 52 у первого и 55 у второго (У антиквара 48). Ну и собственно, у него нет автозарядки

2024-12-20 18:06 UTC, lexaSvarshik requested changes
Бегло пробежался по локали и прототипам, на баланс особо не смотрел, хоть и есть некоторые очень сильные штуки

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/clothing/Ears/headset.ftl
> +ent-ClothingHeadsetBlueShield = полноразмерная гарнитура капитана
```suggestion
ent-ClothingHeadsetBlueShield = полноразмерная гарнитура "Синий Щит"
```

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/clothing/OuterClothing/armor.ftl
> +    .desc = Бронежилет странной формы, напоминающий чешую дракона. Изготовители говорят, что материал бронежилета способен выдержать дыхание дракона.
дракона дракона
```suggestion
    .desc = Бронежилет странной формы, по структуре напоминающий чешую. Изготовители говорят, что материал бронежилета способен выдержать дыхание дракона.
```

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/clothing/Head/hats.ftl
> +    .desc = Недорогой берет, излюбленный офицерами "Синий Щит". Виднеется эмблема синего щита.
синий щит синий щит
```suggestion
    .desc = Недорогой берет, излюбленный офицерами "Синий Щит". На нём изображена эмблема щита синего цвета.
```

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/clothing/OuterClothing/hardsuits.ftl
> +    .desc = Специальный скафандр, разработанный для "Синий щит". Он выделяется своей легкостью и высокой маневренностью.
```suggestion
    .desc = Специальный скафандр, разработанный для "Синий щит". Он отличается своей легкостью и высокой маневренностью.
```

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/clothing/Shoes/shoes.ftl
> +ent-ClothingShoesBootsBlueShieldJack = подковные сапоги
```suggestion
ent-ClothingShoesBootsBlueShieldJack = подкованные сапоги
```

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/clothing/Shoes/shoes.ftl
> +ent-ClothingShoesBootsBlueShieldJackFilled = подковные сапоги
Необязательно прописывать локаль дважды, можно сделать чуть проще
```suggestion
ent-ClothingShoesBootsBlueShieldJackFilled = { ent-ClothingShoesBootsBlueShieldJack }
```

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/clothing/Shoes/shoes.ftl
> +        .desc = Защитные боевые ботинки для боевых сценариев или боевых ситуаций. Все время в бою.
```suggestion
        .desc = { ent-ClothingShoesBootsBlueShieldJack.desc }
```

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/clothing/Uniforms/jumpsuit.ftl
> +    .desc = Рубашка, использующая высокопоставленными людьми синего щита при официальных встречах.
```suggestion
    .desc = Рубашка, используемая высокопоставленными оперативниками синего щита при официальных встречах.
```

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/clothing/Uniforms/jumpsuit.ftl
> +    .desc = Рубашка, использующая высокопоставленными людьми синего щита при официальных встречах.
Опять же просто стянем с уже готового
```suggestion
    .desc = { ent-ClothingUniformJumpsuitBlueShieldShirt.desc }
```

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/clothing/Uniforms/jumpsuit.ftl
> +    .desc = Черная футболка с короткими рукавами, в паре с черными брюками из прочного материала. Прекрасно подходит для отдыха на безопасном секторе NanoTrasen.
```suggestion
    .desc = Черная футболка с короткими рукавами, в паре с черными брюками из прочного материала. Прекрасно подходит для отдыха в безопасном секторе NanoTrasen.
```

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Clothing/Head/hats.yml
> +  description: The inexpensive beret favored by officers is the "Blue Shield". The blue shield emblem is visible.
```suggestion
  description: An inexpensive beret favored by the "Blue Shield" officers. It has the shield emblem in blue color on it.
```

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Clothing/OuterClothing/hardsuits.yml
> +  description: hight higt hight
че

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  description: "An innovative weapon that combines advanced technology and a unique design. It has two shooting modes: normal and enhanced."
```suggestion
  description: An innovative weapon that combines advanced technology and a unique design. It has two shooting modes: normal and enhanced.
```

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Melee/bs_bo.yml
> +    reflectProbProjectile: 0.4
Это как у есворда :\

2024-12-20 18:06 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Loadouts/loadout_groups.yml
> +  minLimit: 0
Я бы 1 сделал, чтобы щит без очков не мог появиться даже по случайности
```suggestion
  minLimit: 1
```

2024-12-21 12:53 UTC, EstKemran commented on Resources/Locale/ru-RU/ss220/clothing/Shoes/shoes.ftl
> +ent-ClothingShoesBootsBlueShieldJackFilled = подковные сапоги
Не сказал бы, что проще. Скорее наоборот

2024-12-21 16:51 UTC, EstKemran commented
По рофлу упали :taa:

2024-12-21 19:34 UTC, Kirus59 commented
> По рофлу упали :taa:

Не по рофлу

2024-12-21 20:02 UTC, Kirus59 requested changes

2024-12-21 20:02 UTC, Kirus59 commented on Resources/Textures/Clothing/Hands/Gloves/combat.rsi/meta.json
> +  "copyright": "Taken from Skyrat-tg at commit https://github.com/Skyrat-SS13/Skyrat-tg/commit/b9c06b16579dc828ac4d6f603995e083075725b2, modified by Estkemran (Github) for SS220",
Для предотвращения возможных проблем при и после апстрима - респрайт лучше добавлять в нашу директорию, а в прототипе менять путь на наши спрайты.

2024-12-21 20:04 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Clothing/Belt/belts.yml
> +    - 10,1,10,2
Я так понимаю это будет как раньше было в РПС?

2024-12-21 20:04 UTC, EstKemran commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
> +  - type: BatteryWeaponFireModes
Тест жаловался на `proto: RedLightLaser`, поэтому убрал. Посмотрим

2024-12-21 20:07 UTC, Kirus59 commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-centcom-SRT-description = Вы оперативник "Синий Щит". Выполните поставленную перед вами задачу!
Ну и там где эта локаль используется - заменить название тоже (я просто упустил где).

2024-12-21 20:07 UTC, EstKemran commented
@Kirus59 Если менять id ГСН, придётся карту ЦК менять (В этом ПРе). Мне менять или оставить?

2024-12-21 20:13 UTC, Kirus59 commented
> @Kirus59 Если менять id с GSN/SRT, придётся карту ЦК менять (В этом ПРе). Мне менять или оставить?

Вообще лучше сделать отдельным ПРом, просто ты в некоторых местах уже сделал, я и поотмечал где не сделано.

2024-12-21 20:17 UTC, EstKemran commented
> > @Kirus59 Если менять id с GSN/SRT, придётся карту ЦК менять (В этом ПРе). Мне менять или оставить?
> 
> Вообще лучше сделать отдельным ПРом, просто ты в некоторых местах уже сделал, я и поотмечал где не сделано.

Менял то, что не заспавнено. А если менять заспавненное (замапленное), то Прайсу не понравится, что меняют прототип карт, поэтому не трогал :mbmbmb:

2024-12-21 20:22 UTC, Kirus59 commented
> Менял то, что не заспавнено. А если менять заспавненное (замапленное), то Прайсу не понравится, что меняют прототип карт, поэтому не трогал :mbmbmb:

Если и менять - то всё, и отдельным коммитом/ПРом, чтобы можно было спокойно откатить в случае чего.
Замаппленое можно спокойно поменять через миграцию

2024-12-22 03:32 UTC, UrPrice commented
В предверии деплоя - ок

2024-12-22 11:05 UTC, Kirus59 approved these changes

2024-12-22 11:22 UTC, merged