More ammo recipies to lathes
SerbiaStrong-220/space-station-14 pull request #2173
Opened 2024-10-28 16:42 UTC by lexaSvarshik

## Описание PR

[Идея](https://discord.com/channels/1158128815311171638/1300048487932493945)

ПР добавляет крафты многих недостающих магазинов в фабы/латы. Так же, добавлено несколько уникальных крафтов для емагнутого автолата.

**Добавлено:**
- Крафт спидлоадера .30 (на мосинку) в охранный техфаб, емагнутый автолат, фаб патронов
- Крафт магазинов .45 магнум (для N1984). Пустой, летал, резина, уран, зажиги.
- Крафт .35 зажигательного магазина (не было в игре)
- Крафт .45 зажигательного магазина (не было в игре)
- .25 безгильзовые - коробка и магазин в емагнутый автолат
- .35 автопистолетные - пустой и летал в емагнутый автолат

**Медиа**

![изображение](https://github.com/user-attachments/assets/772be8b5-0bae-4e61-9092-bc9e7e07d529)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Svarshik
- add: Добавлены крафт .25 безгильзовых и .35 автопистолетных магазинов в емагнутый автолат!
- add: Добавлен крафт спидлоадера .30
- add: Добавлены рецепты некоторых недостающих магазинов

2024-11-10 11:23 UTC, stalengd requested changes

2024-11-10 11:23 UTC, stalengd commented on Resources/Prototypes/Recipes/Lathes/security.yml
Перенести в нашу директорию

2024-11-10 11:23 UTC, stalengd commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/pistol.yml
Перенести в нашу директорию

2024-11-10 11:23 UTC, stalengd commented on Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/magnum.yml
Перенести в нашу директорию

2024-11-17 19:11 UTC, lexaSvarshik commented
Чеки упали из-за фигни какой-то

2024-11-17 21:06 UTC, UrPrice commented
Перезапустил

2024-11-17 22:51 UTC, stalengd approved these changes

2024-11-17 22:52 UTC, merged