WatermelonInHands
SerbiaStrong-220/space-station-14 pull request #2177
Opened 2024-10-28 19:46 UTC by jellycrab-sprite

## Описание PR

Глобальная обнова. Список изменений:
- арбуз в руках 

**Медиа**

![image](https://github.com/user-attachments/assets/f77504d0-73d2-46a1-9bc2-be67cba08bf0)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: DaGo
- add: Добавлены In-hands спрайты арбуза

2024-10-28 22:36 UTC, stalengd approved these changes

2024-10-28 22:56 UTC, UrPrice commented
![image](https://github.com/user-attachments/assets/3840fdcf-5b16-442a-9aba-89767d717dc3)

2024-10-29 18:17 UTC, EstKemran approved these changes

2024-10-29 18:18 UTC, stalengd requested changes

2024-10-29 18:18 UTC, stalengd commented on Resources/Prototypes/Entities/Objects/Consumable/Food/produce.yml
> +      - state: produce-inhand-right
```suggestion
    # SS220 WatermelonInHands begin
    inhandVisuals:
      left:
      - state: produce-inhand-left
      right:
      - state: produce-inhand-right
    # SS220 WatermelonInHands end
```

2024-10-29 19:28 UTC, stalengd approved these changes

2024-10-30 06:55 UTC, merged