Hardsuit centcomm
SerbiaStrong-220/space-station-14 pull request #2180
Opened 2024-10-29 07:22 UTC by Surani1

## Описание PR
Добавлен скафандр варута для цк с пометкой щитспавн.

**Медиа**
![image](https://github.com/user-attachments/assets/ca56b292-515f-4e66-8a82-c9bc0c0c4304)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
щитспавн, поэтому no cl no fun

2024-10-29 09:18 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Clothing/Head/hardsuit-helmets.yml
> +  description: Премиальный шлем бронескафандра для Офицеров Центрального Командования.
уээээээ

2024-10-29 09:18 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Clothing/OuterClothing/hardsuits.yml
> +  description: Премиальный бронескафандр для Офицеров Центрального Командования.
уэээээ

2024-10-29 09:57 UTC, Surani1 commented
Это щитспавн предмет от администрации. Он не будет в игре, кроме как щитспавна

2024-10-29 09:57 UTC, Surani1 commented
Закинул в гит, чтобы каждый раз аплоады админы не писали

2024-10-29 16:39 UTC, EstKemran commented
Это пиздец..

2024-10-31 08:27 UTC, Kirus59 commented
@EstKemran Что по ревью?
@Surani1 Исправляй локализацию

2024-11-01 12:24 UTC, Surani1 commented
> @EstKemran Что по ревью?
> 
> @Surani1 Исправляй локализацию

Конкретнее пжлст

2024-11-01 12:33 UTC, Kirus59 requested changes

2024-11-01 12:33 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Clothing/Head/hardsuit-helmets.yml
> +  description: Премиальный шлем бронескафандра для Офицеров Центрального Командования.
Перенести в локализацию, переводить тут на английский не обязательно (эти поля можно удалить из прототипа).

2024-11-01 12:33 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Clothing/OuterClothing/hardsuits.yml
> +  description: Премиальный бронескафандр для Офицеров Центрального Командования.
Перенести в локализацию, переводить тут на английский не обязательно (эти поля можно удалить из прототипа).

2024-11-08 11:39 UTC, Kit0vras commented
Это пиздец

2024-11-20 13:42 UTC, closed without merging