Tape recorder for iaa and lawyer
SerbiaStrong-220/space-station-14 pull request #2190
Opened 2024-11-01 13:15 UTC by lexaSvarshik

## Описание PR

Фикс: ручка ЦК у магистрата, у авд её больше нет
Новое: в раунндстарт лоадаут адвокату и авд добавлены коробки с диктофоном.

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Svarshik
- add: Добавлены диктофоны для адвокатов и АВД!
- fix: Ручка ЦК переезжает из чемодана АВД в чемодан Магистрата.

2024-11-01 13:49 UTC, Ady4ik requested changes
Адвокату лишнее, имхо, я бы лучше дал магистрату

2024-11-01 13:51 UTC, lexaSvarshik commented
> Адвокату лишнее, имхо, я бы лучше дал магистрату

У магистрата оно уже есть в шкафу. Ну и, опять же, адвокату оно нужно на время допроса, чтоб при надобности уличить СБ в их словах или же, наоборот,  вещественно подкрепить то, что обвиняемый что-то говорил/не говорил.

2024-11-09 05:24 UTC, Ady4ik commented
> > Адвокату лишнее, имхо, я бы лучше дал магистрату
> 
> У магистрата оно уже есть в шкафу. Ну и, опять же, адвокату оно нужно на время допроса, чтоб при надобности уличить СБ в их словах или же, наоборот,  вещественно подкрепить то, что обвиняемый что-то говорил/не говорил.

Тоже правда, я чет изначально о другом подумал

2024-11-09 05:24 UTC, Ady4ik approved these changes

2024-11-09 19:56 UTC, stalengd approved these changes

2024-11-09 19:56 UTC, merged