Disposal Unit AI interactible fix
SerbiaStrong-220/space-station-14 pull request #2213
Opened 2024-11-05 21:17 UTC by Bomjojuk

## Описание PR
Добавляет возможность станционному ИИ взаимодействовать с мусорками

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl:
- tweak: Станционный ИИ теперь может взаимодействовать с утилизационными блоками

2024-11-05 21:38 UTC, UrPrice commented
@stalengd без ревью Адуча, минорные изменения можем без его апрува рассматривать

2024-11-05 21:40 UTC, stalengd commented
> @stalengd без ревью Адуча, минорные изменения можем без его апрува рассматривать

Вот только кто без ревью определит что они минорные...
Ладно, если это минорное, то окей

2024-11-05 21:43 UTC, UrPrice commented
> > @stalengd без ревью Адуча, минорные изменения можем без его апрува рассматривать
> 
> Вот только кто без ревью определит что они минорные... Ладно, если это минорное, то окей

Ну типа трекероведов на это и набирали, чтобы они могли пушить минорные изменения без излишней бюрократии.

2024-11-05 21:50 UTC, Bomjojuk commented
> > @stalengd без ревью Адуча, минорные изменения можем без его апрува рассматривать
> 
> Вот только кто без ревью определит что они минорные... Ладно, если это минорное, то окей

то что сказал прайс, + мы это уже обсудили в идеях qa

2024-11-05 22:04 UTC, stalengd approved these changes

2024-11-05 22:05 UTC, stalengd requested changes
А, стоп, а метку?

2024-11-05 23:20 UTC, Bomjojuk commented
> А, стоп, а метку?

Точн, сек

2024-11-06 15:21 UTC, Surani1 commented
12 коммитов и изменение одной строчки 
![155774f070222683c5730fce24794328](https://github.com/user-attachments/assets/915addf7-128c-4573-8543-077887ae4785)

2024-11-06 17:23 UTC, stalengd approved these changes

2024-11-06 17:23 UTC, merged