Yao features
SerbiaStrong-220/space-station-14 pull request #222
Opened 2023-08-15 22:52 UTC by aw-c

## Описание PR

При объявлении войны ядерным даётся 240 ТК, на раздумье есть 5 минут от начала раунда. В это время они не могут пользоваться консолью шаттла. После объявления войны накладывается дополнительный кулдаун, они смогут отправиться только через 20 минут.
При объявлении войны соло нюке даётся 100 ТК. Ограничения по времени нет.

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Alan Wake, TheArturZh, Ady4ik
- add: Добавлена механика войны!

2023-08-15 23:46 UTC, TheArturZh requested changes

2023-08-15 23:46 UTC, TheArturZh commented on Content.Server/SS220/WarFeatures/ConsoleNukeSystem.cs
> +        private bool _isWarStarted = false;
Системы не создаются заново каждый раунд, в них нельзя хранить состояние вот так.
Из-за этого есть баг, что после раунда с ЯО, в следующих раундах ЯО уже не получают ТК за объявление
Лучше всего запихнуть этот бул в NukeopsRuleComponent где хранить состояние можно.
Как получить энтити ИД геймрула и компонент геймрула можно посмотреть в NukeopsRuleSystem в методе OnComponentInit

2023-08-15 23:46 UTC, TheArturZh commented on Content.Shared.Database/LogType.cs
> +    WarReceiveTC,
Комментарий выше "// DO NOT CHANGE THE NUMERIC VALUES OF THESE"
мне кажется лучше указать значение WarReceiveTC явно (WarReceiveTC = 87), чтобы нельзя было случайно зафакапить логи прихуячив еще один енам выше.

2023-08-15 23:46 UTC, TheArturZh commented on Content.Server/SS220/WarFeatures/ConsoleNukeSystem.cs
> +using Content.Server.Shuttles.Events;
ебать тут юзингов, сомневаюсь что прям всё это нужно

2023-08-15 23:46 UTC, TheArturZh commented on Resources/Prototypes/Entities/Mobs/Player/human.yml
> +    - type: RandomHumanoidAppearance
Откуда это тут взялось

2023-08-15 23:46 UTC, TheArturZh commented on Content.Server/SS220/WarFeatures/LoneNukeOperativeComponent.cs
Компонент на сервере и клиенте специфическими полями никак не дополняется, можно было ограничится Shared'ом назвав его просто LoneNukeOperativeComponent

2023-08-15 23:46 UTC, TheArturZh commented on Content.Client/SS220/WarFeatures/ConsoleNukeComponent.cs
Компонент на сервере и клиенте специфическими полями никак не дополняется, можно было ограничится Shared'ом назвав его просто ConsoleNukeComponent

2023-08-15 23:46 UTC, TheArturZh commented on Content.Client/SS220/WarFeatures/LoneNukeOperativeComponent.cs
Компонент на сервере и клиенте специфическими полями никак не дополняется, можно было ограничится Shared'ом назвав его просто LoneNukeOperativeComponent

2023-08-15 23:46 UTC, TheArturZh commented on Content.Shared/SS220/WarFeatures/SharedConsoleNukeComponent.cs
Компонент на сервере и клиенте специфическими полями никак не дополняется, можно было ограничится Shared'ом назвав его просто ConsoleNukeComponent

2023-08-15 23:46 UTC, TheArturZh commented on Content.Shared/SS220/WarFeatures/SharedLoneNukeOperativeComponent.cs
Компонент на сервере и клиенте специфическими полями никак не дополняется, можно было ограничится Shared'ом назвав его просто LoneNukeOperativeComponent

2023-08-15 23:46 UTC, TheArturZh commented on Content.Server/SS220/WarFeatures/ConsoleNukeComponent.cs
Компонент на сервере и клиенте специфическими полями никак не дополняется, можно было ограничится Shared'ом назвав его просто ConsoleNukeComponent

2023-08-15 23:46 UTC, TheArturZh commented on Content.Server/SS220/WarFeatures/ConsoleNukeSystem.cs
> +                        stackSystem.SetCount(component.Owner, countTC);
Разработчики рекомендуют избегать использования .Owner так как это вроде как вредит производительности, из-за этого это поле было помечено как Deprecated
В данном случае есть возможность вместо `component.Owner` поставить туда `tc` объявленный выше

2023-08-15 23:47 UTC, TheArturZh commented
Если всё еще занят, то могу завтра этим заняться как проснусь

2023-08-16 00:02 UTC, aw-c commented
> Если всё еще занят, то могу завтра этим заняться как проснусь
ПР завершён и мне не нужна помощь его завершить, исключительно ревью!

2023-08-16 00:06 UTC, aw-c commented
Ебать ты здесь наревьювил дядя, я че-то только потом вверх пролистал, ну все замечания по делу, надо кому-то доделать

2023-08-16 00:09 UTC, aw-c commented on Resources/Prototypes/Entities/Mobs/Player/human.yml
> +    - type: RandomHumanoidAppearance
Это после ребейза

2023-08-16 16:35 UTC, aw-c commented
@TheArturZh не артур меня не хватит на выполнение каждой штуки по ревью

2023-08-16 16:36 UTC, TheArturZh commented
Спок я делаю

2023-08-17 03:52 UTC, AndreyKostenkoS commented
Офы опять тесты сломали?

2023-08-17 09:39 UTC, TheArturZh commented
Да, они падают рандомно

2023-08-17 12:20 UTC, TheArturZh commented
ченжлог добавлен яой механ

2023-08-17 12:20 UTC, merged