Lost Souls Revive
SerbiaStrong-220/space-station-14 pull request #2220
Opened 2024-11-10 00:10 UTC by Bomjojuk

## Описание PR
Возвращение первой итерации потерянных шаттлов с некоторыми дополнения + добавление одного нового (туристы)

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl:
- add: С пулл событий потерянных добавлен новый шаттл
- tweak: В пулл рандомных событий возвращены потерянные шаттлы

2024-11-10 06:43 UTC, UrPrice commented
Хочу увидеть от тестеров работу над этим PR, чтобы проверили всё ли работает корректно как и задумывалось, нет ли каких-либо ошибок при спавне / в названиях и т.д.

2024-11-11 05:11 UTC, UrPrice commented
Так как сам изъявил желание диктофоны добавлять. То ждём пока закончишь. Потом пингани ещё раз.
Прикладываю документ по потеряшкам.

[Потеряшки.pdf](https://github.com/user-attachments/files/17695431/default.pdf)

2024-11-11 12:45 UTC, Bomjojuk commented
> Так как сам изъявил желание диктофоны добавлять. То ждём пока закончишь. Потом пингани ещё раз. Прикладываю документ по потеряшкам.
> 
> [Потеряшки.pdf](https://github.com/user-attachments/files/17695431/default.pdf)

Окай

2024-11-12 18:57 UTC, Bomjojuk commented
Делать коммиты на заёбанную голову было ошибкой...

2024-12-20 10:08 UTC, Kirus59 requested changes

2024-12-20 10:08 UTC, Kirus59 commented on Resources/Maps/SS220/Shuttles/lostSoul/lost_cargo.yml
> +        - invalid
Это ломает чеки (вероятно сохранял маппу когда ui бумаги был открыт у тебя).

2024-12-20 10:08 UTC, Kirus59 commented on Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/roles.yml
> +
Перенести в SS220

2024-12-20 10:08 UTC, Kirus59 commented on Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/settings.yml
> +
Перенести в SS220

2024-12-20 10:08 UTC, Kirus59 commented on Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/spawners.yml
> +
Перенести в SS220

2024-12-20 10:08 UTC, Kirus59 commented on Resources/Prototypes/Roles/Jobs/Fun/visitors_startinggear.yml
> +
Перенести в SS220

2024-12-20 10:08 UTC, Kirus59 commented on Resources/Prototypes/GameRules/unknown_shuttles.yml
> +    preloadedGrid: Civil
Это чисто наш шаттл полагаю, так что перенести в SS220

2024-12-20 10:09 UTC, Kirus59 commented
@UrPrice запрос на тесты актуален?

2024-12-21 10:34 UTC, UrPrice commented
> @UrPrice запрос на тесты актуален?

Нет. Согласовали документ по потеряшком с ГА. Либо Жук сам вернётся доделает, либо я когда освобожусь, займусь этим и доведу до ума.

2024-12-24 17:06 UTC, Bomjojuk commented
@UrPrice ГООООЛ

2024-12-27 19:45 UTC, Kirus59 requested changes

2024-12-28 12:07 UTC, Bomjojuk commented on Resources/Prototypes/GameRules/unknown_shuttles.yml
> -#     preloadedGrid: Honki
> А куда

Ты же сказал перенести...

2024-12-28 13:03 UTC, Kirus59 commented on Resources/Prototypes/GameRules/unknown_shuttles.yml
> -#     preloadedGrid: Honki
> > А куда
> 
> Ты же сказал перенести...

Так эти прототипы оффовские же, я говорил перенести тот который наш был

2024-12-28 13:32 UTC, UrPrice commented
![{1C64B601-6547-42A1-8E5B-23F7AC346ACC}](https://github.com/user-attachments/assets/6a5fe1fa-5186-400b-a107-316941178c54)
Clueless

2024-12-28 14:05 UTC, UrPrice requested changes
Так долго маппил кассету, что забыл замаппить диктофон, судя по всему.

Выгрузи отсюда обновлённые версии шаттлов и запушь их в ветку. Предварительно проверь на инвалиды.

[lostsoul.zip](https://github.com/user-attachments/files/18266404/lostsoul.zip)

2024-12-28 15:07 UTC, Bomjojuk commented
> Так долго маппил кассету, что забыл замаппить диктофон, судя по всему.
> 
> Выгрузи отсюда обновлённые версии шаттлов и запушь их в ветку. Предварительно проверь на инвалиды.
> 
> [lostsoul.zip](https://github.com/user-attachments/files/18266404/lostsoul.zip)

диктофона у карго специально нет

2024-12-28 15:11 UTC, Bomjojuk commented on Resources/Prototypes/GameRules/unknown_shuttles.yml
> -#     preloadedGrid: Honki
> > > А куда
> > 
> > 
> > Ты же сказал перенести...
> 
> Так эти прототипы оффовские же, я говорил перенести тот который наш был

все кроме клоунов.. наши...
клоунов я аое задел случайно

2024-12-28 15:15 UTC, UrPrice commented
> > Так долго маппил кассету, что забыл замаппить диктофон, судя по всему.
> > Выгрузи отсюда обновлённые версии шаттлов и запушь их в ветку. Предварительно проверь на инвалиды.
> > [lostsoul.zip](https://github.com/user-attachments/files/18266404/lostsoul.zip)
> 
> диктофона у карго специально нет

Упущение, им ведь эта запись даёт изначальный флейвор - зачем она и планировалась. Без диктофона они не стенограму, ни запись исследовать не смогут. У глав конечно нет флейвора, но у остальных у всех есть. Зачем тогда такая сложность для диктофона?

2024-12-28 15:23 UTC, Bomjojuk commented
> > > Так долго маппил кассету, что забыл замаппить диктофон, судя по всему.
> > > Выгрузи отсюда обновлённые версии шаттлов и запушь их в ветку. Предварительно проверь на инвалиды.
> > > [lostsoul.zip](https://github.com/user-attachments/files/18266404/lostsoul.zip)
> > 
> > 
> > диктофона у карго специально нет
> 
> Упущение, им ведь эта запись даёт изначальный флейвор - зачем она и планировалась. Без диктофона они не стенограму, ни запись исследовать не смогут. У глав конечно нет флейвора, но у остальных у всех есть. Зачем тогда такая сложность для диктофона?

А... я чет забыл, что это не дисастер, добавлю

2024-12-28 16:07 UTC, Bomjojuk commented on Resources/Prototypes/GameRules/unknown_shuttles.yml
> -#     preloadedGrid: Honki
> > > > А куда
> > > 
> > > 
> > > Ты же сказал перенести...
> > 
> > 
> > Так эти прототипы оффовские же, я говорил перенести тот который наш был
> 
> все кроме клоунов.. наши... клоунов я аое задел случайно

А нет, клоунов я не трогал. Все шаттлы что я перенес - наши

2024-12-28 16:09 UTC, Bomjojuk commented on Resources/Prototypes/GameRules/unknown_shuttles.yml
> -#     preloadedGrid: Honki
а блять, всё, понял..

2024-12-28 16:14 UTC, Kirus59 commented on Resources/Prototypes/GameRules/unknown_shuttles.yml
> -#     preloadedGrid: Honki
> А нет, клоунов я не трогал. Все шаттлы что я перенес - наши

Те 3, которыя я выделил - оффовские (скрин с их билда ес чоу).
![Screenshot_20241228_191248_Chrome](https://github.com/user-attachments/assets/7eba6b42-8199-4338-ad99-cd917be39b62)

2024-12-28 16:15 UTC, Bomjojuk commented on Resources/Prototypes/GameRules/unknown_shuttles.yml
> -#     preloadedGrid: Honki
> > А нет, клоунов я не трогал. Все шаттлы что я перенес - наши
> 
> Те 3, которыя я выделил - оффовские (скрин с их билда ес чоу). ![Screenshot_20241228_191248_Chrome](https://private-user-images.githubusercontent.com/145689588/399095500-7eba6b42-8199-4338-ad99-cd917be39b62.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MDI3OTAsIm5iZiI6MTczNTQwMjQ5MCwicGF0aCI6Ii8xNDU2ODk1ODgvMzk5MDk1NTAwLTdlYmE2YjQyLTgxOTktNDMzOC1hZDk5LWNkOTE3YmUzOWI2Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQxNjE0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWE5MmFkZWIyMDZjOTYxMjNlMjBhNjYwZGIwYWUzNjU1ZmVlZjBhZGZiNDIyMzk0NDBhYmQ4NWY5ZGM1ZWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fGuqWulA0zErupD1gsQC0Dy_o6-WtbSBWTy0e98OlKo)

Карго тоже их, я уже понял че ты всё же имел в виду

2024-12-28 16:16 UTC, Bomjojuk commented on Resources/Prototypes/GameRules/unknown_shuttles.yml
> -#     preloadedGrid: Honki
А ну бля, у них это называется "карго лост", уэээ

2024-12-28 16:17 UTC, Bomjojuk commented on Resources/Prototypes/GameRules/unknown_shuttles.yml
> -#     preloadedGrid: Honki
а, ну и у нас тоже геймрул карголост. Короче карго тоже их

2024-12-28 16:27 UTC, Bomjojuk commented on Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/settings.yml
> +
Я хуй пойми блять что это за изменение. Там одна строчка между блоками, как и было

2024-12-28 16:35 UTC, Kirus59 commented on Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/settings.yml
> +
> Я хуй пойми блять что это за изменение. Там одна строчка между блоками, как и было

Там были пробелы))

2024-12-28 21:47 UTC, UrPrice approved these changes

2024-12-28 21:51 UTC, stalengd requested changes

2024-12-28 21:51 UTC, stalengd commented on Resources/Prototypes/GameRules/unknown_shuttles.yml
> +#SS220-LostSoulsRevive end
Здесь метки не нужны, это у оффов также

2024-12-28 22:03 UTC, stalengd commented on Resources/Prototypes/GameRules/unknown_shuttles.yml
> +#SS220-LostSoulsRevive end
Ну на закоменченные строки что там дальше идут метку нужно

2024-12-28 22:09 UTC, stalengd approved these changes

2024-12-28 22:21 UTC, merged

2024-12-29 09:17 UTC, nozychek commented
а вот сейчас точно гоол