Languages
SerbiaStrong-220/space-station-14 pull request #2226
Opened 2024-11-12 04:42 UTC by Jopaglazik

## Описание PR

Добавление системы языков игру. Особо я свои позорные наработки не выкладывал, но у этой было большое желание довести её до ума т.к есть большая мотивация вайбить на таярочке, спасибо алвуру за то что их добавил иначе бы этого пра не было. Поэтому сквозь страдания, слезы, пот и бессонные дни с маниакальным рвением старался осуществить свою цель S-тира.

**Основные изменения:**

- В игру добавлено множество языков для каждых рас и не только.
- Носители языка видят сообщения в оригинальном виде, не носители, соответственно, в "зашифрованном" варианте.
- В трейты персонажей добавлена колонка "Дополнительные языки" с выбором одного из четырёх общегалактических языков.
- Добавлен верб выбора текущего языка на персонаже. (Не самое удобное решение, но UI я не вывез)
- Добавлено окраска сообщений в цвета относительно языка.

**Минорные изменения**

- Персональный ИИ стал более "персональным". Он берёт в себя языки персонажа, который активировал его.
- Диктофону оставил, чтобы переводил язык, ибо проведя разведку в 13 цеху - у них он переводил. (Да и юзлесс шмотка была бы)
- Борги понимают все языки, но разговаривать могут только на "Общегалактическом" и "Бинарном".
- ИИ понимает все языки, но разговаривает только на общем, ибо пока не добавят голопады смысла трогать его нету.(Да и есть технические сложности с тем как этот ИИ вообще работает)
- Роли клоуна раунд стартом выдаётся "Клоунский" язык.
- Получившие разум животные от когнизина, получают во владение "Общегалактический" язык.
- Превратившийся персонажи в зомби теряют возможность переключать языки, чтобы их "груа груа" не шифровалось.
- Добавлены лорные описания языков, согласно вики SS220 13 и 14.
- Добавлены всратые, без шорткатов, админские команды для добавления/удаления языков в компонент энтити. (Мне было лень делать их лучше)
`addlanguage <uid> <protoId> ` `removelanguage <uid> <protoId>` `clearlanguages <uid> <protoId>`

**Технические детали**

- Добавлена поддержка добавления новых языков через прототипы
- Добавлена поддержка добавления языков рабочим ролям через спешл `AddLanguageSpecial`.
- Всем энтити не имеющие компонента `LanguageComponent` присваивается "Универсальный" язык.

**Тестирование**

- Локальный IC чат работает - нормально.
- Виспер чат работает -  нормально.
- Рация через гарнитуру работает - нормально.
- Портативные рации работают - нормально, но для её работы пришлось закомментировать кусок кода санитайзера, ибо тогда она хочет "покашлять". (С диктофоном такая-же история была)
- Интеркомы работают - нормально.
- В гостах видно все оригинальные сообщения.
- Админ логи не ломаются
Спасибо мелкому за ~~детство~~ тестирование

**TTS**
**Так-как апи ТТСа у меня нету, на этом мои полномочия всё. Как он будет работать, будет ли он работать, насколько сильно будет нагружаться, насколько сильно захлёбываться. Возможно придётся санитайзить слога языков, чтобы произносилось нормально, если это вообще будет работать... или вообще придётся рефакторить много чего, тут я не знаю.  Это решать уже ревьюверам что с этим думать.**

**Медиа**

![kallll](https://github.com/user-attachments/assets/eb9e38e7-5a6e-4413-9b19-bb541f98e841)
![kallll2](https://github.com/user-attachments/assets/2b604661-d6f6-46e9-9f16-938436251c21)
![photo_2024-11-11_11-03-16](https://github.com/user-attachments/assets/be90764e-9592-483c-80ab-b8523d237524)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Jopaglazik
- add: Добавлена система языков!
- add: Добавлена кнопка переключения языка.
- add: В чертах персонажа, добавлен выбор дополнительного языка.

2024-11-12 06:59 UTC, lexaSvarshik commented
ГООООООООООООООООООЛ

2024-11-12 07:04 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Language/language.yml
> +  syllables: [бла, бла, бла, бле, мех, ньех, нах, ах, угу, увы]
```suggestion
  syllables: [бла, бла, бла, бле, мех, ньех, нах, ах, угу]
```
Убери брейнрот пожалуйста (да, фраза `"увы"` - брейнрот всея 220)

2024-11-12 07:10 UTC, Jopaglazik commented on Resources/Prototypes/SS220/Language/language.yml
> +  syllables: [бла, бла, бла, бле, мех, ньех, нах, ах, угу, увы]
> Убери брейнрот пожалуйста (да, фраза `"увы"` - брейнрот всея 220)

это и есть отсылка на брейрот

2024-11-12 07:14 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Language/language.yml
> +  syllables: [бла, бла, бла, бле, мех, ньех, нах, ах, угу, увы]
О НЕТ

2024-11-12 07:29 UTC, Bomjojuk commented
От себя добавлю, что логично было бы добавить дворфам владение Гаттерром, так как все дворфы из республики (откуда они все и идут) обязаны знать Гаттер для общения с республиканцами

2024-11-12 07:35 UTC, Bomjojuk commented
Самое время чистить акценты рас от всякой хуйни...

2024-11-12 07:43 UTC, Surani1 reviewed
Прототипы посмотрел, вопрос только в реализации заменяемых слов. Они выполнены как я понял в виде листа и не особо хорошо читаются. У акцентов более гибкая структура прототипа, которую можно легко адаптировать. Обсудить с кирусом и сталеном.

2024-11-12 07:43 UTC, Surani1 commented on Resources/Locale/ru-RU/ss220/language/language-desc.ftl
> +# Sources: https://wiki.ss220.club/index.php/%D0%AF%D0%B7%D1%8B%D0%BA%D0%B8 and https://wiki14.ss220.club/index.php?title=%D0%9B%D0%BE%D1%80
Подправить ссылки

2024-11-12 07:43 UTC, Surani1 commented on Resources/Locale/ru-RU/ss220/verbs/verb-system.ftl
> +#SS220-Add-Languages begin
в SS220 не обязательно оставлять комментарии

2024-11-12 07:56 UTC, Alwayswannahunt commented on Content.Client/SS220/Language/LanguageSystem.cs
> +using Robust.Shared.Utility;
Почистить бы

2024-11-12 07:59 UTC, Alwayswannahunt commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> +        //var ntAllowed = sanitized.Replace("NanoTrasen", string.Empty, StringComparison.OrdinalIgnoreCase);
Причина тряски?

2024-11-12 08:03 UTC, Jopaglazik commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> +        //var ntAllowed = sanitized.Replace("NanoTrasen", string.Empty, StringComparison.OrdinalIgnoreCase);
> Причина тряски?

портативные рации и диктофон когда отправляют сообщения, очень изъявляют желание покашлять, с персонажами проблемы такой не было

2024-11-12 08:04 UTC, Alwayswannahunt commented on Content.Server/EntityEffects/Effects/MakeSentient.cs
> +            language.LearnedLanguages.Add("Galactic");
вынести бы в константу

2024-11-12 08:05 UTC, Alwayswannahunt commented on Content.Server/PAI/PAISystem.cs
> +            languages.LearnedLanguages.Add("Galactic");
В константы вынести

2024-11-12 08:06 UTC, Alwayswannahunt commented on Content.Server/PAI/PAISystem.cs
> +            languages.LearnedLanguages.Add("Universal");
Часто у тебя такая проблема, будто надо придумать откуда брать эти айди

2024-11-12 08:09 UTC, Ady4ik approved these changes
А ХУ ЕТЬ

2024-11-12 08:15 UTC, Alwayswannahunt commented on Content.Server/SS220/Language/LanguageSystem.cs
> +            ent.Comp.CurrentLanguage = ent.Comp.LearnedLanguages.FirstOrDefault("Universal");
в константу вынести и не забыть атрибут валидации айди

2024-11-12 08:21 UTC, Alwayswannahunt commented on Content.Server/SS220/Language/LanguageSystem.cs
> +        if (ScrambleCache.TryGetValue(cacheKey, out var cachedValue))
Хранить каждую фразу - плохая идея. Стоит посмотреть в сторону инъективного шифрования.

2024-11-12 08:24 UTC, Alwayswannahunt commented on Content.Shared/SS220/Language/LanguageComponent.cs
> +    [DataField("learnedLanguages", customTypeSerializer: typeof(PrototypeIdListSerializer<LanguagesPrototype>))]
ProtoId<> существует для такого

2024-11-12 08:30 UTC, Alwayswannahunt commented on Content.Shared/SS220/Language/SharedLanguageSystem.cs
> +        if (comp != null && comp.CurrentLanguage == "Universal")
у тебя же текущий язык содержится в листе LearnedLanguages

2024-11-12 08:48 UTC, Jopaglazik commented on Content.Server/SS220/Language/LanguageSystem.cs
> +        if (ScrambleCache.TryGetValue(cacheKey, out var cachedValue))
> Хранить каждую фразу - плохая идея. Стоит посмотреть в сторону инъективного шифрования.

но там размера кэша из 20 сообщений всего и если он переполнен, то первое сообщение в листе кэша заменяется на новое... так ли это критично? просто я работу шифровальщика основывал на шифровальщике с пары и там так-же через кэш с лимитом 20 сообщений это работает...

2024-11-12 08:50 UTC, Alwayswannahunt commented
@Jopaglazik Стоило бы дойти до разработчиков и описать что хочешь делать. Пока концептуально есть проблема: я не могу написать следующим образом: ":ы ГСБ, этот :щ тупица :9 вокс, уже достал всех, выпишите ордер на него :щ иначе я разберусь с ним сам"
:щ - ключ языка Синта'Унати, :9 - ключ общегалактического

2024-11-12 08:53 UTC, Alwayswannahunt commented on Content.Server/Chat/Managers/ChatSanitizationManager.cs
> +        //var ntAllowed = sanitized.Replace("NanoTrasen", string.Empty, StringComparison.OrdinalIgnoreCase);
> > Причина тряски?
> 
> портативные рации и диктофон когда отправляют сообщения, очень изъявляют желание покашлять, с персонажами проблемы такой не было

Ну у тебя же в заме английские буквы, конечно они будут кашлять...

2024-11-12 09:02 UTC, Kirus59 requested changes

2024-11-12 09:02 UTC, Kirus59 commented on Content.Server/Administration/Commands/LanguageCommands.cs
Перенести в SS220

2024-11-12 09:06 UTC, Jopaglazik commented on Content.Shared/SS220/Language/SharedLanguageSystem.cs
> +        if (comp != null && comp.CurrentLanguage == "Universal")
> у тебя же текущий язык содержится в листе LearnedLanguages

но ведь при инициализации энтити с компонентом LanguageComponent и пустым листом LearnedLanguage универсальный язык присваивается в CurrentLanguage. Либо если добавить компонент LanguageComponent энтити у которого ранее этого компонента не было, то так же универсальный язык присваивается в CurrentLanguage, разве эта проверка тогда не нужна?

2024-11-12 09:41 UTC, Jopaglazik commented on Content.Server/Zombies/ZombieSystem.Transform.cs
> +        RemComp<LanguageComponent>(target); // SS220-Add-Languages
> После того, как вылечится от вируса вернется ли этот компонент?

Если клонировать зомби то с прототипа куклы относительно расы - да , если ты про это. Это не относится к зараженному, но к еще не превратившимся в зомби персонажу

2024-11-12 09:43 UTC, Jopaglazik commented on Content.Shared/SS220/Language/SharedLanguageSystem.cs
> +            return true;
> Тоже самое, возможна ситуация когда в current будет язык, который не находится в Learned?

Возможна, если админы через ВВ присвоят в CurrentLanguage, либо инициализируется энтити с пустым списком Learned и ему присвоится универсальный язык в Current

2024-11-12 09:45 UTC, Jopaglazik commented on Content.Shared/SS220/Language/SharedLanguageSystem.cs
> +            return true;
> Получается будет возвращать true, когда у энтити нет `LanguageComponent` и смогло извлечь прототип `Universal`? А значит что энтитти без этого компонента будет знать все языки?

Да будет понимать и все его будут понимать, например всякие ожившие автоматы, гидропонные лотки, гост-роли и прочие третьестепенные роли. Но говорить на всех языках это право не даст

2024-11-12 09:45 UTC, Jopaglazik commented on Content.Shared/SS220/Language/SharedLanguageSystem.cs
> +            return true;
> Зачем проверка на `CurrentLanguage`? У тебя разве возможна ситуация, когда в `LearnedLanguages` языка не будет, но он будет в current?

Выше алвуру написал

2024-11-12 09:47 UTC, Jopaglazik commented on Content.Shared/SS220/Language/SharedLanguageSystem.cs
> +    }
> Возможно лучше менять цвет текста на клиенте, в момент получения сообщения в чат (Как сделано например с подсветкой кодовых слов в `ChatUiController.ProcessChatMessage`)
> 
> И соответственно выполнять это до смены цвета кодовых слов (чтобы они также выделялись в языках).

Я кодовые слова и хайлайты проверял - они подсвечиваются, если говорящий и слушатель обладают языком и оно не шифруется

2024-11-12 09:47 UTC, Kirus59 commented
@Jopaglazik подумай еще над реализацией замены частей сообщения (выделенного например с помощью тега, как предложил Алвур), а не всего сообщения.
Также неплохо бы было чтобы некоторые слова имели одинаковое шифрование/перевод (согласно лору рас)

2024-11-12 09:52 UTC, Kirus59 commented on Content.Shared/SS220/Language/SharedLanguageSystem.cs
> +        if (comp != null && comp.CurrentLanguage == "Universal")
> но ведь при инициализации энтити с компонентом LanguageComponent и пустым листом LearnedLanguage универсальный язык присваивается в CurrentLanguage. Либо если добавить компонент LanguageComponent энтити у которого ранее этого компонента не было, то так же универсальный язык присваивается в CurrentLanguage, разве эта проверка тогда не нужна?

Почему бы в Learned не добавлять его тогда?

2024-11-12 10:14 UTC, Jopaglazik commented on Content.Server/Chat/Systems/ChatSystem.cs
> +            languageProto = _languageSystem.GetProto(source);
> А чоу тут не сделать как в `SendEntitySpeak`? Тогда и в методы по идее не нужно будет перегрузку дополнительную добавлять

Я так сначала и сделал как в сендентитиспик, но был косяк учитывая то что портативные рации и интеркомы шепчат и их сообщения из-за этого не шифровались, собственно поэтому диктофон например и переводит всё, т.к его отправка сообщений идёт через метод SendEntitySpeak

2024-11-12 13:03 UTC, Ady4ik commented
@Jopaglazik подумай еще над реализацией тир-1 СБ технологии на возможность перевода языков других рас в нормальное состояние, если заключенный отказывается говорить на общегалактическом, к примеру.

2024-11-14 00:05 UTC, Jopaglazik commented on Content.Shared/SS220/Language/SharedLanguageSystem.cs
> +        if (comp != null && comp.CurrentLanguage == "Universal")
> > но ведь при инициализации энтити с компонентом LanguageComponent и пустым листом LearnedLanguage универсальный язык присваивается в CurrentLanguage. Либо если добавить компонент LanguageComponent энтити у которого ранее этого компонента не было, то так же универсальный язык присваивается в CurrentLanguage, разве эта проверка тогда не нужна?
> 
> Почему бы в Learned не добавлять его тогда?
Чтобы лишний раз его не удалять из списка Learned админ командами, а просто в ВВ поменять Current на любой другой?

2024-11-14 01:33 UTC, Jopaglazik commented
> @Jopaglazik подумай еще над реализацией тир-1 СБ технологии на возможность перевода языков других рас в нормальное состояние, если заключенный отказывается говорить на общегалактическом, к примеру.

Диктофон способный переводить в их распоряжении имеется, да и игра рольплейная, в крайнем случае пусть ищут переводчика что будет понимать заключенного, а наврёт ли переводчик или нет так-же решается рп процессом, вообщем пусть решают рп путём

2024-11-14 01:46 UTC, Jopaglazik commented
> @Jopaglazik подумай еще над реализацией замены частей сообщения (выделенного например с помощью тега, как предложил Алвур), а не всего сообщения. Также неплохо бы было чтобы некоторые слова имели одинаковое шифрование/перевод (согласно лору рас)

Насчёт шифрования части сообщения соглы надо подумать, но такое осилить разве что в будущем получится, лично я щас пока не вытяну, а касаемо лорных слов в зашифрованном сообщении - какой смысл? Носители языка будут видеть оригинальное сообщение, а не зашифрованное. Не носители будут видеть неразборчивый бред, зачем тогда не носителю в этом бреду искать контекст из "лорных" слов? Тем более это скорее часть акцентов, а не языка, как у дворфов например

2024-11-28 07:48 UTC, Ady4ik commented
@Jopaglazik приветствую, как успехи?

2024-11-28 19:50 UTC, Jopaglazik commented
> @Jopaglazik приветствую, как успехи?

v draft poka zakinu

2025-03-06 05:31 UTC, Kirus59 commented
Неактуально
https://github.com/SerbiaStrong-220/space-station-14/pull/2628

2025-03-06 05:31 UTC, closed without merging