Добавление выдачи рандомного антага для админов
SerbiaStrong-220/space-station-14 pull request #2231
Opened 2024-11-14 11:04 UTC by Ady4ik

## Описание PR
Добавлена консольная команда позволяющая сделать антагом случайного игрока. Пулл антагов сделан базовый, при необходимости можно дополнять. Сделано в соответствии с [задачей](https://github.com/orgs/SerbiaStrong-220/projects/1?pane=issue&itemId=67748607)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Ady4, ReeZiiiiiiiii
- add: Добавлено веселье для администраторов.
ADMIN:
- add: Добавлена консольная команда makerandomantag делающая случайного игрока антагонистом из списка.

2024-11-15 10:01 UTC, Kirus59 requested changes
Также вопрос, учитывает ли эта команда то, выставлена ли у чела галочка на антага и открыт ли он ему по часам?
Проверки прост на это не вижу...

2024-11-15 10:01 UTC, Kirus59 commented on Content.Server/SS220/Commands/AdminRandomMakeAntagSystem.cs
> +        };
думаю стоит через `enum` реализовать

2024-11-16 14:19 UTC, stalengd commented on Content.Server/SS220/Commands/AdminRandomMakeAntagSystem.cs
> +            var robust = IoCManager.Resolve<IRobustRandom>();
нейминг вышел из чата
```suggestion
            var random = IoCManager.Resolve<IRobustRandom>();
```

2024-11-16 14:32 UTC, stalengd commented on Content.Server/SS220/Commands/AdminRandomMakeAntagSystem.cs
> +                shell.WriteLine("Необходимо указать тип антагониста: Traitor, Thief, или InitialInfected.");
+ передавать список туда, а не хардкодить в строку, в помощь метод `ContentLocalizationManager.FormatListToOr`, он правда не локализован...

2024-11-16 14:37 UTC, stalengd commented on Content.Server/SS220/Commands/AdminRandomMakeAntagSystem.cs
> +        };
Тут не согласен, разве что проверку на валидность Id прототипа добавить можно, я правда до конца так и не понял что это за прототипы, работа этого проверялось вообще?

2024-11-16 14:52 UTC, Kirus59 commented on Content.Server/SS220/Commands/AdminRandomMakeAntagSystem.cs
> +        };
> Тут не согласен, разве что проверку на валидность Id прототипа добавить можно, я правда до конца так и не понял что это за прототипы, работа этого проверялось вообще?

А, я чет упустил что этот список в `GetCompletion` используется.
Но это не id прототипов, это список выводимый в подсказку при написании команды.

2024-11-16 17:58 UTC, Kirus59 approved these changes

2024-11-16 18:19 UTC, merged