Fix SM garbage and nearby garbage
SerbiaStrong-220/space-station-14 pull request #2234
Opened 2024-11-14 23:26 UTC by Ady4ik

## Описание PR
Fix #2212
Запрещает спавн мусора возле СМ/Внутри СМ. 
Наверное должно работать так (хз)
Требуются тесты, потому что кейса, когда он попытался бы заспавнить на кристале СМ я не впоймал (анриал ручками через дебаг)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Ady4
- fix: Исправлена поломка двигателя супер-материи из-за мусора!

2024-11-15 09:03 UTC, Kirus59 requested changes

2024-11-15 09:03 UTC, Kirus59 commented on Content.Server/GameTicking/Rules/VariationPass/EntitySpawnVariationPassSystem.cs
> +                    return;
Почему тут return?

2024-11-16 18:16 UTC, Kirus59 approved these changes

2024-11-16 22:12 UTC, Kirus59 commented on Content.Server/GameTicking/Rules/VariationPass/EntitySpawnVariationPassSystem.cs
> +using Content.Server.GameTicking.Rules.VariationPass.Components;
уэээ

2024-11-17 19:37 UTC, Ady4ik commented
@Kirus59 rfm

2024-11-17 22:39 UTC, merged