fix workflows
SerbiaStrong-220/space-station-14 pull request #2258
Opened 2024-11-17 10:45 UTC by Werzet

Описание PR

2024-11-17 10:55 UTC, UrPrice approved these changes

2024-11-17 11:15 UTC, Werzet reviewed
op

2024-11-21 12:20 UTC, Ady4ik commented
@Werzet rfm?

2024-11-22 04:18 UTC, Werzet commented
> @Werzet rfm?

Нене, ещё не починил.

2024-12-10 00:36 UTC, UrPrice commented
Я забыл, что мы тут хотели

2024-12-10 01:14 UTC, UrPrice requested changes
1

2024-12-10 02:00 UTC, UrPrice requested changes
12

2024-12-10 02:17 UTC, UrPrice requested changes
123

2025-02-22 19:01 UTC, UrPrice approved these changes

2025-02-22 19:03 UTC, UrPrice approved these changes

2025-02-22 19:11 UTC, closed without merging