Broadsword by WMT
SerbiaStrong-220/space-station-14 pull request #2261
Opened 2024-11-18 16:43 UTC by chell4592

## Описание PR

Палаш для ивента чая. [Таск](https://discord.com/channels/1158128815311171638/1307282619372666900).
Поправил суффиксы в ранее сделанных для этого же ивента шмотках.

**Медиа**

![image](https://github.com/user-attachments/assets/d139ca82-8564-467d-8d2e-c1b31c3db9f9)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up. Changelog must have a :cl: symbol, so the bot recognizes the changes and adds them to the game's changelog.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-11-18 21:03 UTC, stalengd requested changes

2024-11-18 21:03 UTC, stalengd commented on Resources/Prototypes/SS220/Entities/Objects/Weapons/Melee/sword.yml
> +  suffix: HOCebent
добавь `Ebent`

2024-11-19 22:28 UTC, stalengd approved these changes

2024-11-19 22:30 UTC, stalengd commented
Ждём мемрана энивей

2024-11-20 18:58 UTC, EstKemran approved these changes

2024-11-20 20:07 UTC, merged