skladowshik-new-skirt
SerbiaStrong-220/space-station-14 pull request #2274
Opened 2024-11-25 10:16 UTC by lexaSvarshik

## Описание PR

По [задаче](https://discord.com/channels/1158128815311171638/1310250256558063726)
**Медиа**

![изображение](https://github.com/user-attachments/assets/a8c2099f-6929-4aa5-8fda-ae10bb15d2e8)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Dinazewwr, okroshka59
- add: Добавлена юбка-комбенизон в набор "Заведующего складом" из лоадаута Квартирмейстера.

2024-11-25 16:18 UTC, stalengd requested changes
См коммент кемрана

2024-11-25 18:11 UTC, EstKemran approved these changes

2024-11-28 20:46 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/clothing/Jumpsuit/jumpsuit.ftl
ой ёмае, забыл

2024-11-28 22:54 UTC, stalengd approved these changes

2024-11-28 22:55 UTC, merged