Zombies can see Initial Infected
SerbiaStrong-220/space-station-14 pull request #2283
Opened 2024-11-29 20:16 UTC by psykana

## Описание PR

Теперь зомби видят нулевых пациентов.

Я не раз видел ситуации когда один нулевой пациент готовит диверсию, а второй через 5 минут смены уже начинает кусать всех, заставляя первого "воевать на два фронта". Мне это сильно не нравится и я видел в дискорде поддержку этой идеи.

Это спорное изменение с точки зрения лора, но можно объяснить обе позиции:
С одной стороны, зомби полностью отбитые и просто преследуют живых.
С другой стороны, нулевые пациенты - биотеррористы Синдиката, в которых с начала смены в какой-то форме находится\живёт зомби вирус, который превратившиеся могут учуять.

**Медиа**

![{07EDA331-58D1-404D-A837-15F757F743E2}](https://github.com/user-attachments/assets/ac33f8e4-a4ce-49f7-9b9a-0dcfa88a5b3f)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- tweak: Теперь зомби видят нулевых пациентов
<!--
Make sure to take this Changelog template out of the comment block in order for it to show up. Changelog must have a :cl: symbol, so the bot recognizes the changes and adds them to the game's changelog.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-11-29 22:35 UTC, UrPrice commented
Не вижу геймплейных проблем в этом. Честно говоря, в текущей ситуации больше геймплейной проблемы, так как нулевой может ошибочно считать, что инфицированный видит его как нулевого

2024-11-29 22:35 UTC, UrPrice approved these changes

2024-11-30 07:24 UTC, Kirus59 requested changes
Это нужно убрать, ибо даже закомменченное подсасывает в чейндждог.
![Screenshot_20241130_102228_Chrome](https://github.com/user-attachments/assets/cbe9a55a-d57a-4a0a-affa-0e3b5fa6f371)

2024-11-30 11:42 UTC, lexaSvarshik commented
Оффам закинуть не думали?

2024-11-30 11:59 UTC, lexaSvarshik commented on Resources/Prototypes/StatusIcon/faction.yml
> +    - Zombie
```suggestion
    - Zombie #SS220 Zombies can see Initial Infected 
```
Пометки?

2024-11-30 13:19 UTC, psykana commented
Закинул в апстрим, если долго будут тянуть то поправлю тут.

2024-12-01 06:42 UTC, Ady4ik approved these changes
Изменение сварщика сделай и RFM

2024-12-02 09:02 UTC, lexaSvarshik commented
Если что оффы аппрувнули это https://github.com/space-wizards/space-station-14/pull/33665 
![изображение](https://github.com/user-attachments/assets/fdc58297-d7a8-488f-aac3-c1c7aa2e1851)

2024-12-16 13:59 UTC, psykana commented
merged into upstream https://github.com/space-wizards/space-station-14/pull/33665

2024-12-16 13:59 UTC, closed without merging