Remove cat tails and ears from human customization
SerbiaStrong-220/space-station-14 pull request #2288
Opened 2024-12-01 16:22 UTC by lexaSvarshik

## Описание PR

Вырезаны кошкоушки и хвосты из меню кастомизации персонажей. Чтобы не закомменчивать весь файл целиком, энтити сделаны абстрактными, работает исправно.

Пункт кастомизации для ушей у людей оставлен, ввиду добавленными оффами ушами, см. https://github.com/space-wizards/space-station-14/pull/30490
## Что/Почему
Изначально это вообще пришло с Корвакса, как спонсорская(донатная) привелегия. (См. https://github.com/space-syndicate/space-station-14/pull/437 , https://github.com/space-syndicate/space-station-14/pull/552, https://github.com/space-syndicate/space-station-14/pull/652 ) На 220 оно перекочевало с апстримом, но у нас оно стало доступно сразу всем.

У слаймолюдов вырезается по той причине, что это слаймоЛЮДЫ, а не слаймокошки или слаймотаяры. Свой облик они копируют именно с людей, а не таяр/фелек/ниан/прочих прочих.

**Зачем вырезаем?** Несколько причин.
- С удалением феленидов появился феномен "протофеленидов", а именно хуманов с ушами и хвостом, соот-ими именами, от прежних фелек отличающихся лишь отсутвием акцента.
- Лорная составляющая. Чем лорно может быть обосновано наличие кошкоушек у рядового и **тем более офицерского** состава станции - абсолютно неясно. С введением генетики/иного, хвосты могут быть в виде ингейм получаемых мутаций от таяр, но в нынешнем виде мы просто имеем исключительно жертв неудачных генных экспериментов.
- МРП-составляющая проекта. На сервере с плашкой ЛРП такое может быть приемлемо, но не у нас. Это подытоживающий пункт, обобщающий все предыдущие. О каком среднем уровне отыгрыша может идти речь, если начальник охраны (или ещё хуже, капитан) станции - кошкомальчик/девочка с соответствующими повадками?

## **Медиа**

### **ДО:**
Жертва эксперимента.
![изображение](https://github.com/user-attachments/assets/0f352db6-8c9b-4a92-aebb-b91a827bd613)
![изображение](https://github.com/user-attachments/assets/6cb80dfe-015b-4839-a73f-4086afed58a9)

![изображение](https://github.com/user-attachments/assets/e02c9701-48fc-4211-9db1-6cc00e6757ea)

### **ПОСЛЕ:**
Базовый хуман.
![изображение](https://github.com/user-attachments/assets/24afb3f4-14d6-4712-971b-21552f3ffa3c)
![изображение](https://github.com/user-attachments/assets/c86d03bc-7108-47f8-974a-1678401e0552)

![изображение](https://github.com/user-attachments/assets/3494f052-2c33-4b87-805b-28f33f0e6dad)
![изображение](https://github.com/user-attachments/assets/cbbef79c-5e7c-4bad-bc1e-f27dcf0a1f55)

Люди
![изображение](https://github.com/user-attachments/assets/9412bdd9-2203-48a8-ab4f-72fbcb0e8dab)
Слаймолюды
![изображение](https://github.com/user-attachments/assets/5d86e1fa-aba5-436a-b54b-b32585f0051b)

пы.сы.
Админские кнопки работают нормально.
![изображение](https://github.com/user-attachments/assets/eceadcc2-6d6f-4a70-9f59-b79ffffe57ac)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Svarshik
- remove: Удалены кошачьи ушки и хвосты из меню кастомизации персонажа.

2024-12-01 16:25 UTC, anders0n9 commented
Где лайк поставить

2024-12-01 16:34 UTC, lexaSvarshik commented
> Где лайк поставить

![изображение](https://github.com/user-attachments/assets/0b45c941-b5d9-4cf1-a7dc-0afc2ef9c017)

2024-12-01 16:37 UTC, Tris0r commented
Don't merge

2024-12-01 16:38 UTC, lexaSvarshik commented
> Don't merge

МЁЁЁЁЁЁЁЁРЖ

2024-12-01 17:14 UTC, UrPrice commented
Обсудим на ближайшем мите, согласен с 70%, кроме слаймолюдов, всё же считаю это придиркой к их неймингу и недостаточным погружением ТСа банально в их лор.

> Slimes - оригинальное название офов

> Слаймолюды — это раса, вокруг которой ведутся споры. Кто-то хочет считать её подвидом людей, а кто-то явно выделяет в отдельный вид слизнеподобных существ \ - выдержка из wiki ss14 ss220

> Слаймолюд (множ. Слаймолюди) \ Слаймомены — раса гуманоидных желеобразных полупрозрачных существ. Слаймолюди происходят из системы 41 Жертвенника, с планеты Ксарксис, представляющей собой океанический мир. \ - выдержка из wiki ss13 ss220 парадиз

Собственно, не вижу причин, по которым слаймолюд может полиморфироваться в полноценный мешок слайма и обратно, но не может себе полиморфировать уши и хвост

2024-12-01 20:08 UTC, lexaSvarshik commented
> Собственно, не вижу причин, по которым слаймолюд может полиморфироваться в полноценный мешок слайма и обратно, но не может себе полиморфировать уши и хвост

В целом, наличие оных у слаймолюдов может быть логически обосновано, но ввиду механик игры, слаймолюды не имеют каких-либо иных полиморфирующихся черт, по типу изменения формы головы, мимикрия под воксов с их клювами и оперением.
Но это уже другой топик, где мы можем сделать из слаймолюдов буквально слизь-франкенштейна.

2024-12-01 20:10 UTC, UrPrice commented
> > Собственно, не вижу причин, по которым слаймолюд может полиморфироваться в полноценный мешок слайма и обратно, но не может себе полиморфировать уши и хвост
> 
> В целом, наличие оных у слаймолюдов может быть логически обосновано, но ввиду механик игры, слаймолюды не имеют каких-либо иных полиморфирующихся черт, по типу изменения формы головы, мимикрия под воксов с их клювами и оперением, и прочее прочее. Но это уже другой топик, где мы можем сделать из слаймолюдов буквально слизь-франкенштейна.

Согласен. Тут я скорее к тому, что их нет особо смысла ограничивать, а наоборот лучше развивать, ибо конкретно ребята, которые не просто брали слаймов ради "ядрышек" и прочего дерьма, пытались отыгрывать как раз-таки полиморфию в разных видах проявления эмоций.

2024-12-06 18:55 UTC, UrPrice commented
Вырезаем у человеков черты ушей и хвостов кошкофембоев.
Слаймолюдов не трогаем.

2024-12-06 18:56 UTC, stalengd requested changes
Не вырезать у слаймов

2024-12-06 18:56 UTC, UrPrice approved these changes
С условием редакции PR'а на откат слаймов к прежнему виду

2024-12-08 18:27 UTC, Tris0r commented
Нет чтоб что-то новое добавлять, но нет,  будем только вырезать.  Ну ладно, раз в полгода что то да будем добавлять.
Правильный путь.

2024-12-09 15:08 UTC, lexaSvarshik commented
> Нет чтоб что-то новое добавлять, но нет, будем только вырезать. Ну ладно, раз в полгода что то да будем добавлять. Правильный путь.

У меня соседний ПР приколы добавляет.

2024-12-09 15:15 UTC, lexaSvarshik commented
Откатил слаймов, хуманы остались.

2024-12-09 18:16 UTC, UrPrice commented
@stalengd

2024-12-09 19:12 UTC, stalengd approved these changes

2024-12-09 19:12 UTC, merged