ADD: Handheld radio now attached to Outer Clothing
SerbiaStrong-220/space-station-14 pull request #2305
Opened 2024-12-06 15:59 UTC by ReeZer2

## Описание PR
Для всей верхней одежды была добавлена возможность крпить рацию.

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: ReeZii
- add: Добавлена возможность крепить рацию в слот верхней одежды.

2024-12-06 18:56 UTC, UrPrice approved these changes

2024-12-17 06:37 UTC, Kirus59 requested changes

2025-02-17 11:35 UTC, ReeZer2 commented
@Kirus59 вроде заебись, можно мЁЁЁЁЁЁрджить

2025-02-17 12:03 UTC, Kirus59 approved these changes

2025-02-17 12:04 UTC, merged