Добавление кнопок консолей и доступов для ИИ
SerbiaStrong-220/space-station-14 pull request #2336
Opened 2024-12-10 17:52 UTC by Burenov

## Описание PR

**Медиа**

![image](https://github.com/user-attachments/assets/105624eb-a4f4-48e3-91be-bfff5fc90871)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Burenov, Ezik2008
- add: Добавлены кнопки консолей в хотбар ИИ!
- add: Добавлены новые иконки для хотбара ИИ!
- tweak: Изменение иконок хотбара и действий ИИ под один стиль
- add: Добавлены новые доступы для ИИ

2024-12-10 18:35 UTC, UrPrice commented on Resources/Prototypes/Entities/Mobs/Player/silicon.yml
> +  #SS220 Station Ai Actions start
Лишняя метка

2024-12-10 18:35 UTC, UrPrice commented on Resources/Prototypes/Entities/Mobs/Player/silicon.yml
> +    #SS220 Station Ai Actions start
блок метки открылся и не закрылся

2024-12-11 08:56 UTC, lexaSvarshik requested changes
Откати в файлах пустые изменения в самом конце, это автоформатирование IDE сделало.

2024-12-12 16:31 UTC, stalengd requested changes

2024-12-12 16:31 UTC, stalengd commented on Resources/Prototypes/Entities/Mobs/Player/silicon.yml
> +  - type: StationMap #SS220 Station Ai Actions end
```suggestion
  - type: StationMap #SS220 Station Ai Actions
```

2024-12-12 16:31 UTC, stalengd commented on Resources/Prototypes/Entities/Mobs/Player/silicon.yml
> +    - PlayerBorgSyndicateSaboteurGhostRole
```suggestion
    - PlayerBorgSyndicateSaboteurGhostRole

```

2024-12-12 16:31 UTC, stalengd commented on Resources/Prototypes/Entities/Structures/Dispensers/chem.yml
> +    pack: EmptyInventory
```suggestion
    pack: EmptyInventory

```

2024-12-12 16:31 UTC, stalengd commented on Resources/Prototypes/Entities/Structures/Machines/chem_master.yml
> +    - Chemist
```suggestion
    - Chemist

```

2024-12-12 16:31 UTC, stalengd commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +        - Ingot
```suggestion
        - Ingot

```

2024-12-12 16:31 UTC, stalengd commented on Resources/Prototypes/Entities/Structures/Piping/Atmospherics/binary.yml
> +    node: radiator
```suggestion
    node: radiator

```

2024-12-12 16:31 UTC, stalengd commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/bar_sign.yml
> +    current: Spacebucks
```suggestion
    current: Spacebucks

```

2024-12-12 16:31 UTC, stalengd commented on Resources/Prototypes/SS220/Entities/Structures/Machines/photocopier.yml
> +    price: 2500
```suggestion
    price: 2500

```

2024-12-12 16:31 UTC, stalengd commented on Resources/Prototypes/SS220/Entities/Structures/Power/Generation/Supermatter/observer.yml
> +     Glass: 500
```suggestion
     Glass: 500

```

2024-12-12 16:32 UTC, stalengd commented
@UrPrice одобрено?

2024-12-12 16:48 UTC, Burenov commented
Не мёржите, мне спрайты не одобрили ещё

2024-12-13 01:29 UTC, UrPrice commented
> @UrPrice одобрено?

Да, это по задаче с дискорда

2024-12-13 17:00 UTC, Tris0r commented
@EstKemran ревьюить будешь??

2024-12-20 21:39 UTC, Burenov commented
@EstKemran ну, иконки новые, делал ёжик, ты вроде ревьюил, выноси вердикт

2024-12-20 21:54 UTC, stalengd requested changes

2024-12-20 21:54 UTC, stalengd commented on Resources/Prototypes/Actions/station_ai.yml
> +    ##SS220-resprite end
Вот так везде сделать
```suggestion
      # SS220-resprite start
      #sprite: Interface/Actions/actions_ai.rsi
      sprite: SS220/Interface/Actions/actions_ai.rsi
      # SS220-resprite end
      state: ai_core
```

2024-12-20 21:54 UTC, stalengd commented on Resources/Prototypes/Entities/Mobs/Player/silicon.yml
> +  - type: StationMap #SS220 Station Ai Actions end
Всё ещё актуально как бы

2024-12-20 21:54 UTC, stalengd commented on Resources/Prototypes/SS220/Entities/Structures/Machines/photocopier.yml
> +  - type: StationAiWhitelist #SS220 AI Access
Метка здесь не нужна

2024-12-20 21:54 UTC, stalengd commented on Resources/Prototypes/SS220/Entities/Structures/Machines/photocopier.yml
> +  - type: StationAiWhitelist #SS220 AI Access
Метка здесь не нужна

2024-12-20 21:55 UTC, EstKemran commented
> @EstKemran ну, иконки новые, делал ёжик, ты вроде ревьюил, выноси вердикт

> @EstKemran ну, иконки новые, делал ёжик, ты вроде ревьюил, выноси вердикт

Молодец :goodcat: . Одобрение на спрайты дам

2024-12-20 21:55 UTC, EstKemran approved these changes

2024-12-21 09:39 UTC, Burenov commented on Resources/Prototypes/SS220/Entities/Structures/Power/Generation/Supermatter/observer.yml
> +     Glass: 500
Но тут же ноль изменений, что вы хотите

2024-12-21 09:40 UTC, Burenov commented on Resources/Prototypes/Entities/Structures/Wallmounts/Signs/bar_sign.yml
> +    current: Spacebucks
Тут же тоже ничаго не меняется

2024-12-21 09:40 UTC, Burenov commented on Resources/Prototypes/Entities/Structures/Piping/Atmospherics/binary.yml
> +    node: radiator
И тута

2024-12-21 09:40 UTC, Burenov commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +        - Ingot
А тут

2024-12-21 09:41 UTC, Burenov commented on Resources/Prototypes/Entities/Structures/Machines/chem_master.yml
> +    - Chemist
А тута

2024-12-21 09:41 UTC, Burenov commented on Resources/Prototypes/Entities/Structures/Dispensers/chem.yml
> +    pack: EmptyInventory
?

2024-12-21 14:12 UTC, stalengd commented on Resources/Prototypes/Entities/Structures/Dispensers/chem.yml
> +    pack: EmptyInventory
Ты удалил новую строку в конце файла, верни. В остальных местах то же

2024-12-21 20:29 UTC, stalengd approved these changes

2024-12-21 20:51 UTC, merged