New assistants uniform
SerbiaStrong-220/space-station-14 pull request #2341
Opened 2024-12-11 13:03 UTC by lexaSvarshik

## Описание PR

Добавлены новые комбенизоны и юбки-комбенизоны для ассистентов (интерн, техассик, науч. ассик). По [задаче](https://discord.com/channels/1158128815311171638/1306952224416469012).

Сделаны в самом верху лоадаута, добавлены в шкафы с вещами соответсвующего отдела
**Медиа**

![image](https://github.com/user-attachments/assets/c229f634-1aeb-4e04-a166-3e554c3bb5f8)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Vimenant2
- add: Добавлены новые комбенизоны и юбки-комбенизоны для ассистентов!

2024-12-11 13:04 UTC, lexaSvarshik commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/medidrobe.yml
> -    ClothingHeadHatSurgcapGreen: 4
тварь

2024-12-11 16:28 UTC, stalengd approved these changes

2024-12-12 17:25 UTC, EstKemran commented
![explorer_3TtMIs7Sha](https://github.com/user-attachments/assets/83f3dfb5-fb3b-49b1-a87f-9a5ab374b359)
У нас ведь есть общий файл и для jumpsuit, и для jumpskirt, в котором собраны прототипы одежда. Зачем создавать новые, не нужные, засоряя репу. Её до этого не просто так чистили от этого.

![изображение](https://github.com/user-attachments/assets/2ec0c116-7bd7-42d1-9c30-1be98848dd96)
У джапскёртов есть свой парент

2024-12-12 17:43 UTC, stalengd requested changes
Внести требования Кемрана

2024-12-12 19:20 UTC, lexaSvarshik commented
Я как знал

2024-12-17 22:31 UTC, stalengd approved these changes

2024-12-17 22:31 UTC, merged