RenameStart
SerbiaStrong-220/space-station-14 pull request #2343
Opened 2024-12-11 16:39 UTC by 21Melkuu

## Описание PR

Позволяет сменить имя в начале раунда

**Технические детали**
Добавил новый тип QuickDialogWindow со всеми его вытекающими. 

**Медиа**

![image](https://github.com/user-attachments/assets/b8d02804-9eea-4d05-85a4-19b1b26df48b)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: 21Gnomkuu"
- add: Добавлено возможность переименования в начале раунда 

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up. Changelog must have a :cl: symbol, so the bot recognizes the changes and adds them to the game's changelog.

2024-12-11 16:57 UTC, 21Melkuu commented
@UrPrice ну значит так
![image](https://github.com/user-attachments/assets/9158f123-685c-469e-ab2d-e073f845add6)

2024-12-11 17:12 UTC, UrPrice commented
Мне нравится, только пусть @stalengd @Kirus59 посмотрят

2024-12-11 18:59 UTC, stalengd requested changes

2024-12-11 18:59 UTC, stalengd commented on Content.Server/SS220/RenameStart/RenameStartComponent.cs
> +    public int MaxChar = 36;
Стоит использовать `HumanoidCharacterProfile.MaxNameLength`

2024-12-11 18:59 UTC, stalengd commented on Content.Client/SS220/DialogWindowDescUI/DialogWindowDesc.xaml.cs
Как я понял, ты тут нагородил полную копию существующего окна и всего к нему только ради дого чтобы часть заголовка была серой. Вместо этого, я предлагаю использовать существующее диалоговое окно, но поменять текстовый элемент для `entry.Prompt` с `Label` на `RichTextLabel`, и добиться нужного вида части текста с помощью его тегов.

2024-12-11 19:23 UTC, UrPrice approved these changes
При условии, что технически всё хорошо

2024-12-11 19:24 UTC, 21Melkuu commented on Content.Client/SS220/DialogWindowDescUI/DialogWindowDesc.xaml.cs
> Как я понял, ты тут нагородил полную копию существующего окна и всего к нему только ради дого чтобы часть заголовка была серой. Вместо этого, я предлагаю использовать существующее диалоговое окно, но поменять текстовый элемент для `entry.Prompt` с `Label` на `RichTextLabel`, и добиться нужного вида части текста с помощью его тегов.

в целом все это нужно было чтобы дать возможность добавить описание + привести окно в "красивое состояние". Я может что-то упустил из вида, но найти нормальный quickDialog с моими требованиями я так и не нашел. 

Была идея просто изменить само диалоговое окно для всех, но наверное, оно будет странным.

Сам пример стремного `quickDialog`: 
![image](https://github.com/user-attachments/assets/3157b042-4fe8-4b30-93b2-412e5c1a02f1)

Ну конечно всегда можно стерпеть использовать обычный диалог, забить хуй на описание, чуть поправить окно и готово. Но без описания звучит конечно странно.

2024-12-11 20:12 UTC, lexaSvarshik commented
надо будет ещё затестить чтобы у юзверей не было возможности вбить что-то символьное/на английском

2024-12-13 09:49 UTC, 21Melkuu commented on Content.Client/SS220/DialogWindowDescUI/DialogWindowDesc.xaml.cs
@stalengd так что переделываю изначальное окно?

2024-12-13 19:26 UTC, stalengd commented on Content.Client/SS220/DialogWindowDescUI/DialogWindowDesc.xaml.cs
Ладно, оставляй так, но я тебе тогда сейчас ещё докину измнений

2024-12-13 19:30 UTC, stalengd requested changes

2024-12-13 19:30 UTC, stalengd commented on Content.Client/SS220/DialogWindowDescUI/DialogWindowDesc.xaml.cs
> +public sealed partial class DialogWindowDesc : DefaultWindow
Добавь summary на то, что это как оффовское окно (указать тип), но с описанием или чем там

2024-12-13 19:30 UTC, stalengd commented on Content.Client/SS220/DialogWindowDescUI/DialogWindowDesc.xaml.cs
> +public sealed partial class DialogWindowDesc : DefaultWindow
```suggestion
[GenerateTypedNameReferences]
public sealed partial class DialogWindowDesc : FancyWindow
```

2024-12-13 19:30 UTC, stalengd commented on Content.Client/SS220/DialogWindowDescUI/DialogWindowDesc.xaml.cs
> +        MinWidth *= 2; // Just double it.
Не-не-не

2024-12-13 19:30 UTC, stalengd commented on Resources/Prototypes/Roles/Jobs/Science/borg.yml
> +    - type: RenameStart #SS220-RenameStart
На весь блок метки

2024-12-13 19:30 UTC, stalengd commented on Resources/Prototypes/Roles/Jobs/Science/borg.yml
> +    - type: RenameStart #SS220-RenameStart
На весь блок метки

2024-12-13 19:31 UTC, stalengd commented
И ещё, ты проверил что оно переименовывает везде, в том числе в окне конца раунда?

2024-12-14 19:23 UTC, 21Melkuu commented
> И ещё, ты проверил что оно переименовывает везде, в том числе в окне конца раунда?

Теперь да.
![1](https://github.com/user-attachments/assets/42e5858b-31af-4092-a14b-94905e8fceb1)
![2](https://github.com/user-attachments/assets/d487f75f-95f4-4297-90db-96a6ebed5a08)

2024-12-14 21:13 UTC, stalengd commented on Content.Client/SS220/DialogWindowDescUI/DialogWindowDesc.xaml.cs
> +        MinWidth *= 2; // Just double it.
@21Melkuu я именно про строчку с MinWidth имел в виду, а ты обе убрал. Ну и строчку убрал, и ничем не заменил - как бы минимальный размер в xaml задаётся, зачем тут то трогать?

2024-12-15 00:58 UTC, 21Melkuu commented on Content.Client/SS220/DialogWindowDescUI/DialogWindowDesc.xaml.cs
> +        MinWidth *= 2; // Just double it.
> @21Melkuu я именно про строчку с MinWidth имел в виду, а ты обе убрал. Ну и строчку убрал, и ничем не заменил - как бы минимальный размер в xaml задаётся, зачем тут то трогать?

произошло недопонимание

2024-12-15 01:38 UTC, stalengd commented
@21Melkuu такой минимальный размер в итоге остаётся? И я думаю стоит указать в ченж логе на каких ролях доступно переименование

2024-12-15 09:02 UTC, UrPrice commented
Надо будет этот функционал в будущем к потеряшкам прикрутить

2024-12-15 13:00 UTC, 21Melkuu commented
> @21Melkuu такой минимальный размер в итоге остаётся? И я думаю стоит указать в ченж логе на каких ролях доступно переименование

Ну я считаю да, так как минимальный размер более понятное единица измерения, +- ты всегда представляешь какое окно будет, если оно будет минимальным. Ченджлог изменю, после уточнений с юрпрайсом

2024-12-15 13:07 UTC, 21Melkuu commented
> Надо будет этот функционал в будущем к потеряшкам прикрутить К подкрепе также это нужно, чтобы не было подкреп с именем "Чёрный злобный парень явно не синдикатовец, он просто из компани синидкот"

Прикрутить несложно будет, достаточно выдать компонент через прототип, там уже все само будет работать. Если их пока в игре нет, то кто нибудь да выдаст. Или их прототип уже есть в игре?

Насчет подкреп, хз даже, так как оно меняет вообще везде имя и Чёрный злобный парень явно не синдикатовец, он просто из компани синидкот" это прям имена у подкреп, не карта? И про какую именно подкрепу мы говорим нюковская или минорная? Если речь про минорную то имеет смысл. Или ты хочешь дать туда и туда?

2024-12-15 13:53 UTC, UrPrice commented
> > Надо будет этот функционал в будущем к потеряшкам прикрутить К подкрепе также это нужно, чтобы не было подкреп с именем "Чёрный злобный парень явно не синдикатовец, он просто из компани синидкот"
> 
> Прикрутить несложно будет, достаточно выдать компонент через прототип, там уже все само будет работать. Если их пока в игре нет, то кто нибудь да выдаст. Или их прототип уже есть в игре?
> 
> Насчет подкреп, хз даже, так как оно меняет вообще везде имя и Чёрный злобный парень явно не синдикатовец, он просто из компани синидкот" это прям имена у подкреп, не карта? И про какую именно подкрепу мы говорим нюковская или минорная? Если речь про минорную то имеет смысл. Или ты хочешь дать туда и туда? 

Да сильно не парься, если что отдельным таском прототиперам отдадим. А так да, про минорных речь.

2024-12-15 14:07 UTC, 21Melkuu commented
> @21Melkuu такой минимальный размер в итоге остаётся? И я думаю стоит указать в ченж логе на каких ролях доступно переименование

кл изменил

2024-12-15 18:04 UTC, stalengd approved these changes

2024-12-15 18:05 UTC, merged