where is my CHEBUREKI??
SerbiaStrong-220/space-station-14 pull request #2345
Opened 2024-12-12 09:48 UTC by Tris0r

## Описание PR
Добавление в лодаут ГВ (10 часов) и в комод ГВ корпоративного комбинезона и юбки-комбинезона

**Медиа**
![девощка](https://github.com/user-attachments/assets/282381d2-a405-45de-98d7-c1a4eccfe7e9)
![мужичок](https://github.com/user-attachments/assets/85888e51-9dba-4cb6-96c6-54bc21a553cc)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
🆑 Cortez, molochk

- add: Добавлена корпоративная одежда в лодаут и в комод главного врача

2024-12-12 09:51 UTC, Tris0r commented
Это мой первый PR, поэтому будьте ко мне снисходительнее...
:gatoowo18:

2024-12-12 16:15 UTC, stalengd commented on Resources/Locale/ru-RU/ss220/clothing/Jumpskirt/jumpskirt.ftl
> +    .desc = "Красивый, стильный костюм настоящего главврача. Он подчёркивает натуру человека и его красоту харизмы..." Дальше на неоткрываемой этикетке ничего нет.
Может быть "красоту его харизмы"? И что такое "неоткрываемая этикетка"?

2024-12-12 16:17 UTC, stalengd commented on Resources/Prototypes/Loadouts/Jobs/Medical/chief_medical_officer.yml
Закинуть изменения в нашу папку

2024-12-12 16:47 UTC, Tris0r commented
Сказал же не душить...

2024-12-12 17:27 UTC, stalengd commented on Resources/Textures/SS220/Clothing/Uniforms/Jumpskirt/cmo_corpW.rsi/meta.json
> +  "license": "CC-BY-SA-3.0",
Пихай тогда нашу дефолтную CLA, примеры найдёшь, думаю, почти каждый наш спрайт по ней

2024-12-12 17:32 UTC, Tris0r commented on Resources/Prototypes/Catalog/Fills/Lockers/dressers.yml
> +      - id: ClothingUniformJumpskirtCMOCorporate #SS220 - CMOCorporate
А тут то что надо

2024-12-12 17:33 UTC, EstKemran commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +  parent: ClothingUniformBase
Поменять на `ClothingUniformSkirtBase`

2024-12-12 17:56 UTC, Tris0r commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +  parent: ClothingUniformBase
Why...

2024-12-12 18:19 UTC, EstKemran commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +  parent: ClothingUniformBase
> Why...

![изображение](https://github.com/user-attachments/assets/7e452859-f2ab-43ad-87f8-41b62c0a8840)
Без этого парента, на юбках, одетых на женских персонажах, если не ошибаюсь, пропадал пиксель у юбки. И чтобы этого бага избежать, создали базовых прототип `ClothingUniformSkirtBase`, где у компонента `Clothing` есть параметр `femaleMask: UniformTop`

2024-12-12 19:10 UTC, lexaSvarshik commented on Resources/Prototypes/Catalog/Fills/Lockers/dressers.yml
> +      - id: ClothingUniformJumpskirtCMOCorporate #SS220 - CMOCorporate
пробелы убрать

2024-12-12 19:19 UTC, lexaSvarshik requested changes
Немного по локализации, пометки исправить, в остальном нормально.
Но, честности ради, я бы переделал описание.

2024-12-12 19:19 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/ss220/clothing/Jumpskirt/jumpskirt.ftl
> +    .desc = "Красивый, стильный костюм настоящего главврача. Он подчёркивает натуру человека и его красоту харизмы..." Дальше на неоткрываемой этикетке ничего нет.
"Человека" заменить на что-то более нейтральное, у нас кроме людей другие гуманоиды есть

2024-12-12 19:19 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +  description: «A beautiful, stylish suit of a real chief physician. He emphasizes the nature of a person and his beauty of charisma...» There is nothing further on the unopened label.
```suggestion
  description: "A beautiful, stylish suit of a real chief medical officer. It emphasises the person's nature and the beauty of his charisma..." Nothing further on the unopened label.
```

2024-12-12 19:19 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpsuit/jumpsuits.yml
> +  description: «A beautiful, stylish suit of a real chief physician. He emphasizes the nature of a person and his beauty of charisma...» There is nothing further on the unopened label.
```suggestion
  description: "A beautiful, stylish suit of a real chief medical officer. It emphasises the person's nature and the beauty of his charisma..." Nothing further on the unopened label.
```

2024-12-12 19:19 UTC, lexaSvarshik commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - CMOCorpJumpskirt #ss220
```suggestion
  - CMOCorpJumpsuit #SS220-CMOCorporate
```

2024-12-12 19:19 UTC, lexaSvarshik commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - CMOCorpJumpsuit #ss220
```suggestion
  - CMOCorpJumpsuit #SS220-CMOCorporate
```

2024-12-12 19:40 UTC, stalengd commented on Resources/Locale/ru-RU/ss220/clothing/Jumpskirt/jumpskirt.ftl
> +    .desc = "Красивый, стильный костюм настоящего главврача. Он подчёркивает натуру человека и его красоту харизмы..." Дальше на неоткрываемой этикетке ничего нет.
Даже в таких контекстах "человек" обычно норм, всё таки у него смысл чуть шире чем просто раса.

2024-12-17 12:24 UTC, Tris0r commented
Почему не мёрж

2024-12-17 14:15 UTC, lexaSvarshik commented
> Почему не мёрж

something broke  
```
Exception whilst loading prototypes from /Prototypes/SS220/Entities/Clothing/Uniforms/Jumpsuit/jumpsuits.yml:
(Line: 75, Col: 145, Idx: 2591) - (Line: 75, Col: 183, Idx: 2629): While parsing a block mapping, did not find expected key. Exception: 
```

2024-12-17 14:49 UTC, Tris0r commented
> > Почему не мёрж
> 
> something broke  
> ```
> Exception whilst loading prototypes from /Prototypes/SS220/Entities/Clothing/Uniforms/Jumpsuit/jumpsuits.yml:
> (Line: 75, Col: 145, Idx: 2591) - (Line: 75, Col: 183, Idx: 2629): While parsing a block mapping, did not find expected key. Exception: 
> ```

А чё молчите тогда

2024-12-18 12:28 UTC, Tris0r commented
Изи все ошибки исправил.

2024-12-18 16:55 UTC, stalengd commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - CMOCorpJumpskirt #ss220
@Tris0r

2024-12-21 21:05 UTC, EstKemran approved these changes

2024-12-22 11:08 UTC, stalengd requested changes

2024-12-22 11:08 UTC, stalengd commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - CMOCorpJumpskirt #ss220
Всё ещё не исправлено

2024-12-22 11:18 UTC, stalengd requested changes

2024-12-22 11:18 UTC, stalengd commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  # -Hand/FootWraps-More-Color-End
Верни

2024-12-22 11:18 UTC, stalengd commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - GlassesCyber #-Two Floppa Iteration
Верни

2024-12-22 11:18 UTC, stalengd commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  #-CapHeadLoadoutsChanges-Begin
Верни

2024-12-22 11:18 UTC, stalengd commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  #-loadout-captain-begin
Верни

2024-12-22 11:18 UTC, stalengd commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  #-loadout-captain-end
Верни

2024-12-22 11:24 UTC, stalengd approved these changes

2024-12-22 11:48 UTC, merged