Добавление двух карамельных тростей для готовки
SerbiaStrong-220/space-station-14 pull request #2349
Opened 2024-12-13 05:54 UTC by Burenov

## Описание PR

Добавлена карамелька, заготовка для карамельной трости и возможность готовить из этого сами карамельные трости
1. Карамелька
Рецепт:
- 10ед сахара
- 10ед воды
- 15 секунд в микроволновк
2. Заготовка карамельной трости
Рецепт:
- Раскатать скалкой карамельку.
3. Красная карамельная трость
Рецепт:
- заготовка карамельной трости
- 5ед сиропа гренадин "спящая красавица"
- 15 секунд в микроволновке
4. Зелёная карамельная трость
Рецепт:
- заготовка карамельной трости
- 5ед лаймового сока
- 15 секунд в микроволновке
5. Красно-зелёная карамельная трость
- заготовка карамельной трости
- 5ед сиропа гренадин "спящая красавица"
- 5ед лаймового сока
- 15 секунд в микроволновке
6. Две карамельной трости
- 2 заготовки карамельной трости
- 5ед сиропа гренадин "спящая красавица"
- 5ед лаймового сока
- 20 секунд в микроволновке
![image](https://github.com/user-attachments/assets/d84c738a-07e5-4285-9718-f2de73d53f26)

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Burenov
- add: Добавлена карамелька!
- add: Добавлена заготовка для карамельной трости!
- add: Добавлена четыре разновидности карамельки!

2024-12-13 14:50 UTC, lexaSvarshik requested changes
На русском не пишем в прототипах, перенеси локализацию в ftl файл

2024-12-13 14:52 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/ingridients.yml
> +  description: Даже не пытайте опереться на неё
```suggestion
  description: Даже не пытайтесь опереться на неё
```

2024-12-13 16:42 UTC, Burenov commented
> На русском не пишем в прототипах, перенеси локализацию в ftl файл

Мне сказали в наших можно писать, поэтому я пишу на русском

2024-12-13 19:33 UTC, stalengd commented
> > На русском не пишем в прототипах, перенеси локализацию в ftl файл
> 
> Мне сказали в наших можно писать, поэтому я пишу на русском

Обманули

2024-12-14 11:12 UTC, Abiergo commented
![image](https://github.com/user-attachments/assets/b7dda666-6c15-4514-9e65-954f7642ed8c)
пупупуууу

2024-12-14 19:32 UTC, Kirus59 requested changes

2024-12-14 19:32 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/ingridients.yml
В прототипах на русском не пишем (за исключением комментариев).
Названия и описания сделать через локализацию (переводить на английский тут если чоу не обязательно, а поля `name` и `description` можно убрать из прототипа).

2024-12-14 19:32 UTC, Kirus59 commented on Resources/Prototypes/SS220/Recipes/Cooking/meal_recipes.yml
то же самое

2024-12-14 19:32 UTC, Kirus59 commented on Resources/Prototypes/SS220/Recipes/Cooking/meal_recipes.yml
> +#SS220 caramel cane start
В нашей директории пометки `SS220` можно не писать

2024-12-14 19:32 UTC, Kirus59 commented on Resources/Textures/SS220/Objects/Consumable/Food/caramel.rsi/meta.json
> +  "copyright": "sprite by dinazewwr (Discord) for SS220",
```suggestion
  "copyright": "sprited by dinazewwr (Discord) for SS220",
```

2024-12-16 05:43 UTC, Burenov commented
> > > На русском не пишем в прототипах, перенеси локализацию в ftl файл
> > 
> > 
> > Мне сказали в наших можно писать, поэтому я пишу на русском
> 
> Обманули

Прайс ответит за это

2024-12-17 05:46 UTC, Burenov commented
> > > > На русском не пишем в прототипах, перенеси локализацию в ftl файл
> > > 
> > > 
> > > Мне сказали в наших можно писать, поэтому я пишу на русском
> > 
> > 
> > Обманули
> 
> Прайс ответит за это
ПРАВДУ ПЫТАЮТСЯ СКРЫТЬ ОТ ВАС!!!

2024-12-17 06:12 UTC, Alwayswannahunt commented
> ПРАВДУ ПЫТАЮТСЯ СКРЫТЬ ОТ ВАС!!!

Abuser alert!

2024-12-17 06:31 UTC, Kirus59 approved these changes

2024-12-17 08:33 UTC, UrPrice approved these changes
Выполнено по поставленной задаче из дискорда

2024-12-17 08:38 UTC, merged