Актуализация правил в соответствии с вики
SerbiaStrong-220/space-station-14 pull request #2350
Opened 2024-12-13 07:32 UTC by Burenov

## Описание PR

Актуализировал правила в соответствии с вики версией
**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:Burenov
- tweak: Актуализированы правила!

2024-12-13 07:49 UTC, Tris0r commented on Resources/ServerInfo/Guidebook/ServerRules/SS220/RuleC4.xml
> +  Взяли должность инженера - будьте любезны настроить двигатель и подачу энергии. Играете врачем - лечите людей. Это особенно касается важных должностей, вроде тех же инженеров, ведь без питания стан
Не "врачем", а "врачом"

2024-12-13 07:49 UTC, Tris0r commented on Resources/ServerInfo/Guidebook/ServerRules/SS220/RuleC3.xml
> +  Правило о ПГ не распространяется на стычки с антагонистами, выживание в схватке с которыми стремится к нулю. К таким антагонистам сейчас относятся: Ядерные оперативники, Зомби, Космический дракон,
Зачем после "Жнец" точка, если там нужна запятая?

2024-12-13 07:50 UTC, Tris0r commented on Resources/ServerInfo/Guidebook/ServerRules/SS220/RuleC8.xml
> +  Правило о ВХ не распространяется на стычки с антагонистами, выживание в схватке с которыми стремится к нулю. К таким антагонистам сейчас относятся: Ядерные оперативники, Зомби, Космический дракон,
То же самое : точка вместо запятой.

2024-12-14 19:26 UTC, Kirus59 requested changes

2024-12-14 19:26 UTC, Kirus59 commented on Resources/ServerInfo/Guidebook/ServerRules/SS220/RuleC5.xml
> +  Запрещено трогать или взаимодействовать с ССД игроками, кроме как в следующих случаях: относить их в свой отдел  или крио (тем не менее это нежелательно, так как в случае длительного отсутствия игр
```suggestion
  Запрещено трогать или взаимодействовать с ССД игроками, кроме как в следующих случаях: относить их в свой отдел или крио (тем не менее это нежелательно, так как в случае длительного отсутствия игрок будет автоматически телепортирован в крио), оказывать медицинскую помощь или спасать их от непосредственной опасности (например, выносить из пожара).
```

2024-12-16 16:27 UTC, Kirus59 approved these changes

2024-12-16 16:31 UTC, merged