Add discord link requie
SerbiaStrong-220/space-station-14 pull request #2356
Opened 2024-12-15 02:04 UTC by Werzet

## Описание PR

Начало итерации по введению обязательной привязки дискорда. 

- Добавлен функционал по получению ссылок привязки от бэка личного кабинета. 
- Добавлено ожидание и проверка наличия привязки перед входом.
- Добавлено окошечко для получения ссылки.

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено новая привязка аккаунта к дискорду через личный кабинет.

2024-12-15 09:00 UTC, UrPrice commented
@Werzet везде, где не наш неймспейс - забыл метки проставить

2024-12-15 12:08 UTC, stalengd requested changes

2024-12-15 12:08 UTC, stalengd commented on Content.Server/Mapping/MappingManager.cs
> +using System.IO;
Пустое изменение

2024-12-15 12:08 UTC, stalengd commented on Content.Shared/Corvax/CCCVars/CCCVars.cs
> +using Robust.Shared.Configuration;
Пустое изменение

2024-12-16 06:29 UTC, stalengd requested changes

2024-12-16 06:29 UTC, stalengd commented on Content.Server/SS220/Discord/DiscordPlayerManager.cs
> +    private sealed record DiscordAuthInfoResponse(bool AccountLinked);
Плохо что подтипы объявлены между методов, нужно или в самом начале или в самом конце.

2024-12-16 23:30 UTC, stalengd approved these changes

2024-12-17 00:06 UTC, merged