BonusForFullyDiscovered
SerbiaStrong-220/space-station-14 pull request #2376
Opened 2024-12-21 21:34 UTC by 21Melkuu

## Описание PR

Перезалив, в прошлый раз насрал

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: 21Gnomkuu"
- add: Добавлен бонус за полное изучение артефакта
<!--
Make sure to take this Changelog template out of the comment block in order for it to show up. Changelog must have a :cl: symbol, so the bot recognizes the changes and adds them to the game's changelog.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-12-21 21:38 UTC, 21Melkuu commented
@UrPrice бам бим, списки шмоток, локализация и прочее советую проверить если что-то не так

2024-12-21 22:07 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Recipes/Lathes/electronics.yml
> +     Gold: 500
```suggestion

```

2024-12-21 22:08 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Recipes/Lathes/electronics.yml
> +     Gold: 500
fix tut

2024-12-21 22:09 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/prototypes/entities/objects/blueprint/blueprint.ftl
Сделай просто `BaseBlueprint `и подтягивай описание с него, чтобы можно было в описании указать `{ ent-BaseBlueprint.desc }`

2024-12-21 22:10 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/prototypes/entities/objects/blueprint/blueprint.ftl
> +ent-BlueprintSyndicateMicrowaveMachineCircuitboard = чертёж микроволновки Donk co
```suggestion
ent-BlueprintSyndicateMicrowaveMachineCircuitboard = чертёж платы микроволновки Donk co.
```

2024-12-21 22:11 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/prototypes/entities/objects/blueprint/blueprint.ftl
> +ent-BlueprintBeltChiefEngineer = чертёж пояса СИ
```suggestion
ent-BlueprintBeltChiefEngineer = чертёж пояса Старшего Инженера
```

2024-12-21 23:11 UTC, 21Melkuu commented on Resources/Locale/ru-RU/prototypes/entities/objects/blueprint/blueprint.ftl
чеки прошел, теперь к тебе, я нихуя не понял, покажите где искать пример

2024-12-22 01:19 UTC, lexaSvarshik commented on Resources/Locale/ru-RU/prototypes/entities/objects/blueprint/blueprint.ftl
`Resources\Locale\ru-RU\ss14-ru\prototypes\catalog\fills\backpacks\duffelbag.ftl`
Для примера. Много разных дюфелей, у всех одинаковое расписание

2024-12-26 05:24 UTC, Kirus59 commented
@21Melkuu веселье убираем, закомментированное тоже подсасывает в ЧЛ
![image](https://github.com/user-attachments/assets/b333edab-a174-4b31-a0b3-d0262ae8fab5)

2024-12-26 05:28 UTC, 21Melkuu commented
> @21Melkuu веселье убираем, закомментированное тоже подсасывает в ЧЛ ![image](https://private-user-images.githubusercontent.com/145689588/398642308-b333edab-a174-4b31-a0b3-d0262ae8fab5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTEwNDgsIm5iZiI6MTczNTE5MDc0OCwicGF0aCI6Ii8xNDU2ODk1ODgvMzk4NjQyMzA4LWIzMzNlZGFiLWExNzQtNGIzMS1hMGIzLWQwMjYyYWU4ZmFiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwNTI1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGFkMGJiNWNiZTkxNGFhZGNlYjVkNzhkOTdmOTJjOGNiY2IxYmZjYTZkOTgyMWE1YWVmMWU4NGI0MDQ3ZGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TC07I6AUMXcH6PbjRxmkY9_Bds_qj3ZoV1JuZ650u0E)

👍

2024-12-26 05:46 UTC, Kirus59 requested changes

2024-12-26 05:46 UTC, Kirus59 commented on Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactComponent.cs
> +    public List<string>? BonusProtype;
```suggestion
    [DataField(customTypeSerializer: typeof(PrototypeIdSerializer<EntityPrototype>)), ViewVariables]
    public List<string>? BonusPrototype;
```

2024-12-26 05:46 UTC, Kirus59 commented on Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.cs
> +        _throwing.TryThrow(protoUid, direction);
```suggestion
        var protoId = _random.Pick(component.BonusPrototype);
        if (!TrySpawnNextTo(protoId, uid, out var protoUid);
            return;

        var xform = Transform(protoUid.Value);
        var throwing = xform.LocalRotation.ToWorldVec() * 5f; // magic number throwing force
        var direction = xform.Coordinates.Offset(throwing);

        _throwing.TryThrow(protoUid.Value, direction);
```
Вроде правильно написал (через гит не совсем удобно).
Проверка ProtoUid на null - лишняя, т.к. `TrySpawnNextTo` принимает значение true только когда выдаваемый в out EntityUid не null

2024-12-26 05:46 UTC, Kirus59 commented on Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.cs
> +        var throwing = xform.LocalRotation.ToWorldVec() * 5f; // magic number throwing force
мб это "магическое" число сделаешь в каком-то промежутке и чтобы рандомилось?
Типо чтобы не всегда с фиксированной силой кидал, а с разной.

2024-12-26 05:46 UTC, Kirus59 commented on Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.cs
> +            component.IsBonusIssued = false;
Тут разве не true должно записывать?

2024-12-26 05:49 UTC, Kirus59 commented
@UrPrice глянь по прототипам, которые будут спавнится артами при полном изучении.
А то тут предлагают некоторые синди предметы (Омега мыло, шляпа-хамалеон, миксер ДНК, модуль оружия борга), лазерный пистолет, Тесла-пушку и т.д.

2024-12-26 06:46 UTC, UrPrice commented on Resources/Prototypes/Entities/Objects/Specific/Xenoarchaeology/item_artifacts.yml
> +    - ClothingBackpackNuclear
ClothingBackpackNuclear
Вот это братец шитспавн, а всё что с пометкой такой - это спрайты и прототипы на мягких условиях. Пока убери, лучше подложи им какой-то другой рюкзак синди, не ивентовый.

2024-12-26 06:52 UTC, UrPrice commented
В остальном - пойдёт. Учитывая концепцию, а иногда и сложность изучить полностью - то это должно быть интересно и весело. Что касается дополнений. Можно было бы вложить различные T3 технологии в этот список, но думаю мы потом вернёмся к этом, когда будем откатывать PR Зонеса на возможность изучения всех технологий.

2024-12-26 08:33 UTC, 21Melkuu commented on Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactComponent.cs
> +    public List<string>? BonusProtype;
Без датафилда с " " фаталит

2024-12-26 08:35 UTC, 21Melkuu commented on Content.Server/Xenoarchaeology/XenoArtifacts/ArtifactSystem.cs
> +            component.IsBonusIssued = false;
да, переименовывал филды, забыл поправить

2024-12-26 08:38 UTC, 21Melkuu commented
> В остальном - пойдёт. Учитывая концепцию, а иногда и сложность изучить полностью - то это должно быть интересно и весело. Что касается дополнений. Можно было бы вложить различные T3 технологии в этот список, но думаю мы потом вернёмся к этом, когда будем откатывать PR Зонеса на возможность изучения всех технологий.

То что просил убрал, а по поводу Т3. В данный момент нет никакого смысла, имхо, так как шанс дропа будем честны мал, а пока у нас все т3 есть, то изучить фулл ветки будет в 3 раза быстрее, чем поймать полезную т3 теху. Да и всегда можно отдать прототиперам, если появится резкая нужда.

2024-12-26 09:00 UTC, Kirus59 approved these changes

2024-12-26 09:03 UTC, merged