forms update
SerbiaStrong-220/space-station-14 pull request #2381
Opened 2024-12-22 12:43 UTC by EstKemran

## Описание PR

**Медиа**
![изображение](https://github.com/user-attachments/assets/4fa5f71a-bd9a-4935-9e46-1b432e82edfe)
![изображение](https://github.com/user-attachments/assets/ba407700-05c9-4468-b917-6bcf980b947d)
![изображение](https://github.com/user-attachments/assets/05b91209-1804-4196-9d35-ac105dfa4671)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Кавир, блёб
- add: Добавлены новые формы для копировального аппарата!
- tweak: Теперь приказ о казни находиться в разделе юридического отдела!

2024-12-22 12:58 UTC, stalengd requested changes

2024-12-22 12:58 UTC, stalengd commented on Resources/PhotocopierForms/FormIndex.yml
Здесь метки стоит убрать, это наш файл (как и директория целиком)

2024-12-22 13:01 UTC, stalengd commented
Думаю нужно согласовать как минимум с wiki... Кто вообще ответственен за такие изменения?

2024-12-22 17:10 UTC, Tris0r commented
> Думаю нужно согласовать как минимум с wiki... Кто вообще ответственен за такие изменения?

бубенка

2024-12-26 21:40 UTC, Gun-Done commented
Я хоть и добавляю сейчас это на вики, мне это вообще не нравится. Во-первых, это %дата, %имя - это всё выглядит убого и совсем не похоже на настоящую форму. Где это видано, чтобы вместо (ИМЯ) тебе в бланке выдавало %имя? Во-вторых, у тебя в запросе на признании врагом имя и должность в ряд выстроены, в постановлении зачем-то это перенесено на новую строку и вместо требования указать должность там уже за тебя вписано "магистрат".

Мне бы хотелось видеть везде нормальные унифицированные документы, а не хер пойми какой шаблон на каждом. Где хочется ты пишешь (ДАТА), а где %дата.

_Nevernightd, редактор wiki_

2024-12-26 21:50 UTC, Alwayswannahunt commented
> Во-первых, это %дата, %имя - это всё выглядит убого и совсем не похоже на настоящую форму.

При написании на бумаге формы %дата и %имя замениться на текущую дату и имя того, кто писал на бумаге, очевидно что на вики не нужно писать именно так.

2024-12-26 21:52 UTC, Gun-Done commented
> > Во-первых, это %дата, %имя - это всё выглядит убого и совсем не похоже на настоящую форму.
> 
> При написании на бумаге формы %дата и %имя замениться на текущую дату и имя того, кто писал на бумаге, очевидно что на вики не нужно писать именно так.

Ты уже третий, кто решил, что я этого не знаю.

Принтер должен выдавать унифицированные документы, все по форме, чтобы везде было одинаково написано, что требуется указать. Эти %дата, %имя выглядят как то, что принтер тебе не должен печатать на бумаге, вот моя позиция.

2024-12-26 21:58 UTC, Alwayswannahunt commented
> > > Во-первых, это %дата, %имя - это всё выглядит убого и совсем не похоже на настоящую форму.
> > 
> > 
> > При написании на бумаге формы %дата и %имя замениться на текущую дату и имя того, кто писал на бумаге, очевидно что на вики не нужно писать именно так.
> 
> Ты уже третий, кто решил, что я этого не знаю.
> 
> Принтер должен выдавать унифицированные документы, все по форме, чтобы везде было одинаково написано, что требуется указать. Эти %дата, %имя выглядят как то, что принтер тебе не должен печатать на бумаге, вот моя позиция.

Так унифицированный или тебе % не нравится?
Ещё вспомни, что вместо "(ИМЯ)" и прочего должно быть "_________". Считай, что %имя это и есть эта пустая строчка.

2024-12-26 23:06 UTC, stalengd approved these changes
Технически апрув, но не мержить пока не утрясётся по дизайну

2024-12-27 12:47 UTC, Glek3197 commented
Вставлю свои пять копеек.
Я предлагаю поменять строку «Уважаемый офицерский состав АСН "Севастополь"!» на строку «Уважаемому офицерскому составу АСН "Севастополь"» для повышения официозности и сухости текста.
Я также предлагаю поменять слово "содержание" на "заключение" в конце постановления о признании врагом корпорации.
В заявлении о нарушении КЗ предлагаю поменять "(ФИО заявителя)" на "(ПОЛНОЕ ИМЯ ЗАЯВИТЕЛЯ)", весь текст в скобках записать заглавными буквами, а также удалить примеры из формы. Мне кажется, они там излишни.
В форме приказа о казни добавить подсказки в скобках напротив "представленный к казни:" и "нарушения:".
В форме постановления признания врагом НТ заменить строку "магистрат" на строку с подсказкой "(ИМЯ ПРЕДСТАВИТЕЛЯ СУДЕБНОЙ ВЛАСТИ)" и убрать точку; поменять строку "в должности:" на "должность представителя судебной власти:". 
В форме запроса о признании врагом НТ убрать строку с подписью, места для печатей достаточно;
В той-же форме убрать запятые в предложении о мерах пресечения, они там лишние.
В той-же форме разделить места для имени представителя судебной власти и должности представителя судебной власти на две отдельных строки.
В той-же форме убрать часть текста про "исходя из положения" и заменить "положение . . . гласит: . . . ; согласно вышеупомянутому положению . . . признание . . . невозможно без одобрения . . , прошу признать . . ."
К слову, а смысл в этой форме, если в случаях, предусмотренных законом, признание проводится без директивы от ЦК?
Так и выходит, согласно положению о врагах корпорации, следовательно, директива ЦК нужна лишь в случае запроса о признании врагом НТ кого-либо, кто не подходит под критерии "разумная враждебная форма жизни, стремящаяся нанести серьёзный ущерб станции и экипажу". Критерии нужно расширить до чего-то вроде "серьёзной угрозы целостности, работоспособности или жизни активов НаноТрейзен, или таких, которые приносят серьёзный убыток НаноТрейзен" и обобщить, не зацикливаясь на станции и её экипаже, ведь признание врагом НТ может происходить и на наземных объектах НТ.
Насчет "%имя":
Если принтер не печатает сходу имя пользователя вместо "%имя", то не вижу разницы между использованием этой строки и строки "(ИМЯ)", разве что выглядит уродливо по сравнению с остальными формами.

В общем, формы нужно проверить, сравнить с другими формами, еще раз проверить, еще раз сравнить, и вносить правки так, чтобы новые формы имели тот-же стиль и такую-же терминологию, как и все остальные.
Предполагаю, что я нашел не все сомнительные части форм, но мне лень.
Позже, вероятно, ещё добавлю.

2024-12-27 17:09 UTC, EstKemran commented
> Во-первых, это %дата, %имя - это всё выглядит убого и совсем не похоже на настоящую форму. Где это видано, чтобы вместо (ИМЯ) тебе в бланке выдавало %имя? 

Почему не похожа? А где настоящая форма? У меня получается тупой плагиат? Почему убого? Почему там должно быть (ИМЯ), а не %имя?

Специально для удобства игроков и была придумана это механика. Смысл её ограничивать, учитывая, что на вики все формы с этой механикой?

> вместо требования указать должность там уже за тебя вписано "магистрат".

Потому что это бумага для магистрата? Почему бы сразу не указать его должность?

> Мне бы хотелось видеть везде нормальные унифицированные документы, а не хер пойми какой шаблон на каждом. Где хочется ты пишешь (ДАТА), а где %дата.

Гайд: Заходишь в трекер и пишешь там хотелки. Может и уже существующие сделаешь унифицированными

2024-12-27 17:10 UTC, EstKemran commented
> Вставлю свои пять копеек. Я предлагаю поменять строку «Уважаемый офицерский состав АСН "Севастополь"!» на строку «Уважаемому офицерскому составу АСН "Севастополь"» для повышения официозности и сухости текста. Я также предлагаю поменять слово "содержание" на "заключение" в конце постановления о признании врагом корпорации. В заявлении о нарушении КЗ предлагаю поменять "(ФИО заявителя)" на "(ПОЛНОЕ ИМЯ ЗАЯВИТЕЛЯ)", весь текст в скобках записать заглавными буквами, а также удалить примеры из формы. Мне кажется, они там излишни. В форме приказа о казни добавить подсказки в скобках напротив "представленный к казни:" и "нарушения:". В форме постановления признания врагом НТ заменить строку "магистрат" на строку с подсказкой "(ИМЯ ПРЕДСТАВИТЕЛЯ СУДЕБНОЙ ВЛАСТИ)" и убрать точку; поменять строку "в должности:" на "должность представителя судебной власти:". В форме запроса о признании врагом НТ убрать строку с подписью, места для печатей достаточно; В той-же форме убрать запятые в предложении о мерах пресечения, они там лишние. В той-же форме разделить места для имени представителя судебной власти и должности представителя судебной власти на две отдельных строки. В той-же форме убрать часть текста про "исходя из положения" и заменить "положение . . . гласит: . . . ; согласно вышеупомянутому положению . . . признание . . . невозможно без одобрения . . , прошу признать . . ." К слову, а смысл в этой форме, если в случаях, предусмотренных законом, признание проводится без директивы от ЦК? Так и выходит, согласно положению о врагах корпорации, следовательно, директива ЦК нужна лишь в случае запроса о признании врагом НТ кого-либо, кто не подходит под критерии "разумная враждебная форма жизни, стремящаяся нанести серьёзный ущерб станции и экипажу". Критерии нужно расширить до чего-то вроде "серьёзной угрозы целостности, работоспособности или жизни активов НаноТрейзен, или таких, которые приносят серьёзный убыток НаноТрейзен" и обобщить, не зацикливаясь на станции и её экипаже, ведь признание врагом НТ может происходить и на наземных объектах НТ. Насчет "%имя": Если принтер не печатает сходу имя пользователя вместо "%имя", то не вижу разницы между использованием этой строки и строки "(ИМЯ)", разве что выглядит уродливо по сравнению с остальными формами.
> 
> В общем, формы нужно проверить, сравнить с другими формами, еще раз проверить, еще раз сравнить, и вносить правки так, чтобы новые формы имели тот-же стиль и такую-же терминологию, как и все остальные. Предполагаю, что я нашел не все сомнительные части форм, но мне лень. Позже, вероятно, ещё добавлю.

Передам состовителю

2024-12-29 15:00 UTC, UrPrice commented on Resources/PhotocopierForms/nanotrasen_station/science/rnd_dfct.xml
> +[italic]Место для печатей – Научный руководитель[/italic]]]></Content>
[italic]Место для печатей[/italic]]]></Content>

2024-12-29 15:03 UTC, Glek3197 commented
Я предлагаю заменить форму НТ-ИСЛ-ДЕФ на следующую:

> [bold]Форма НТ-ИСЛ-ТЭС[/bold]
> [head=2]Техническая экспертиза синтетика[/head]
> 
> [italic]Дата: %дата[/italic] 
> 
> Эксперт: %имя
> Должность эксперта: %должность
> Идентификатор синтетика:
> Тип синтетика:
> 
> Свод законов синтетика:
> 
> Легальность свода законов: (ПЕРЕЧИСЛЕНИЕ)
> Текущая модификация: Модификация отдела (НАЗВАНИЕ ОТДЕЛА) / Стандарт
> Установленные модули:
> 
> Результат анализа поведения синтетика:
> (Перечисление поведенческих аномалий если таковые есть или запись об отсутствии оных)
> 
> Результат экспертизы:
> Экспертом синтетик (ИДЕНТИФИКАТОР СИНТЕТИКА) признаётся исправным, все системы в норме / дефективным в связи с аномальным поведением / дефективным в связи с аномальным сводом законов / дефективным в связи с отсутствием законов
> (ИСКЛЮЧИТЬ В СЛУЧАЕ ИСПРАВНОСТИ) Считаю деактивацию синтетика необходимой.
> 
> [italic]Место для печатей – Научный руководитель[/italic]

Форма написана мной лично и выполняет в том числе функцию, которую должна выполнять форма НТ-ИСЛ-ДЕФ, но предоставляет возможность подтвердить исправность синтетика и уточняет критерии дефективности.

2025-02-07 10:03 UTC, Kirus59 requested changes
Тегов `%имя` и `%должность` больше нет.
Ну и они и не заменялись бы при печати, а лишь при пересохранении документа

2025-02-07 10:05 UTC, closed without merging