Добавление недостающих спрайтов для юбки ГСБ
SerbiaStrong-220/space-station-14 pull request #2391
Opened 2024-12-23 06:15 UTC by Tris0r

## Описание PR
Добавлены недостающие спрайты для юбки ГСБ

**Медиа**
![image](https://github.com/user-attachments/assets/d3e745f6-e069-4499-bf76-d5f101dedb63)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
no cl

2024-12-23 06:16 UTC, Tris0r commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +  #ss220 FIX END
Это всё закомментировано потому что оно просто не работает никак, а из за них спрайты не грузились нормально

2024-12-23 09:19 UTC, Kirus59 commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +  #ss220 FIX END
Ну оно б работало, если бы стейты назвал `overlay-inhand-left`
Но вообще я хз зачем это накладывание друг на друга, вместо чисто спрайтов инхэнд

2024-12-23 09:20 UTC, Kirus59 commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
> +      "directions": 4
Спрайты наши?

2024-12-23 09:28 UTC, Tris0r commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
> +      "directions": 4
> Спрайты наши?

не знаю.

2024-12-23 09:28 UTC, Tris0r commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
> +  #ss220 FIX END
> Ну оно б работало, если бы стейты назвал `overlay-inhand-left` Но вообще я хз зачем это накладывание друг на друга, вместо чисто спрайтов инхэнд

ну вот я так же подумал и сделал как обычно

2024-12-23 09:30 UTC, Kirus59 commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
> +      "directions": 4
> не знаю.

Всмысле?
А откуда они тогда

2024-12-23 09:41 UTC, Kirus59 commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
> +      "directions": 4
> Диназёввр дала мне

Ну так значит наши?

2024-12-23 09:43 UTC, Tris0r commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
> +      "directions": 4
> > Диназёввр дала мне
> 
> Ну так значит наши?

Откуда она взяла - мне неизвестно

2024-12-23 11:59 UTC, lexaSvarshik commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
> +      "directions": 4
это рофлс

2024-12-23 14:46 UTC, EstKemran commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
> +  "copyright": "Created by Flareguy using sprites from tgstation at commit https://github.com/tgstation/tgstation/commit/c838ba21dae97db345e0113f99596decd1d66039 & the jumpskirt base found in color.r
`...f99596decd1d66039 & the jumpskirt base found in color.rsi., monkey and inhands sprited by dinazewwr (Discord) for SS220",`
:gonnacryhampter:

2024-12-23 15:22 UTC, Tris0r commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
> +  "copyright": "Created by Flareguy using sprites from tgstation at commit https://github.com/tgstation/tgstation/commit/c838ba21dae97db345e0113f99596decd1d66039 & the jumpskirt base found in color.r
> `...f99596decd1d66039 & the jumpskirt base found in color.rsi., monkey and inhands sprited by dinazewwr (Discord) for SS220",` :gonnacryhampter:

а что не так? :goodcat:

2024-12-23 19:23 UTC, Kirus59 requested changes

2024-12-23 19:23 UTC, Kirus59 commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
Т.к. спрайты наши - то переноси в нашу директорию, чтобы при и после апстримов не было проблем

2024-12-23 19:24 UTC, Tris0r commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
Но половина не наши

2024-12-23 19:25 UTC, Kirus59 commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
> Но половина не наши

Ну так наши в нашу директорию пренеси, ты же в компоненте `Item` можешь указать иной путь

2024-12-23 19:25 UTC, Kirus59 commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
Не все спрайты, а только новые стейты

2024-12-23 19:26 UTC, Tris0r commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
> > Но половина не наши
> 
> Ну так наши в нашу директорию пренеси, ты же в компоненте `Item` можешь указать иной путь

:cotyaaa:

2024-12-24 04:21 UTC, Tris0r commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
> +  "copyright": "Created by Flareguy using sprites from tgstation at commit https://github.com/tgstation/tgstation/commit/c838ba21dae97db345e0113f99596decd1d66039 & the jumpskirt base found in color.r
а всё, понял :goodcat:

2024-12-24 04:46 UTC, Tris0r commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
> > Но половина не наши
> 
> Ну так наши в нашу директорию пренеси, ты же в компоненте `Item` можешь указать иной путь

а как мне к "equipped-INNERCLOTHING-monkey" через item указать путь

2024-12-24 09:54 UTC, Tris0r commented
Я щас плакать буду

2024-12-24 11:08 UTC, Kirus59 commented on Resources/Textures/Clothing/Uniforms/Jumpskirt/hos.rsi/meta.json
> +
лишняя строка

2024-12-24 11:08 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +    sprite: SS220/Clothing/Uniforms/Jumpskirt/hos.rsi
А зачем?
Мог же просто путь поменять....

2024-12-24 11:11 UTC, Tris0r commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +    sprite: SS220/Clothing/Uniforms/Jumpskirt/hos.rsi
Моветон. Пути наши, а в папке не нашей.

2024-12-24 11:13 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +    sprite: SS220/Clothing/Uniforms/Jumpskirt/hos.rsi
> Пути наши, а в папке не нашей.

Это норма для респрайтов, главное пометки оставлять в оффовском прототипе

2024-12-24 11:16 UTC, Tris0r commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +    sprite: SS220/Clothing/Uniforms/Jumpskirt/hos.rsi
Ну я так решил. Нельзя что-ли?

2024-12-24 11:19 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +    sprite: SS220/Clothing/Uniforms/Jumpskirt/hos.rsi
> Ну я так решил. Нельзя что-ли?

Возвращай обратно, путь до спрайтов поменяй ток, ну и фикс `Item` компонента можешь оставить.

2024-12-24 11:22 UTC, Tris0r commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +    sprite: SS220/Clothing/Uniforms/Jumpskirt/hos.rsi
> > Ну я так решил. Нельзя что-ли?
> 
> Возвращай обратно, путь до спрайтов поменяй ток, ну и фикс `Item` компонента можешь оставить.

Ну нееееееет.... ;(((((

2024-12-24 15:50 UTC, lexaSvarshik requested changes
Прототип перенести в `Resources/Prototypes/SS220/Entities/Clothing/Uniforms/jumpskirts.yml`

2024-12-25 04:45 UTC, Tris0r commented
> Прототип перенести в `Resources/Prototypes/SS220/Entities/Clothing/Uniforms/jumpskirts.yml`

![image](https://github.com/user-attachments/assets/291385b5-3f7b-47e4-87e6-59756a956197)
Ты когда лезешь со своими советам, то хотя бы вникай в суть происходящего то...

2024-12-25 08:02 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +
Уэээээ, ну это в нашей директории так что ladno.
Но лучше такого не делать

2024-12-25 08:03 UTC, Kirus59 approved these changes

2024-12-25 08:23 UTC, Tris0r commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +
Я вообще не трогал это

2024-12-25 08:24 UTC, Tris0r commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +
Когда ревертил коммит замержилось так видимо

2024-12-25 08:26 UTC, Kirus59 commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +
> Я вообще не трогал это

Ты сюда прототип перенес и добавил пустую строку (что правильно для разделения прототипов).
А когда удалял прототип отсюда - видимо забыл про эту пустую строку

2024-12-25 08:26 UTC, merged

2024-12-25 09:31 UTC, Tris0r commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/Jumpskirt/jumpskirts.yml
> +
> > Я вообще не трогал это
> 
> Ты сюда прототип перенес и добавил пустую строку (что правильно для разделения прототипов). А когда удалял прототип отсюда - видимо забыл про эту пустую строку

а, я слепошарый . не то увидел.