Добавление баллистических очков ТОЛЬКО в лодаут пилота СБ
SerbiaStrong-220/space-station-14 pull request #2397
Opened 2024-12-23 19:44 UTC by Tris0r

## Описание PR
fix:#2395 

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
no cl

2024-12-23 19:46 UTC, EstKemran commented
Обождите пока

2024-12-23 19:46 UTC, Tris0r commented
> Обождите пока

Cтален сказал 2000 закрытых Пров до НГ сделать, так что нельзя ждать

2024-12-24 11:11 UTC, Kirus59 commented
@EstKemran Ну чоу там?
@Tris0r после `fix:` добавь пробел, чтобы слинковалось с ссылкой на ишуе

2024-12-24 15:53 UTC, lexaSvarshik commented
Ты вообще не то сделал. В ишуе ведь написано 
 ### Надо перенести часы с "игры на офицере СБ" на "игру в отделе СБ"
 То бишь надо сделать счетчик не по каждой роли индивидуально а общее время в сбшном отделе

2024-12-24 15:57 UTC, EstKemran commented
> @EstKemran Ну чоу там? @Tris0r после `fix:` добавь пробел, чтобы слинковалось с ссылкой на ишуе

Написал Лёне, он не ответил. Так что да, либо за общее время в отделе, либо каждой роле (или только офицеру, потому что другие вещи тоже только в его лодаутах) отдельно за их часы

2024-12-24 15:57 UTC, EstKemran commented
> Ты вообще не то сделал. В ишуе ведь написано
> ### Надо перенести часы с "игры на офицере СБ" на "игру в отделе СБ"
> 
> То бишь надо сделать счетчик не по каждой роли индивидуально а общее время в сбшном отделе

![изображение](https://github.com/user-attachments/assets/5b2dce7b-f4dd-491a-8a25-780cacd56140)
Поменяли

2024-12-24 15:58 UTC, lexaSvarshik requested changes

2024-12-24 15:58 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Loadouts/Jobs/Security/security_officer.yml
>        !type:RoleTimeRequirement
```suggestion
      !type:DepartmentTimeRequirement
        department: Security
```

2024-12-24 15:58 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Loadouts/Jobs/Security/security_officer.yml
> +      role: JobSecurityPilot #ss220 fix ballistic glasses
```suggestion

```

2024-12-24 15:58 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Loadouts/loadout_groups.yml
> +  name: loadout-group-security-pilot-glasses
Не нужно

2024-12-24 15:58 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Loadouts/loadout_groups.yml
> +#  - GlassesBallistic
Верни на родину

2024-12-24 15:59 UTC, lexaSvarshik commented
> Поменяли

Ну и ну. Я в целом предложил как можно сделать

2024-12-24 16:05 UTC, Tris0r commented
> Ты вообще не то сделал. В ишуе ведь написано
> 
> ### Надо перенести часы с "игры на офицере СБ" на "игру в отделе СБ"
> То бишь надо сделать счетчик не по каждой роли индивидуально а общее время в сбшном отделе

![image](https://github.com/user-attachments/assets/f921297e-d3b5-44c6-aed1-e328ad90ac26)

Реально не то???
Ты бы хотя бы разобрался изначально, а потом уже говорил тогда.

2024-12-24 16:06 UTC, Tris0r commented on Resources/Prototypes/SS220/Loadouts/loadout_groups.yml
> +#  - GlassesBallistic
Ало дружище, я без тебя разберусь

2024-12-25 02:30 UTC, lexaSvarshik commented
> Реально не то??? Ты бы хотя бы разобрался изначально, а потом уже говорил тогда.

Я зашел в ишуе, почитал, зашёл в ПР и вообще не понял че к чему. Потом уже мне рассказали

2024-12-25 05:01 UTC, Tris0r commented
@Kirus59

2024-12-25 08:08 UTC, Kirus59 approved these changes

2024-12-25 08:29 UTC, merged