sm qol fixes
SerbiaStrong-220/space-station-14 pull request #2401
Opened 2024-12-24 11:57 UTC by Alwayswannahunt

## Описание PR

Жёстко выдал спидранКодинга в лучших традициях any%.

По хорошему нужно чтобы кто-то проверил, что оно действительно работает как задумано, у меня пока времени нет.
Раз СМ появился на почти всех картах, то надо бы и учесть реакцию игроков.

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **озНакомился** с [наставлЕниями по рабоТе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я невнимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал и сразу выключал локальный сервер со своими изменениями и всё протестировал.
- [x] Я ленюсь добавить скриншот/видео демонстрации PR в игре, хотят этот PR этого не требует.

**Изменения**
:cl: AlwyAnri
- tweak: Замедлен расход плазмы в коллекторах, если они работают рядом с кристаллом суперматерии!
- tweak: Замедлен износ катушек тесла, если они работают рядом с кристаллом суперматерии!
- tweak: Кристалл суперматерии теперь охотнее теряет температуру! Зима пришла?!
- fix: Исправлено появление пепла, когда игрок вбегал в кристалл!

2024-12-24 22:23 UTC, stalengd requested changes
Мапперы балдеют от этой прикормки

2024-12-24 22:23 UTC, stalengd commented on Content.Server/Tesla/Components/TeslaCoilComponent.cs
> +    public float SMLookupRange = 5f;
Вот такое название в yaml будет `sMLookupRange`? Not yaml-friendly enough

2024-12-24 22:23 UTC, stalengd commented on Content.Server/Tesla/EntitySystem/TeslaCoilSystem.cs
> +// SS220-SM-fix-begin
Отступ бы после этого в одну строку, да и в принципе на метки юзингов можно забить

2024-12-24 22:23 UTC, stalengd commented on Content.Server/Tesla/EntitySystem/TeslaCoilSystem.cs
> +        var sm_queries = _entityLookup.GetEntitiesInRange<SuperMatterComponent>(Transform(entity).Coordinates, entity.Comp.SMLookupRange);
`sm_queries` - bad naming

2024-12-25 18:00 UTC, Alwayswannahunt commented
Я потестил есчо

2024-12-25 18:14 UTC, Alwayswannahunt commented
@stalengd А я пну тебя и так и так
@UrPrice, я тут добавил ЛКП что защищено от ивентового выключения света. Он есть и как прототип, и как компонент. Если будешь фиксить карты после апдейт, то стоит и это добавить.

2024-12-25 18:35 UTC, stalengd requested changes

2024-12-25 18:35 UTC, stalengd commented on Content.Server/SS220/SuperMatter/Crystal/Components/HighPriorityAPCComponent.cs
> +namespace Content.Server.SS220.SuperMatterCrystal.Components;
Почему в неймспейсе СМа?

2024-12-25 18:35 UTC, stalengd commented on Content.Server/Singularity/Components/RadiationCollectorComponent.cs
> +    public float SMNearReactionRateModifier = 0.2f;
Опят нейминг

2024-12-25 18:57 UTC, stalengd approved these changes

2024-12-25 19:12 UTC, merged

2024-12-26 06:08 UTC, UrPrice commented
> я тут добавил ЛКП что защищено от ивентового выключения света. Он есть и как прототип, и как компонент. Если будешь фиксить карты после апдейт, то стоит и это добавить.

Учту, спасибо