Craftable desword
SerbiaStrong-220/space-station-14 pull request #2404
Opened 2024-12-24 17:55 UTC by lexaSvarshik

## Описание PR

Добавлена возможность крафта даблы из двух обычных мечей. Как настоящей, так и игрушечной. Может быть полезно, если у тебя есть лишний меч от павшего товарища или трофей.

**Медиа**

![изображение](https://github.com/user-attachments/assets/689e034b-648e-4739-b1c0-3cb0581dd5b4)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Svarshik
- add: Добавлена возможность крафта двухклинкового энергомеча из двух обыкновенных (настоящего и игрушечного)

2024-12-26 13:50 UTC, UrPrice approved these changes
Да, это механика из 13, на парашизе примерно так его и получают (покупают два обычных есворда и скрещивают)

2024-12-26 23:10 UTC, stalengd requested changes

2024-12-26 23:10 UTC, stalengd commented on Resources/Prototypes/Entities/Objects/Fun/Instruments/instruments_percussion.yml
> +
Что здесь произошло?

2024-12-26 23:10 UTC, stalengd commented on Resources/Prototypes/SS220/Shitspawn/FractWarEbent/Weapons/Melee/soldiers_weapon.yml
Измнения этого файла здесь должны быть? В описании PR ничего про них не написано

2025-01-28 09:56 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Shitspawn/FractWarEbent/Weapons/Melee/soldiers_weapon.yml
Здесь изменено для того, чтобы из ивентового оружия не получилось бы сделать даблу

2025-01-28 09:58 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Shitspawn/FractWarEbent/Weapons/Melee/soldiers_weapon.yml
Ибо это тупо если мы тыкнем саблей по мечу/серпу/топору и получится дабла.

2025-01-28 09:59 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/Shitspawn/FractWarEbent/Weapons/Melee/soldiers_weapon.yml
Да и в любом случае стоит парентить от базы а не от е-сворда

2025-01-28 18:13 UTC, stalengd commented on Resources/Prototypes/SS220/tags.yml
> +
Зачем им теги?

2025-01-29 09:06 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/tags.yml
> +
Потому что оффы таким образом закодили систему крафта

2025-01-29 09:07 UTC, lexaSvarshik commented on Resources/Prototypes/SS220/tags.yml
> +
Я пытался сделать это как-то более изящно, но оно не хочет.

2025-01-29 15:51 UTC, stalengd commented on Resources/Prototypes/SS220/tags.yml
> +
Так разве нельзя по id прототипа крафты делать?

2025-01-29 16:04 UTC, stalengd approved these changes

2025-01-29 16:05 UTC, merged