𝔖𝔲𝔯𝔤𝔢𝔯𝔶 update
SerbiaStrong-220/space-station-14 pull request #2412
Opened 2024-12-26 18:23 UTC by Alwayswannahunt

## Описание PR

Ну смотрите, вам нужны механы и конструкторы, механы я вам дам, конструктор не дам. Крч, какой-то сахар медикам.

**Код**

Добавлен компонент позволяющий открывать UI по использованию предмета на чём-то, используется когда нужно предугадывание. 

Графы хирургических операции получили красивые conditions 

**Медиа**

Фотка лампуса через...

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: AlwyAnri
- add: Добавлено много операций для медиков (не забыть их расписать...)

2024-12-26 22:08 UTC, UrPrice commented
Вот что происходит когда устаёшь ждать NewMed от офов

2024-12-27 08:55 UTC, plagexx commented
Не все герои носят плащи

2025-05-02 10:45 UTC, stalengd commented on Content.Client/SS220/Surgery/SurgeryStartUi/SurgeryDrapeMenu.xaml.cs
> +        }
Обычно в таких случаях сначала всё отключают, а потом включают, чтобы не получилось так, что отключили то что нужно было включить

2025-05-02 10:45 UTC, stalengd commented on Content.Client/SS220/Surgery/SurgeryStartUi/SurgeryPerformButton.cs
Не совсем понял зачем эта кнопка нужна

2025-05-02 10:45 UTC, stalengd commented on Resources/Locale/ru-RU/ss220/surgery/condition.ftl
> +surgery-availability-condition-state-straight = прямой, провека
```suggestion
surgery-availability-condition-state-straight = прямой, проверка
```

2026-04-03 07:31 UTC, Alwayswannahunt commented
/gemini review

2026-04-03 07:52 UTC, Alwayswannahunt commented
/gemini review

2026-04-15 21:31 UTC, Alwayswannahunt commented
/gemini review

2026-04-15 21:40 UTC, Alwayswannahunt commented on Content.Shared/SS220/Surgery/Systems/SharedSurgerySystem.cs
> +            _damageable.TryChangeDamage(args.Target, surgeryTool.FailureDamage, origin: args.User);
ты фрик

2026-04-15 21:41 UTC, Alwayswannahunt commented on Content.Shared/SS220/Surgery/Systems/SharedSurgerySystem.cs
> +            surgeryTool.NextFailureDamageTime = _gameTiming.CurTime + surgeryTool.FailureDamageDelay;
Ты мне 7 минут этот высер генерил?

2026-04-16 17:06 UTC, stalengd requested changes
Не ну это реджект

2026-04-16 17:06 UTC, stalengd commented on Content.Shared/Weapons/Melee/SharedMeleeWeaponSystem.cs
> +        if (checkCombatMode && !CombatMode.IsInCombatMode(user))
меткой меня полей

2026-04-16 17:06 UTC, stalengd commented on Content.Shared/Implants/SharedSubdermalImplantSystem.cs
> +    private const float HiddenImplantInjectionChance = 0.15f;
меееетку

2026-04-16 17:07 UTC, UrPrice commented
🫨

2026-05-25 11:23 UTC, Alwayswannahunt commented
/gemini review

2026-05-30 13:32 UTC, Alwayswannahunt commented
/gemini review

2026-05-30 13:47 UTC, Alwayswannahunt commented on Content.Client/SS220/DialogWindowProtoIdUI/DialogWindowTTSProtoId.xaml.cs
> +        _promptLines[0].Item2.Editable = false;
Your skill issue is inimaginable

2026-05-30 13:48 UTC, Alwayswannahunt commented on Content.Client/SS220/Surgery/SurgeryStartUi/SurgeryPuppetBox.xaml.cs
> +        return button;
Your skill issue is inimaginable

2026-05-30 13:49 UTC, Alwayswannahunt commented on Content.Client/SS220/Surgery/NodeGraphUi/OperationNodeLabel.xaml.cs
> +    }
Добро пожаловать в будущее старик

2026-05-30 13:51 UTC, Alwayswannahunt commented on Content.Server/SS220/Surgery/Systems/SurgerySystem.cs
> +        _bloodstream.TryModifyBleedAmount(entity.Owner, entity.Comp.OnSurgeryMoveBleed * distance * entity.Comp.OngoingSurgeries.Count);
ну что-то в этом есть

2026-05-30 13:52 UTC, Alwayswannahunt commented on Content.Server/SS220/Surgery/Actions/ApplyDamageAction.cs
> +        }
Я нонконформист есчо

2026-05-30 15:36 UTC, stalengd approved these changes
LGTM

2026-05-30 15:36 UTC, stalengd commented on Content.Client/SS220/DialogWindowProtoIdUI/DialogWindowTTSProtoId.xaml.cs
> +/// A modified <see cref="DialogWindow"/> window in which you can send an additional description to explain a particular action being performed
Точно актуальное описание? Чёт ничего не пойму из него.

2026-05-30 15:36 UTC, stalengd commented on Content.Shared/SS220/Surgery/Graph/SurgeryGraphNode.cs
> +    private SurgeryGraphEdge[] _edges= Array.Empty<SurgeryGraphEdge>();
Ботик дело говорит

2026-05-30 15:59 UTC, Alwayswannahunt commented on Content.Client/SS220/DialogWindowProtoIdUI/DialogWindowTTSProtoId.xaml.cs
> +/// A modified <see cref="DialogWindow"/> window in which you can send an additional description to explain a particular action being performed
Поймал на копипасте, исправлю

2026-05-31 08:45 UTC, Alwayswannahunt commented
Ой, в апдейт вмерджить забыли, какая жалость!

2026-05-31 08:47 UTC, merged