Xmas resprites
SerbiaStrong-220/space-station-14 pull request #2416
Opened 2024-12-28 11:08 UTC by RobUster0

## Описание PR

Праздник для работяг и существ станции! 

**Медиа**

![image](https://github.com/user-attachments/assets/c73271d9-5e9b-40ed-9fae-af5fc01fa7fe)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Vimenant
- add: С праздниками! Добавлены новогодние каски и новогодний шлем СБ в лодауты!
- tweak: Новогодние пИИ и станционный ИИ! Король крыс и его слуги нарядились тоже!

2024-12-30 02:46 UTC, stalengd requested changes

2024-12-30 02:46 UTC, stalengd commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - SecurityHelmetXmas
А метку?

2024-12-31 12:29 UTC, EstKemran approved these changes

2024-12-31 20:15 UTC, UrPrice approved these changes

2025-01-01 01:31 UTC, stalengd approved these changes

2025-01-01 01:31 UTC, merged