Lost souls fix
SerbiaStrong-220/space-station-14 pull request #2431
Opened 2024-12-29 21:47 UTC by Bomjojuk

## Описание PR
Фикс отсутствия шаттлов в листе ивентов

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

2024-12-29 22:21 UTC, UrPrice commented on Resources/Prototypes/GameRules/roundstart.yml
А зачем тут развернули пометки? По итогу закоменченное не офами, а нами - без пометок

2024-12-29 22:21 UTC, UrPrice commented on Resources/Prototypes/GameRules/roundstart.yml
@stalengd

2024-12-29 22:23 UTC, stalengd commented on Resources/Prototypes/GameRules/roundstart.yml
Ну там где закоенчено действительно пометки должны быть

2024-12-30 00:55 UTC, UrPrice commented on Resources/Prototypes/GameRules/roundstart.yml
@Bomjojuk делай как надо
как не надо не делай

2024-12-30 10:33 UTC, stalengd requested changes
Метки стоят неправильно, должны стоять там, где у нас изменения, в том числе закоменчивание, и только там. Можешь открыть файл у оффов и посмотреть.

2024-12-30 12:02 UTC, Bomjojuk commented
> Метки стоят неправильно, должны стоять там, где у нас изменения, в том числе закоменчивание, и только там. Можешь открыть файл у оффов и посмотреть.

Поправлю как освобожусь

2024-12-30 18:31 UTC, Bomjojuk commented
@stalengd надеюсь, правильно сделал

2024-12-30 23:24 UTC, stalengd approved these changes

2024-12-31 06:01 UTC, UrPrice commented
5-ый перезапуск чеков
@stalengd точно все ок?

2024-12-31 06:24 UTC, stalengd commented
> 5-ый перезапуск чеков @stalengd точно все ок?

Как видишь

2024-12-31 06:24 UTC, merged