fix-blueshield-belts
SerbiaStrong-220/space-station-14 pull request #2438
Opened 2024-12-31 15:07 UTC by EstKemran

## Описание PR

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я **ознакомился** с [наставлениями по работе с репозиторием](https://serbiastrong-220.github.io/ss220-docs/development/ss220-guidelines/) и следовал им при создании PR'а.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Kemran
- fix: Исправлены пояс и РПС синего щита

2024-12-31 18:02 UTC, Kirus59 requested changes

2024-12-31 18:02 UTC, Kirus59 commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        - BlasterPowerCell # SS220 fix-blueshield-belts
В прошлый раз не заметил этого, но этот прототип создан для щитспавна на ивенте, лучше создай отдельный базовый для своих.

2024-12-31 18:03 UTC, Kirus59 commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        - BlasterPowerCell # SS220 fix-blueshield-belts
Можешь с этим id создать в целом то, только тогда для щитспавн-ячейки поменяй id

2024-12-31 18:06 UTC, Kirus59 commented
@EstKemran Т.к. ты добавил компонент `ItemSlots` для пояса ОСЩ - то нужно также добавить контейнер `item` в компоненте `ContainerContainer`
![image](https://github.com/user-attachments/assets/b67117b3-1760-4a92-b440-3c6ac8cb2426)

2025-01-03 02:19 UTC, UrPrice commented
А что исправлено, что мне смотреть?

2025-02-01 09:23 UTC, waf926 commented
> А что исправлено, что мне смотреть?

Теперь в пояс щита можно батарейки складывать (магазины для крс)

2025-02-07 09:50 UTC, Kirus59 commented
@EstKemran В чейнджлоге пожалуйста напиши подробнее что было исправлено/изменено.

@UrPrice  Ну тут короч изменил сетку хранилища РПС осщ (на такую же, как у других рпс) + добавил вайтлист на некоторые предметы (по тегам Sidearm, Medkit + по компоненту Станбаттона).
Поясу он добавил раундстартовый станбаттон.

Ну и еще заменил КРС на КРВ в шкафу ОСЩ. Я по прототипу вижу разницу только в режиме стрельбы и описании между ними, поэтому это так и должно быть?

2025-02-07 09:54 UTC, UrPrice commented
> Ну и еще заменил КРС на КРВ в шкафу ОСЩ. Я по прототипу вижу разницу только в режиме стрельбы и описании между ними, поэтому это так и должно быть?

Не знаю. Вроде не со мной обсуждалось. Но наверное да, будем считать что так надо.

2025-02-07 09:54 UTC, UrPrice approved these changes

2025-02-07 09:59 UTC, Kirus59 commented on Resources/Prototypes/Entities/Clothing/Belt/belts.yml
> +        - BlasterPowerCell # SS220 fix-blueshield-belts
> В прошлый раз не заметил этого, но этот прототип создан для щитспавна на ивенте, лучше создай отдельный базовый для своих.

Тоже самое сделай и для КРС и КРВ

2025-02-07 10:02 UTC, EstKemran commented
Забейте пока, я потом доделаю

2025-03-05 17:16 UTC, closed without merging