Возможность зажигать спичку о сапоги
SerbiaStrong-220/space-station-14 pull request #304
Opened 2023-09-01 21:58 UTC by CthulhuFhtaghn

## Описание PR

Добавляет компонент matchbox сапогам (всяким боевым и исследовательским) и лакированным туфлям, потому что зажигать спичку о подошву это стильно. Одобрено ПМом.

Возможная проблема - если оффы сделают TODO и добавят компоненту изменение спрайта в зависимости от заполненности, но тогда можно будет просто этот компонент у сапог убрать. А еще я не смог запустить тест и заливаю так, я уверен что ничто не пойдет не так...

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add:

2023-09-01 22:02 UTC, TheArturZh commented
За визуальные состояния заполненности отвечает ItemCounter, так что забей
Тесты аппрувнул, подожду пока пройдут

2023-09-01 22:37 UTC, TheArturZh requested changes

2023-09-01 22:37 UTC, TheArturZh commented on Resources/Prototypes/Entities/Clothing/Shoes/boots.yml
> +    - type: Matchbox
Не тот уровень индентации, не будет работать

2023-09-25 09:28 UTC, CthulhuFhtaghn commented
Но вообще я вспомнил что оффы кажется сами именно это сделали, так что закрываю ПР?

2023-09-25 09:33 UTC, TheArturZh commented
Угу, думаю можно закрывать

2023-09-25 09:33 UTC, closed without merging