Some objects can be placed on placeable surfaces
SerbiaStrong-220/space-station-14 pull request #41
Opened 2023-05-27 18:20 UTC by apexman

## Описание PR

Список объектов, которые можно кликом положить на стол
* handcuff
* experimental welding tool (and other welders)
* syringe
* absorbents

Гаечный ключ будет сразу разбирать стол

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- fix: Исправлена механика для некоторых объектов, которые раньше нельзя было кликом положить на стол

2023-05-28 05:16 UTC, apexman commented
таска
http://jewishcat.net:8101/bcgpd7er8bfb5ug1z9rx1zoi89h/vcx53ttenkifefgef5m5477dsfr/criaenkyppjnc7k7dx5wgggbrfy

2023-06-03 19:05 UTC, Redict commented on Content.Server/Chemistry/EntitySystems/ChemistrySystem.Injector.cs
> +using Linguini.Syntax.Ast;
??

2023-06-07 12:26 UTC, rincew1nd requested changes

2023-06-07 12:26 UTC, rincew1nd commented on Content.Shared/Cuffs/SharedCuffableSystem.cs
>              TryCuffing(args.User, target, uid, component);
Вот этот метод должен чекать, можно ли заковать объект и возвращать результат. Если цель была закована успешно, `args.Handled` должно быть true.

2023-06-07 12:26 UTC, rincew1nd commented on Content.Server/Fluids/EntitySystems/SpraySystem.cs
> +        if (HasComp<PlaceableSurfaceComponent>(args.Target)
Компонент с `PlaceableSurfaceComponent` может быть не `IsPlaceable`
```
HasComp<PlaceableSurfaceComponent>(args.Target, out var placeableSurfaceComponent) && placeableSurfaceComponent.IsPlaceable
```

2023-06-07 12:26 UTC, rincew1nd commented on Content.Server/Chemistry/EntitySystems/ChemistrySystem.Injector.cs
>              if (_solutions.TryGetDrawableSolution(target, out var drawableSolution))
`else if`, баг в апстриме.

2023-06-11 10:38 UTC, rincew1nd commented
Тут ещё мерж конфликты есть. Нужно мастер подмержить и порешать.

2023-07-18 13:39 UTC, merged