Синдром туретта
SerbiaStrong-220/space-station-14 pull request #427
Opened 2023-10-12 09:49 UTC by CthulhuFhtaghn

Хорошая серия

## Описание PR

Добавляет трейт синдрома туретта. Персонаж с ним получает рандомный шанс (от 0 до 0.6 с повышенным шансом на 0) вставить перед каждой своей фразой реплику из своего списка (выбранного случайно). Есть попискивания и мяуканья, есть ругань. Одобрено неким Sunday.

Также добавил в копировальный аппарат форму справки о наличии синдрома туретта.

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2023-10-12 18:18 UTC, TheArturZh requested changes

2023-10-12 18:18 UTC, TheArturZh commented on Content.Server/SS220/TouretteSyndrome/TouretteAccentSystem.cs
> +        msg = msg[0].ToString().ToLower() + msg.Remove(0, 1);
Нужна проверка в начале функции
```csharp
if (string.IsEmpty(msg))
    return msg
```
не крашит потому что пустые стринги туда пока не приходят, но я бы подстраховался

2023-10-12 18:18 UTC, TheArturZh commented on Resources/Prototypes/Traits/inconveniences.yml
> +    - type: TouretteAccent
Нужно перенести в отдельный файл в папку SS220

2023-10-13 19:17 UTC, TheArturZh requested changes

2023-10-13 19:17 UTC, TheArturZh commented on Content.Server/SS220/TouretteSyndrome/TouretteAccentSystem.cs
> +            return msg
; нужна, не компилит

2023-10-13 20:26 UTC, TheArturZh commented
йа долбаёб
IsEmpty на IsNullOrEmpty

2023-10-13 21:05 UTC, CthulhuFhtaghn commented
Сделано

2023-10-13 21:07 UTC, TheArturZh requested changes

2023-10-13 21:07 UTC, TheArturZh commented on Resources/Prototypes/SS220/TouretteCollection/confusing.yml
> +  id: cute
Дубликат ID, не грузится прототип

2023-10-15 09:50 UTC, merged