Гайдбук с КЗ.
SerbiaStrong-220/space-station-14 pull request #44
Opened 2023-05-29 13:55 UTC by Devianartaro

## Описание PR
Новый раздел для гайдбука под законы.
Все было взято с вики корвакс. в будущем можно будет все изменить под вики ss220.
Мой дс - Gados#1923

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлено руководство про космический закон.

2023-05-31 18:44 UTC, Redict commented
Нет скриншотов из игры

2023-06-04 08:40 UTC, TheArturZh commented
Тяжесть статьи не читаема, у людей с дальтонизмом или засвеченным моником будет вообще пиздец. Лучше сделать градацию от зеленого к красному с I по V уровень, и так чтоб value цвета сильно отличался от фона. Схожесть с вики в таких деталях ИМХО не важна

2023-06-04 14:58 UTC, Legendaxe reviewed
Все нормально, но согласен с комментатором выше что цвета лучше сделать более выделяющимися

2023-06-04 14:58 UTC, Legendaxe commented on Resources/ServerInfo/Guidebook/Law/Charges.xml
> +Описание:Снятие обвинений.
```suggestion
 Описание:Снятие обвинений.
```
Все ниже идущие описания начинаются с пробела (Либо тут ставь, либо там убирай)

2023-06-04 23:02 UTC, Redict requested changes
Исправляй вышеописанное

2023-06-07 11:26 UTC, rincew1nd commented
Я дальтоник, моим глазам от первой версии было безумно больно.
Вторая версия лучше, но лучше всё же поменять цвета для удобства чтения. Так же у тебя есть чёрный цвет, который просто не видно на фоне окна.

Предлагаю следующие цвета (возможно стоит посмотреть ещё на синие цвета, они будут более заметны, что бы не было только градации от зелёного к красному): #00FF00, #55FF55, #FFFF00, #FF5555, #FFFF00
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/4948767/33a7ee51-62f8-460a-8f0e-761e8346e79f)

Так же у тебя нет тяжести для статей, ни цифр, ни цвета.

2023-06-07 11:31 UTC, rincew1nd requested changes

2023-06-07 11:31 UTC, rincew1nd commented on Resources/ServerInfo/Guidebook/Law/x02.xml
> +# х02 - Нарушение ограничений оборота опасных предметов
Слишком длинно для интерфейса, так как основные заголовки не врапаются на новую строку.
Можно сделать вот так, например:
```
# х02 - Нарушение ограничений
# оборота опасных предметов
# 
```

2023-06-07 11:31 UTC, rincew1nd commented on Resources/ServerInfo/Guidebook/Law/x04.xml
> +# х04 - Нарушение общественного порядка
Слишком длинная строка для заголовка.

2023-06-07 11:31 UTC, rincew1nd commented on Resources/ServerInfo/Guidebook/Law/x07.xml
> +# х07 - Преступления против трудового порядка
Слишком длинная строка для заголовка.

2023-07-17 18:44 UTC, aw-c commented
@OCOtheOmega доделывать пр будешь или закрывать?

2023-07-27 21:19 UTC, closed without merging