anom_run
SerbiaStrong-220/space-station-14 pull request #461
Opened 2023-10-20 12:49 UTC by ZoNeSRuS

## Описание PR

Аномалии получили возможность убегать из одного тайла плазменного окна.
Во время Пульса аномалии начинают двигаться в хаотичном порядке в течении 20 секунд, с очень быстро убывающей скоростью.
Компоненте RandomWalk добавлена переменная Change, которая модифицирует скорость передвижения каждый тик.
По умолчанию 1.

Хотел бы немного советов, как это все завернуть красиво, а то у меня глаз дергается.

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:ZoNeSRuS
- add: Аномалии научились убегать от РНД

2023-10-22 17:57 UTC, TheArturZh requested changes

2023-10-22 17:57 UTC, TheArturZh commented on Content.Server/Physics/Controllers/RandomWalkController.cs
> +            randomWalk.MaxSpeed=randomWalk.MaxSpeed=15;
Зачем присваивание такое странное?

2023-10-22 17:57 UTC, TheArturZh commented on Content.Server/Physics/Controllers/RandomWalkController.cs
> +           randomWalk.MaxSpeed=randomWalk.MaxSpeed=0;
тоже странное присваивание

2023-10-22 17:57 UTC, TheArturZh commented on Content.Server/Physics/Controllers/RandomWalkController.cs
> +        randomWalk.MaxSpeed=randomWalk.MaxSpeed*randomWalk.Сhange;
используй оператор `=*`

2023-10-22 17:57 UTC, TheArturZh commented on Content.Server/Physics/Controllers/RandomWalkController.cs
> +    }
поведение должно быть отключаемым и прописываться в прототипе для каждой аномалии по-отдельности с помощью була в компоненте Anomaly с изначальным значением false
Нужно потому что аномалии добавляются постоянно и мы должны иметь возможность определять каким аномалиям такое поведение нужно а каким нет

2023-10-23 04:04 UTC, ZoNeSRuS commented on Content.Server/Physics/Controllers/RandomWalkController.cs
> +            randomWalk.MaxSpeed=randomWalk.MaxSpeed=15;
Вопрос хороший, задал его сам себе, похоже я был пьян или уставший.

2023-10-23 04:18 UTC, ZoNeSRuS commented on Content.Server/Physics/Controllers/RandomWalkController.cs
> +        randomWalk.MaxSpeed=randomWalk.MaxSpeed*randomWalk.Сhange;
> используй оператор `=*`

Я тоже так хотел, но не получилось, сейчас погуглил нужно '*='

2023-10-23 04:56 UTC, ZoNeSRuS commented on Content.Server/Physics/Controllers/RandomWalkController.cs
> +    }
> поведение должно быть отключаемым и прописываться в прототипе для каждой аномалии по-отдельности с помощью була в компоненте Anomaly с изначальным значением false Нужно потому что аномалии добавляются постоянно и мы должны иметь возможность определять каким аномалиям такое поведение нужно а каким нет

Я понял о чем ты. Сам хотел сделать подобное, но у меня возникли проблемы с тем как из данной процедуры вызвать значение компонента Anomaly. Может есть какой то пример в коде?
Я мог бы конечно пройти к ней через `uid`, но что то мне подсказывает что есть куда более простой вариант.

2023-10-23 13:51 UTC, merged