Пилот и прочее
SerbiaStrong-220/space-station-14 pull request #471
Opened 2023-10-25 18:22 UTC by VladIsLove-e

## Описание PR

Добавлен солдатский и офицерский мундиры
Берет пилота
Бомбер пилота
Шкаф пилота
Пилот на дельту(икс 3 сука)

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2023-10-25 18:32 UTC, VladIsLove-e commented
*перекрестился*

2023-10-25 19:47 UTC, TheArturZh commented
Авторство спрайтов указывается в meta.json. Если спрайты сделаны с нуля то нужно указать наш EULA/CLA в поле лицензии в meta.json
Пути должны быть нормальные. Если хочешь указать авторство, то нужно делать это в файле.

2023-10-25 19:56 UTC, Kit0vras requested changes

2023-10-25 19:56 UTC, Kit0vras commented on Resources/Textures/SS220/Clothing/OuterClothing/Armor/secbomber.rsi/meta.json
> +  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/2fea0a59470c476cf3f927833d3918d89cbe6af8 and WhereMyTea Editions",
```suggestion
  "copyright": "Taken from tgstation at commit https://github.com/tgstation/tgstation/commit/2fea0a59470c476cf3f927833d3918d89cbe6af8 and edited by wheremytea (Discord)",

```

2023-10-25 19:56 UTC, Kit0vras commented on Resources/Textures/SS220/Clothing/Uniforms/Mundir.rsi/meta.json
> +  "copyright": "Made for SS220 by MIXnikita",
```suggestion
  "copyright": "Made by mixnikita (Discord) for SS220",

```

2023-10-25 19:56 UTC, Kit0vras commented on Resources/Textures/SS220/Clothing/Uniforms/OfficerMundir.rsi/meta.json
> +  "copyright": "Made for SS220 by MIXnikita",
```suggestion
  "copyright": "Made by mixnikita (Discord) for SS220",

```

2023-10-25 19:56 UTC, Kit0vras commented on Resources/Prototypes/SS220/VladIsLove/VladIsLove.yml
> +  description: Настоящие лётчики носят и бронежилеты, и модные куртки
```suggestion
  description: Настоящие лётчики носят и бронежилеты, и модные куртки.
```

2023-10-25 19:56 UTC, Kit0vras commented on Resources/Prototypes/SS220/VladIsLove/VladIsLove.yml
> +  description: Берет с наушниками... Чтоб уши грели
```suggestion
  description: Берет с наушниками... Чтоб уши грели.
```

2023-10-25 19:56 UTC, Kit0vras commented on Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
> +  description: Место для хранение пожитков славных лётчиков Корпорации
```suggestion
  description: Место для хранение пожитков славных лётчиков Корпорации.
```

2023-10-26 02:28 UTC, VladIsLove-e commented on Resources/Textures/SS220/Clothing/Uniforms/Mundir.rsi/meta.json
> +  "copyright": "Made for SS220 by MIXnikita",
Это не михитка рисовал, а Glek)

2023-10-26 02:28 UTC, VladIsLove-e commented on Resources/Textures/SS220/Clothing/Uniforms/OfficerMundir.rsi/meta.json
> +  "copyright": "Made for SS220 by MIXnikita",
Тоже

2023-10-26 02:39 UTC, Kit0vras commented on Resources/Textures/SS220/Clothing/Uniforms/Mundir.rsi/meta.json
> +  "copyright": "Made for SS220 by MIXnikita",
Так а почему он тогда указан?
В таком случае glek3197

2023-10-26 04:27 UTC, FriedrichStrassen commented
Всем евросоюзом делаем мои чёртовы курточки и шапочки :D

2023-10-26 05:26 UTC, VladIsLove-e commented on Resources/Textures/SS220/Clothing/Uniforms/Mundir.rsi/meta.json
> +  "copyright": "Made for SS220 by MIXnikita",
> Так а почему он тогда указан? В таком случае glek3197

Я в прототипе менял, ибо мне было лень)

2023-10-26 06:54 UTC, DexlerXD requested changes
Согласен с @Kit0vras в его комментах, но  ещё пару вещей можно добавить...

2023-10-26 06:54 UTC, DexlerXD commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> +- type: entity
```suggestion
#SS220-Pilot
- type: entity
```
Стоит добавлять комменты, чтобы в будущем можно было легко понять, что делали именно мы.

2023-10-26 06:54 UTC, DexlerXD commented on Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
> +# Pilot
```suggestion
#SS220-Pilot
```

2023-10-27 07:39 UTC, VladIsLove-e commented
Всё принял

2023-10-27 07:53 UTC, Kit0vras commented on Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
> +  description: Место для хранение пожитков славных лётчиков Корпорации.
:clueless:

2023-10-27 10:16 UTC, DexlerXD commented
Ну получше, только вот для человека отдельную папочку создавать, а не раскидывать файлы по соответствующим содержанию файла папкам такое себе дело...

2023-10-27 10:18 UTC, VladIsLove-e commented
> Ну получше, только вот для человека отдельную папочку создавать, а не раскидывать файлы по соответствующим содержанию файла папкам такое себе дело...

Это только на протипы, которые новые. В любом случае поиск есть

2023-10-27 10:20 UTC, DexlerXD commented
> > Ну получше, только вот для человека отдельную папочку создавать, а не раскидывать файлы по соответствующим содержанию файла папкам такое себе дело...
> 
> Это только на протипы, которые новые. В любом случае поиск есть

Я не хочу душить, но это правда немного портит то, как структурирован проект

2023-10-29 17:00 UTC, TheArturZh approved these changes

2023-10-29 21:04 UTC, Kit0vras approved these changes

2023-10-29 22:13 UTC, merged