PDA: Messenger program system
SerbiaStrong-220/space-station-14 pull request #48
Opened 2023-05-31 19:12 UTC by TokDenis

## PDA: Messenger program system

Добавил мессенджер программу для cartridge системы.
MessengerCartridgeComponent - хранит полученные сообщения и информацию о пользователе программы
MessengerCartridgeSystem - использует DeviceNetworkSystem для общения между мессенджерами, подробнее можно почитать в комментариях самой системы

**Проблемы**
1. Хранение в MessengerCartridgeComponent только полученных сообщений выглядит логично, что бы не задваивать данные. Но не слишком удобно для получения от туда данных.
2. Есть идея заменить\дополнить MessengerCartridgeComponent чем то вроде _MessengerServerComponent_ который и будет выступать в роле хранилища сообщений. Его можно будет поставить на карте, можно будет выключить, украсть или взять данные по чужим чатам и т.д.
3. Как первый этап Canvas говорил что можно использовать за сервер TelecomServer.
4. Есть проблема с получением имени члена экипажа, ид карта не инициализирована при OnInstall программы с мессенджером.
5. Мы хотим вообще использовать DeviceNetworkSystem или работать без этого?
6. Может ли пользователь менять имя? Локально для себя можно будет менять имя контактов, в перспективе.

**TODO**
1. Добавление нового контакта при прилете с шатла. т.е. смене network сети.
2. Интерфейс тестовый, сделаем красиво как с функционалом определимся.
3. Пиликать рингтоном при получение сообщения. (главная фича в общем то)

**Медиа**
<img width="2000" alt="1" src="https://github.com/SerbiaStrong-220/space-station-14/assets/77569658/fecc401a-db72-4605-8479-5946291a73d6">
<img width="2001" alt="2" src="https://github.com/SerbiaStrong-220/space-station-14/assets/77569658/1e0afe7f-85ee-49f9-88a8-f3aff479a542">
<img width="2005" alt="3" src="https://github.com/SerbiaStrong-220/space-station-14/assets/77569658/650f9dc7-58fc-4fa8-965f-5963d6bd1f09">

**Проверки**
- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
- add: MessengerCartridgeComponent 
- add: MessengerCartridgeSystem

2023-06-07 12:39 UTC, rincew1nd commented
Немного дополнительной информации.
Посчитал эту задачи интересной и полезной в освоении базового UI, обмена сообщениями и эвентами.
В итоге уделил часов 10 своего времени и накидал рабочий прототип который можно допилить:
https://github.com/rincew1nd/space-station-14/tree/messenger-cartridge-system

Что было сделано:
- Базовый UI
- Регистрация пользователей в системе при наличии Id карты в PDA
- Онлайн статус пользователя
- Отправка сообщений пользователям, получение истории сообщений
- Кеш сообщений работает только в пределах одной станции

Что нужно сделать:
- Красивый UI
- Кеш сообщений на стороне пользователя для сокращения трафика Server-Client
- Оповещение получателей о новых сообщениях
- Оповещение отправителей о неудачной доставке (пользователь офлайн)
- Обновление имени при его изменении на Id карте (если такое вообще возможно)
- Получение истории переписки с других станций, если она была
- Сброс истории сообщений в конце раунда
- Возможно: терминал на станции через который можно посмотреть переписку, требует доступы
- Возможно: добавить проверку рейнджа до ближайшего терминала что бы не давать смотреть историю сообщений в дали от станции

2023-06-07 12:41 UTC, Redict commented
@rincew1nd @TokDenis синканитесь по задаче тогда

2023-06-07 13:48 UTC, rincew1nd commented
> @rincew1nd @TokDenis синканитесь по задаче тогда

Мы уже. Я ему отдал исходники 3 дня назад. Просто решил сюда продублировать.

2023-06-20 23:22 UTC, TokDenis commented
- Переделал UI
- Звук рингтона при новом сообщение
- Локализовал
- Стейт +- эффективно отправляется. При первом открытии отправляется весь стейт, далее только отсутствующие. 
- Аутентификация ID картой. Можно расширить.
- Авторизация системой AccessReader
- Добавил два прототипа сервера Nanotrasen и синдиката
- Мессенджер основан на чатах и их участниках. Можно расширить чаты до групп, каналов и тд


Общий вид (не прочитанное сообщение выделяется желтым)
<img width="1275" alt="image" src="https://github.com/SerbiaStrong-220/space-station-14/assets/77569658/05d53c6e-48fd-4e92-89a4-374c26ae7c2a">
<img width="1275" alt="image" src="https://github.com/SerbiaStrong-220/space-station-14/assets/77569658/c3dbf1e9-b46c-429c-9226-0c46fc5bb118">

Поиск по чатам и сообщениям
<img width="1276" alt="image" src="https://github.com/SerbiaStrong-220/space-station-14/assets/77569658/1d8337ac-6758-4894-a04d-ff825f016393">

Избранное (чат с самим собой)
<img width="1277" alt="image" src="https://github.com/SerbiaStrong-220/space-station-14/assets/77569658/c0205532-c7dd-4f33-86a4-0b2900cda4bb">

2023-06-21 21:20 UTC, Redict commented
Ready for review?

2023-06-21 23:09 UTC, TokDenis commented
> Ready for review?

Yes

2023-06-23 06:27 UTC, rincew1nd requested changes

2023-06-23 06:27 UTC, rincew1nd commented on Content.Server/Messenger/MessengerServerSystem.cs
> +                message.Id = messageKey.Id;
Айдишник должен заполняться внутри AddMessage. Передай с ref message

2023-06-23 06:27 UTC, rincew1nd commented on Content.Server/Messenger/MessengerServerSystem.cs
> +        foreach (var (_, contact) in component.GetClientToContact())
Огромное колличество мусорных объектов в памяти. Зачем создавать чаты которых пока ещё даже нет.

2023-06-23 06:27 UTC, rincew1nd commented on Content.Server/CartridgeLoader/Cartridges/MessengerClientCartridgeSystem.cs
> +        switch (command)
Энум

2023-06-23 06:29 UTC, rincew1nd commented
Посмотрел всё что касается сервера. UI не смотрел, не осталось свободного времени.

2023-06-23 09:10 UTC, rincew1nd commented
Ещё тестов нет и они падают

2023-06-25 15:24 UTC, TokDenis commented on Resources/Prototypes/Entities/Objects/Devices/Circuitboards/Machine/production.yml
> +      prototype: CrewMonitoringServer
Копипаста, поправлю

2023-06-25 15:28 UTC, TokDenis commented on Resources/Prototypes/Entities/Objects/Devices/pda.yml
> +  - type: StationLimitedNetwork
Да, ограничение работает на текущю станцию (как я понял, можешь посмотреть), т.е. если ты перейдешь в другую станцию и там будет другой сервер, то пда свяжется с ним, а не будет отправлять сообщения на все сервера на карте.

2023-06-25 15:28 UTC, TokDenis commented on Resources/Prototypes/Entities/Objects/Devices/cartridges.yml
> +      receiveFrequencyId: MessengerClient
Я пробовал, но тк сам клиент работает как отдельный компанент я решил не засорять пда и тем более можно накинуть клиент на любое entity и прописать логику работы. Как пример - консоль с которой можно отправить сообщения или вендинговый автомат который отправляет всем рекламу...

2023-06-25 15:30 UTC, TokDenis commented on Resources/Prototypes/Entities/Structures/Machines/messenger_server.yml
> +    - type: AccessReader
Да, (если у него тег !NuclearOperative) сейчас как я понял из вражеских доступов только NuclearOperative.

2023-06-25 15:30 UTC, TokDenis commented on Resources/Prototypes/Entities/Structures/Machines/messenger_server.yml
> +  id: PDASyndicateMessengerServer
Как пример. Вроде у них есть свой корабль, не? Туда установить можно.

2023-06-25 15:32 UTC, TokDenis commented on Resources/Prototypes/Entities/Objects/Devices/cartridges.yml
> +    - type: StationLimitedNetwork
Что бы на другую станцию не передавать\получать сообщения. Это то как Network устроен. Можем убрать, но вроде там было какое то условие что этот компонент требуется.

2023-06-25 15:32 UTC, TokDenis commented on Content.Shared/Content.Shared.csproj
> +  <ItemGroup>
Что то автоматически добавилось, уберем

2023-06-25 15:34 UTC, TokDenis commented on Content.Shared/Messenger/MessengerState.cs
> +    public HashSet<string> ActiveAddresses = new();
Нет, ты же можешь открыть программу на компьютере и на телефоне, ну на консоли и на пда, как пример. Т.е. зачем ограничивать?

2023-06-25 15:35 UTC, TokDenis commented on Content.Shared/Messenger/MessengerState.cs
> +    public uint From;
Это идентификатор контакта на сервере, это не entity. Переименую в FromContactId

2023-06-25 15:37 UTC, TokDenis commented on Content.Shared/CartridgeLoader/Cartridges/MessengerUiMessageEvent.cs
> +    public readonly bool IsFullState;
Клиент запрашивает всё состояние. Например - ты оперативник изьял пда у чела, вместо того что бы запрашивать все чаты по отдельности и все сообщения. Передается FullState - содержит все чаты и последние сообщения. Потом уже при переходе на чат подгружаются сообщения чата.

2023-06-25 15:39 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerComponent.cs
> +public sealed class ContactKey : IId
Что бы типизировать использование. Для программиста проще разные типы чем uint который везде принимается (как мне кажется).

2023-06-25 15:44 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerComponent.cs
> +        var contactKey = _contactsStore.Add(new MessengerContact(name, netAddress));
Для расширения. Контакт может быть заведен программно и не привязываться к entity, при этом можно завести еще один _clientToContact (назвать по другому) и хранить идентификаторы других entity которые будут выступать в роли аутентификатора. Или вообще не entityUid хранить.

У одного игрока может быть несколько контактов за счет смены id карты, можно поменять карт и ты уже другой человек. По этому тут идет привязка именно к entity карты.

2023-06-25 15:45 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerComponent.cs
> +    private readonly Dictionary<uint, TValue> _storage = new();
Точно? Как то можно проверить на гонку?

2023-06-25 15:46 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerComponent.cs
> +public interface IId
Для дженериков выше

2023-06-25 15:46 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerComponent.cs
> +    public MessengerChat GetChat(   ChatKey key)
сделаем

2023-06-25 15:50 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerComponent.cs
> +        return new HashSet<ChatKey>(_publicChats);
Что бы его скопировать.

2023-06-25 15:50 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerComponent.cs
> +        return _privateChats.Get(key, out var chats) ? new HashSet<ChatKey>(chats) : new();
копирование

2023-06-25 15:53 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerSystem.cs
> +    private bool GetIdCardComponent(EntityUid? loaderUid, [NotNullWhen(true)] out EntityUid? idCardUid,
А почему грузить?

2023-06-25 15:55 UTC, TokDenis commented on Content.Server/CartridgeLoader/Cartridges/MessengerClientCartridgeSystem.cs
> +    private void BroadcastCommand(EntityUid senderUid, EntityUid loaderUid, string command)
Есть компонент StationLimitedNetwork он это отслеживает. Ренж отслеживает вроде WirelessNetworkConnection

2023-06-25 16:00 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerSystem.cs
> +        foreach (var (_, contact) in component.GetClientToContact())
Не такое уж и огромное. Так проще и расширять понятнее. Вот есть контакты, вот есть чаты, в чатах есть их члены и сообщения. Сообщения тоже отдельно хранятся. В общем небольшая база данных.

2023-06-25 19:13 UTC, rincew1nd commented on Content.Server/Messenger/MessengerServerComponent.cs
> +public sealed class ContactKey : IId
Они одинаковые и засоряют кодовую базу. Если хочешь типизацию, сделай базовый класс и унаследуйся. Но имхо они избыточны.

2023-06-25 19:17 UTC, rincew1nd commented on Content.Server/Messenger/MessengerServerComponent.cs
> +        return new HashSet<ChatKey>(_publicChats);
Так а зачем его копировать, ты же его нигде не меняешь потом. Это чисто аксес на просмотр.

2023-06-25 19:17 UTC, rincew1nd commented on Content.Server/Messenger/MessengerServerComponent.cs
> +        return _privateChats.Get(key, out var chats) ? new HashSet<ChatKey>(chats) : new();
Коммент выше такой же.

2023-06-25 19:19 UTC, rincew1nd commented on Content.Server/Messenger/MessengerServerSystem.cs
> +    private bool GetIdCardComponent(EntityUid? loaderUid, [NotNullWhen(true)] out EntityUid? idCardUid,
Каждый самый маленький аксес данных будет дёргать постоянно сущности с сервака. Мне кажется что такие вещи стоит как-то по другому делать, но пока не знаю как правильнее.

2023-06-25 19:22 UTC, rincew1nd commented on Content.Server/Messenger/MessengerServerSystem.cs
> +        foreach (var (_, contact) in component.GetClientToContact())
Окей. Видимо нужно учитывать что это не высоконагруженный сервак и у нас не десятки тысяч человек, наверно сможем выделить лишнюю память на кеш под раунд.

2023-06-26 21:07 UTC, KashRas commented
Выдаёт постоянно ошибку, мол, сервер не найден.

2023-06-26 21:47 UTC, TokDenis commented
> Выдаёт постоянно ошибку, мол, сервер не найден.

Я на карту не добавлял. В поиске entity найди мессенджер и установи, клиент подключится при открытие UI

2023-06-27 04:39 UTC, KashRas commented
> > Выдаёт постоянно ошибку, мол, сервер не найден.
> 
> Я на карту не добавлял. В поиске entity найди мессенджер и установи, клиент подключится при открытие UI

Всё равно не видит сервер.

2023-07-09 22:49 UTC, TokDenis commented on Resources/Prototypes/Entities/Objects/Devices/pda.yml
> +  - type: StationLimitedNetwork
Посмотрел по коду. Да ограничивает в пределах текущей станции на которой находишься. т.е. перейдешь на другую сеть сменится на сеть станции на которую перешел.

2023-07-09 22:50 UTC, TokDenis commented on Resources/Prototypes/Entities/Objects/Devices/cartridges.yml
> +    - type: StationLimitedNetwork
ответил выше

2023-07-17 19:14 UTC, aw-c commented
@TokDenis привет, есть что доделывать и мёржить или закрывать?

2023-07-17 19:34 UTC, TokDenis commented
> @TokDenis привет, есть что доделывать и мёржить или закрывать?

Нужно доделать правки на которые указал rincew1nd, я напишу в дискорде когда будет готово. Думаю на неделе выделю несколько часиков

2023-07-28 20:55 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerComponent.cs
> +        message.Id = key.Id;
Это ок, мне нужен ид в структуре сообщения. При заполнение в store этот ид пишется только как ключ. Не знаю как быстро поправить что бы ид при записи в store записывался и в само сообщение

2023-07-28 21:07 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerComponent.cs
> +        chat.Id = key.Id;
Отписал выше

2023-07-28 21:09 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerComponent.cs
> +        return new HashSet<ChatKey>(_publicChats);
Меняю

2023-07-28 21:10 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerComponent.cs
> +        return _privateChats.Get(key, out var chats) ? new HashSet<ChatKey>(chats) : new();
Полученный сет я потом дополняю

2023-07-28 21:10 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerComponent.cs
> +        messengerContact.Id = key.Id;
Так должно быть, описал выше

2023-07-28 21:14 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerComponent.cs
> +    public bool GetContactKey(EntityUid client, [NotNullWhen(true)] out ContactKey? key)
Надо разобраться используем ли мы [NotNullWhen(true)] Очень много где по коду встречал, по этому тут так реализовал

2023-07-28 21:19 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerSystem.cs
> +    private static bool ParseId(string key, NetworkPayload payload, [NotNullWhen(true)] out uint? v)
Вынес в отдельные фунции что бы уточнить что конкретно я хочу получить из payload.

2023-07-28 21:26 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerSystem.cs
> +                if (!AccessCheck(uid, args.Data))
Немного не понял. Можешь подробнее? Это обязательно нужно в текущей итерации?

2023-07-28 21:28 UTC, TokDenis commented on Content.Server/Messenger/MessengerServerSystem.cs
> +                message.Id = messageKey.Id;
До записи в компонент ид не известно.

2023-07-29 14:25 UTC, rincew1nd commented on Content.Server/Messenger/MessengerServerSystem.cs
> +                if (!AccessCheck(uid, args.Data))
В шарпе все классы это object. Object можно конвертнуть обратно в классы, так как object знает какой он был классом.
Если сделать ‘’’if(object is NewClass classObj)’’’, то код зайдёт в if только если объект нужного типа и конвертнулся нормально, а classObj будет заполнен инстансом.

args.Data это объект, который можно сделать отдельным классом на каждый тип ивентов. А потом смотреть на тип ивента и понимать в какой класс нужно конвертнуть данные. Если конвертация упала, то что-то пошло не так.

2023-08-03 01:33 UTC, merged

2023-08-03 08:09 UTC, TokDenis commented
Инструкция как поставить сервер что бы работало

Ищем сервер для сообщений и ставим в нужное место
![photo_2023-08-03_12-06-41](https://github.com/SerbiaStrong-220/space-station-14/assets/77569658/a1bcc270-14b2-4913-a604-f035f4a16404)

Проверяем работает открывая приложение в пда
![photo_2023-08-03_12-06-48](https://github.com/SerbiaStrong-220/space-station-14/assets/77569658/ebea0ad8-a359-4747-8516-a97145234360)