Rnd reb
SerbiaStrong-220/space-station-14 pull request #496
Opened 2023-11-02 10:34 UTC by ZoNeSRuS

## Описание PR

Очередной разбаланс патч для РНД, скорее всего последний.

_Изначально сосуд аномалий был очень сильно апнут, что бы показать РНД силу компонентов, рнд это понравилось, теперь увы придется вернуть к нормальным значениям._
Эффективность улучшения сосуда аномалий снижена. Пример 3го тира.
300%>>>125%

_Артефакторы жаловались, что они не поспевают за аномалиями и изучаются все супер медленно. Теперь им не придется сидеть большую часть смены глядя в монитор._
Сканер артефактов теперь имеет время скана 30с, а не 60с.
Тир3 сканер артефактов сканит 7с.

_Изменение аномалий открыло новое взаимодействие сними, к сожалению оно делало их слишком легким, концепт хороший, но нужно его пустить в другое русло._
Аномалии при попытке их телепортировать коллапсируют, держите их подальше от врат в на карте "Гейт".

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:ZoNeSRuS
- tweak: изменено РНД

2023-11-03 20:33 UTC, DexlerXD commented on Content.Shared/Teleportation/Systems/SharedPortalSystem.cs
> +
```suggestion
        if (HasComp<AnomalyComponent>(subject))
           _anomalySystem.DoAnomalySupercriticalEvent(subject);

```
Не хочу душить, но так получше выглядит, все равно `anomaly` дальше не используется.

2023-11-03 20:38 UTC, DexlerXD requested changes

2023-11-03 20:38 UTC, DexlerXD commented on Content.Server/Anomaly/Components/AnomalyVesselComponent.cs
> +    public float PartRatingPointModifier = 1.5f;
```suggestion
    public float PartRatingPointModifier = 1.5f; //SS220-rnd-reb
```

2023-11-03 20:38 UTC, DexlerXD commented on Content.Server/Xenoarchaeology/Equipment/Components/ArtifactAnalyzerComponent.cs
> +    public TimeSpan AnalysisDuration = TimeSpan.FromSeconds(30);
```suggestion
    public TimeSpan AnalysisDuration = TimeSpan.FromSeconds(30); //SS220-rnd-reb
```

2023-11-03 20:38 UTC, DexlerXD commented on Content.Server/Xenoarchaeology/Equipment/Components/ArtifactAnalyzerComponent.cs
> +    public float PartRatingAnalysisDurationMultiplier = 0.5f;
```suggestion
    public float PartRatingAnalysisDurationMultiplier = 0.5f; //SS220-rnd-reb
```

2023-11-03 20:38 UTC, DexlerXD commented on Content.Shared/Teleportation/Systems/SharedPortalSystem.cs
> +
```suggestion
        //SS220-rnd-reb
        if (HasComp<AnomalyComponent>(subject))
           _anomalySystem.DoAnomalySupercriticalEvent(subject);

```

2023-11-04 12:39 UTC, ZoNeSRuS commented on Content.Server/Anomaly/Components/AnomalyVesselComponent.cs
> +    public float PartRatingPointModifier = 1.5f;
Правильно ли я понял что ты уже подправил и мне ничего делать не надо? Если да, то спасибо, а то я как то спрашивал как подобные изменения оформлять и норм ответа не получил.

2023-11-04 15:22 UTC, ZoNeSRuS commented
Сделал правки исходя из ревью.

2023-11-04 16:00 UTC, merged