Фиксы и доработки функционала TTS
SerbiaStrong-220/space-station-14 pull request #50
Opened 2023-06-01 21:26 UTC by rincew1nd

## Описание PR
В TTSManager добавлена базовая синхронизация потоков. В случае разговора через рацию события генерации ТТСа отправлялись без задержки, что приводило к множественному запросы одних и тех же фраз.
Добавлена отдельная громкость для рации.
Изменения связанные с шепотом в ТТС, теперь громкость шепота будет уменьшаться по мере отдаления от источника до 6 тайлов.

**Проверки**
- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Rincew1nd
- add: Добавлена отдельная громкость для рации.
- tweak: Изменения шепота в ТТС. Громкость будет уменьшаться по мере отдаления от источника до 6 тайлов.

2023-06-01 21:58 UTC, Redict commented on Content.Server/Corvax/TTS/TTSManager.cs
> +        if (Monitor.TryEnter(_lockObject, TimeSpan.FromSeconds(_timeout)))
Нужны именованные локи по cacheKey

2023-06-02 00:44 UTC, rincew1nd commented on Content.Server/Corvax/TTS/TTSManager.cs
> +        if (Monitor.TryEnter(_lockObject, TimeSpan.FromSeconds(_timeout)))
Поправил

2023-06-04 12:23 UTC, SantaGitHub commented
А ты тестил? Приложи медиа к ПРу
Как хотфикс в принципе норм, но есть проблема, что у тебя для одного ключа будет большой список дедлоков.
Условно: кто то говорит в рацию. Нужно для 60 ентити сделать обработку TTS, ключ у всех будет один из-за чего у тебя накопится очередь из 60 потоков, которые друг за другом будут обрабатываться и обработка будет зависеть скорости от функционала твоего Func()

Наилучший подход - это если переделаем вызов этого ивента в RadioSystem

2023-06-04 22:47 UTC, Redict requested changes

2023-06-05 16:34 UTC, SantaGitHub commented on Content.Server/Corvax/TTS/TTSManager.cs
> +            Locks.TryRemove(key, out semaphore);
А смысл в удалении? Чтобы потом создать снова? (это в тему, что одна фраза может по несколько раз озвучиваться

2023-06-05 16:47 UTC, Redict commented on Content.Server/Corvax/TTS/TTSManager.cs
> +            Locks.TryRemove(key, out semaphore);
Я скорее о том, что твои изменения нужно произвести, а не это

2023-06-06 12:57 UTC, merged