Admin-ghost playtime tracker and command
SerbiaStrong-220/space-station-14 pull request #507
Opened 2023-11-06 13:16 UTC by DexlerXD

## Описание PR

Время, проведенное в агосте, теперь также считается в бд. Для админов добавлена команда `playtime_getaghost`, выводящая общее кол-во часов, проведенное в агосте определенным игроком.
**Медиа**

![изображение](https://github.com/SerbiaStrong-220/space-station-14/assets/69513582/22f2fc45-871a-429a-9ab4-5935c337546a)
![изображение](https://github.com/SerbiaStrong-220/space-station-14/assets/69513582/08c15884-818b-4898-ae3c-f3f69d8fe51f)
**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Dexler
- add: Добавлена админ команда playtime_getaghost, возвращающая время в часах, проведенное игроком в админ-госте.

2023-11-06 16:33 UTC, aw-c commented on Content.Server/Players/PlayTimeTracking/PlayTimeTrackingSystem.cs
> +                trackers.Add(AGhostTrackerTime);
Захардкожено конечно дай бог

2023-11-07 10:04 UTC, Werzet requested changes
Надо разобраться на счёт трекера времени. Мне вот сказали, что нужно добавить трекер только на время с включенной админкой, а агост не нужен, поэтому я добавлял AdminTrackerTime.

2023-11-12 13:17 UTC, Werzet requested changes

2023-11-12 13:17 UTC, Werzet commented on Content.Server/Players/PlayTimeTracking/PlayTimeTrackingSystem.cs
> +                return;
Думаю не стоит тут прерывать выполнение.

2023-11-12 13:17 UTC, Werzet commented on Content.Server/Administration/Commands/PlayTimeCommands.cs
> +using Content.Server.Players.PlayTimeTracking;
А тут можно убрать лишние изменения.

2023-11-12 13:17 UTC, Werzet commented on Content.Server/Players/PlayTimeTracking/PlayTimeTrackingManager.cs
> +using System.Diagnostics.CodeAnalysis;
И тут

2023-11-18 09:36 UTC, Werzet approved these changes

2023-11-18 23:22 UTC, TheArturZh requested changes

2023-11-18 23:22 UTC, TheArturZh commented on Content.Server/Players/PlayTimeTracking/PlayTimeTrackingSystem.cs
> +            if (player.AttachedEntity is { } attachedEntity &&
```suggestion
            if (player.AttachedEntity is { Valid: true } attachedEntity &&
```
На всякий случай, потому что у удаленных (невалидных) энтити нет метадаты

2023-11-19 12:22 UTC, TheArturZh approved these changes

2023-11-24 10:20 UTC, merged