Дельта апдейт
SerbiaStrong-220/space-station-14 pull request #515
Opened 2023-11-12 16:12 UTC by VladIsLove-e

## Описание PR

Шаттл карго был понерфлен, а так же декоративно изменён с целью соответствовать специфики работы утилей.
Допросные и мостик обзавелись таймерами.
Проводка инженера серьёзно изменена (не откажусь от критики).
Пилот получил свой шкаф и доступ к кораблю.
Криминалистическая консоль спрятана от юристов и АВД.
Клоуну стало куда легче сбегать из дурки, вентиляция теперь в каждой камере
Прочие мелкие изменения.

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2023-11-17 08:40 UTC, VladIsLove-e commented
Тесты сломаны или как? Пр неделю весит...

2023-11-19 04:56 UTC, Kit0vras requested changes
Подстанция на шаттле повёрнута не в ту сторону, нужно, чтоб было, как справа:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/88f48594-ce28-4098-ab74-c3cb8a47611d)

Провод у СМЭС сингулярности:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/c101a249-dbde-4c77-b025-45592dd3587d)

Нужно убрать угловой.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/79041b79-a66e-4f28-a9ea-990fdffe8967)

От комнаты ДАМ идут ВВ и СВ, но они ни к чему не подключены: (возможно, забыл убрать?)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/8199fa17-e03b-4818-a08b-81ecdf0e7476)

Спавнер пилота на шаттле работать не будет, так как у шаттла нет компонента BecomeStation - и ещё, кроме компонента, для этого грид с ролью нужно прописать в прототипе карты:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/cbe5a411-f4f6-485b-8c26-d57206465f15)

Под правой стеной оружейной ВВ идёт под стеной: (лица инженеров представили?)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/189b0cca-d4d2-499f-8781-6cb24682a506)

Неверно подключённая подстанция и СМЭС над оружейной (сначала подключается СМЭС, а от неё - подстанция, а тут она загнана в жуткий цикл - забирай энергию у станции, отдавай энергию станции)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/cd8d7b94-8b79-4b30-a546-332ddd204534)

Белые тайлы под решётками окон комнаты криоподов нужно заменить на покрытие:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/3d288104-342f-4cfb-9683-c65b42b827c2)

Не понёрфлен (вроде, говорили об этом? я уже и не помню):
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/a937cf59-ce78-4a3a-b754-1f5608ff1dff)

Целых 3 стака золота в хранилище (утили, идите нафиг):
По инструкциям, стоит размещать 1 стак золота, на деле - 1-2 в зависимости от станции, но не больше.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/5a05eef1-93ad-45d0-b836-56c2c4ffdb7c)

Т-труба в никуда в комнате под робототехникой:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/aa5e6b6c-a9b8-4c4d-82b9-4614d85c7cfb)

Кольца из проводов в вирусологии:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/9765a56f-c05c-4240-85c2-28a1b050ec9b)

Об этом точно говорили - куча аптечек, количество которых нужно понизить до 2 каждого вида, в крайнем случае - распределить между другими видами аптечек:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/cd3277e1-7027-4a92-ae9a-8421ffd32887)

Было бы хорошо переоборудовать в комнату с ресурсами для гейта слева и комнату с самим гейтом справа, так как их функционал уже реализован:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/062b74a6-e2ef-4fa7-a663-3b944f5ed35a)

Квадроцикл парамедика есть, а ключа к нему - я не нашёл:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/a31fdc8b-2a57-40a1-a568-428fd5c41454)

Стоит разместить доску заказов у кухни (у бара тоже можно):
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/81927962-180d-4459-b910-3829381c89cb)

Может, стоит всё же пощадить этих лягушек в карго и выдать им вентиляцию и скруббер?
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/af62104d-1ace-4102-b1e5-dc41e55dcd2d)

Заменить плитку под окном у стыковки карго на покрытие:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/bfeb8409-2a03-41b8-b1d4-eaa51ea3c8b9)

Не переименованная камера в комнате над СМЭСами инженерной:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/ee365feb-b431-4add-87d7-56d7b1eda69f)

Огромный список не переименованных камер в общем доступе - даже если это камера, смотрящая на голый коридор, её всё равно стоит переименовывать:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/9d796ece-4c37-4947-8ec2-b8f6c0a07b6d)

Две камеры в СБ:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/ac3e59a5-75cd-4ba7-aa36-34fca338257f)

Изменить плитку справа от двери к утилизаторам под окном на покрытие:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/8ebf43d2-67b1-4990-8495-65a132851ada)

У Утилей большая полупустая комната, и у них прямо здесь - стоит СМЭС и подстанция, почему-то в их доступе, прямо в комнате, а не закрыто в помещении с инженерным доступом. Кроме того, их же лкп в комнате питается от другой подстанции, а не их:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/3650df38-c8b1-4151-ad2b-3c189e204ca6)

Туалет капитана очень чистенький (это-то ладно, может, он следит за собой и даже моется?) и почему то имеет незапертую дверь, к тому же, в морозильную камеру:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/d3c52d55-c401-4d29-8450-33b7b0e74e2c)

Хотя специально для этого есть шлюз:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/579b4774-fb60-4206-9050-5f8189363100)

Консоль контроля питания в РнД не имеет ВВ кабеля под собой:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/654f9b9a-6e57-4a01-bf4d-c84e82352de9)

Изменить плитку под верхним окном на скриншоте, в атмосе, на покрытие:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/df017110-12a1-4e23-b7f6-7a28eafc42e2)

Висящий в воздухе светильник в комнате инженерных СМЭСов:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/71e463a4-bb4d-41ef-97c1-6fc754c10937)

Изменить плитку под окном в комнате СМЭСов на покрытие:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/5098b817-172c-43fe-a589-489f0af1a96b)

Просто как примечание: Можно было бы перевести на русский эти бумаги под библиотекой. Любители ДнД были бы рады.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/25fb5445-42c7-48d8-ad42-2634082b147f)

Отсутствующий скруббер в дормах:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/723d9d61-3563-49a7-b6b4-ef873e3bf8a4)

У НР на столе есть 4 кнопки, но они не подписаны и вообще не понятно, что они делают - стоит подписать:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/00aaa79d-79f4-448d-ab74-3bf12ac547e6)

Проверил, так и есть, + неверно повёрнутый лкп:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/17b1c722-ffda-40e7-878e-f247af03b1b0)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/7d44bdeb-3725-4e84-9793-168a707d94f7)

Исправить ошибку в названии факса сссп:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/51009de4-8c98-4b6d-966e-0c5f142c4870)

Стоит убрать доступ с красных шлюзов в прибытии слева, так как туда он тоже иногда стыкуется (да, не знаю, почему - возможно, его слоты чем то заняты). Никто доступа наружу не получит, так как стыковочные всё также будут заблокированы, а ещё - тут растения поверх шкафа и торгомата установлены:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/af405ca2-e95e-4b37-a4be-e0b1d7e951ca)

Шаттл так и не приобрёл никакой формы. Ещё я недоумеваю, почему с одной стороны гермы - сверху, а с другой - снизу? логичнее было бы, если бы они были симметричны. А ещё, заменить плитку под левым нижним окном внизу на покрытие:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/d672e55c-6f3a-441d-b062-522c4af0fcc0)

Почему нельзя было сделать по человечески - провести трубы по коридору и завести их в каждую палату ровненько, под стеклом, как делают все? А ещё, почти под всеми окнами расположена плитка, нужно заменить на пок [...]

2023-11-25 12:18 UTC, VladIsLove-e commented
Отвечая на ревью: вся проводка на карте будет под 0 снесена и перестроена, поэтапно, в будущих ПР-ах буду указывать уже сделанные отделы, внутри которых можно искать ошибки, так что отдельные провода китовара будут какое-то время на месте.
Пистолет был понерфлен.
Золото- в бородатые времена решилось игроками и админами в трекере, как и серебро
Чисто аптечек и так было уменьшено % на ~20
Гейт придёт с функционалом (от офов)
Лягушек пощадим в след. обнове
Камеры подпишем в след. обнове
Туалет капитана выглядит стильным, так и останется
В прибытии не в растениях проблема, а в продублированных шкафах, которые я уберу в след. обнове
Внешняя форма шаттла продиктована формой порта, тут его можно только уменьшать. По внутреннему убранству- скрины с предложениями в лс/важные вопросы приветствуются. Текущее положение гермозатворов- дизайнерское решение. Если игрокам на практике не понравится- будут симметрично. 
Трубы в дурке- сделаем новую схему + перестрою эту часть мед. отдела в след. обнове
Пиво- фича.

2023-11-25 12:31 UTC, Kit0vras commented
Уменьшение магазина на 9 патронов - это не нёрф.
Говорилось о стандартном пистолете с переименованием, с незначительным усилением при желании. Он всё также стреляет быстрее, чем пулемёт.

2023-11-25 12:32 UTC, Kit0vras commented
Насчёт пива и туалета я согласен, это выглядит больше как доёб

2023-11-25 12:34 UTC, Kit0vras commented
Уменьшено на 20% с какого времени? Насколько помню, оно не изменилось с того времени, как это обсуждалось. Я про аптечки в меде, если что вдруг.

2023-11-25 12:35 UTC, Kit0vras commented
Золото, шаттл - это ладно

2023-11-25 12:37 UTC, VladIsLove-e commented
> Уменьшение магазина на 9 патронов - это не нёрф. Говорилось о стандартном пистолете с переименованием, с незначительным усилением при желании. Он всё также стреляет быстрее, чем пулемёт.

33% и да, забыл тут упомянуть, но с тобой в лс же говорил- я сделаю новую пушку в принципе

2023-11-25 12:38 UTC, VladIsLove-e commented
> Уменьшено на 20% с какого времени? Насколько помню, оно не изменилось с того времени, как это обсуждалось. Я про аптечки в меде, если что вдруг.

сравнивая с тем, что сейчас на серверах.

2023-11-25 12:43 UTC, Kit0vras commented
> > Уменьшение магазина на 9 патронов - это не нёрф. Говорилось о стандартном пистолете с переименованием, с незначительным усилением при желании. Он всё также стреляет быстрее, чем пулемёт.
> 
> 33% и да, забыл тут упомянуть, но с тобой в лс же говорил- я сделаю новую пушку в принципе

А в чём проблема залить его и починить дополнительно коммитом мелочи вроде, к примеру, шкафов, камер в этом обновлении?

2023-11-25 12:46 UTC, VladIsLove-e commented
> > > Уменьшение магазина на 9 патронов - это не нёрф. Говорилось о стандартном пистолете с переименованием, с незначительным усилением при желании. Он всё также стреляет быстрее, чем пулемёт.
> > 
> > 
> > 33% и да, забыл тут упомянуть, но с тобой в лс же говорил- я сделаю новую пушку в принципе
> 
> А в чём проблема залить его и починить дополнительно коммитом мелочи вроде, к примеру, шкафов, камер в этом обновлении?

потому что я только сегодня узнал, что даже если тесты сломаны- можно мёрджить, так что сегодня я ничего не делал, а завтра работа. заняться дельтой я смогу только в след. воскресенье. так что либо мёрдж либо ещё неделю ждём. последняя фраза уже месяц повторяется, к слову

2023-11-25 13:39 UTC, DexlerXD approved these changes

2023-11-25 13:52 UTC, merged