Фикс сумок сб+ ивент
SerbiaStrong-220/space-station-14 pull request #516
Opened 2023-11-12 16:32 UTC by VladIsLove-e

## Описание PR

Вещмешки и сумки СБ имели отличное снаряжение от рюкзаков сб, этот момент исправлен.
Так же изменена текстура ивентового предмета и добавлен новый- энерго сабля

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2023-11-13 00:41 UTC, DexlerXD requested changes
Знаю, что в репо и так насрано плащами ксено, но  `e_saber.rsi` тоже чеки роняет...

2023-11-13 00:44 UTC, DexlerXD commented
Также на будущее: изменение прототипов и добавление чего-то нового должно быть в разных пр'ах по хорошему

2023-11-13 10:43 UTC, VladIsLove-e commented
> Знаю, что в репо и так насрано плащами ксено, но `e_saber.rsi` тоже чеки роняет...

На локалке всё норм, не имею представления в чём проблема

2023-11-13 12:39 UTC, Kit0vras commented
> > Знаю, что в репо и так насрано плащами ксено, но `e_saber.rsi` тоже чеки роняет...
> 
> На локалке всё норм, не имею представления в чём проблема

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/f8053aa3-839f-490e-81f9-9975377c5750)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/8d19231c-672c-4f5a-b860-4a4786a2fccc)

2023-11-25 11:18 UTC, DexlerXD approved these changes

2023-11-25 11:19 UTC, merged