Avrit map
SerbiaStrong-220/space-station-14 pull request #527
Opened 2023-11-17 07:52 UTC by spo9k

## Описание PR
Аврит, возможно кто ждал.

**Медиа**

**Проверки**

- [+/-] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [+] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [+] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [-] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
- add: Добавлен Синий Щит, комната для него.
- add: Добавлен БригМедик, и всё для него.
- add: Добавлены КриоПоды
- add: Добавлены копированные аппараты

 :cl: spook

2023-11-17 08:07 UTC, FriedrichStrassen commented
Пилота добавь. к нему всё есть

2023-11-17 19:39 UTC, spo9k commented
@FriedrichStrassen  Забыл дописать, пилот есть. ( Добавлен )

2023-11-20 10:56 UTC, Kit0vras requested changes
Карты нет в пуле.

ID карты стоит изменить с SS220Avrite на 220Avrite, как у остальных портированных станций.

На карте СЛИШКОМ переборщили с количеством светильников, и так это и не исправили. По крайней мере, на перекрёстках стоит снизить кол-во ламп с 4 до 2.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/7c2e6aad-a478-4e35-967a-f66e717641a4)

В остальных комнатах тоже много где установлено больше светильников, чем хотелось бы - там, где стоит 3 светильника, можно обойтись и одним. Стоило бы пересмотреть освещение.

Заменить плитки на покрытие под окном у инженерного склада, перед входом в инженерку.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/a4e7ebe5-ac06-4537-a85e-9c83d38bc0b8)

У репортёров, выше этого склада, сломана труба с вентиляцией.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/c7cf409a-b92a-4a2f-90ea-9db440e16da6)

Неверно настроена карта камер - во первых, её нужно делать через рендер, после чего уменьшить в ~5 раз и настроить её положение (с этим обратись ко мне в лс, я постараюсь помочь)

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/7397d742-854f-4649-a7c3-ba2c9f813c04)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/dffaeb93-3115-4382-9e1e-031bdc43763f)

Чем делать это под армированной стеной, проведи НВ кабель у ОСЩ из коридора слева. Если хочется больше защиты - тогда поставь личный лкп.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/e31c57c7-6a74-492e-bfbe-291d34880f65)

Заменить всю плитку под окнами мостика на покрытие.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/528b0680-924c-4ed9-b274-a6f62584edd0)

И под окнами входов тоже:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/72c4766a-8fbc-49bc-b8d8-64ccb02c3de8)

Печать капитана нужно убрать - она хранится в его шкафу, и второй существовать не должно.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/4e5c1782-799f-4174-9104-68edf3000f33)

Заменить плитку на покрытие под окнами конференц-зала.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/1ea46887-f8a3-4ec8-bf63-866fc0e03e71)

Вообщем, с тайлами под окнами тут много где накосячили, так что проще будет потыкать покрытием по всем окнам, где заметишь светлые пиксели сквозь решётку.

Охладитель из морозилки нужно подключать к пассивной вентиляции, в то время как обычная вентиляция не должна к нему подключаться, иначе он будет охлаждать всю дистру.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/7aa8ade2-922c-4d01-8efa-12340ee6f1f5)

Нет стола под электрогрилем на кухне.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/09891dc1-8482-4623-88f5-6052b52bb1a5)

Может, я чего-то не понимаю, но зачем на КПП эвакуации у сб 4 (!!!) консоли ID-карт, когда это "имущество" мостика и ГП? Во первых, облегчает задачу антагонистам, во вторых - стоило бы заменить на консоль криминальных записей, монитор камер, всё такое.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/34f2ab8c-6a38-4180-b24c-236b4bab5286)

На сингулярности кабель идёт почему-то через окно, хотя может идти через шлюзы.
Также энергосеть выстроено неправильно, зацикливая СМЭСы. Должен идти 1 кабель на питание СМЭСов, и второй - на потребление от них к подстанции, и они не должны пересекаться, как это сделано сейчас.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/86a92407-bbb9-46ac-92f5-ed8e1783e814)

С печатью КМа тоже самое, она уже есть в шкафу.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/1c50bc45-af00-4e48-ad1a-85e85b9e5ee1)

Нижние техи под медом: Для этого есть шлюз, но ВВ почему то идёт через стену.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/d1534033-4644-430f-bf25-95d3e1baeaad)

Печать главы персонала также хранится у него в шкафу.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/d7fd83df-a9a7-4fba-84ba-80068e528b78)

В кустах в коридоре под камерами заключения сб лежит спонсорский плащ, как мне говорили, такое делать низя.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/c6487a28-7dee-4e65-9ea6-06711ab341e4)

В комнате криоподов нужно заменить плитку на покрытие под окнами, а ещё поставить под них решётку:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/4b6bc0ea-3545-42f9-99cd-dc2efac75d05)

Есть комната пилота, но я не нашёл шкафа пилота и листочка с его брифингом. Спавнер роли, вероятно, тоже стоило бы переместить в его комнату.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/b734168c-6bcc-4f28-9241-6a2f81c7e1ce)

Вот тут, я бы сказал, не побоюсь этого слова, насрано:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/879a4033-db17-4540-8304-b8674131f75f)

Имбовый жилет с 70% защитой от пуль:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/c9edeaaf-9f2c-4e84-b734-22b2cbebfb5f)

И в остальном - лута на 6 тк (диск можно оставить, но сигареты, магазин и ева - жирно, как мне кажется. Да и хим-раздатчик тоже)

Подправить неграмотный текст на памятнике, который находится в левой части карты.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/e42994ce-58c6-4cab-b76c-682621f50cd3)

Эти раздвижные окна у бармена выглядят супер-странно, потому что зачем они, если к нему можно просто перелезть через стол?
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/af61342a-b6b9-4769-8905-e89efabf03c6)

В таком случае, было бы логично сделать, ну, что-то такое:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/5803ee1e-e4ba-465b-ae21-6e02c2f4f445)

Почему у детектива медицинская койка? приходи, ложись, лечись? Стоит заменить на обычную кровать.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/bc48b28e-e66b-4a46-9539-5951d04a9fd9)

Спонсорский плащ в атмосе.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/70b316e2-c147-44bd-8592-213d7912fad4)

Слева от ботаники - Цифровая звуковая рабочая станция, которая находится в чёрном листе, так как это - исследование хай-тира музыки РнД.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/7b088196-8bc4-4349-82b9-70d78c1ce1f1)

Дубли варп-поинтов для гостов:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/59e0273b-8751-4289-b8b4-b62ddba1b3cc)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/62906e95-f7df-479b-aa0b-69808e8d7e27)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/0d0b59a2-be35-40ca-a236-3a66875b03c7)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/bcaddecc-76e9-477a-bf14-8d5711e8a5cc)

Каторга: Скафандры для рабочих (обычная EVA) стоило бы заменить, как мне кажется, на тюремные EVA, это ведь каторга для заключённых.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/3116320d-9024-4bf9-99c9-a924e8663888)

Спонсорский комбинезон скелета справа от комнаты НР.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/dbe44a87-8f73-49b8-aeeb-2495305292e5)

Шахтёрский аванпост: 4 усиленных скафандра, которые охраняются 1 карпом и 1 клопом, тоесть, получить их ооочень легко, так что я даже не знаю - мне кажется, стоит или забалансить, или повысить опасность.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/44c934c2-d5f4-4e1a-9e24-28b73af6f193)

Торговый аванпост: Накакано камнями по несколько штук в тайле.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/9254a4b9-6b92 [...]

2023-11-20 11:09 UTC, Kit0vras commented
Насчёт вопросов, помощи, уточнений, советов, оспаривания пункта и т.д и т.п, - пиши либо сюда, либо в лс, отвечу почти в любое время.

2023-12-08 16:10 UTC, DexlerXD requested changes

2023-12-08 16:10 UTC, DexlerXD commented on Content.IntegrationTests/Tests/PostMapInitTest.cs
весь файл изменяется, надо пофиксить

2023-12-09 11:12 UTC, spo9k commented
@DexlerXD поменял формат в LF

2023-12-09 12:02 UTC, DexlerXD approved these changes

2023-12-09 12:03 UTC, merged