Переименование вещей синдиката, чтобы это не мешало РП и антуражу игры
SerbiaStrong-220/space-station-14 pull request #536
Opened 2023-11-25 16:57 UTC by AlexandrSTG

## Описание PR
Я изменил названия и описания предметов для Агентов синдиката, чтобы в них было меньше меты, а сам их просмотр обычны членом экипажа не разрушал атмосферу для играющего и не портил "сюрприз". Сделанная работа заменяет большинство названий и описаний вещей агентов на более безобидные, для СБ же, чтобы обнаружить неладное в вещи, придется тщательно вчитаться в описание вещи.
Отпечатки перчаток ниндзя и хамелионных перчаток заменены на другие, чтобы подходить антуражу.
Добавлен предмет для мапперов: фейковый ЕМАГ, который не работает и называется "Модифицированная ID карта"
В аплинке некоторые описания предметов были заменены для того, чтобы новые описания

**Медиа**
[Залил видео с тем как все это выглядит в игре](https://youtu.be/SH8mpjyGuXA)
![изображение](https://github.com/SerbiaStrong-220/space-station-14/assets/58810935/35d5311f-94ad-4252-bda8-372fdf323add)
![изображение](https://github.com/SerbiaStrong-220/space-station-14/assets/58810935/82e84c96-8ae6-47f4-9e0f-e2bb4de1cca5)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншоты/видео демонстрации PR в игре.

**Изменения**
add: Добавлены суффиксы прототипам, название которых были изменены, чтобы их было можно найти по старому названию в игре для щитспавна. Добавлены суффиксы прототипам, названия которых не были затронуты по той же причине.
аdd: Добавлена в прототипы "модифицированная ID карта" для мапперов, которая выглядит как "криптографический секвенсор", с тегом "фейк, fake". Она ничего не делает.

tweaks:
Вещмешки синдиката, хирургический набор и т.д. были переименованы на:
черно-красный вещмешок ent-ClothingBackpackDuffelSyndicate
Вместительный и удобный вещмешок цвета эбонита и крови, в который влезут «игрушки» для любых возрастов.
черно-красный вещмешок с эмблемой ent-ClothingBackpackDuffelSyndicateAmmo
Вместительный и удобный вещмешок цвета эбонита и крови с эмблемой огнестрельного орудия.
медицинский черно-красный вещмешок ent-ClothingBackpackDuffelSyndicateMedical 
Вместительный и удобный вещмешок с красной эмблемой "Звезды жизни" цвета эбонита и крови. Интересно, его хозяин соблюдает клятву Гиппократа?

Вещи наследующие их названия копируют описание и названия вещмешков выше:
вещмешок пижам синдиката ClothingBackpackDuffelSyndicatePyjamaBundle с дополнительным описанием
Вещмешок синдиката ClothingBackpackDuffelSyndicateAmmo с дополнительным описанием
Хирургический вещмешок синдиката ClothingBackpackDuffelSyndicateMedical
Набор медицины ClothingBackpackDuffelSyndicateFilledMedical
Вещмешок костюма карпа ClothingBackpackDuffelSyndicateCarpSuit
Вещмешок синдиката ClothingBackpackDuffelSyndicate
Зомби набор синдиката ClothingBackpackDuffelZombieBundle
Набор C-4 синдиката ClothingBackpackDuffelSyndicateC4tBundle
Набор Eva синдиката ClothingBackpackDuffelSyndicateEVABundle
набор "C-20r" ClothingBackpackDuffelSyndicateFilledSMG
набор "China-Lake" ClothingBackpackDuffelSyndicateFilledGrenadeLauncher
набор "L6 Saw" ClothingBackpackDuffelSyndicateFilledLMG
набор "Бульдог" ClothingBackpackDuffelSyndicateFilledShotgun
набор медикаментов ClothingBackpackDuffelSyndicateMedicalBundleFilled

Ренеймы обычных вещей:

	Шприц ромерола SyringeRomerol
_Имеет перессылку на обычное описание и название шпритца_
	
	персональный ИИ Синдиката SyndicatePersonalAI
_персональный ИИ 
Новейшая модель вашего электронного друга! Теперь веселье засияет новыми Красками!_ 

	плечевая кобура синдиката ClothingBeltSyndieHolster
_алая плечевая кобура
Глубокая плечевая кобура, способная вместить множество различных видов оружия, боеприпасов._ 

	Перчатки Полярный звезды ClothingHandsGlovesNorthStar
_пара сине-белых перчаток ClothingHandsGlovesNorthStar
Чувствуется какая-то легкость рук, когда держишь их. При одевании их, хочется сжать пальцы в кулак, будто они засияют как звезда, и вы невольно захотите сказать: «Омаева му шиндеру…» — когда кто-то падёт от вашей руки._

	криптографический секвенсор Emag
_модифицированная ID карта
Зачем кому-то портить ID карту? Она вообще работает? Еще и провода из нее торчат... лучше её не трогать._
	
	минибомба синдиката SyndieMiniBomb
_минибомба с таймером  
Аккуратное, стильное взрывное устройство с приятно-потрескивающим таймером, предназначенное сеять хаос и разрушение._
	
	бомба Синдиката SyndicateBomb
_БОМБА
Это бомба с таймером! Она тикает? Вы хотели стать героем!? Самое время!_

	челюсти жизни синдиката SyndicateJawsOfLife
_алые челюсти жизни
Набор челюстей жизни, скомпонованных при помощи магии науки. Окрашены в цвета алой крови.
святая граната HolyHandGrenade_
	
	Святая бомба
	_светящаяся благословлённая держава 
«Благослови, Господи, свою ручную гран... ой, державу, каковою можешь Ты в своей милости разносить врагов Твоих на маленькие кусочки»._

	ВСЕ О СИГВЕЕ СИНДИКАТА:
	В аплинке:
```
uplink-syndicate-segway-crate-name = стильный алый сегвей Синдиката
uplink-syndicate-segway-crate-desc = Алый цвет, красивый и брутальный узор на шинах, стильные диски... вы знаете на чем вы будете уезжать от ядерного взрыва! Будьте врагом корпорации на стиле! Поставляется в ничем непримечательном ящике для перевоза скота. 
```

	сегвей синдиката VehicleSyndicateSegway
_стильный алый сегвей
Алый цвет, красивый и брутальный узор на шинах, стильные диски... вы знаете на чем вы будете уезжать от ядерного взрыва._
	
	ключ от сегвея синдиката VehicleKeySyndicateSegway
_ключ от алого сегвея
Сам ключ предвкушает отличную поездку с ветерком. Узор на бирке ключа выполнен стильно и минималистично._
	
	Ящик с Сегвееем Синдиката CrateFunSyndicateSegway
Стало копировать название и описание «Ящик для скота», но в описании добавлено «На дне видны следы от колес»

	обезвоженный космический карп DehydratedSpaceCarp
Теперь имеет имя и описание плюшевой игрушки, но к описанию добавил «Кажется или оно дышит?»
	В аплинке пришлось заменить название и описание
`uplink-carp-dehydrated-desc = Выглядит как обычная игрушка карпа! Однако стоит добавить воды и тут же он начнет кусать все подряд! Хоть он и не двигается, но все слышит и чувствует._
`
	скафандр EVA синдиката ClothingOuterHardsuitSyndicate
_Алый скафандр EVA_ 
Копирует описание и имя обычной белой ЕВЫ, но с дополнительным оригинальным описанием «На бирке написано 'Совершенно не собственность вражеской корпорации, честно!'».
	шлем синдиката ClothingHeadHelmetSyndicate
_стильный шлем
Стильный, герметичный, прочный шлем._
	противогаз синдиката ClothingMaskGasSyndicate
_Черный боевой противогаз
Высокотехнологичный противогаз с возможностью подключить его к баллону, разработанный специально для борьбы в тяжелых условиях! Теперь с функцией защиты для глаз!_

	бутылочка ноктюрина NocturineChemistryBottle
Сделал так, что она копирует описание и название обычной бутылочки.
	
	глушитель связи RadioJammer
Теперь копирует название и описание оценочного аппарата, к описанию добавляется «Устройство имеет огромную антенну и сменный аккумулятор.»

	коробка ключей шифрования синдиката BoxEncryptionKeySyndie
Стала «коробка ключей шифрования», копирует описание коробки ключей шифрования.

	Комбенизон оперативника ClothingUniformJumpsuitOperative
_комбинезон специальных операций
Униформа для тех, кто участвует преступных или не очень операциях в глубоком космосе._ 

	юбка-комбинезон оперативника ClothingUniformJumpskirtOperative
юбка-комбинезон специальных операций
Копирует название у комбенизона оперативника
	
	поглотитель энергии PowerSink
_Большое устройство с консолью
Устройство. Какие-то светодиоды, индикаторы... экран с процентной шкалой прогресса... крепления... что оно вообще делает? Определенно не стоит совать в него свою руку._
в аплинке поменял на:
`uplink-power-sink-name = Устройство поглощения энергии`

	аплинк синдиката BaseUplinkRadio 
_старое радио
Винтажное радио, которое по никому не ясной причине застыло на крайне необычной частоте, со словом  [...]

2023-11-25 17:00 UTC, AlexandrSTG commented
Ну, вроде все. Немного напортачил с описанием ПР, так как с редактированием в гите не работал. Надеюсь, что многие останутся довольны изменением

2023-11-25 17:12 UTC, AndreyKostenkoS commented
А одобрение от Адуча или Сандея было?

2023-11-25 17:27 UTC, ZoNeSRuS commented
Смотри, у нас ПР анти мета, но ты сам своими описаниями создаешь новую мету. Не нужно думать за игрока о писании. Я про: 
1. "При одевании их, хочется сжать пальцы в кулак, будто они засияют как звезда, и вы невольно захотите сказать: «Омаева му шиндеру…» — когда кто-то падёт от вашей руки."
2. "кто участвует преступных или не очень операциях в глубоком космосе."
С перчатками подумай, а комбез просто опиши как одежду спец войск.

Я понимаю что это сделает описание более суховатым, но оно должно описывать предмет когда держишь его в руке, а не генерировать мысли читающего.

2023-11-25 17:27 UTC, ZoNeSRuS commented
> А одобрение от Адуча или Сандея было?

Да, карточка на мне.

2023-11-25 17:39 UTC, Kit0vras requested changes

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/backpacks/duffelbag.ftl
> +    .desc = { ent-ClothingBackpackDuffelSyndicate.desc } Имеет этикетку с изображениями карпов и буквой «S», на ней написано: «Будь извилистым как карп, кусай за самое больное!».
Что думаешь насчёт пунктуации, может, так красивше выйдет?
```suggestion
    .desc = { ent-ClothingBackpackDuffelSyndicate.desc } Имеет этикетку с изображениями карпов и буквой «S», на которой написано: «Будь извилистым, как карп - кусай за самое больное!».
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/backpacks/duffelbag.ftl
> +    .desc = { ent-ClothingBackpackDuffelSyndicate.desc } Имеет этикетку с изображением кулака вверх и буквой «S», на ней написано: «Хороший сон - хорошо выполненный план!».
```suggestion
    .desc = { ent-ClothingBackpackDuffelSyndicate.desc } Имеет этикетку с изображением кулака вверх и буквой «S», на которой написано: «Хороший сон - хорошо выполненный план!».
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/belt/belts.ftl
> +    .desc = Глубокая плечевая кобура, способная вместить множество различных видов оружия, боеприпасов.
```suggestion
    .desc = Глубокая плечевая кобура, способная вместить множество различных видов оружия и боеприпасов.
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/hands/gloves.ftl
> +    .suffix = перчатки Полярный звезды
```suggestion
    .suffix = перчатки Полярной звезды
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/hands/gloves.ftl
> +    .desc = Чувствуется какая-то легкость рук, когда держишь их. При одевании их, хочется сжать пальцы в кулак, будто они засияют как звезда, и вы невольно захотите сказать: «Омаева му шиндеру…» — ко
Подумай над этим вариантом:
```suggestion
    .desc = Вы чувствуете необычную лёгкость в руках, когда держите их. При их одевании вам хочется сжать пальцы в кулак, будто они должны засиять, как звезда, и невольно сказать: «Omae wa mou shindeiru…» - в то время, когда кто-то уже падёт от вашей руки.
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/masks/masks.ftl
> +    .desc = Высокотехнологичный противогаз с возможностью подключить его к баллону, разработанный специально для борьбы в тяжелых условиях! Теперь с функцией защиты для глаз!
А к чему тут восклицание? возможно, можно использовать во втором предложении, если переиначить на "Теперь -".
```suggestion
    .desc = Высокотехнологичный противогаз с возможностью подключить его к баллону, разработанный специально для борьбы в тяжелых условиях. Теперь с функцией защиты для глаз.
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
> +    .desc = Униформа для тех, кто участвует преступных или не очень операциях в глубоком космосе.
```suggestion
    .desc = Униформа для тех, кто участвует в преступных или не очень операциях в глубоком космосе.
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
> +ent-SyndiPDA = Кроваво-красный КПК
```suggestion
ent-SyndiPDA = кроваво-красный КПК
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
> +    .desc = КПК вызывающий учащение пульса, когда на него смотришь... будто бы его держал военный преступник.
Не уверен насчёт того, не создал ли я здесь тавтологию, но подумай над этим вариантом:
```suggestion
    .desc = КПК, вызывающий у вас учащение пульса, когда вы смотрите на него... Будто бы его держал военный преступник.
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/power/powersink.ftl
> +ent-PowerSink = Большое устройство с консолью
```suggestion
ent-PowerSink = большое устройство с консолью
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/power/powersink.ftl
> +    .desc = Устройство. Какие-то светодиоды, индикаторы... экран с процентной шкалой прогресса... крепления... что оно вообще делает? Определенно не стоит совать в него свою руку.
Хаха, отсылку понял
```suggestion
    .desc = Устройство. Какие-то светодиоды, индикаторы... Экран с процентной шкалой прогресса... Крепления... Что оно вообще делает? Определенно не стоит совать в него свою руку.
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/syndicate.ftl
> +ent-Telecrystal = Кроваво-красный кристалл
```suggestion
ent-Telecrystal = кроваво-красный кристалл
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/syndicate.ftl
> +    .desc = Пульсирует будто человеческое сердце и сияет словно рубин. Интересно, для чего он нужен?
```suggestion
    .desc = Пульсирует, будто человеческое сердце и сияет, словно рубин. Интересно, для чего он нужен?
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/vehicles/buckleable.ftl
> +    .desc = Алый цвет, красивый и брутальный узор на шинах, стильные диски... вы знаете на чем вы будете уезжать от ядерного взрыва.
```suggestion
    .desc = Алый цвет, красивый и брутальный узор на шинах, стильные диски... Вы знаете, на чём будете уезжать от ядерного взрыва.
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/bombs.ftl
> +ent-SyndicateBomb = БОМБА
Почему? Зачем акцентировать внимание капсом? может лучше просто
```suggestion
ent-SyndicateBomb = бомба
```
бомба и бомба, чё бубнить то. А, если она тоже учебная, то можно использовать { ent-TrainingBomb }. (Не юзал, не знаю)

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-carp-dehydrated-desc = Выглядит как обычная игрушка карпа! Однако стоит добавить воды и тут же он начнет кусать все подряд! Хоть он и не двигается, но все слышит и чувствует.
```suggestion
uplink-carp-dehydrated-desc = Выглядит, как обычная игрушка карпа. Однако, стоит добавить воды и он тут же начнет кусать все подряд. Хоть он и не двигается, но все слышит и чувствует.
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-nocturine-chemistry-bottle-desc = Высокоэффективное снотворное и гипнотическое средство, разработанное Синдикатом для тайных операций. Билет в один конец в хонкоград. Поставляется в бутылочке
```suggestion
uplink-nocturine-chemistry-bottle-desc = Высокоэффективное снотворное и гипнотическое средство, разработанное Синдикатом для тайных операций. Билет в один конец в хонкоград. Поставляется в бутылочке на 30u. (Не выпейте его случайно, если перепутаете бутылочки.)
```

2023-11-25 17:39 UTC, Kit0vras commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-syndicate-segway-crate-desc = Алый цвет, красивый и брутальный узор на шинах, стильные диски... вы знаете на чем вы будете уезжать от ядерного взрыва! Будьте врагом корпорации на стиле! Постав
```suggestion
uplink-syndicate-segway-crate-desc = Алый цвет, красивый и брутальный узор на шинах, стильные диски... вы знаете, на чем вы будете уезжать от ядерного взрыва. Будьте врагом корпорации на стиле! Поставляется в ничем непримечательном ящике для перевоза скота.
```

2023-11-25 18:06 UTC, VladIsLove-e commented
"При одевании их, хочется сжать пальцы "
Одевают кого-то, надевают что-то

2023-11-25 18:13 UTC, VladIsLove-e commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/backpacks/duffelbag.ftl
> +    .desc = { ent-ClothingBackpackDuffelSyndicate.desc } Имеет этикетку с изображениями карпов и буквой «S», на ней написано: «Будь извилистым как карп, кусай за самое больное!».
и правильнее

2023-11-25 18:20 UTC, DexlerXD requested changes
Чейнджлист перенести, так как в `add` и `tweak` должны быть краткие описания, которые будет отображаться в чейнджлоге в игре.
Вообще все, что идет после слова `Изменения`, должно быть по шаблону.

2023-11-25 19:10 UTC, AlexandrSTG commented
>     1. "При одевании их, хочется сжать пальцы в кулак, будто они засияют как звезда, и вы невольно захотите сказать: «Омаева му шиндеру…» — когда кто-то падёт от вашей руки."
Перчатки полярной звезды являются отсылкой. Я не знаю, как тут поступить, если честно. По хорошему просто можно убрать описание вообще. Но мне 5 людей доказывали, что это нужно оставить. Я и оставил в такой манере. 

>        С перчатками подумай, а комбез просто опиши как одежду спец войск.
Я лично считаю, что стёб, преукрашивание очень уместна в предметах. Вся игра буквально из этого состоит 
> Очевидно, что к гранате которая является мемом сама по себе - это не относится.
Ну... а перчатки не мем?

2023-11-25 19:17 UTC, AlexandrSTG commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/masks/masks.ftl
> +    .desc = Высокотехнологичный противогаз с возможностью подключить его к баллону, разработанный специально для борьбы в тяжелых условиях! Теперь с функцией защиты для глаз!
Потому что это будто слоган из глупой рекламы. "Теперь еще больше!!!!" 
С первой точкой согласен, со второй нет.

2023-11-25 19:26 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/masks/masks.ftl
> +    .desc = Высокотехнологичный противогаз с возможностью подключить его к баллону, разработанный специально для борьбы в тяжелых условиях! Теперь с функцией защиты для глаз!
Да, сделай
Теперь - с защитой для глаз!

2023-11-26 14:07 UTC, DexlerXD approved these changes

2023-11-26 14:08 UTC, merged

2023-11-26 17:37 UTC, AlexandrSTG commented
> > "При одевании их, хочется сжать пальцы " Одевают кого-то, надевают что-то
> 
> Так ошибку бы исправить.

Упс. Забыл в изменениях уточнить то, что исправлено. Зонес мне сказал убрать мета-описание. Оно было убрано. Осталось первое предложение только, и то изменённое.