Syndie thing rename 2, missing translates
SerbiaStrong-220/space-station-14 pull request #552
Opened 2023-12-02 23:06 UTC by AlexandrSTG

## Описание PR

Кратко: добавлены новые названия вещей Cиндиката для мета-защиты, добавлены переводы (вещей и гост-ролям), исправлены ошибки в газировке "РПГ".
Были переименованы и исправлены вещи с их описанием для Синдиката с прошлого обновления. В том числе и грамматические ошибки и не изящные описания. Что-то изменилось и вот что:

перчатки Полярной звезды
```
пара сине-белых перчаток 

Одев их, можно с уверенностью чувствовать себя жестоким и брутальным героем из аниме-сериалов.

```

комбинезон/юбка-комбинезон специальных операций -> комбинезон/юбка-комбинезон оперативника
_да, было неудачное название, вернул как было._

КПК Синдиката
```
кроваво-красный КПК

Смотря на этот КПК, ваше сердцебиение учащается... cловно его владелец совершил нечто ужасное.
```

сегвей синдиката
Описание: 
**было:** Алый цвет, красивый и брутальный узор на шинах, стильные диски... Вы знаете, на чём будете уезжать от ядерного взрыва!
**стало:** Красный цвет, брутальный узор протекторов, стильные диски... Вы знаете, на чём будете уезжать от ядерного взрыва!

Ключ от Синдикатского сегвея:
Описание:
**Было:** Сам ключ предвкушает отличную поездку с ветерком. Узор на бирке ключа выполнен стильно и минималистично.
**Стало:** Предвещает поездку с ветерком! Узор на бирке ключа выполнен минималистично, но со стилем.

некрономикон
```
древний фолиант
Имеется пометка: Klatuu, Verata, Nikto  – Не забыть об этом опять!
```
Радио Аплинк и вещмешок одиного оперативника теперь копируют названия обычных оперативников.

Святая граната
Название: 
светящаяся благословлённая держава -> благословлённая держава

И т.д.

**Добавлены переводы:** 
- КПК пирата: "ЯРГХХ!!!"
- ядро аномалии: "Ядро аномалии от неописуемого объета. Успей продать пока не остыло! Если оно вообще теплое... и можно его подобрать."
- визер Синдиката (худ свой-чужой)
- скафандр парамедика
- СВУ из банки
- переводы гост-ролей (о них далее)

Для гост-ролей:
Агент Синдиката
Описание:
Вы натренерованный Агент Синдиката, посланный на задание по помощи другим Агентам. Вам плевать на свою жизнь и вы готовы сделать все, что прикажет вызвавший вас Агент.
Правила:
Вы Агент Синдиката. В ваши обязанности входит помочь Агенту Синдиката, который вас вызвал. Вам запрещено выдавать свою или чужую причастность к Синдикату. Вы готовы выполнить все приказы призвавшего вас на помощь Агента, которые не нарушают правила сервера.

Обученный Агент Макака Синдиката
Описание роли:
Вы тренерованная разумная макака или же Агент Синдиката, посланная на задание на помощь другим Агентам. Будьте послушной и тогда вас наградят вкусным-вкусным лакомством. Не позвольте другой стороне переманить вас бананом на свою сторону.
Правила:
Вы Агент Синдиката. В ваши обязанности входит помочь Агенту Синдиката, который вас вызвал. Вам запрещено выдавать свою или чужую причастность к Синдикату. Вы готовы выполнить все приказы призвавшего вас на помощь Агента, которые не нарушают правила сервера.

Космический ниндзя
Описание:
Клан Паука послал своего нового бойца на испытательное задание. Используйте свои навыки, оттачиваемые с рождения, для скрытного выполнения целей поставленные кланом.
Правила:
Вы космический ниндзя, посланный своим кланом для выполнения целей. Сделайте это тихо и скрытно. Сделайте все, что возможно, чтобы выполнить их, не нарушая правила сервера.

Всеми любимая газировка ВладИзЛава: 
Расслабляющая Персиковая Газировка
Описания:
**Было:** Ходят слухи, что ежедневное употребелнние данного напитка уменьшает риск возникновения такой срашной болезни как щиткурство. Но это лишь слухи
**Стало:** Ходят слухи, что ежедневное употреление данного напитка сделает вас добрее и эмпатичнее к окружающим. Но это лишь слухи! Продается под взрывной маркой "РПГ"!

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: AlexandrSTG
- add: новые переводы для ядер аномалий, пустотного скафандра парамедика, пиратов, визора Синдиката и т.д.
- tweak: Исправлены старые ошибки ренейма Синди предметов для антуража и атмосферы. Изменены названия предметов, что не вошли в прошлое обновление.
- tweak: исправлено описание газировки РПГ для антуража и атмосферы (и грамматических ошибок).
- add: Добавлены переводы гост-ролям ниндзя, агентов Синдиката подкрепления и обезьяньего подкрепления.
<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2023-12-03 10:54 UTC, DexlerXD requested changes

2023-12-03 10:54 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
> +    .desc = Смотря на этот КПК, ваше сердцебиение учащается. Словно его владелец совершил нечто ужасное.
```suggestion
    .desc = Смотря на этот КПК, ваше сердцебиение учащается... Словно его владелец совершил нечто ужасное.
```
мне кажется, троеточие стоит оставить

2023-12-03 14:29 UTC, AlexandrSTG commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/devices/pda.ftl
> +    .desc = Смотря на этот КПК, ваше сердцебиение учащается. Словно его владелец совершил нечто ужасное.
Исправил.

2023-12-04 19:53 UTC, DexlerXD requested changes
у тебя мерж конфликты, решай

2023-12-06 19:21 UTC, AlexandrSTG commented
> у тебя мерж конфликты, решай

Я сделать фикс. Фикс пройти. Фикс проверяться. Граматика надо проверить. Хозяину нравицца?

2023-12-06 19:48 UTC, DexlerXD approved these changes

2023-12-06 19:48 UTC, merged