Smart fridge
SerbiaStrong-220/space-station-14 pull request #555
Opened 2023-12-03 14:13 UTC by SkaldetSkaeg

## Описание PR

Добавлена отдельная модель умного холодильника (SmartFridge [SS220]) учитывающего указанные в задаче функционал:
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/30115570/368b1f5b-40ef-4fe1-8c6b-e64994879e26)
**Медиа**

<img width="146" alt="image" src="https://github.com/SerbiaStrong-220/space-station-14/assets/30115570/cab3e965-2303-4dbd-b166-0ef17c989674">
<img width="457" alt="image" src="https://github.com/SerbiaStrong-220/space-station-14/assets/30115570/6de52cb6-c4ff-4f32-90ee-ff11381cbc1f">
<img width="242" alt="image" src="https://github.com/SerbiaStrong-220/space-station-14/assets/30115570/31bc89a1-189e-4f72-bd82-3f7d40e76a88">

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

add: Новый вый вид умных холодильников с более быстрой выдачей, адекватным указанием имен в меню и возможностью перемещать предметы из контейнеров.
<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2023-12-03 14:25 UTC, Kit0vras commented
Нужно внести холодильник в `Resources/Migration.yml`, чтобы все умные холодильники на картах заменялись на эти

2023-12-03 15:26 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss220/smartftidge.ftl
> +ent-StorageSmartFridge = Умный холодильник
```suggestion
ent-StorageSmartFridge = умный холодильник
```

2023-12-03 15:27 UTC, Kit0vras commented
а овощи в нём хранить можно? потому что там написано только о семенах
в 13 ботаники в нём хранят овощи

2023-12-03 15:33 UTC, SkaldetSkaeg commented on Resources/Locale/ru-RU/ss220/smartftidge.ftl
> +ent-StorageSmartFridge = Умный холодильник
но тут как в оригинале

2023-12-03 15:40 UTC, SkaldetSkaeg commented
> а овощи в нём хранить можно? потому что там написано только о семенах в 13 ботаники в нём хранят овощи

Да, как я понял, тут         - Produce

2023-12-03 15:47 UTC, Kit0vras commented
ник писать не обязательно, если ничего не писать - то используется твой ник гитхаба

2023-12-04 14:56 UTC, Kit0vras approved these changes

2023-12-04 14:56 UTC, Kit0vras commented
Насчёт прототипов косяков не вижу, насчёт кода - ждём Декслера

2023-12-04 20:37 UTC, DexlerXD requested changes
Выглядит круто, но есть вопрос к выдаче таблеток: если он должен их выдавать быстро, то не логично ли будет таблетки выдавать не в руки, а на пол? Скорость работы от быстрой выдачи, если она происходит в руки, не особо увеличивается.

2023-12-04 20:37 UTC, DexlerXD commented on Content.Server/SS220/MachineStorage/EntityMachineStorageSystem.cs
???

2023-12-04 20:38 UTC, SkaldetSkaeg commented on Content.Server/SS220/MachineStorage/EntityMachineStorageSystem.cs
О, а вот это я пропустил

2023-12-04 20:40 UTC, SkaldetSkaeg commented on Content.Server/SS220/MachineStorage/EntityMachineStorageSystem.cs
Надо будет такое мне проверять получше. Пережиток старой реализации.

По поводу выдачи на пол. Могу добить эту реализацию, так как начинал.

2023-12-04 20:42 UTC, DexlerXD commented on Content.Server/SS220/MachineStorage/EntityMachineStorageSystem.cs
> Надо будет такое мне проверять получше. Пережиток старой реализации.
> 
> По поводу выдачи на пол. Могу добить эту реализацию, так как начинал.

Давай, будет круто

2023-12-05 14:19 UTC, 21Melkuu commented
ура наконец холодильники действительно умные, мб это и оффам нунжно?

2023-12-05 16:49 UTC, DexlerXD requested changes
в шапки файлов лицензию добавь еще

2023-12-10 15:59 UTC, DexlerXD requested changes
![изображение](https://github.com/SerbiaStrong-220/space-station-14/assets/69513582/dd580b39-b93b-4c4d-8b6e-a91456c418ff)
исправить бы надо

2023-12-10 16:01 UTC, SkaldetSkaeg commented
интересно

2023-12-10 16:39 UTC, DexlerXD requested changes
![изображение](https://github.com/SerbiaStrong-220/space-station-14/assets/69513582/98bfcd94-de63-4358-bc1d-a1b457202b7c)
теперь другое

2023-12-10 18:55 UTC, DexlerXD approved these changes

2023-12-10 18:56 UTC, merged