Admin "Add objective" button fix
SerbiaStrong-220/space-station-14 pull request #568
Opened 2023-12-06 18:40 UTC by DexlerXD

## Описание PR

У админов в панели антагов теперь работает кнопочка "Добавить цель".
**Медиа**

![изображение](https://github.com/SerbiaStrong-220/space-station-14/assets/69513582/3cd689f4-b654-495a-beae-0e4caf361003)
**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Dexler
- add: Добавлен функционал кнопке "Добавить цель" в админской панели антагонистов.

2023-12-07 13:41 UTC, Werzet requested changes

2023-12-07 13:41 UTC, Werzet commented on Content.Client/Administration/UI/Tabs/AdminTab/AntagonistsWindow.xaml.cs
> +            //SS220-antag-add-objective begin
Это полностью наше окно, так что не нужно коментить функции и подписывать наши пометки. Прям переписывай нестсняясь и наш EUL коммент добавь

2023-12-07 14:09 UTC, DexlerXD commented on Content.Client/Administration/UI/Tabs/AdminTab/AntagonistsWindow.xaml.cs
> +            //SS220-antag-add-objective begin
> Это полностью наше окно, так что не нужно коментить функции и подписывать наши пометки. Прям переписывай нестсняясь и наш EUL коммент добавь

Может, тогда сразу в наши папки переместить это окно?

2023-12-09 00:43 UTC, TheArturZh approved these changes

2023-12-10 08:51 UTC, Werzet approved these changes

2023-12-10 08:52 UTC, merged