Lobbying bundle gets dressings & MORE FAKE MONEY
SerbiaStrong-220/space-station-14 pull request #570
Opened 2023-12-06 23:40 UTC by AlexandrSTG

## Описание PR

Что случилось? Вот что:
- набор лоббиста теперь содержит 50 тысяч кредитов (частично-фальшивых денег).
- набор лоббиста теперь поставляется с костюмом и туфлями, кроме очков.

Набор Лоббиста теперь не просто 5К! А ЦЕЛЫХ 50К! (Но они фальшивые и соотношение стоимости 1 к 5, но это не важно!) Вообще, могло быть и 100К фальшивок, но мне не разрешили. Вопросы не ко мне.
Так же теперь в комплекте лоббиста идет деловой дрескод из костюма адвоката (с другим описанием) и красивых туфель.
Так же добавил дополнительное описание в Аплинк про то, что набор лоббиста поставляется с дрескодом. 

**Медиа**

https://cdn.discordapp.com/attachments/1178946561674334278/1182048583072104568/2023-12-06_22-57-50.mp4?ex=65834787&is=6570d287&hm=d60074f8d16cbab8ef2de0976ffdeebe2c5fc797581719f902fe903f31266804&

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: AlexandrSTG
- add: набор лоббиста получает деловой дрескод в комплект и 50 тысяч кредитов, замест старых
- tweak: изменил глупость в описании из аплинка об ФАЛЬШИВЫХ ДЕНЬГАХ и теперь это, ВОЗМОЖНО, правда.

2023-12-08 11:26 UTC, TheArturZh commented
Новые прототипы нужно перенести в папку SS220
Изменения в прототипах оффов (Resources/Prototypes/Catalog/Fills/Items/briefcases.yml) нужно выделить соответствующими комментариями, типа так:
```yml
- бла-бла
# SS220 Lobbying-Bundle-Rebalace Begin
- изменения
# SS220 Lobbying-Bundle-Rebalace End
- бла-бла
```

2023-12-08 15:49 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Misc/space_cash.yml
> +    count: 50000
думаю, можно в отдельный файл вынести

2023-12-08 15:50 UTC, DexlerXD commented on Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
> +  id: ClothingUniformJumpsuitLawyerBlackSyndieLobbyingBundle
```suggestion
# SS220-lobbying-bundle-fake-money begin
- type: entity
  parent: ClothingUniformJumpsuitLawyerBlack
  id: ClothingUniformJumpsuitLawyerBlackSyndieLobbyingBundle
# SS220-lobbying-bundle-fake-money end
```

2023-12-08 15:52 UTC, DexlerXD commented on Resources/Prototypes/Catalog/Fills/Items/briefcases.yml
> +      - id: SpaceCashFake50000
```suggestion
      # SS220-lobbying-bundle-fake-money begin
      - id: ClothingUniformJumpsuitLawyerBlackSyndieLobbyingBundle
      - id: ClothingShoesBootsLaceup
      - id: SpaceCashFake50000
      # SS220-lobbying-bundle-fake-money end
```

2023-12-08 15:55 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/space_cash.ftl
> +    .desc = { ent-SpaceCashFake.desc }
так как будет относится к нашим новым прототипам, можно будет у нас отдельный файл локализации создать также

2023-12-08 15:55 UTC, DexlerXD commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-bribe-desc = Сердечный подарок, который может помочь вам изменить чьё-то мнение. Настоящие или фальшивые? Да. (В набор дополнительно входят стильные черные очки и деловой дрескод, на которые у
```suggestion
# SS220-lobbying-bundle-fake-money
uplink-bribe-desc = Сердечный подарок, который может помочь вам изменить чьё-то мнение. Настоящие или фальшивые? Да. (В набор дополнительно входят стильные черные очки и деловой дрескод, на которые ушло больше денег, чем в выдано.)
```

2023-12-08 15:56 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
> +    .desc = Красивая обетка и нужные слова – основа сделки.
```suggestion
# SS220-lobbying-bundle-fake-money begin
ent-ClothingUniformJumpsuitLawyerBlackSyndieLobbyingBundle = чёрный деловой костюм
    .desc = Красивая обетка и нужные слова – основа сделки.
# SS220-lobbying-bundle-fake-money end
```

2023-12-08 15:57 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/items/briefcases.ftl
> +ent-BriefcaseBrownFilled = { bounty-item-briefcase }
```suggestion
# SS220-lobbying-bundle-fake-money 
ent-BriefcaseBrownFilled = { bounty-item-briefcase }
```

2023-12-08 15:57 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/items/briefcases.ftl
> +ent-BriefcaseSyndieSniperBundleFilled = { bounty-item-briefcase }
```suggestion
# SS220-lobbying-bundle-fake-money
ent-BriefcaseSyndieSniperBundleFilled = { bounty-item-briefcase }
```

2023-12-08 15:57 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/items/briefcases.ftl
> +ent-BriefcaseSyndieLobbyingBundleFilled = { bounty-item-briefcase }
```suggestion
# SS220-lobbying-bundle-fake-money
ent-BriefcaseSyndieLobbyingBundleFilled = { bounty-item-briefcase }
```

2023-12-09 12:50 UTC, AlexandrSTG commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/items/briefcases.ftl
> +ent-BriefcaseBrownFilled = { bounty-item-briefcase }
Честно я бы даже это удалил, ибо оно берет просто название прототипа у чемодана. Это не совсем нужно.

2023-12-09 12:51 UTC, AlexandrSTG commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/items/briefcases.ftl
> +ent-BriefcaseSyndieSniperBundleFilled = { bounty-item-briefcase }
Скорее это даже не нужно, полез куда не надо.

2023-12-09 12:51 UTC, AlexandrSTG commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/space_cash.ftl
> +    .desc = { ent-SpaceCashFake.desc }
Тогда нужно это делать отдельно в папке 220?

2023-12-09 12:59 UTC, AlexandrSTG commented on Resources/Prototypes/Entities/Objects/Misc/space_cash.yml
> +    count: 50000
Вынести в отдельный файл? Я так и не понял, ты это сделал тут? Я этого не вижу. Плюс это типо новый контент сс220, однако это не совсем так, кароче. Как поступить? просто твое принять?

2023-12-10 21:19 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/items/briefcases.ftl
> +ent-BriefcaseBrownFilled = { bounty-item-briefcase }
> Честно я бы даже это удалил, ибо оно берет просто название прототипа у чемодана. Это не совсем нужно.

Так что с этим делать будешь?

2023-12-10 21:21 UTC, DexlerXD requested changes
Напиши чейнджлог более кратко и формально

2023-12-10 21:36 UTC, DexlerXD requested changes

2023-12-10 21:36 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/clothing/uniforms/jumpsuits.ftl
> +    .desc = Красивая обетка и нужные слова – основа сделки.
```suggestion
    .desc = Красивая обертка и нужные слова – основа сделки.
```
букву `р` потерял

2023-12-10 21:36 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/items/briefcases.ftl
> +    .suffix = набор лоббиста, Синдикат, Кредиты,
набор лоббиста с маленькой буквы, а кредиты с маленькой? + запятая лишняя на конце

2023-12-10 21:36 UTC, DexlerXD commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/space_cash.ftl
> +    .suffix = 10000,fake,фейк
50к, но суффикс 10к?

2023-12-11 06:56 UTC, AlexandrSTG commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/space_cash.ftl
> +    .suffix = 10000,fake,фейк
Пропустил мимо глаз. И правда.

2023-12-12 16:33 UTC, AlexandrSTG commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/space_cash.ftl
> +    .desc = { ent-SpaceCashFake.desc }
сделал

2023-12-12 17:10 UTC, AlexandrSTG commented
Перенес локализацию в отдельную папку сс220 в locate. Перенес прототип в папку сс220 в прототипах. Поправил описания текста в различных локализациях (случайно затронуто, но было необходимо)

2023-12-12 17:45 UTC, DexlerXD approved these changes

2023-12-12 17:48 UTC, merged