Реворк системы передачи предметов между игроками
SerbiaStrong-220/space-station-14 pull request #574
Opened 2023-12-08 17:40 UTC by Lazzi0706

## Описание PR

В общем, в дискорде были замечания по поводу передачи предметов из рук в руки в связи с их неудобством. Я решил это наконец переделать и сделать на лад 13-й станции. Сейчас осталось лишь провести код ревью для красоты и удалять статус передачи после ухода на N-ое расстояние. Позже доделаю, пока-что драфт.
**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Новая механика передачи предметов между игроками
- remove: Файлы локализации ибо работаем онли на русскоговорящих
- tweak: Наименование системы из Transfer System -> Item Offer System
- fix: Исправлено веселье (????????????????)

2023-12-10 16:37 UTC, DexlerXD reviewed
Выглядит неплохо.
Говоря про проверку, можно попробовать подписаться на `MoveEvent` через `ItemReceiverComponent` и в обработчике события проверять расстояние до передающего предмет. Таким образом, если передающий находится на большем расстоянии, чем какое-либо расстояние, то мы убираем алёрт.

2023-12-10 16:37 UTC, DexlerXD commented on Content.Server/SS220/ItemOfferVerb/Systems/ItemOfferSystem.cs
> +                    if (!TryComp<ItemReceiverComponent>(uid, out var itemReceiverComponent))
Если бы я писал такую систему, то я скорее всего бы добавлял компонент через `EnsureComp<>()`, таким образом добавляя компонент, если его нет, или получая его, если он есть, а уже по передаче предмета в методе `TransferItemInHands()` удалял бы компонент.

2023-12-10 16:37 UTC, DexlerXD commented on Content.Server/SS220/ItemOfferVerb/Systems/ItemOfferSystem.cs
> +            if (!args.CanInteract || !args.CanAccess || args.Hands == null || args.Hands.ActiveHandEntity == null
уфф

2023-12-10 18:03 UTC, Lazzi0706 commented on Content.Server/SS220/ItemOfferVerb/Systems/ItemOfferSystem.cs
> +            if (!args.CanInteract || !args.CanAccess || args.Hands == null || args.Hands.ActiveHandEntity == null
> уфф

Excuse me? Можно подробнее что не "уффф"? :gatto:

2023-12-10 18:51 UTC, DexlerXD commented on Content.Server/SS220/ItemOfferVerb/Systems/ItemOfferSystem.cs
> +            if (!args.CanInteract || !args.CanAccess || args.Hands == null || args.Hands.ActiveHandEntity == null
> > уфф
> 
> Excuse me? Можно подробнее что не "уффф"? :gatto:

Не, это просто my honest reaction. Много логического "или" в одной проверке.

2023-12-12 10:49 UTC, DexlerXD requested changes
Тест упал все равно (

2023-12-12 13:45 UTC, TheArturZh commented
По-хорошему нужно каждый update делать проверку на расстояние между принимающим и передающим, нагрузка не будет сколько-либо существенной, т.к. компонент потом всё равно удаляется. Иначе передающий может съебать в закат а алерт останется.

2023-12-12 13:55 UTC, DexlerXD commented
> По-хорошему нужно каждый update делать проверку на расстояние между принимающим и передающим, нагрузка не будет сколько-либо существенной, т.к. компонент потом всё равно удаляется. Иначе передающий может съебать в закат а алерт останется.

Проверки через MoveEvent недостаточно?

2023-12-12 13:56 UTC, TheArturZh commented
Нет, компонент вешается только на принимающего

2023-12-12 13:58 UTC, DexlerXD commented
> Нет, компонент вешается только на принимающего

ааааа, у нас же передающий еще есть, тут я не доглядел :starege:

2023-12-12 14:01 UTC, TheArturZh commented
Так же туда же нужно добавить проверку на наличие предмета в руках передающего. Иначе игроки могут поломать всякое, что не должно отдавать предметы, сначала инициируя передачу а потом запихивая предмет и забирая его обратно. Микроволновку так можно будет абузить например.

2023-12-12 16:57 UTC, Lazzi0706 commented
> @Lazzi0706 тогда попробуй через Update проверять расстояние между игроками, воспользуемся самым очевидным способом

Я первоначально через Update и делал, однако там отвратительный способ поиска расстояния между объектами, т.к я не помню, надо ли через Transform систему это делать, или через другую

2023-12-14 16:39 UTC, merged