synd key stealth
SerbiaStrong-220/space-station-14 pull request #579
Opened 2023-12-11 15:23 UTC by ZoNeSRuS

## Описание PR

Прячет ключ канала синдиката, если он вставлен не в синдикатский наушник.
Добавлена новая компонента StealthChannel которая отвечает за скрытность канала.
Наушник проверяется на дефолт канал, и если канал ключа ему не соответствует и является стелс, то он просто не отображается.

На картинке ниже наушник синдиката и наушник АВД в который вставлен ключ синдиката.
**Медиа**

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/42711621/e1e70fc7-ecbd-4f24-9d35-62280b6cc540)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/42711621/ff21f286-0f26-45b6-bde0-7d00fb249bd6)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/42711621/4cef7c05-68e2-4a43-ac76-72399e64ecd2)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: ZoNeSRuS
- add: Канал синдиката не видно в не синди гарнитурах.

2023-12-11 15:48 UTC, Ady4ik commented
У тебя правильно написан перевод стелса на английский в названии ПРа - stealth, а в файлах ты используешь stalth, почему?

2023-12-11 21:15 UTC, DexlerXD requested changes

2023-12-11 21:15 UTC, DexlerXD commented on Resources/Prototypes/radio_channels.yml
> +  stealthChannel: true #SS220-synd_key_stalth
```suggestion
  stealthChannel: true #SS220-synd_key_stealth
```

2023-12-11 21:15 UTC, DexlerXD commented on Content.Shared/Radio/RadioChannelPrototype.cs
> +    //SS220-synd_key_stalth
```suggestion
    //SS220-synd_key_stealth begin
    /// <summary>
    ///     Determines the visibility of the key during inspection
    /// </summary>
    [DataField("stealthChannel")]
    public bool? StealthChannel = false;
    //SS220-synd_key_stealth end
```

2023-12-11 21:15 UTC, DexlerXD commented on Content.Shared/Radio/EntitySystems/EncryptionKeySystem.cs
> +            //SS220-synd_key_stalth
```suggestion
            //SS220-synd_key_stealth begin
            if (id != defaultChannel && proto.StealthChannel == true)
                return;
            //SS220-synd_key_stealth end
```

2023-12-12 04:16 UTC, ZoNeSRuS commented
Простите опечатка которую я не заметил когда делал ктрлС ктрлВ

2023-12-12 10:47 UTC, DexlerXD approved these changes

2023-12-12 10:47 UTC, merged