Карта Marathon под SS220 + Убраны неиграбельные карты Ishimura, Bagel
SerbiaStrong-220/space-station-14 pull request #584
Opened 2023-12-12 14:13 UTC by spo9k

## Описание PR
Карта Marathon переделана под SS220, карта от последнего обновления оффов то есть елки и т.д уже есть. На карту добавлен Бригмедик, криоподы, СинийЩит, копированные аппараты и немного изменена церковь под НГ. и переведенна на русский то есть факсы, warp point.
Убраны карты из мапула Ишимура, Багель ( Багель непадает в маппуле, а ишимура неиграбельна)

**Медиа**

**Проверки**

- [+] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [+] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [+] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [-] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: spo9k
-add: Добавлена карта Marathon

2023-12-12 14:17 UTC, Kit0vras commented
Поставь пробел перед add, чтобы дефис превратился в точку
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/fbf9cf39-3857-4e83-95dc-aaa8dbecb5eb)

Исправь формат файла в пуле, как было с прошлыми, чтобы не менялся весь файл.

Саму карту погляжу чуточку позже, сейчас немного занят

2023-12-14 17:16 UTC, Kit0vras requested changes
Вместо подмороженного покрытия лучше поставить какую-нибудь плитку, чтобы провода и трубы были всё также скрыты, как и раньше.
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/d7755809-d86b-43c5-b3c4-2a2c73a5f494)

Нужно перевести факсы (не все переведены) и камеры видеонаблюдения на русский. Это легче сделать через yml файл карты.

Заменить эти платы в хранилище над столовой на спавнеры плат (уже знаешь).

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/6d994651-fc1a-433e-9ba2-6e11e54d3f36)

У БЩ нет листочка с брифингом.

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/f477ef58-8a67-4070-a5af-a02825dfafb4)

В остальном норм.

2023-12-22 11:20 UTC, Kit0vras requested changes
Обновления от апстрима согласно https://discord.com/channels/1097181193939730453/1178431328694325370/1187454318530547882

2023-12-22 11:23 UTC, Kit0vras requested changes
Убрать роли

2023-12-22 11:23 UTC, Kit0vras commented on Resources/Prototypes/SS220/Maps/marathon220.yml
Убрать сеньор-роли.

2023-12-22 11:23 UTC, Kit0vras commented on Resources/Prototypes/SS220/Maps/Pools/default.yml
Починить файл, переведя в нужный формат.

2023-12-22 16:09 UTC, spo9k commented
@Kit0vras проверяй вроде всё гуд

2023-12-22 17:55 UTC, DexlerXD approved these changes

2023-12-22 17:55 UTC, merged