New debug tools
SerbiaStrong-220/space-station-14 pull request #590
Opened 2023-12-16 15:36 UTC by VladIsLove-e

## Описание PR

Добавлены дебаг предметы:
Ножи по 100 ед. урона, кукла на 1000 хп и мишень на 100к хп
**Медиа**

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/139070688/f8a5de22-2cd8-4ca4-80b7-294ddd3e6b9f)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: 
- add: Добавлены дебаг предметы для админов.

2023-12-16 15:39 UTC, VladIsLove-e commented
У куклы рандомное человеческое имя и внешность, так что её можно использовать для ивентов (правда хз в каких)

2023-12-16 16:14 UTC, Kit0vras commented
Слишком много мусорных строчек, сделай базовый, наследуемый от комбат кнайфа абстрактный нож и наследуй остальные от него, меняя только название и тип урона

2023-12-16 16:15 UTC, Kit0vras commented
Ну хотя ладно, их не намного меньше будет, но всё равно будет меньше накакано

2023-12-16 16:18 UTC, ZoNeSRuS commented
Ура больше мусора в итак уже замусореном Ф5

2023-12-16 16:37 UTC, Kit0vras commented
> Ура больше мусора в итак уже замусореном Ф5

А я говорил, что если он хочет такое, то надо делать нож с переключением режимов или что-нибудь такое, а не делать 15 ножей

2023-12-16 17:13 UTC, VladIsLove-e commented
> Ну хотя ладно, их не намного меньше будет, но всё равно будет меньше накакано



> > Ура больше мусора в итак уже замусореном Ф5
> 
> А я говорил, что если он хочет такое, то надо делать нож с переключением режимов или что-нибудь такое, а не делать 15 ножей

А я говорил, что поговорил с декслером- увы. Не в моих силах сделать это. А в щитспавне насрано всегда было.

2023-12-18 21:49 UTC, Kit0vras commented
Я нашёл некоторое решение, которое не будет сменой режимов ножу, но позволит не устраивать этот срач.
- Прописываешь ножам nospawn - в итоге предметов не будет в меню спавна, но

- Делаешь сумку для дебаг-ножей, в которые пихаешь все свои ножи (Тоесть заполняешь её через прототип, как рюкзаки твоим синди-отрядам, ну ты понял). В итоге у тебя нет срача, ты просто берёшь 1 сумку, в которой лежат все ножи. Это явно более лучшее решение, чем оставлять это так, как сейчас.

Также, я создал директорию `/Prototypes/SS220/Entities/Debugging` (для текстур - `/Textures/SS220/Debugging`, если понадобится), пихай все вещи, предназначенные для дебага, туда, так как у нас соблюдается файловая иерархия и это более очевидная директория для хранения подобных предметов, + чтобы они были в одном месте, а не разбросаны кто где.

Добавь хуману тег `Debug`, чтобы пользователю было точно очевидно, что это не предназначено для игры.

Раздели ножи и куклы+мишени на 2 файла, чтобы они лежали в одной директории, но раздельными файлами, чтобы пользователю было более очевидно, где ему искать нужный ему файл - никто не будет ожидать дебаг-кукол в файле с дебаг-ножами.

2023-12-24 15:47 UTC, VladIsLove-e commented
Сделал наследование с пустого ножа, ну и всё, о чём кит писал

2023-12-24 15:51 UTC, Kit0vras requested changes

2023-12-24 15:51 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Debugging/debugKnife.yml
> +  description: Зачем ты это читаешь?
```suggestion
  description: Сумка, наполненная ножами на 100 урона каждого типа. Предназначена для отладки и тестирования урона.
```

2023-12-24 15:53 UTC, VladIsLove-e commented on Resources/Prototypes/SS220/Entities/Debugging/debugKnife.yml
> +  description: Зачем ты это читаешь?
Этот человек даёт дебаг предметам описание, вызовите ему врача

2023-12-24 16:23 UTC, Kit0vras commented
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/c12c2423-a949-43fd-b5fa-3069b8e44ef1)

2023-12-27 06:35 UTC, Kit0vras approved these changes

2024-01-14 14:38 UTC, TheArturZh approved these changes

2024-01-14 14:38 UTC, merged