Text fixing 2
SerbiaStrong-220/space-station-14 pull request #601
Opened 2023-12-21 21:38 UTC by AlexandrSTG

## Описание PR

Небольшая работа с текстом. 
- Убрал ненужное случайный выбор описаний на английском для квадрациклов.
- Убрал глупую подсказку.
- Изменил подсказку о трогании травы, убрал подсказку об генерации омнизина в гипоспрее.
- Изменено описания мыла Синдиката в аплинке.
- Изменено описание ЕВЫ синдиката в аплинке.
- Описание ПИИ Синдиката теперь без меты.
- Ящик инструментов Синдиката больше не "подозрительный".
- Карпы теперь имеют описание с "кусь".

**Медиа**

Медиа не требуется.

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

 :cl: AlexandrSTG
- tweak: изменены описания обычных вещей, карпов, тулбокса Синдиката, ПИИ Синдиката, изменено описание вещей в аплинке, убраны не нужные подсказки из игры.
- remove: убран Александр П. из игры.
<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!
->

2023-12-22 07:19 UTC, Kit0vras requested changes

2023-12-22 07:19 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/carp.ftl
> +    .desc = Существо из космоса, которое способно сделать неподготовленному больной "кусь".
```suggestion
    .desc = Существо из космоса, которое способно сделать неподготовленному болючий "кусь".
```

2023-12-22 07:19 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/decoration/flora.ftl
> +    .desc = Блюспейс елка с подарками, обвешанная украшениями! Загляни туда и увидишь подарок, который был заранее подготовлен для тебя!
```suggestion
    .desc = Блюспейс ёлка с подарками, обвешанная украшениями! Загляни туда и увидишь подарок, который был заранее подготовлен для тебя!
```

2023-12-22 07:19 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/fun/pai.ftl
> +    .desc = Синдикат
ты имел ввиду суффикс?
```suggestion
    .suffix = Синдикат
```

2023-12-22 07:19 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/toolbox.ftl
> +ent-ToolboxSyndicate = черный ящик для инструментов
```suggestion
ent-ToolboxSyndicate = чёрный ящик для инструментов
```

2023-12-22 07:19 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/toolbox.ftl
> +    .desc = Зловеще выглядящий ящик для инструментов. Кто знает, что может храниться в нем..?
```suggestion
    .desc = Зловеще выглядящий ящик для инструментов. Кто знает, что в нём может храниться..?
```

2023-12-22 07:19 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/vehicles/buckleable.ftl
> +    .desc = Четырехколесное транспортное средство малых габаритов.
```suggestion
    .desc = Четырёхколесное транспортное средство малых габаритов.
```

2023-12-22 07:19 UTC, Kit0vras commented on Resources/Locale/ru-RU/store/uplink-catalog.ftl
> +uplink-soap-desc = Новейшая гигееническая разработка Синдиката! Ни один сотрудник НТ не устоит, если уронить его в душевой.
гигиена
```suggestion
uplink-soap-desc = Новейшая гигиеническая разработка Синдиката! Ни один сотрудник НТ не устоит, если уронить его в душевой.
```

2023-12-22 07:19 UTC, Kit0vras commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Травы нету! Личной жизни нету! Вас не существует! Есть только ваш персонаж в компьютерной игре Space Station 14."
Вообще, стоило бы добавить это как дополнительную подсказку, потому что трава - это мем, который говорит, что ты засиделся, а ты переделал её под подсказку, которая как бы издевается над тобой, говоря, что ты только и делаешь, что играешь. (но трава ведь важна!)

2023-12-22 10:15 UTC, AlexandrSTG commented on Resources/Prototypes/Datasets/tips.yml
> +    - "Травы нету! Личной жизни нету! Вас не существует! Есть только ваш персонаж в компьютерной игре Space Station 14."
Мне Патрик сказал, что мешает. Попросил убрать. Никто против не был :)

2023-12-23 22:24 UTC, AlexandrSTG commented
Спасибо Киту за проверку. Теперь должно быть все верно. Я лично не писал с буквой Ё никогда, стоит учитывать это в будующем.

2023-12-23 22:26 UTC, Kit0vras commented
А я думал, что у тебя просто буквы ё на клавиатуре нет :Clueless:

2023-12-24 07:11 UTC, ZoNeSRuS commented
Зачем вообще нужна буква ё?

2023-12-24 13:48 UTC, DexlerXD approved these changes

2023-12-24 13:48 UTC, merged