Добавление питомца для Агента Внутренних Дел (Прошлый пулл был совмещен с предыдущими пулами по моей ошибке)
SerbiaStrong-220/space-station-14 pull request #613
Opened 2023-12-24 18:14 UTC by Ady4ik

## Описание PR
Добавление питомца для Агента Внутренних Дел - Ракеты. Добавление питомца; питомца с суффиксом Роль (С ним есть проблемы с локализацией, нужна помощь); Спавнера Гост рольки. Так много прототипов было сделано по примеру оффициалов 
Есть проблема с локализацией 

**Медиа**
Отсутствует.

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлен питомец для Агента Внутренних Дел - Ракета.

2023-12-24 21:11 UTC, Kit0vras commented
`его в неё` - звучит супер-странно, пните меня, если я шиз

2023-12-27 06:33 UTC, Kit0vras requested changes

2023-12-27 06:33 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
> +    .desc = Любимый питомец Агента Внутренних Дел. Ракета никогда не падал в пустоту. Не пытайся толкнуть его туда.
```suggestion
    .desc = { ent-MobCatSpace.desc }
```

2023-12-27 06:33 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss14-ru/prototypes/entities/mobs/npcs/pets.ftl
> +    .desc = Любимый питомец Агента Внутренних Дел. Ракета никогда не падал в пустоту. Не пытайся толкнуть его туда.
Питомец семейства кошачьих, подготовленный к худшему.

Ни у одного питомца напрямую не упоминается, чей он, + это описание более осмыслено.

2023-12-27 06:33 UTC, Kit0vras commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-spacecat-description = Любимый питомец Агента Внутренних Дел. Он никогда не падал в пустоту. Не пытайся толкнуть его в неё.
```suggestion
ghost-role-information-pet-spacecat-description = Питомец семейства кошачьих, подготовленный к худшему.
```

2023-12-27 06:33 UTC, Kit0vras commented on Resources/Prototypes/Entities/Mobs/NPCs/pets.yml
> +  description: He never falled in void. Don`t try to bring him in it.
```suggestion
  description: Feline pet, prepared for the worst.
```

2023-12-27 06:33 UTC, Kit0vras commented on Resources/Locale/ru-RU/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-spacecat-name = Ракета
```suggestion
ghost-role-information-pet-spacecat-name = Ракета
```

2023-12-28 13:35 UTC, Werzet approved these changes

2023-12-28 13:35 UTC, merged