Glintwine
SerbiaStrong-220/space-station-14 pull request #618
Opened 2023-12-26 14:18 UTC by Imleriya

## Описание PR
Добавлен новый напиток Глинтвейн. Рецепт 4 юнитов: по 1 юниту каждого реагента - Вино, Сахар, Апельсиновый сок, Универсальный фермент.
Спрайт напитка сделан SubL для SS220.

**Медиа**
![icon](https://github.com/SerbiaStrong-220/space-station-14/assets/149191829/434a933b-c075-4919-b597-d09f25af7f9b)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl:
- add: Добавлен напиток Глинтвейн.

2023-12-26 14:45 UTC, Kit0vras requested changes

2023-12-26 14:45 UTC, Kit0vras commented on Resources/Prototypes/SS220/Reagents/Consumable/Drink/alcohol.yml
> +  desc: Глядя на этот напиток вы чувствует наступление Рождества.
```suggestion
  desc: Глядя на этот напиток, вы чувствуете наступление Рождества.
```

2023-12-27 06:11 UTC, Kit0vras approved these changes

2023-12-28 15:19 UTC, TheArturZh requested changes
в ПР два одинаковых RSI спрайта - один в папке SS220, другой у оффов. Нужно убрать лишний, оставив только тот, что в папке SS220, и поправить пути в прототипах.

2023-12-28 15:19 UTC, TheArturZh commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks.yml
> +#SS220 Glintwine end
Нужно перенести в отдельный файл с аналогичным путём в папке SS220

2023-12-29 06:54 UTC, Imleriya commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks.yml
> +#SS220 Glintwine end
Пофикшено.

2023-12-29 14:08 UTC, TheArturZh requested changes

2023-12-29 14:08 UTC, TheArturZh commented on Resources/Prototypes/SS220/Reagents/Consumable/Drink/alcohol.yml
> +  desc: Глядя на этот напиток, вы чувствуете наступление Рождества.
Вынос описания и имени реагента в файл локализации (.ftl) теперь обязателен, иначе не проходит тесты
В поле name и desc нужно указать ключи локализации, reagent-name-glintwine и reagent-desc-glintwine соответственно
Файл для локов наших реагентов нужно создать по пути `Resources/Locale/ru-RU/ss220/reagents/meta/drinks.ftl`

2023-12-29 14:10 UTC, TheArturZh commented
С полем physicalDesc нужно сделать то же самое

2024-01-19 19:50 UTC, Ady4ik requested changes
Я бы убрал отсылку на Нюрнбег, потому что в поисковке и исторических источниках информация рознится.
Если есть желание сделать отсылку, сделай лучше отсылку на "Планету Немецию" или что-то в таком роде.

2024-01-19 20:03 UTC, Ady4ik approved these changes
Я забираю свои слова, я был не прав

2024-01-19 21:48 UTC, TheArturZh approved these changes

2024-01-19 21:48 UTC, merged