Помощница офицеров новый пёсик Рокси
SerbiaStrong-220/space-station-14 pull request #644
Opened 2024-01-05 20:50 UTC by spo9k

## Описание PR
Добавлен новый питомец для отдела СБ, а именно для офицеров Собака Рокси, имеет очки СБ, свою карту СБ как у пун-пуна(вытащить нельзя только через админку), чтоб на ней поиграть она появляется в гост ролях, но ее взять может только тот человек кто отыграл на СБ 4+ часов.

**Медиа**
![Рокси2](https://github.com/SerbiaStrong-220/space-station-14/assets/135381384/0374c6c6-f387-496c-b634-76f878b5de7f)
![Рокси](https://github.com/SerbiaStrong-220/space-station-14/assets/135381384/e4f5fd49-ad2b-4d5d-b12f-340082be443d)

**Проверки**

- [+] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [+] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [+] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [+] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
- add: Добавлен новый питомец Рокси

2024-01-05 23:53 UTC, TheArturZh commented
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/16546901/073718b5-92ed-415d-9817-f236fd8b33cc)
нормально организовать бы, без папки с ником

2024-01-05 23:55 UTC, spo9k commented
Ну там просто уже как бы фелинид же есть в моей папке, вот я сразу так сделал. Ну могу питомца так расскидать, это прям нужно или не так важно?

2024-01-06 00:00 UTC, TheArturZh commented
Ну вот это прям нежелательно, потому что и владислав вслед за тобой хотел так сделать
Если у нас будут именные папки разрабов повсюду вместо то это будет неудобно. Я хочу заходить в папку с нашими энтитями и сразу видеть их все. Чей там код я узнаю и так, без проблем

2024-01-06 00:03 UTC, spo9k commented
Хорошо, услышал тебя, исправлю🥺

2024-01-06 16:12 UTC, spo9k commented
@TheArturZh Ну собаку перенес, вчера вообще не вдуплял, как перенести, но вроде сделал. А Феленидов в новом ПР потом перенесу, чтоб тут каких либо ошибок не было

2024-01-06 16:58 UTC, Kit0vras requested changes

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Mobs/NPCs/animals.yml
> +  name: Охранная собака
```suggestion
  name: охранная собака
```
С маленькой буквы, это не имя собственное

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Mobs/NPCs/animals.yml
> +  description: Как ни странно, эта свинья на самом деле собака.
ну блин, как-то обидно звучит, да и не выглядит она как свинья..

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Mobs/NPCs/animals.yml
> +    name: "Собака Службы Безопасности"
```suggestion
    name: "собака Службы Безопасности"
```
Тоже не имя собственное

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Mobs/NPCs/animals.yml
> +    description: "Помогите команде безопасности, кусая злодеев и лая на все, что движется."
```suggestion
    description: "Помогите отделу охраны, кусая злодеев и лая на все, что движется."
```

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Mobs/NPCs/animals.yml
> +      300: Dead
зачем и почему настолько дофига, это не собака-киборг, поставь хотя бы 200

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Mobs/NPCs/animals.yml
> +    bloodMaxVolume: 300 # :3
```suggestion
    bloodMaxVolume: 200 # :3
```
В этой собаке крови столько же, как в огромном медведе или горилле. Помню, раньше у медведя вообще 500 было, так там отряд уборщиков нужен был, чтоб это убрать

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Mobs/NPCs/pets.yml
> +  description: Охраная собака — помощница офицеров, по поимки злодеев. Больно кусается, лучший офицер станции.
```suggestion
  description: Не стоит шутить с ней - в списке её наград есть медаль за отвагу.
```
Насколько помню, ни у одного питомца нет описания, которое на 100% причисляло бы их к кому-то. Полагаю, это сделано для того, чтобы их можно было присвоить для кого ты захочешь. Нужно нейтральное описание, как у остальных.

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Mobs/NPCs/pets.yml
> +    description: "Собака службы безопасности. Издевайтесь над офицерами, чтобы погладить их по голове и преследовать жестоких преступников по пятам"
```suggestion
    description: "Охранная собака. Оберегайте порядок, помогайте в поимке преступников."
```
Охранная собака звучит более нейтрально и более применимо к другим случаям использования. Остальную часть предложения вовсе не смог понять.

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/markers/Spawners/mobs.yml
> +  name: Спавнер Охрайной Рокси
```suggestion
  name: спавнер Рокси
```

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Textures/Clothing/Eyes/Glasses/meson.rsi/meta.json
Поправь формат файла, как всегда делаешь

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Textures/Clothing/Eyes/Glasses/secglasses.rsi/meta.json
И тут

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Textures/Clothing/Eyes/Glasses/sunglasses.rsi/meta.json
И тут

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Textures/Clothing/Mask/breath.rsi/meta.json
И тут

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/emergency.rsi/meta.json
И тут

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/emergency_double.rsi/meta.json
И тут

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/generic.rsi/meta.json
И тут

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/red.rsi/meta.json
И тут

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/yellow.rsi/meta.json
И тут

2024-01-06 16:58 UTC, Kit0vras commented on Resources/Textures/SS220/Mobs/Animals/Roxi.rsi/meta.json
> +  "copyright": "Original work by jonson, and i need help sprite remake textures spo9k.",
Непонятный копирайт. Кто такой Джонсон? как его искать будут? что он там помогать должен - вообще не важно

`Made by` Никнейм `(Discord/Github)`. `Edited by` Никнейм `(Discord/Github)`.

В скобках указывается его "адрес", дискорд либо гитхаб, чтобы художника могли хоть как-то найти. Если делается конкретно куда-то (к примеру, на конкретный проект) то после инфы в скобках оригинального художника можно дописать `for SS14` (вместо SS14 - проект, к примеру).

2024-01-06 17:01 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Mobs/NPCs/animals.yml
> +    description: "Помогите команде безопасности, кусая злодеев и лая на все, что движется."
Кста, а разве гост-роль не в pets пишется? не помню

2024-01-06 17:02 UTC, Kit0vras commented
@spo9k

2024-01-06 17:08 UTC, spo9k commented on Resources/Prototypes/SS220/Entities/Mobs/NPCs/animals.yml
> +  description: Как ни странно, эта свинья на самом деле собака.
Это когда ты через админку спавнишь, то будет так написано, а когда она появляется на самой карте где СБ, то там другое описание. 
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/135381384/2833e85c-1f5d-4c0c-ae5c-2d430fa6f7e3)

2024-01-06 17:09 UTC, spo9k commented on Resources/Textures/SS220/Mobs/Animals/Roxi.rsi/meta.json
> +  "copyright": "Original work by jonson, and i need help sprite remake textures spo9k.",
А вот нету его гитхаба, тип я нашел спрайт, и немного его исправил, там было так написано, так что я хз, если он найдется то я оставлю как автор спрайта этого.

2024-01-06 17:11 UTC, spo9k commented on Resources/Prototypes/SS220/Entities/Mobs/NPCs/animals.yml
> +      300: Dead
Бойцовская собака. Ну 200 наверно можно, но точно незнаю, надо же по тестить как игроки будут, реагировать.

2024-01-07 08:16 UTC, Kit0vras commented on Resources/Textures/SS220/Mobs/Animals/Roxi.rsi/meta.json
> +  "copyright": "Original work by jonson, and i need help sprite remake textures spo9k.",
Тогда "сделано им, изменено вон тем"

2024-01-14 13:34 UTC, TheArturZh approved these changes

2024-01-14 13:34 UTC, merged

2024-01-17 05:50 UTC, FriedrichStrassen commented
Бафните макгрифа.