Респрайт ЦК и добавление новых ГостРолей ЦК
SerbiaStrong-220/space-station-14 pull request #645
Opened 2024-01-06 17:09 UTC by Ady4ik

## Описание PR
https://github.com/orgs/SerbiaStrong-220/projects/1/views/2?filterQuery=%D0%BF%D0%B5%D1%80%D0%B5&pane=issue&itemId=44494460

Есть проблема с тем, что у меня не работают спавнилки этих самых новых ролей. Так же я немного запутался, нужно ли будет создавать ещё новых прототипов, чтобы их можно было заспавнить как гостроль. Поэтому открываю драфт, чтобы умные люди подсказали мне, что и как.

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:Ady4, WMT, MrALPAKA
- add: Добавлены новые ГостРоли ЦК, которые может заспавнить администрация.
- add: Добавлена новая одежда ЦК и персональные ПДА для новых ГостРолей.
- tweak: Изменен спрайт ПДА, ручки, наушников ЦК.

2024-01-06 17:35 UTC, Kit0vras requested changes

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Back/belts.yml
> +  name: Пояс ГСН
```suggestion
  name: пояс ГСН
```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Back/belts.yml
> +  description: Данный пояс позволяет хранить всё необходимое в удобном и быстродоступном месте, а материал, из которого он выполнен, позволяет выглядеть ещё более стильнно.
```suggestion
  description: Этот пояс позволяет хранить всё необходимое в удобном и быстродоступном месте, а материал из которого он выполнен, позволяет выглядеть ещё более стильно.
```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Back/belts.yml
> +  id: ClothingBeltWebbingSRTFilled
зачем ты дублируешь название и описание? ты наследуешь это от прошлого, оставь только StorageFill и Суффикс. Компонент спрайта тоже не нужен, так как ты ничего в нём не менял

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Back/belts.yml
> +  noSpawn: false
```suggestion

```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Head/BeretNanoTrasenOfficer.yml
> +  name: Берет Офицера NanoTrasen
```suggestion
  name: берет Офицера NanoTrasen
```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Head/BeretNanoTrasenOfficer.yml
> +  description: Чёрный офицерский берет с выгравированным щитом и мечом, объявляющий миру, что его владелец является защитником NanoTrasen
```suggestion
  description: Чёрный офицерский берет с выгравированным щитом и мечом, объявляющий миру, что его владелец является защитником NanoTrasen.
```
Выгравированным на ткани? хотя может такое и бывает, ладно уж

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Head/NavyFieldOfficerCap.yml
> +  description: Если видите её на станции, прячьте колени
```suggestion
  description: Если видите её владельца на станции, прячьте колени.
```
Звучит более понятно, а то есть фуражка на станции - и что? может он её потерял в пыльном углу

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Head/NavyFieldOfficerCap.yml
> +  name: фуражка полевого офицера
```suggestion
  name: фуражка полевого Офицера
```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/OuterClothing/SRTCoat.yml
> +  description: Бронекостюм тёмно-синего цвета. Отличная защита от большинства видов урона.
```suggestion
  description: Бронекостюм тёмно-синего цвета. Отличная защита от большинства видов урона.
```
всм бронекостюм? статы те же, что и у парадного плаща выше

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Satchel/SRT_satchel.yml
> +  description: Прочная сумка спецназа NanoTrasen
```suggestion
  description: Прочная сумка спецназа NanoTrasen.
```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Satchel/SRT_satchel.yml
> +  - type: Storage
устаревшее значение. Теперь это делается сеткой:
```
  - type: Storage
    grid:
    - 0,0,6,3
```
это значения дефолтного рюкзака

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/nt_NO_uniform.yml
> +  name: униформа офицера NanoTrasen
```suggestion
  name: униформа Офицера NanoTrasen
```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/nt_NO_uniform.yml
> +  description: На этой униформе изображено звание «лейтенант-коммандер». Носят исключительно офицеры Нанотрейзен. Для защиты используются экзотические материалы.
```suggestion
  description: На этой униформе изображено звание «лейтенант-коммандер». Её носят исключительно офицеры NanoTrasen. Защитные свойства форме придают экзотические материалы.
```
Для защиты кого? формы?

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Uniforms/nt_dip_uniform.yml
> +  description: Очень яркая и официальная униформа дипломатического корпуса НаноТрейзен.
```suggestion
  description: Очень яркая и официальная униформа дипломатического корпуса NanoTrasen.
```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Devices/centcomm_newpda.yml
> +  name: ПДА Дипломата ЦК
```suggestion
  name: КПК Дипломата ЦК
```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Devices/centcomm_newpda.yml
> +  name: ПДА Дипломата ЦК
КПК - русифицированный вариант аббревиатуры, использующийся в игре

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Devices/centcomm_newpda.yml
> +  description: ПДА Дипломата Центрального Командования. Его изысканный стиль позволяет более утонченно проводить переговоры. Особым аргументом является ручка, которая находится внутри него.
```suggestion
  description: КПК Дипломата Центрального Командования. Его изысканный стиль позволяет более утонченно проводить переговоры. Особым аргументом является ручка, которая находится внутри.
```
и так понятно, что ручка внутри него, а не в кармане, так что последнее местоимение не нужно.

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Devices/centcomm_newpda.yml
> +  name: ПДА Полевого Офицера ЦК
```suggestion
  name: КПК Полевого Офицера ЦК
```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Devices/centcomm_newpda.yml
> +  description: ПДА Полевого Офицера Центрального Комадования. Несмотря на идеально выполненный дизайн, это ПДА было заляпано кровью не один десяток раз.
```suggestion
  description: КПК Полевого Офицера Центрального Командования. Несмотря на идеально выполненный дизайн, этот КПК был заляпан кровью не один десяток раз.
```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Devices/centcomm_newpda.yml
> +  name: ПДА Офицера ЦК
```suggestion
  name: КПК Офицера ЦК
```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Devices/centcomm_newpda.yml
> +  description: ПДА Офицера Центрального Командования. Красиво выполненный дизайн позволяет Офицерам находить, чем заняться во время ожидания ответа от станции.
```suggestion
  description: КПК Офицера Центрального Командования. Красиво выполненный дизайн позволяет Офицерам находить, чем заняться во время ожидания ответа от станции.
```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Weapons/Melee/ntbaton.yml
> +  description: А вы знали, что офицеры ЦК любят играть в бейсбол головами некомпитентного руководства своих активов?
```suggestion
  description: А вы знали, что Офицеры ЦК любят играть в бейсбол головами некомпетентного руководства своих активов?
```

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Weapons/Melee/ntbaton.yml
> +    sizeOpened: 15
```suggestion
    sizeOpened: 15
```
это и значение ниже скорее всего не будут верно работать, это работает теперь по гриду

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Weapons/Melee/ntbaton.yml
> +    size: 5
```suggestion
    size: 5
```
и это

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Textures/Markers/jobs.rsi/meta.json
может лучше добавить джоб иконки вместе с метой в сс220, или это нельзя?

2024-01-06 17:35 UTC, Kit0vras commented on Resources/Textures/SS220/Objects/Weapons/Melee/ntbaton.rsi/meta.json
> +  "copyright": "Sprited by mixnikita",
```suggestion
  "copyright": "Sprited by MIXnikita (Github) for SS220",
```

2024-01-06 17:39 UTC, Kit0vras commented
Может быть, стоит вообще всё это тоже стоит перенести в сс220? Чтоб проблем было меньше, а то они обожают респрайтить то, что респрайтить не нужно
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/7ee58397-b879-4e4a-8ab7-5a5825b8f2b1)

2024-01-06 17:40 UTC, Kit0vras commented
на ЦК-дефолт вещи можно накинуть `noSpawn` и сделать миграцию ЦК-дефолт вещей на наши в `migration.yml`

2024-01-07 08:15 UTC, Ady4ik commented on Resources/Prototypes/SS220/Entities/Clothing/OuterClothing/SRTCoat.yml
> +  description: Бронекостюм тёмно-синего цвета. Отличная защита от большинства видов урона.
там плащ как плащ, в плане одежда, а не в плане плащ, как у обычного главы.

2024-01-07 09:36 UTC, Ady4ik commented
@TheArturZh В общем то мне нужна помощь с этим ПРом
1. У меня почему то не работают спавнеры, а именно текстурка в щитспавне есть, содержимое его покетов я прописал, но он не спавнится
2. Нет в щитспавне ПДА (не понимаю, почему, это для меня нонсонс)
3. Не видит текстурку ручки, хотя все стейты совпадают.
Сегодня ещё потыкаюсь, но пока немного устал.

2024-01-07 09:56 UTC, TheArturZh commented
Добавь [Work In Progress] в тайтл и поставь Ready For Review чтоб тесты начались, оно скорее всего найдёт ошибки

2024-01-07 10:02 UTC, TheArturZh commented
у тебя копия файла лишняя есть "Resources/Textures/SS220/Clothing/Uniforms/nt_NO_uniform.rsi/equipped-INNERCLOTHING-monkey копия.png"

2024-01-07 10:22 UTC, TheArturZh commented on Resources/Prototypes/SS220/Entities/Objects/Devices/centcomm_newpda.yml
> +    state: centcommnew_pda
у всех полей компонентов отсутствует правильный отступ, из-за чего прототип не грузится
должно быть не так
```
- type: Pda
id: FieldOfficerIDCard
```
а так
```
- type: Pda
  id: FieldOfficerIDCard
```

2024-01-07 10:24 UTC, TheArturZh commented on Resources/Prototypes/SS220/Entities/Objects/Misc/identification_cards.yml
> +  name: ID карта Полевого Офицера ЦК
ID дублируется, прототип не грузится

2024-01-07 10:29 UTC, TheArturZh commented on Resources/Prototypes/SS220/Roles/Jobs/СentComm/NanoTrasenOfficer.yml
> +  - AllAccess
У каждого джоба должен быть трекер игрового времени. Нужно добавить сюда прототип трекера:
```
- type: playTimeTracker
  id: JobCentcommOfficer
```
и добавить на него ссылку в прототип джоба с помощью поля playTimeTracker, куда вписывается ID трекера:
```
playTimeTracker: JobCentcommOfficer
```

2024-01-07 10:31 UTC, TheArturZh commented on Resources/Prototypes/SS220/Roles/Jobs/СentComm/NanoTrasenOfficer.yml
> +  - AllAccess
у дипломата та же проблема

2024-01-07 10:32 UTC, TheArturZh commented
расписал всё на что игра рулагась, как запустятся тесты может еще что-то всплывёт

2024-01-07 10:34 UTC, TheArturZh commented on Resources/Prototypes/SS220/Roles/Jobs/СentComm/NanoTrasenOfficer.yml
> +  - AllAccess
`supervisors: job-supervisors-hos`
ну и то что у ОЦК хос начальник это конечно кек

2024-01-07 10:42 UTC, TheArturZh commented on Resources/Prototypes/SS220/Roles/Jobs/СentComm/NanoTrasenNavyOfficer.yml
> +      state: nanotrasennavyofficer
Ссылается на текстурку centnnavyofficer, но такой в SS220/Markers/jobs.rsi нет. мб centnnavyofficer.png?

2024-01-07 10:46 UTC, TheArturZh commented on Resources/Prototypes/SS220/Entities/Objects/Misc/pen.yml
> +    sprite: Textures/SS220/Objects/Tools/pen.rsi
Оно само дописывает /Textures/ в начале пути, из-за чего получается несуществующий путь и спрайт ручки не грузится
нужно вписать вместо этого `SS220/Objects/Tools/pen.rsi`

2024-01-07 14:58 UTC, Ady4ik commented
@TheArturZh все сделал по инструкции, но видимо где-то остался косяк. Не хочет спавнить, потому что не видит прото КПК. Хотя КПК сделан правильно...

2024-01-07 19:30 UTC, TheArturZh commented on Resources/Prototypes/SS220/Entities/Objects/Devices/centcomm_newpda.yml
> +    state: centcommnew_pda
20 линия всё еще неправильный отступ

2024-01-07 20:02 UTC, Ady4ik commented
Ура оно спавнит, но пока не надо мерджить, там ещё куча дел осталось

2024-01-07 20:09 UTC, Ady4ik commented
Увожу пока в драфт, спасибо большое артур за помощь

2024-01-07 20:10 UTC, Ady4ik commented
Спасибо большое артур за помощь, но пока ещё дел тут предстоит миллионы и тонны

2024-01-08 11:20 UTC, FriedrichStrassen commented
а что ещё осталось?

2024-01-12 10:23 UTC, Ady4ik commented
Вылезла проблема, что centcommnew_pda не видит стейтов BasePDA, следовательно, надо либо перенести спрайт в папку, где лежат все ПДА, либо делать дупликацию (мне не нравится такое)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/141335742/d6e8451d-2226-4399-9d7c-d13a415e097a)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/141335742/4f011627-947c-4519-985d-f116569f51af)

2024-01-16 07:01 UTC, FriedrichStrassen commented
Насколько я помню, берет ЦК есть ещё в мешке с вещами блауэршилда. Можно в принципе ему закинуть. Тогда синий щит и ГСН будут выглядеть одинаково. Собственно Синий Щит и является выходцем из этой структуры по бэку своему. 
Нужно ли это - я сам не знаю, так что можешь подумать надо ли или нет

2024-04-15 13:57 UTC, ZoNeSRuS commented
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/42711621/ec878657-599b-429e-bee7-e7962180d4a6)
Новая код база от адуча

2024-04-18 07:54 UTC, closed without merging