Rebalance Cargo
SerbiaStrong-220/space-station-14 pull request #655
Opened 2024-01-13 17:30 UTC by 21Melkuu

## Описание PR

Ребаланс цен баунти карго, возможные будущие правки.

**Проверки**

- [ x ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ x ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ x ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ x ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

Полный список изменений можно просмотреть тут:  https://discord.com/channels/1097181193939730453/1190335711551950918

:cl: 21Melkuu
- tweak: Измены цены баунти карго

2024-01-13 17:32 UTC, Kit0vras commented
они же чинили баунти и заказы больше не повторяются, разве нет?

2024-01-13 17:33 UTC, Kit0vras commented on Resources/Locale/en-US/cargo/bounties.ftl
убирай, во первых, не в тот файл, во вторых - просто сделаем черри-пик переводов, где это уже сделано

2024-01-13 17:37 UTC, 21Melkuu commented on Resources/Locale/en-US/cargo/bounties.ftl
ниче не пон, почему это не тот файл и чеза пики

2024-01-13 17:45 UTC, Kit0vras requested changes

2024-01-13 17:45 UTC, Kit0vras commented on Resources/Prototypes/Catalog/Bounties/bounties.yml
> +    amount: 2
```suggestion
    amount: 2 #ss220 Rebalance
```

2024-01-13 17:45 UTC, Kit0vras commented on Resources/Prototypes/Catalog/Bounties/bounties.yml
> +  reward: 4000 #ss220 Rebalance
но ты же ничего не изменил, зачем коммент

2024-01-13 17:45 UTC, Kit0vras commented on Resources/Prototypes/Catalog/Bounties/bounties.yml
> +    amount: 4
```suggestion
    amount: 4 #ss220 Rebalance
```

2024-01-13 17:45 UTC, Kit0vras commented on Resources/Prototypes/Catalog/Bounties/bounties.yml
> +    amount: 5
```suggestion
    amount: 5 #ss220 Rebalance
```

2024-01-13 17:45 UTC, Kit0vras commented on Resources/Prototypes/Catalog/Bounties/bounties.yml
> +### - ss220 new Bounty
Переноси все наши новые баунти в `Resources/Prototypes/SS220/Catalog/Bounties/bounties.yml`

2024-01-13 17:45 UTC, Kit0vras commented on Resources/Prototypes/Catalog/Bounties/bounties.yml
> +  description: Химики НаноТрейзен, обнаружили мощный химикат в растениях вида Смертокрапива. Данный яд используется для бесопасности при изучении опасной фауны.
```suggestion
  description: Химики NanoTrasen обнаружили мощный химикат в растениях вида Смертокрапива. Данный яд используется для сдерживания опасной фауны при её изучении. Постарайтесь добыть её.
```

2024-01-13 17:45 UTC, Kit0vras commented on Resources/Prototypes/Catalog/Bounties/bounties.yml
> +  description: Медики НаноТрейзен, обнаружили новый способ добычи Омнизина. Происходит массовая закупка данного вида для синтеза мощных медикоментов.
```suggestion
  description: Лучшие умы компании обнаружили новый трудозатратный способ синтеза секретного препарата. Спасите несколько жизней, отправив нам Амброзию Деус.
```

2024-01-13 17:45 UTC, Kit0vras commented on Resources/Locale/en-US/cargo/bounties.ftl
А. я понял, это не перевод, а наши. Тогда делай это в нашем файле - `Resources/Locale/ru-RU/ss220/cargo/bounties.ftl`

2024-01-13 17:45 UTC, Kit0vras commented on Resources/Prototypes/Catalog/Bounties/bounties.yml
> +  description: Сумашедшие повара придумали новый деликатес с участием ШАРА СЛИЗИ! Им срочно нужны новые постащики. Фу...Какая мерзость.
```suggestion
  description: Невероятные повара придумали новый деликатес из ШАРА СЛИЗИ! Им срочно нужны новые поставщики. Удовлетворите вкус этих гурманов, отправив несколько шаров слизи.
```

2024-01-13 17:46 UTC, Kit0vras commented
@21Melkuu

2024-01-13 18:20 UTC, 21Melkuu commented
так-с.. ну вроде все поправил с новым комитом

2024-01-13 18:32 UTC, Kit0vras requested changes

2024-01-13 18:32 UTC, Kit0vras commented on Resources/Prototypes/Catalog/Bounties/bounties.yml
> +    amount: 5
```suggestion
    amount: 5 #ss220 Rebalance
```

2024-01-13 18:32 UTC, Kit0vras commented on Resources/Prototypes/Catalog/Bounties/bounties.yml
> +### - ss220 new Bounty
@21Melkuu

2024-01-13 20:04 UTC, ZoNeSRuS commented
это что БАЛАНС МЕЛКОГО?

2024-01-13 21:39 UTC, 21Melkuu commented
ну теперь точно все

2024-01-13 21:40 UTC, 21Melkuu commented
> это что БАЛАНС МЕЛКОГО?

Да, гимн терпения.

2024-01-13 21:53 UTC, Kit0vras requested changes

2024-01-13 21:53 UTC, Kit0vras commented on Resources/Prototypes/Atmospherics/gases.yml
> +  pricePerMole: 13
```suggestion
  pricePerMole: 13 #ss220 Rebalance
```
Проглядел просто :(

2024-01-13 21:54 UTC, Kit0vras commented
в принципе, если на названия уже сделал локали, то может описания тоже туда перенести?

2024-01-13 22:08 UTC, 21Melkuu commented
> в принципе, если на названия уже сделал локали, то может описания тоже туда перенести?

нет, крашит, название не впихнуть

2024-01-13 22:12 UTC, Kit0vras commented
> > в принципе, если на названия уже сделал локали, то может описания тоже туда перенести?
> 
> нет, крашит, название не впихнуть

не названия к описаниям, а описания к названиям

2024-01-19 09:42 UTC, Kit0vras commented
> > > в принципе, если на названия уже сделал локали, то может описания тоже туда перенести?
> > 
> > 
> > нет, крашит, название не впихнуть
> 
> не названия к описаниям, а описания к названиям

@21Melkuu

2024-01-19 09:43 UTC, Kit0vras requested changes
описания в ftl

2024-01-19 12:21 UTC, 21Melkuu commented
> описания в ftl

Да нахуя оно нужно, кто мне блять объяснит, кроме тго факта, что мне нужно делать комит

2024-01-19 12:29 UTC, Kit0vras commented
> > описания в ftl
> 
> Да нахуя оно нужно, кто мне блять объяснит, кроме тго факта, что мне нужно делать комит

чтобы у тебя не было срача и названия с описаниями лежали в одном месте
это дело на пять минут

2024-01-19 14:00 UTC, Kit0vras approved these changes

2024-01-21 22:43 UTC, 21Melkuu commented
@TheArturZh

2024-01-22 00:07 UTC, TheArturZh approved these changes

2024-01-22 00:07 UTC, merged