Ретекстур шахмат, шашек и доски для них
SerbiaStrong-220/space-station-14 pull request #659
Opened 2024-01-15 07:24 UTC by TTTomaTTT

## Описание PR

Ретекстур шахмат и шашек.

**Медиа**

![Sprite-0002](https://github.com/SerbiaStrong-220/space-station-14/assets/155060886/6f018fdf-5400-47a0-b5fb-d3a3b6855d9d)
![Sprite-0006](https://github.com/SerbiaStrong-220/space-station-14/assets/155060886/0b40c760-0fec-4d58-81a8-fceecb2a5fca)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/155060886/678557bb-9d3a-4648-a82b-57395831fb3e)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- tweak: Изменены текстуры шахматной доски, шахматных фигур и шашек.
<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-01-15 08:05 UTC, Ady4ik commented
Лучше будет, если ты сделаешь отдельно спрайты в ss220 и просто поменяешь путь к спрайтам для шашек и шахмат, оставив оригинальные в файлах, на всякий случай

2024-01-15 20:57 UTC, Kit0vras requested changes

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/checkers.yml
> +    sprite: SS220/Objects/Fun/Tabletop/chessboard.rsi
```suggestion
    sprite: SS220/Objects/Fun/Tabletop/chessboard.rsi #SS220-Tabletop-Resprite
```
Ну и такой же коммент везде ниже, где ты в офф файлах менял путь. Это так, на всякий случай

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/checkers.yml
> +    sprite: SS220/Objects/Fun/Tabletop/chessboard_tabletop.rsi
```suggestion
    sprite: SS220/Objects/Fun/Tabletop/chessboard_tabletop.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/checkers.yml
> +      sprite: SS220/Objects/Fun/Tabletop/checker_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/checker_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/checkers.yml
> +      sprite: SS220/Objects/Fun/Tabletop/checker_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/checker_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/checkers.yml
> +      sprite: SS220/Objects/Fun/Tabletop/checker_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/checker_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/checkers.yml
> +      sprite: SS220/Objects/Fun/Tabletop/checker_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/checker_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +    sprite: SS220/Objects/Fun/Tabletop/chessboard.rsi
```suggestion
    sprite: SS220/Objects/Fun/Tabletop/chessboard.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +    sprite: SS220/Objects/Fun/Tabletop/chessboard_tabletop.rsi
```suggestion
    sprite: SS220/Objects/Fun/Tabletop/chessboard_tabletop.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +    sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi
```suggestion
    sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:57 UTC, Kit0vras commented on Resources/Prototypes/Entities/Objects/Fun/Tabletop/chess.yml
> +      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi
```suggestion
      sprite: SS220/Objects/Fun/Tabletop/chess_pieces.rsi #SS220-Tabletop-Resprite
```

2024-01-15 20:58 UTC, Kit0vras commented
Если новые шашки-шахматы-доска твои - то перекинь в мете лицензию и копирайт на себя и нас

2024-01-16 16:20 UTC, TheArturZh approved these changes

2024-01-16 16:20 UTC, merged