engReb
SerbiaStrong-220/space-station-14 pull request #663
Opened 2024-01-19 17:24 UTC by ZoNeSRuS

## Описание PR

Изменение инженерии, что бы подчеркнуть важность главного движка.
Дам: количество запчастей в ящике 9>12
ТЭГ: Удален со всех карт
Карго: Добавлена возможность купить ТЭГ.

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: ZoNeSRuS
- add: ТЭГ можно купить в карго за 2к.
- remove: ТЭГ удален со всех карт.
- tweak: Количество деталей в ДАМе 9>12

2024-01-19 17:31 UTC, Kit0vras requested changes

2024-01-19 17:31 UTC, Kit0vras commented on Resources/Prototypes/SS220/Catalog/Fills/Crates/engines.yml
> +  name: Ящик с двигателем ТЭГ
```suggestion
  name: ящик с двигателем ТЭГ
```
Я точно не помню, но по идее, в товарах названия всё также с маленькой буквы идут, не?

2024-01-19 17:31 UTC, Kit0vras commented on Resources/Prototypes/SS220/Catalog/Fills/Crates/engines.yml
> +  description: Упакован БС технологией, не открывать
```suggestion
  description: Упакован с помощью блюспейс технологии. Не открывать!
```

2024-01-19 17:31 UTC, Kit0vras commented on Resources/migration.yml
> +# 2024-01-20 - ss220 engreb
```suggestion
# 2024-01-20 - ss220 engineering rebalance
```
Кукурузник того, кто посмотрит на это через год, представь
Кто такой этот ваш энгреб и нужно ли заедать это хлебом?

2024-01-20 16:34 UTC, Kit0vras approved these changes

2024-01-20 17:22 UTC, SkaldetSkaeg commented
там народ запросил повышение цены ТЭГа

2024-01-21 02:46 UTC, TheArturZh approved these changes

2024-01-21 02:46 UTC, merged