Reb
SerbiaStrong-220/space-station-14 pull request #685
Opened 2024-01-27 20:45 UTC by 21Melkuu

Одобрение адуча, трекер: https://discord.com/channels/1097181193939730453/1200071538095951872
## Описание PR

Описание все в трекере

**Проверки**

- [ X ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ X ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ X ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ X ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: 21Melkuu
- add: Новое изучение в т2 инженерной ветке - термоэлектрический генератор
- remove: Удален ТЭГ из карго
- remove: Удалены газодобытчики диоксид азота и водяного пара 
- tweak: Количество топлива дама 1000 -> 500
- tweak: Количество молей плазмы в баллоне 2,5 молей -> 5 молей
- tweak: Замена газодобытчиков с 4500 кпа на 1000 кпа на некоторых картах
- tweak: Изоляционные перчатки в ИнжеМате 1 -> 2

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.

2024-01-27 21:05 UTC, ZoNeSRuS commented
Немного не понял, поче му бы добытчики не унифицировать через мигоацию?

2024-01-27 21:07 UTC, 21Melkuu commented
> Немного не понял, почему бы добытчики не унифицировать через миграцию?

да хз, потому что на некоторых картах он стоит верно, на некоторых нет. Ну могу ебнуть миграцию, если такой вариант не заходит

2024-01-27 21:11 UTC, Kit0vras commented
> Немного не понял, почему бы добытчики не унифицировать через миграцию?

потому что если кислород и азот тоже через миграцию менять, то ты буквально запретишь кому-угодно где угодно юзать 4500, потому что они будут заменяться на 1000, так что он правильно сделал

@21Melkuu может газодобытчики пара и со2 тоже просто из карт сотрёшь, а не мигрируешь? потому что в случае миграции их буквально нельзя юзать, а может кому то шиза придёт в чём то необычном их использовать (ну да, ну да, так я и поверил, ну и бред)

2024-01-27 21:11 UTC, DexlerXD commented
мерж конфликтииии

2024-01-27 21:12 UTC, Kit0vras requested changes

2024-01-27 21:12 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Devices/Circuitboards/Machine/production.yml
> +  description: Печатная плата для термоэлектрического генератора циркуляционного насоса
```suggestion
  description: Печатная плата для циркуляционного насоса термоэлектрического генератора.
```

2024-01-27 21:12 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Devices/Circuitboards/Machine/production.yml
> +  description: Печатная плата для термоэлектрического генератора
```suggestion
  description: Печатная плата для термоэлектрического генератора.
```

2024-01-27 21:15 UTC, 21Melkuu commented
@Kit0vras на других приставках ss220 тоже заменить или только те что в ротации?

2024-01-27 21:16 UTC, Kit0vras commented
> @Kit0vras на других приставках ss220 тоже заменить или только те что в ротации?

только ротацию

2024-01-28 00:03 UTC, 21Melkuu commented
вот би помощи по чеку....

2024-01-28 16:51 UTC, 21Melkuu commented
А ГОСПОДИ ОНО ЗАРАБОТАЛО

2024-01-28 16:51 UTC, 21Melkuu commented
@TheArturZh

2024-01-28 17:51 UTC, DexlerXD approved these changes

2024-01-28 17:52 UTC, merged