NewBarricade
SerbiaStrong-220/space-station-14 pull request #696
Opened 2024-01-31 14:38 UTC by EstKemran

## Описание PR

https://discord.com/channels/1097181193939730453/1200711354013716581
Баррикады из трех материалов. Баррикады обычные, направленные и напольные. Первые два вида имеют компонент Occluder, последний нет. Отличаются стоимостью материалов и прочностью. Эти баррикады можно строить на стене/окне, а так же разрушить с помощью ближнего боя (В отличии от оффских). Эти баррикады в первую очередь защищают то, к чему они прикреплены(В отличии от оффских).

**ОШИБКА!** Возникает ошибка Construction: Invalid construction graph 'BarricadeSteel' in recipe 'BarricadeSteel'!. Исправить не смог. Help. PR **незавершён** и мне **нужна помощь** чтобы его закончить. 

**Медиа**

![Content Client_fXWdpFYN54](https://github.com/SerbiaStrong-220/space-station-14/assets/157578255/beb007f8-64b3-40fd-b4fb-bbbe218b6a68)
![Content Client_MHqyAy6CXM](https://github.com/SerbiaStrong-220/space-station-14/assets/157578255/15f963b3-392f-4eb2-ad1e-c66f2c8cf811)
![Content Client_8Pm0TcokRE](https://github.com/SerbiaStrong-220/space-station-14/assets/157578255/1e34adc4-bc02-4454-b524-029bf8211777)

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [✓] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
- add: Добавлено 9 новых баррикад

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-01-31 15:03 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  parent: EstBaseBarricade
```suggestion
  parent: BaseBarricade220
```

2024-01-31 15:03 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  id: EstBaseBarricadeDirectional
```suggestion
  id: BaseBarricadeDirectional220
```

2024-01-31 15:04 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  id: EstBaseBarrucadeFloor
```suggestion
  id: BaseBarricadeFloor220
```

2024-01-31 15:04 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  parent: EstBaseBarricade
```suggestion
  parent: BaseBarricade220
```

2024-01-31 15:05 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  parent: EstBaseBarricadeDirectional
```suggestion
  parent: BaseBarricadeDirectional220
```

2024-01-31 15:06 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  parent: EstBaseBarricade
```suggestion
  parent: BaseBarricade220
```

2024-01-31 15:07 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  - type: Sprite
```suggestion
  - type: Sprite
```
перенеси путь к спрайту в базовые баррикады, и у наследуемых пиши
  - type: Sprite
    state: стейт спрайта

2024-01-31 15:09 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +    noRot: false
```suggestion
    noRot: false 
```
они же по умолчанию и так крутятся, нет? получается можно просто стереть

2024-01-31 15:09 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  parent: EstBaseBarricade
```suggestion
  parent: BaseBarricade220
```

2024-01-31 15:10 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +        damage: 440
```suggestion
        damage: 440
```
имхо многовато хп для постройки из пары кусков стали

2024-01-31 15:11 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  parent: EstBaseBarricadeDirectional
```suggestion
  parent: BaseBarricadeDirectional220
```

2024-01-31 15:11 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  parent: EstBaseBarricadeDirectional
```suggestion
  parent: BaseBarricadeDirectional220
```

2024-01-31 15:12 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  parent: EstBaseBarrucadeFloor
```suggestion
  parent: BaseBarricadeFloor220
```

2024-01-31 15:12 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  parent: EstBaseBarrucadeFloor
```suggestion
  parent: BaseBarricadeFloor220
```

2024-01-31 15:13 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  parent: EstBaseBarrucadeFloor
```suggestion
  parent: BaseBarricadeFloor220
```

2024-01-31 15:13 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  name: Напольная укрепленная баррикада
```suggestion
  name: напольная укрепленная баррикада
```

2024-01-31 15:13 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  name: Напольная стальная баррикада
```suggestion
  name: напольная стальная баррикада
```

2024-01-31 15:17 UTC, Kit0vras commented
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/d52c3142-aecc-4bfa-92af-d2c9d4c79389)
тут ты добавил 2 одинаковых файла, а самих рецептов нет

в отредактированные айди я подописывал 220, потому что не знаю, могут ли они совпасть с айди оффовскими баррикад, если нет - то 220 тоже можно убрать

2024-01-31 15:29 UTC, EstKemran commented
@Kit0vras Добавил нужный прототип. Проверь его пожалуйста. У меня с ним что-то не получилось.

2024-02-02 10:33 UTC, Kit0vras requested changes

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/Entities/Structures/barricades.yml
> +          bounds: "-0.5,-0.5,0.5,-0.36" #"-0.49,-0.39,0.49,-0.36"  NewBarricade #696
```suggestion
          bounds: "-0.5,-0.5,0.5,-0.36" #SS220-Barricade
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/Recipes/Construction/structures.yml
> +  #conditions: | NewBarricade #696
```suggestion
  #conditions: #SS220-Barricade
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/Recipes/Construction/structures.yml
> +    #- !type:TileNotBlocked | NewBarricade #696
```suggestion
    #- !type:TileNotBlocked #SS220-Barricade
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/Recipes/Construction/structures.yml
> +  #conditions: | NewBarricade #696
```suggestion
  #conditions: #SS220-Barricade
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/Recipes/Construction/structures.yml
> +    #- !type:TileNotBlocked | NewBarricade #696
```suggestion
    #- !type:TileNotBlocked #SS220-Barricade
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  description: Баррикада из стальных листов. Защищает вас от чужих глаз. Способен выдержать пулю.
```suggestion
  description: Баррикада из стальных листов. Защищает вас от чужих глаз. Способна выдержать пулю.
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  description: Баррикада из листов пластали. Защищает вас от чужих глаз. Способен выдержать взрыв C4.
```suggestion
  description: Баррикада из листов пластали. Защищает вас от чужих глаз. Способна выдержать взрыв C4.
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  name: укрепленная баррикада
```suggestion
  name: укреплённая баррикада
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  name: деревянная уплотненная баррикада
```suggestion
  name: уплотнённая деревянная баррикада
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  description: Баррикада из стальных листов. Защищает вас от чужих глаз. Способен выдержать пулю.
```suggestion
  description: Баррикада из стальных листов. Защищает вас от чужих глаз. Способна выдержать пулю.
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  description: Баррикада из листов пластали. Защищает вас от чужих глаз. Способен выдержать взрыв C4.
```suggestion
  description: Баррикада из листов пластали. Защищает вас от чужих глаз. Способна выдержать взрыв C4.
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  name: укрепленная баррикада
```suggestion
  name: укреплённая баррикада
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  description: Баррикада небольшой высоты из деревяннах досок. Есть шанс защитить от шальной пули.
```suggestion
  description: Баррикада небольшой высоты из деревянных досок. Есть шанс защитить от шальной пули.
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/barricade.yml
> +  name: напольная укрепленная баррикада
```suggestion
  name: напольная укреплённая баррикада
```

2024-02-02 10:33 UTC, Kit0vras commented on Resources/Textures/SS220/Structures/barricades.rsi/meta.json
> +  "copyright": "#© SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
нет, это идёт как лицензия, если спрайт ты делал сам. В копирайте указывается автор. К примеру:
`Made by QWERTY123 (Github) for SS220.`
или
`Made by QWERTY123 (Discord) for SS220.`
или
`Made by QWERTY123 (Discord/Github) for SS220.`
В зависимости от того, какой ник ты указываешь в копирайте и отличаются ли они у тебя на гите и дс. Это чтоб тебя потом смогли отыскать в случае чего

2024-02-02 10:34 UTC, Kit0vras commented
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/1512c0ce-3bbf-4dc6-887e-e23e620eb758)

2024-02-02 11:08 UTC, TheArturZh commented on Resources/Textures/SS220/Structures/barricades.rsi/meta.json
> +  "copyright": "#© SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
в поле license пишется `EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt`

2024-02-02 11:21 UTC, TheArturZh commented on Resources/Textures/SS220/Structures/barricades.rsi/meta.json
> +  "license": "© SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
```suggestion
  "license": "EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt",
```
именно в таком виде, иначе не пройдёт тест

2024-02-02 11:29 UTC, TheArturZh commented on Resources/Textures/SS220/Structures/barricades.rsi/meta.json
> +  "copyright": "Sprited by EstKemran (Github) for SS220"
```suggestion
  "copyright": "Sprited by EstKemran (Github) for SS220",
```
падают тесты из-за отсутствия запятой

2024-02-02 11:43 UTC, EstKemran commented
Уменьшить количество стали с 2-ух до 1-ого при разборе?

2024-02-02 11:53 UTC, TheArturZh commented
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/16546901/e1dde2d0-3e2d-473e-8802-3c70c3a3b193)

2024-02-02 11:57 UTC, EstKemran commented
@TheArturZh Посмотри последний коммит, и если все нормально, запусти пожалуйста тест снова

2024-02-02 13:14 UTC, EstKemran commented
АААААА! Наконец-то он заработал. Огромное вам спасибо, Kit0vras, TheArturZh.

2024-02-02 13:17 UTC, TheArturZh approved these changes

2024-02-02 13:18 UTC, merged