MinorTweaks
SerbiaStrong-220/space-station-14 pull request #698
Opened 2024-02-01 20:05 UTC by EstKemran

## Описание PR

https://discord.com/channels/1097181193939730453/1199704860724039740
https://discord.com/channels/1097181193939730453/1201181146411700334
Маленькие изменения по трекерам

**Медиа**

**Проверки**

- [+] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [+] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [+] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [+] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
- add: Добавлено два магазина ПП с резиновыми патронами в сейф Офицера "Синего Щита"
- add: Добавлен нож в ботинки Офицера "Синего Щита"
- remove: Убран станнер из сейфа Офицера "Синего Щита"
- remove: Убран визор охраны из шкафа Смотрителя
- tweak: Изменен магазин в дрозде из сейфа Офицера "Синего щита
- tweak: Изменены резисты скафандра Бригмедика. Уменьшен вес скафандра в обмен на его защитные свойства
- tweak: Одежда Смотрителя из его шкафа перекачивала в комод

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-02-01 20:48 UTC, Kit0vras requested changes

2024-02-02 10:26 UTC, DexlerXD commented
жду комментария на обсуждение характеристик

2024-02-02 10:37 UTC, Kit0vras requested changes

2024-02-02 10:37 UTC, Kit0vras commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        Blunt: 0.85 #0.8 #SS220-MinorTweaks start
```suggestion
        Blunt: 0.85 #SS220-MinorTweaks start
```

2024-02-02 10:37 UTC, Kit0vras commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        Slash: 0.85 #0.8
```suggestion
        Slash: 0.85
```

2024-02-02 10:37 UTC, Kit0vras commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +        Piercing: 0.80 #0.7
```suggestion
        Piercing: 0.80
```

2024-02-02 10:37 UTC, Kit0vras commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    walkModifier: 0.90 #0.65 SS220-MinorTweaks
```suggestion
    walkModifier: 0.90 #SS220-MinorTweaks
```

2024-02-02 10:37 UTC, Kit0vras commented on Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
> +    sprintModifier: 0.90 #0.65 SS220-MinorTweaks
```suggestion
    sprintModifier: 0.90 #SS220-MinorTweaks
```

2024-02-02 10:37 UTC, Kit0vras commented on Resources/Prototypes/Roles/Jobs/Command/blue_shield.yml
> +#    shoes: ClothingShoesBootsJack #SS220-MinorTweaks
```suggestion

```

2024-02-02 10:37 UTC, Kit0vras commented on Resources/Prototypes/Roles/Jobs/Command/blue_shield.yml
> +#    shoes: ClothingShoesBootsJack #SS220-MinorTweaks
Это наша роль, так что можно не комментить, а просто удалить строку и всё

2024-02-02 15:24 UTC, EstKemran commented
Одобрение на изменение характеристик скафандра получено

2024-02-02 20:27 UTC, Ady4ik commented
@DexlerXD лей

2024-02-02 20:45 UTC, DexlerXD approved these changes

2024-02-02 20:45 UTC, merged