clearupgarbage command
SerbiaStrong-220/space-station-14 pull request #706
Opened 2024-02-03 02:50 UTC by Lazzi0706

## Описание PR

Небольшое изменение в коде команды для однородности с [clearspentammo](https://github.com/SerbiaStrong-220/space-station-14/pull/702)
**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- tweak: Команда очистки "ClearUpGarbage" переведена в нижний регистр -> "clearupgarbage"
- tweak: Русифицировано описание команды

2024-02-03 08:18 UTC, DexlerXD requested changes
тестикииии

2024-02-03 08:18 UTC, DexlerXD commented on client_output.txt
> +[DEBG] root: OS: Microsoft Windows 10.0.18363 X64
???

2024-02-03 09:30 UTC, Lazzi0706 commented on client_output.txt
> +[DEBG] root: OS: Microsoft Windows 10.0.18363 X64
> ???

xddddddddddddddddddddddd

2024-02-03 11:52 UTC, TheArturZh commented
Тест упал по причине тест хуйня

2024-02-04 15:35 UTC, DexlerXD approved these changes

2024-02-04 16:27 UTC, merged