Фракционная война-апдейт
SerbiaStrong-220/space-station-14 pull request #713
Opened 2024-02-04 19:36 UTC by VladIsLove-e

## Описание PR

Обновлены все суффиксы, добавлено 7 видов брони синдика , обновлена экипировка ивентовых челов, добавлены ботинки, маска, рюкзак синдиката, починено энерго оружие(ивентовое), починены иконки персонажей ивентовые,  починил и обновил в новый дизайн карты сссп, балансные правки брони и кажется всё.
**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl:
- tweak: Возвращён VladIsLove.

2024-02-04 19:50 UTC, Kit0vras requested changes

2024-02-04 19:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Neck/iron_squad_cloaks.yml
>    description: Этот плащ не только нарушает любые санитарные нормы, но и наделяет таким авторитетом надевшего его, что о первом никто не смеет упомянуть.
```suggestion
  description: Этот плащ не только нарушает любые санитарные нормы, но и наделяет владельца таким авторитетом, что его никто не посмеет обсуждать за спиной.
```
о ком первом?
упомянуть о чём? как?

2024-02-04 19:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Neck/iron_squad_cloaks.yml
>    description: Снаружи жесткая ткань с отчётливо видными следами тления, а внутри слышится стойкий аромат машинного масла.
```suggestion
  description: Снаружи жёсткая ткань с отчётливо видными следами тления, а внутри слышится стойкий аромат машинного масла.
```

2024-02-04 19:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/Specific/EventPointCapture/postament.yml
>    description: Постамент для флага. Для захвата установите сюда флаг вашей фракции.
```suggestion
  description: Постамент для флага. Для захвата, установите сюда флаг вашей фракции.
```

2024-02-04 19:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Shitspawn/Ebent/CustomItems.yml
>    description: Модифицированный модульный интерком синдиката, надеваемый на голову, и содержащий ключ шифрования. Имеет 5 ячеек для ключей шифрования.
```suggestion
  description: Модифицированный модульный интерком синдиката, надеваемый на голову и содержащий ключ шифрования. Имеет 5 ячеек для ключей шифрования.
```

2024-02-04 19:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Shitspawn/Ebent/HardsuitIronSquad.yml
> +  description: Тяжёлый боевой костюм обшитый сонариумовым сплавом, используется железным отрядом в самых тяжёлых схватках.
```suggestion
  description: Тяжёлый боевой костюм, обшитый сонариумовым сплавом. Используется железным отрядом в самых тяжёлых схватках.
```

2024-02-04 19:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Shitspawn/Ebent/HardsuitIronSquad.yml
> +  description: Тяжёлый боевой костюм обеспечивающий большую защиту ценой пониженной мобильности.
```suggestion
  description: Тяжёлый боевой костюм, обеспечивающий большую защиту ценой пониженной мобильности.
```

2024-02-04 19:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Shitspawn/Ebent/HardsuitIronSquad.yml
> +  description: Боевой скафандр соблюдающий баланс между мобильностью и защитой носителя.
```suggestion
  description: Боевой скафандр, соблюдающий баланс между мобильностью и защитой носителя.
```

2024-02-04 19:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Shitspawn/Ebent/HardsuitIronSquad.yml
> +  description: Скафандр изготовленный из полимерных титановых нанотрубок с встроенными ускорителями, обеспечивает приличную защиту и ускоренное перемещение.
```suggestion
  description: Скафандр, изготовленный из полимерных титановых нанотрубок с встроенными ускорителями. Обеспечивает приличную защиту и ускоренное перемещение.
```

2024-02-04 19:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Shitspawn/Ebent/HardsuitIronSquad.yml
> +  description: Улучшенная версия скафандра Cyanide, обеспечивает ещё больше защиты и манёвренности.
```suggestion
  description: Улучшенная версия скафандра Cyanide. Обеспечивает ещё больше защиты и манёвренности.
```

2024-02-04 19:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Shitspawn/Ebent/HardsuitIronSquad.yml
> +  description: Лёгкий и прочный скафандр обеспечит радиационную защиту и высокую мобильность.
```suggestion
  description: Лёгкий и прочный скафандр, обеспечивающий радиационную защиту и высокую мобильность.
```

2024-02-04 19:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Shitspawn/Ebent/hardsuit-helmetsIronSquad.yml
> +  description: Толстый слой металла обеспечитвает активную защиту от пуль, лазеров, но не от пота.
```suggestion
  description: Толстый слой металла обеспечивает активную защиту от пуль и лазеров, но не от пота.
```

2024-02-04 19:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Shitspawn/Ebent/hardsuit-helmetsIronSquad.yml
> +  description: Тонкий слой металического листа с мягкой обшивкой из шерсти неизвестного происхождения.
```suggestion
  description: Тонкий слой металлического листа с мягкой обшивкой из шерсти неизвестного происхождения.
```

2024-02-04 19:50 UTC, Kit0vras commented on Resources/Prototypes/SS220/Shitspawn/Ebent/hardsuit-helmetsIronSquad.yml
> +  description: Яркий дизайн и смертоносное исполнение- в лучших традициях CryTech technology.
```suggestion
  description: Яркий дизайн и смертоносное исполнение - в лучших традициях CryTech technology.
```

2024-02-04 20:17 UTC, spo9k commented
😲

2024-02-04 20:48 UTC, VladIsLove-e commented
Сюдаааа тесты

2024-02-05 17:46 UTC, DexlerXD approved these changes

2024-02-05 17:46 UTC, merged