acceleration rounding
SerbiaStrong-220/space-station-14 pull request #715
Opened 2024-02-05 08:35 UTC by Lazzi0706

## Описание PR

Убран -0.0 с UI консоли управления шаттла
**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- fix: Исправлено некорректное отображение ускорения в интерфейсе консоли управления шаттлом (-0.0 -> 0.0)

2024-02-05 10:49 UTC, TheArturZh requested changes
Округление до целого это слишком сильно, нужна 1 знака после запятой как раньше
Между 0.51 тайла в секунду и 1 тайлом в секунду есть существенная разница
https://learn.microsoft.com/ru-ru/dotnet/api/system.math.round?view=net-8.0#system-math-round(system-double-system-int32-system-midpointrounding)

2024-02-05 10:49 UTC, TheArturZh commented on Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml.cs
> +        GridAngularVelocity.Text = $"{Math.Round(gridBody.AngularVelocity):0.0}";
зачем убран минус?

2024-02-11 09:10 UTC, Lazzi0706 commented on Content.Client/Shuttles/UI/ShuttleConsoleWindow.xaml.cs
> +        GridAngularVelocity.Text = $"{Math.Round(gridBody.AngularVelocity):0.0}";
> зачем убран минус? получается AngularVelocity направлен полностью в другую сторону

Окей, сейчас доделаю другие вещи и займусь этим

2024-04-14 14:10 UTC, ZoNeSRuS commented
@Ady4ik Офы уже поменяли консоль шаттла. Думаю пр можно просто закрыть.

2024-04-15 14:37 UTC, Ady4ik commented
@DexlerXD закрываем

2024-04-15 20:17 UTC, closed without merging