Анимации крыльев Нианов
SerbiaStrong-220/space-station-14 pull request #719
Opened 2024-02-07 12:44 UTC by Xenoksys

## Описание PR

**Медиа**

https://github.com/SerbiaStrong-220/space-station-14/assets/108728328/f6c34fe7-abfa-4d81-9a04-d309b159a6fb

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Анимации крыльев нианов

2024-02-07 12:52 UTC, SkaldetSkaeg commented
Медиа точно надо бы

2024-02-07 12:58 UTC, Xenoksys commented
> Медиа точно надо бы

Реди

2024-02-07 18:22 UTC, SkaldetSkaeg commented
Я не спрайтер, но в кнопку бы другой спрайт.

2024-02-07 18:33 UTC, DexlerXD requested changes
WavingSystem, во-первых, лежит не в нашей папке, про копирайт говорить и смысла нет. Во-вторых, очевидно, система скопипащена. Надо использовать либо оригинальную систему, либо сделать помарку, что система взята откуда-то и т. п. (но чистый копипаст всё равно использовать нельзя).

2024-02-10 01:25 UTC, WhitlyOfficial commented
### Ревью по спрайтам
1. Нужно исправить иконку действия
2. Исправить линейность анимации
Линейные анимации свойственны машинерии, однако в анимации живых существ должно быть видно нелинейное движение.
В анимации хвостов унатхов это сделано благодаря количеству спрайтов в анимации, наложенных на 0.1 задержку. Тут же и малое количество спрайтов анимации, и большая её задержка.
3. Если и добавлять такую фичу - то на все виды крыльев.
4. Не стоит добавлять эту анимацию, как перманентную. Это пипец как странно выглядит на кошачьих хвостах на трупах, т.к. трупы не способны к движению, а анимки у мертвого тела не останавливаются. В этом случае это будет выглядеть ещё хуже, т.к. область анимации ещё больше.

2024-02-12 10:58 UTC, Xenoksys commented
> ### Ревью по спрайтам
> 
>     1. Нужно исправить иконку действия
> 
>     2. Исправить линейность анимации
>        Линейные анимации свойственны машинерии, однако в анимации живых существ должно быть видно нелинейное движение.
>        В анимации хвостов унатхов это сделано благодаря количеству спрайтов в анимации, наложенных на 0.1 задержку. Тут же и малое количество спрайтов анимации, и большая её задержка.
> 
>     3. Если и добавлять такую фичу - то на все виды крыльев.
> 
>     4. Не стоит добавлять эту анимацию, как перманентную. Это пипец как странно выглядит на кошачьих хвостах на трупах, т.к. трупы не способны к движению, а анимки у мертвого тела не останавливаются. В этом случае это будет выглядеть ещё хуже, т.к. область анимации ещё больше.

Ваше мнение для нас очень важно, но не очень то и нужно
Людям понравилось

2024-02-12 11:14 UTC, WhitlyOfficial commented
> > ### Ревью по спрайтам
> > ```
> > 1. Нужно исправить иконку действия
> > 
> > 2. Исправить линейность анимации
> >    Линейные анимации свойственны машинерии, однако в анимации живых существ должно быть видно нелинейное движение.
> >    В анимации хвостов унатхов это сделано благодаря количеству спрайтов в анимации, наложенных на 0.1 задержку. Тут же и малое количество спрайтов анимации, и большая её задержка.
> > 
> > 3. Если и добавлять такую фичу - то на все виды крыльев.
> > 
> > 4. Не стоит добавлять эту анимацию, как перманентную. Это пипец как странно выглядит на кошачьих хвостах на трупах, т.к. трупы не способны к движению, а анимки у мертвого тела не останавливаются. В этом случае это будет выглядеть ещё хуже, т.к. область анимации ещё больше.
> > ```
> 
> Ваше мнение для нас очень важно, но не очень то и нужно Людям понравилось

Как жаль, что вы считаете моё мнение не нужным, ведь для мержа ПРа все пункты ревью должны быть выполнены.

2024-05-22 16:16 UTC, Surani1 commented
@Kit0vras @DexlerXD @Xenoksys что с крыльями по итогу?

2024-05-22 18:09 UTC, Kit0vras commented
Либо исправляет замечания, либо закрываем, @DexlerXD ?

2024-05-22 19:42 UTC, closed without merging

2024-05-22 19:42 UTC, DexlerXD commented
ну, продвижений не было, исправлять тут не вижу смысла
если надо, кто-то другой сделает заново