Teleporter grid restriction
SerbiaStrong-220/space-station-14 pull request #722
Opened 2024-02-08 10:10 UTC by SkaldetSkaeg

## Описание PR

При попытке создать второй портал на другом гриде первый портал теперь будет удаляться.
**Медиа**

<img width="304" alt="image" src="https://github.com/SerbiaStrong-220/space-station-14/assets/30115570/425f60d3-1694-40c7-843b-837fabfd1cf3">

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

- tweak: При попытке разместить второй портал в другом гриде теперь первый портал удаляется.
<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-02-08 10:21 UTC, Kit0vras commented
Желательно не на любом другом гриде, а именно на гриде с трейд-постом, разве нет? Хотя тут наверно лучше Адуча спросить
@Ady4ik

2024-02-08 10:29 UTC, Kit0vras commented
Ладно, ты прав, не подумал о таком

2024-02-09 15:48 UTC, DexlerXD commented
@Ady4ik одобряем в итоге?

2024-02-09 15:51 UTC, VladIsLove-e commented
А от радиуса не получится?

2024-02-09 15:52 UTC, VladIsLove-e commented
Это было бы логичнее

2024-02-09 16:07 UTC, Ady4ik commented
Давайте пока рестрикт по гриду, это вполне себе логично, потом может придумаем, как сделать грамотную проверку на расстояние

2024-02-09 18:13 UTC, DexlerXD requested changes

2024-02-09 18:13 UTC, DexlerXD commented on Content.Shared/Teleportation/Components/HandTeleporterComponent.cs
> +using Content.Shared.DoAfter;
*нервный тик в глазу*

2024-02-09 19:01 UTC, SkaldetSkaeg commented on Content.Shared/Teleportation/Components/HandTeleporterComponent.cs
> +using Content.Shared.DoAfter;
Я хз, есть идеи как это менять?
ctrl+c ctrl+v не фиксит

2024-02-09 21:26 UTC, DexlerXD commented on Content.Shared/Teleportation/Components/HandTeleporterComponent.cs
> +using Content.Shared.DoAfter;
> Я хз, есть идеи как это менять? ctrl+c ctrl+v не фиксит

берешь оригинальный файл, вставляешь с заменой и через гит отменяешь все изменения, кроме этого

2024-02-09 21:26 UTC, DexlerXD commented on Content.Shared/Teleportation/Components/HandTeleporterComponent.cs
> +using Content.Shared.DoAfter;
а все уже, хорош

2024-02-09 21:27 UTC, DexlerXD approved these changes

2024-02-09 21:28 UTC, merged