Shlepi
SerbiaStrong-220/space-station-14 pull request #729
Opened 2024-02-12 16:55 UTC by WhitlyOfficial

## Описание PR
База, Базис, Основа спонсорских шмоток.
Требует теста от дяди Вера.

- [ ] Доделать
- [ ] Пофиксить

**Медиа**
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/98218741/5bad1889-5bb0-4d63-85e2-a34767ced35c)

**Проверки**
- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Meower
- add: Добавлены спонсорские предметы
- add: Добавлено выделение ника в OOC чате

2024-02-12 17:11 UTC, Kit0vras requested changes

2024-02-12 17:11 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Sponsor/clothing.yml
> +  description: Простые дешёвые очки с корректирующими линзами
```suggestion
  description: Простые дешёвые очки с корректирующими линзами.
```

2024-02-12 17:11 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Sponsor/clothing.yml
> +  description: Вы - самый обычный семьянин
```suggestion
  description: Вы - самый обычный семьянин.
```

2024-02-12 17:11 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Sponsor/clothing.yml
> +  description: Выглядит очень тяжелой
```suggestion
  description: Выглядит очень тяжёлой.
```

2024-02-12 17:11 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Sponsor/clothing.yml
> +  description: Я - Зубен...
```suggestion
  description: Я - Мафиозник!
```
мне кажется, так лучше впишется, потому что "Зубен" - как то стрёмно (да, я понимаю, что фраза обрывается), и как-то ООС

2024-02-12 17:11 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Sponsor/clothing.yml
> +  description: Самое мужское одеяние
```suggestion
  description: Самое мужественное одеяние.
```
может ты это имела ввиду? мужское - предназначенное для мужчин, мужественное - отражающее мужественность

2024-02-12 17:11 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Sponsor/items.yml
> +  description: Содержит в себе золотой костюм клоуна. Осторожно! Ваших рук не хватит для предметов в наборе!
```suggestion
  description: Содержит в себе золотой костюм клоуна. Осторожно! Набор предметов не поместится в ваших руках!
```
Мне кажется, что так более очевидно, что что-то не влезет в руки, чем абстрактное "ваших рук не хватит на это"
Если да, то ниже - тоже самое сделать

2024-02-14 17:01 UTC, WhitlyOfficial commented
у меня ветка совершила самооткат на локале O_o

2024-02-18 18:06 UTC, DexlerXD requested changes

2024-02-18 18:06 UTC, DexlerXD commented on Content.Server/Chat/Managers/ChatManager.cs
> +            }
```suggestion
            //SS220-shlepi begin
            var SponsorInfo = player.ContentData()?.SponsorInfo;
            if (SponsorInfo is not null && SponsorInfo.Tiers.Any(x => x is not Shared.SS220.Discord.SponsorTier.None))
            {
                wrappedMessage = Loc.GetString("chat-manager-send-ooc-patron-wrap-message", ("patronColor", "#ffe77a"), ("playerName", player.Name), ("message", FormattedMessage.EscapeText(message)));
            }
            //SS220-shlepi end
```

2024-02-18 18:06 UTC, DexlerXD commented on Resources/Prototypes/Corvax/sponsor.yml
пометки на изменения добавить бы

2024-02-18 18:41 UTC, DexlerXD approved these changes

2024-02-18 18:42 UTC, merged