Rufood
SerbiaStrong-220/space-station-14 pull request #738
Opened 2024-02-15 16:16 UTC by 21Melkuu

## Описание PR

https://discord.com/channels/1097181193939730453/1205125239424557056/1205125239424557056 добавление русской кухни. Там же и вся медиа.

**Проверки**

- [ X ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ X ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ X ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ X ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

Добавлены новые блюда и напитки, а так же их рецпеты. Список:
✔️Борщ
Миска+ Мясо+ Картофель+ Ломтик лук+ Свекла+ Вода [10]
✔️Щи
Миска+ Мясо+ Картофель+ Ломтик лука+ Капуста+ Вода [10]
Микроволновка 10 сек
✔️Окрошка
Миска+ Мясо курицы+ Картофель+ Ломтик лука+ Вареное яйцо 
Микроволновка 10 сек
✔️Окрошка на квасе
Миска+ Мясо курицы+ Картофель+ Ломтик лука+ Вареное яйцо + квас [10]
Микроволновка 10 сек
✔️Винегрет
Миска+ Картофель+ Ломтик лука+ Свекла+ Горох+ Морковь
Микроволновка 10 сек
✔️Чебурек
Мясо+ Тесто+ Соль+ Ломтик лука
Микроволновка 15 сек
✔️Шаурма
Тесто+ Мясо курицы+ Майонез+ Капуста+ Помидор+ Ломтик сыра
Микроволновка 15 сек 
✔️Яблочный компот
Яблочный сок + вода
✔️Ягодный компот
Ягодный сок + вода

✔️Добавлены семена свеклы

:cl: 21Melkuu
- add: Добавлены новые блюда, напитки
- add: Добавлена свекла для выращивания

2024-02-15 16:36 UTC, 21Melkuu commented
опять поднимать...

2024-02-15 17:50 UTC, 21Melkuu commented
Чеки я поднял, тот что не прошел, не мое. Ждем мистера адуча, в таком случае

2024-02-15 18:20 UTC, Kit0vras requested changes

2024-02-15 18:20 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss220/reagents/meta/juice.ftl
> +reagent-desc-juice-beet = Сок свеклы
```suggestion
reagent-desc-juice-beet = Сок со сладким вкусом, почему-то ассоциирующийся у вас с грязью.
```

2024-02-15 18:20 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/shawarma.yml
> +  description: Аппетитная начинка, завернутая в лаваш - шаурма, которая всегда поднимает настроение.
```suggestion
  description: Аппетитная начинка, завернутая в лаваш - блюдо, которое всегда поднимает настроение.
```

2024-02-15 18:20 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/shawarma.yml
> +  description: Шаурма, которая поднимает настроение, но только круче!
```suggestion
  description: То же блюдо, поднимающее вам настроение, но только круче!
```

2024-02-15 18:20 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/soup.yml
> +  name: борщ
но ведь в игре уже есть борщ... Просто возьми его и добавь ему рецепт

2024-02-15 18:20 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/soup.yml
> +  description: Холодный суп.
```suggestion
  description: Суп, который можно есть ложкой или пить из бокала в зависимости от настроения.
```

2024-02-15 18:20 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/soup.yml
> +  description: По-настоящему освежающий салат.
```suggestion
  description: Культурное наследие, которое прекрасно охладит вас в жаркий летний день.
```

2024-02-15 18:20 UTC, Kit0vras commented on Resources/Textures/SS220/Objects/Consumable/Drinks/glass_apple.rsi/meta.json
> +    "license": "CC-BY-SA-3.0",
под всю мету ставь нашу лицензию, он же для нас это делал, нет? По крайней мере у SubL точно

2024-02-15 18:20 UTC, Kit0vras commented on Resources/Prototypes/SS220/Flavors/flavors.yml
> +- type: flavor
Флаворы делаются не так.
посмотри в `/Resources/Locale/ru-RU/flavors` и `Resorces/Prototypes/Flavors/flavors.yml`
Комплексные флаворы составляются из локалей

2024-02-15 18:28 UTC, Kit0vras commented
@21Melkuu

2024-02-15 18:36 UTC, 21Melkuu commented on Resources/Textures/SS220/Objects/Consumable/Drinks/glass_apple.rsi/meta.json
> +    "license": "CC-BY-SA-3.0",
у гобавки так и должно, а сабл мне так ничего не ответил насчет лицензии

2024-02-15 18:40 UTC, 21Melkuu commented on Resources/Prototypes/SS220/Flavors/flavors.yml
> +- type: flavor
оно работает, чеки не долбит, зачем мне еще парится над этим? 
А сделал я локализацию для реагентов, потому что долбил чек

2024-02-15 18:42 UTC, 21Melkuu commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/soup.yml
> +  name: борщ
да видел, но заметил, это я когда уже сделал. Плюс спрайты, те что рисовали наносить на старый борщ фигня идея, поэтому новый

2024-02-15 19:07 UTC, Kit0vras commented on Resources/Prototypes/SS220/Flavors/flavors.yml
> +- type: flavor
а ты проверял, как оно работает? у тебя не будет "ням. ням. на вкус как"

2024-02-15 19:08 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/soup.yml
> +  name: борщ
чтобы что и почему, зачем второй борщ, просто положи это на первый

2024-02-15 19:12 UTC, Kit0vras requested changes

2024-02-15 19:12 UTC, Kit0vras commented on Resources/Prototypes/SS220/Flavors/flavors.yml
> +  description: Ням. На вкус мясной бульон с овощами.
```suggestion
  description: Ням. На вкус как мясной бульон с овощами.
```

2024-02-15 19:12 UTC, Kit0vras commented on Resources/Prototypes/SS220/Flavors/flavors.yml
> +  description: Ням. На вкус кислый бульон с овощами.
```suggestion
  description: Ням. На вкус как кислый бульон с овощами. 
```

2024-02-15 19:12 UTC, Kit0vras commented on Resources/Prototypes/SS220/Flavors/flavors.yml
> +  description: Ням. На вкус соленые вареные овощи.
```suggestion
  description: Ням. На вкус как соленые вареные овощи.
```

2024-02-15 19:12 UTC, Kit0vras commented on Resources/Prototypes/SS220/Flavors/flavors.yml
> +  description: Ням. На как свекла.
```suggestion
  description: Ням. На вкус сладко и как земля. 
```
прикол в том, что у свеклы землистый вкус из-за химического соединения

2024-02-15 19:12 UTC, Kit0vras commented on Resources/Prototypes/SS220/Flavors/flavors.yml
> +  description: Ням. Освежающий вкус мяса и овощей с кислинкой.
```suggestion
  description: Ням. На вкус как мясо и овощи с кислинкой.
```

2024-02-15 19:12 UTC, Kit0vras commented on Resources/Prototypes/SS220/Flavors/flavors.yml
> +  description: Ням. Освежающий вкус мяса и овощей.
```suggestion
  description: Ням. На вкус как мясо с овощами. 
```

2024-02-15 20:14 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss220/reagents/meta/drinks.ftl
> +reagent-desc-apple-compote = Изготовлен из свежих яблок,по рецепту бабушки.
уээээээээ

2024-02-15 20:15 UTC, Kit0vras commented
яблочный сок забыл изменить, я там закидывал описание, но чот не изменилось, хотя ты вроде принял

2024-02-17 13:33 UTC, WhitlyOfficial commented
@21Melkuu у тебя проеб по чекам, медиа в данном случае нужно, т.к. добавляются спрайты 🐱

2024-02-17 13:37 UTC, 21Melkuu commented
> @21Melkuu у тебя проеб по чекам, медиа в данном случае нужно, т.к. добавляются спрайты 🐱

Ваше мнение было очень важно для нас.
Медия в трекере.
Упавший чек не мой, а йоллоу танк

2024-02-17 13:38 UTC, WhitlyOfficial commented
> Ваше мнение было очень важно для нас. Медия в трекере. Упавший чек не мой, а йоллоу танк

так добавил бы картинку с трекера, 2 кнопки нажать

2024-02-17 14:23 UTC, DexlerXD commented
@21Melkuu кста в проверках крестики ставить надо без пробелов по бокам

2024-02-25 16:26 UTC, WhitlyOfficial reviewed
Переделать спрайты:
- чебурека (слишком огромная палитра из 25 цветов, беды с контуром)
- шаурмы (слишком огромная палитра из 126 цветов, плохой спрайт in total)

2024-02-28 14:54 UTC, Ady4ik requested changes

2024-02-28 14:54 UTC, Ady4ik commented on Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
> +  cost: 3450
```suggestion
  cost: 3450 # SS220 Cargo fix
```

2024-02-28 14:54 UTC, Ady4ik commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Drinks/drinks.yml
> +  description: Изготовлен из свежих яблок.
```suggestion
  description: Его сладковатый аромат напоминает вам сказки о былой жизни на Земле.
```

2024-02-28 14:54 UTC, Ady4ik commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Drinks/drinks.yml
> +  description: Изготовлен из свежих ягод.
```suggestion
  description: Аромат ягод напоминает вам сказку о Красной Шапочке.
```

2024-02-28 14:54 UTC, Ady4ik commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/soup.yml
> +  description: Красный суп.
```suggestion
  description: Принесите мне кто-нибудь квас и хлеб!
```

2024-02-28 14:54 UTC, Ady4ik commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/soup.yml
> +  description: Борщ с капусткой, но не красный.
```suggestion
  description: Суп с капусткой, но не красный.
```

2024-02-28 14:54 UTC, Ady4ik commented on Resources/Prototypes/SS220/Flavors/flavors.yml
> +  description: сладко и как земля
```suggestion
  description: сладко и земельно. 
```

2024-02-28 14:54 UTC, Ady4ik commented on Resources/Prototypes/SS220/Hydroponics/seeds.yml
> +  name: пакет семян (свекла)
```suggestion
  name: пакет семян (свёкла)
```

2024-02-28 14:54 UTC, Ady4ik commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/produce.yml
> +  name: свекла
```suggestion
  name: свёкла
```

2024-02-28 14:54 UTC, Ady4ik commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/produce.yml
> +  description: Сочная и полезная свекла - отличный выбор для салатов и гарниров.
```suggestion
  description: Сочная и полезная - отличный выбор для салатов и гарниров.
```

2024-02-28 14:54 UTC, Ady4ik commented on Resources/Prototypes/SS220/Entities/Objects/Specific/Hydroponics/seeds.yml
> +  name: пакет семян (свекла)
```suggestion
  name: пакет семян (свёкла)
```

2024-02-28 14:54 UTC, Ady4ik commented on Resources/Prototypes/SS220/Hydroponics/seeds.yml
> +  displayName: свекла
```suggestion
  displayName: свёкла
```

2024-02-29 14:52 UTC, Ady4ik commented
@DexlerXD @TheArturZh если что можно мерджить, если я нигде не проебался

2024-02-29 15:40 UTC, WhitlyOfficial reviewed
Сиквел ревью.
Переделать спрайты:
- Спрайт чебурека приемлем
- Спрайты шаурмы переделать целиком (Невидимые пиксели && плохие цвета && плохой контраст). Если нужен будет концепт - к meower.

2024-02-29 16:50 UTC, 21Melkuu commented
> Сиквел ревью. Переделать спрайты:
> 
> * Спрайт чебурека приемлем
> * Спрайты шаурмы переделать целиком, но не формой (Невидимые пиксели && плохие цвета && плохой контраст). Если нужен будет концепт - к meower.

невидимые пиксили убрали, все остальное личное субъективное мнение, не имеющие ничего общего к ревью.

2024-02-29 16:56 UTC, WhitlyOfficial commented
> невидимые пиксили убрали, все остальное личное субъективное мнение, не имеющие ничего общего к ревью. UPD: нет, наебал, не убрали. 5 минут и залью еще раз

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/98218741/d1e63ca4-2ba4-4264-98f5-b40c685c1704)

2024-03-02 15:56 UTC, WhitlyOfficial commented
> невидимые пиксили убрали, все остальное личное субъективное мнение, не имеющие ничего общего к ревью. UPD: нет, наебал, не убрали. 5 минут и залью еще раз

жду выполнения пунктов ревью, иначе так и будете без апрува сидеть
про ревью
_Reviews allow collaborators to comment on the changes proposed in pull requests, approve the changes, or request further changes before the pull request is merged. Repository administrators can require that all pull requests are approved before being merged._

2024-03-09 10:48 UTC, WhitlyOfficial requested changes
Фикс копирайтов
![1213076802873065473](https://github.com/SerbiaStrong-220/space-station-14/assets/98218741/404c4c99-bbb0-401b-8f62-e78a117d6d13)

2024-03-09 10:48 UTC, WhitlyOfficial commented on Resources/Textures/SS220/Objects/Consumable/Food/shawarma.rsi/meta.json
> +    "copyright": "Added by gabova(discord)",
```suggestion
    "copyright": "Created by gabova(discord), modified by Whitly / Meower",
```
Крутые названия у коммитов, жаль что про копирайт забыли

2024-03-09 13:14 UTC, Kit0vras requested changes

2024-03-09 13:14 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/soup.yml
> +  name: борщ
Добавь дефолтному борщу рецепт и замени ему спрайты, вместо того, чтобы создавать ненужный второй борщ.

2024-03-09 13:14 UTC, Kit0vras commented on Resources/Textures/SS220/Objects/Consumable/Food/shawarma.rsi/meta.json
> +    "copyright": "Added by gabova(discord)",
Добавь модифицированный копирайт, указанный автором.

2024-03-09 13:16 UTC, 21Melkuu commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/soup.yml
> +  name: борщ
Отказано, в этом нет никого смысла.
Зачем мне менять старый, когда я могу создать новый

2024-03-09 13:32 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Consumable/Food/soup.yml
> +  name: борщ
Потому что если есть старый - новый не нужен, поменяй старый, потому что в новом нет смысла.

2024-03-09 14:37 UTC, WhitlyOfficial requested changes
Пофиксить бы.

2024-03-09 14:37 UTC, WhitlyOfficial commented on Resources/Textures/SS220/Objects/Consumable/Drinks/glass_berry.rsi/meta.json
> +    "copyright": "Added by gabova(discord)",
```suggestion
    "copyright": "Taken from https://github.com/discordia-space/CEV-Eris/raw/f7aa28fd4b4d0386c3393d829681ebca526f1d2d/icons/obj/drinks.dmi and modified by gabova(discord)",
```
Оригинальный спрайт стакана, как и напитков, сделан другим человеком и залит под CC-BY-SA-3.0
Его модификации должны быть подписаны, как модификации, по условию лицензии.

2024-03-09 14:37 UTC, WhitlyOfficial commented on Resources/Textures/SS220/Objects/Consumable/Food/shawarma.rsi/meta.json
> +    "copyright": "Added by gabova(discord)",
Напоминаю, что без упоминания автора/ссылки на оригинальный материал/ссылки на авторство спрайт не может использоваться, т.к. это нарушение лицензии.

2024-03-09 14:37 UTC, WhitlyOfficial commented on Resources/Prototypes/SS220/Flavors/flavors.yml
> +- type: flavor
В игре это будет выглядеть как
> "Ням. На вкус мясо со свежими овощами."

Выглядит хуево, ведь обычно пишет
> "Ням. На вкус как мясо со свежими овощами."

Или в случае, если описание из однословного прилагательного/наречия
> "Ням. На вкус лиственно и дёшево."

2024-03-09 15:11 UTC, DexlerXD commented
Попрошу заметить, что отказ в исполнении просьб ревьюверов - вполне обоснованное основание для закрытия ПРа.

2024-03-09 15:17 UTC, 21Melkuu commented
> Попрошу заметить, что отказ в исполнении просьб ревьюверов - вполне обоснованное основание для закрытия ПРа.

Я ожидаю ответ адуча. Доебывать, что надо мне изменять оригинальный спрайт, а не делать в папке ыы220 фактически разрушают структуру сборки

2024-03-09 15:27 UTC, Kit0vras commented
> > Попрошу заметить, что отказ в исполнении просьб ревьюверов - вполне обоснованное основание для закрытия ПРа.
> 
> Я ожидаю ответ адуча. Доебывать, что надо мне изменять оригинальный спрайт, а не делать в папке ыы220 фактически разрушают структуру сборки

Если ты добавляешь что-то новое - то да, ты добавляешь что-то новое.
Если это что-то уже есть - ты переписываешь и изменяешь его с комментариями, вместо того, чтобы добавлять третий борщ, игнорируя второй, как будто это нежеланная и невкусная морковь в его составе, которую тебя заставляют съесть

2024-03-09 15:28 UTC, 21Melkuu commented on Resources/Prototypes/SS220/Flavors/flavors.yml
> +- type: flavor
Я исправил флаворы еще в прошлый раз

2024-03-09 15:29 UTC, 21Melkuu commented
@WhitlyOfficial я по-моему случайно вжал не ту кнопку на твой копирайт, закинь еще раз пожалуйста

2024-03-09 15:35 UTC, DexlerXD commented
@21Melkuu менять файлы оффов с нашими пометками - давняя практика. Добавив рецепт и поменяв ссылку на спрайты ты бы ничего не сломал

2024-03-16 11:08 UTC, Kit0vras commented
Пофикси конфликт и можно принимать

2024-03-16 17:17 UTC, Ady4ik commented
@Kit0vras ласт ревью?

2024-03-16 17:34 UTC, Kit0vras approved these changes

2024-03-17 22:07 UTC, Ady4ik commented
@TheArturZh merge that

2024-03-18 09:58 UTC, merged