No death
SerbiaStrong-220/space-station-14 pull request #741
Opened 2024-02-16 08:20 UTC by ZoNeSRuS

## Описание PR

Долгожданный внес клонерки на помойку(в тир 3 РНД)
Конерка:
1. Платы удалены со всех карт.
2. Добавлено в тир 3 исследования РНД.

Возрождение:
Новая фичча позволяющая госту вернуться в лобби. через 20 минут после смерти.

Сдаться в крите:
Удалено у всех кукл игроков. Животные и другие все еще имеют эту кнопку.

Последние слова:
Теперь РЕАЛЬНО последние слова. После их произнесения вы не сможете вернуться в тело.

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: ZoNeSRuS
- add: Добавлена кнопка "возрождение"
- remove: Удалена возможность "сдаться" в крите, исключение животные.
- tweak: Изменены "последние слова". Теперь после них вы не сможете ожить.
- tweak: Клонерка удалена и перемещена в РНД.

2024-02-16 08:26 UTC, ZoNeSRuS commented
Да йопта где ошибки.

2024-02-16 09:00 UTC, VladIsLove-e commented
Теперь последние слова не юзабельны,
Предлагаю сделать так: с момента Крита можно написать последние слова, но до момента смерти они не отправится. Через условные 5 секунд от крита кнопка убирается. Если человек был в Крите дольше(к примеру)10 секунд, последний слова произносятся шёпотом (так их и издалека не слышно и это логичнее, мол ослабел)

2024-02-16 09:01 UTC, ZoNeSRuS commented
> Теперь последние слова не юзабельны, Предлагаю сделать так: с момента Крита можно написать последние слова, но до момента смерти они не отправится. Через условные 5 секунд от крита кнопка убирается. Если человек был в Крите дольше(к примеру)10 секунд, последний слова произносятся шёпотом (так их и издалека не слышно и это логичнее, мол ослабел)

С радостью бы выслушал эти слова на собрании разрабов, где все это обсуждалось и утверждалось, но ты не пришел.

2024-02-16 09:05 UTC, VladIsLove-e commented
> > Теперь последние слова не юзабельны, Предлагаю сделать так: с момента Крита можно написать последние слова, но до момента смерти они не отправится. Через условные 5 секунд от крита кнопка убирается. Если человек был в Крите дольше(к примеру)10 секунд, последний слова произносятся шёпотом (так их и издалека не слышно и это логичнее, мол ослабел)
> 
> С радостью бы выслушал эти слова на собрании разрабов, где все это обсуждалось и утверждалось, но ты не пришел.

Злюка

2024-02-16 11:15 UTC, DexlerXD requested changes

2024-02-16 11:15 UTC, DexlerXD commented on Resources/Prototypes/SS220/Recipes/Lathes/electronics.yml
> +     Gold: 100
???

2024-02-16 11:15 UTC, DexlerXD commented on Content.Server/Ghost/GhostSystem.cs
> +        //SS-220 end
во всех комментах с пометками нашего кода желательно добавить и название фичи/ветки, на которой производились изменения
```
//SS220-respawn begin
DoStuff();
//SS220-respawn end
```
типа такого

2024-02-16 11:15 UTC, DexlerXD commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +
???

2024-02-16 12:23 UTC, ZoNeSRuS commented on Resources/Prototypes/SS220/Recipes/Lathes/electronics.yml
> +     Gold: 100
работал с этим файлом, потом изменения откатил.

2024-02-16 12:23 UTC, ZoNeSRuS commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +
работал с этим файлом, потом изменения откатил.(2)

2024-02-16 16:33 UTC, DexlerXD requested changes

2024-02-16 16:33 UTC, DexlerXD commented on Resources/Prototypes/SS220/Recipes/Lathes/electronics.yml
> -     Gold: 100
все еще здесь прикол

2024-02-16 16:33 UTC, DexlerXD commented on Content.Server/Ghost/GhostSystem.cs
> +         [Dependency] private readonly IServerConsoleHost _host = default!;
```suggestion
        [Dependency] private readonly IServerConsoleHost _host = default!;
```

2024-02-16 16:33 UTC, DexlerXD commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +
тут также надо бы изменения убрать

2024-02-17 08:13 UTC, ZoNeSRuS commented on Resources/Prototypes/Entities/Structures/Machines/lathe.yml
> +
> тут также надо бы изменения убрать

Да понял, тут рил мой косяк.

2024-02-17 08:14 UTC, ZoNeSRuS commented on Resources/Prototypes/SS220/Recipes/Lathes/electronics.yml
> -     Gold: 100
> все еще здесь прикол

Тут убрался символ табуляции после 100. Я ХЗ как его назад вернуть.

2024-02-17 14:21 UTC, DexlerXD approved these changes

2024-02-17 14:31 UTC, merged