Добавление новых целей станции ( II итерация)
SerbiaStrong-220/space-station-14 pull request #766
Opened 2024-02-20 19:22 UTC by Ady4ik

## Описание PR
Добавление 3 новых целей станции

**Медиа**
Нету

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Ady4
- add: Добавлены новые цели станции.
- add: Добавлены новая бумажная форма для цели станции.

2024-02-20 19:24 UTC, Ady4ik commented
@Kit0vras жду душку по русский язык и знаки препитаний.

2024-02-20 19:32 UTC, Kit0vras commented
> @Kit0vras жду душку по русский язык и знаки препитаний.

уууэээээээ

2024-02-20 20:01 UTC, Kit0vras requested changes

2024-02-20 20:01 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss220/station-goals/additional-goals.ftl
> +    Также необходимо создание специальных ответвлений станции, которые позволят изможденным сотрудникам станции добраться до сервисного отдела станции, а именно:
```suggestion
    Также необходимо создание специальных ответвлений станции, которые позволят изнеможённым сотрудникам станции добраться до сервисного отдела, а именно:
```
там три версии одного слова, но как я понял, это - самая лайтовая, когда ты не при смерти, а просто сильно устал

2024-02-20 20:02 UTC, Kit0vras commented
на

2024-02-20 20:06 UTC, Kirus59 commented on Resources/PhotocopierForms/nanotrasen_station/hr/cmd_ept.xml
> +Причины по которым я должен получить данную работу:
А зачем пробел перед запятой......

2024-02-20 20:08 UTC, Kirus59 commented
@Kit0vras а зачем пробел перед запятой......

2024-02-20 20:08 UTC, Kit0vras commented
> @Kit0vras а зачем пробел перед запятой......

потому что это так делается

2024-02-20 20:09 UTC, Kit0vras commented
пробел идёт после запятой, зачем тебе пробел перед запятой, где пробел перед запятой

2024-02-21 09:51 UTC, Ady4ik commented on Resources/Locale/ru-RU/ss220/station-goals/additional-goals.ftl
> +    В целях безопасности строго воспрещается медицинскому и научному сотрудникам вступать в контакт с потенциальной опасностью.
а тут что не так

2024-02-21 13:50 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss220/station-goals/additional-goals.ftl
> +    В целях безопасности строго воспрещается медицинскому и научному сотрудникам вступать в контакт с потенциальной опасностью.
не по русски звучит как то

2024-02-21 13:50 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss220/station-goals/additional-goals.ftl
> +    В целях безопасности строго воспрещается медицинскому и научному сотрудникам вступать в контакт с потенциальной опасностью.
и так звучит более логично в рамках предложения

2024-02-21 18:24 UTC, DexlerXD approved these changes

2024-02-21 18:28 UTC, merged