Gun Safe Resprite
SerbiaStrong-220/space-station-14 pull request #781
Opened 2024-02-28 18:43 UTC by Kit0vras

## Описание PR

Респрайт оружейного сейфа. Дверцы всё также две, вместо открытия - раздвигаются в стороны (на открытие не было место и смотрелось бы это ужасно), лампочки - две. Тёмные полосы на левой дверце - ручки (типа есть такие системы, что открываешь одну створку, и вторая открывается вместе с ней).
Внутри всё также пустой, так как оружие хранится в нём не как в инвентаре.
**Медиа**

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/7a39d74f-e746-4d12-86ee-0ae3e37bf11e)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/b53fbf8b-059c-45bc-9fc9-dc75cadff757)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/94222b0e-eff8-4209-80fb-68e5a8a23024)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl:
- tweak: Изменён спрайт оружейного сейфа.

2024-02-28 18:45 UTC, WhitlyOfficial approved these changes
спрайты норм

2024-02-29 15:31 UTC, DexlerXD requested changes

2024-02-29 15:31 UTC, DexlerXD commented on Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
> +
бля

2024-02-29 15:31 UTC, DexlerXD commented on Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
> +
тут тоже

2024-03-04 17:10 UTC, Kit0vras commented on Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
> +
я ничего не делал там, оно делает это автоматически
а что не так?

2024-03-04 17:54 UTC, Kit0vras commented on Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
> +
Я попытался исправить и даже отменить, но каждый раз при сохранении файла оно возвращает пустую строку вместо строки с двумя табами (вообще так и должно быть, оно буквально исправило эти строки, что делает постоянно при изменении некоторых файлов, где с ними косячили, там и должна быть пустая строка)

2024-03-04 17:59 UTC, DexlerXD approved these changes

2024-03-04 18:00 UTC, merged