Added grid restriction for fulton
SerbiaStrong-220/space-station-14 pull request #802
Opened 2024-03-07 18:23 UTC by SkaldetSkaeg

## Описание PR
Попросили ограничить по гридам фултоны -- сделано.
**Медиа**
<img width="368" alt="image" src="https://github.com/SerbiaStrong-220/space-station-14/assets/30115570/8e63acfa-745d-42b7-8f7b-5557c2e17bcd">

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl:
- tweak: Фултоны больше не могут переносить вещи, если маяк находится в другом гриде.

2024-03-08 12:42 UTC, SkaldetSkaeg commented
PR спорный, надо обсуждать

2024-03-09 10:47 UTC, SkaldetSkaeg commented
По фултнону на экспах: фултоны перепривязывать не надо, достаточно просто развернуть снаружи от шаттла.

2024-03-13 14:53 UTC, SkaldetSkaeg commented
Сделано

2024-03-13 14:54 UTC, Kit0vras requested changes

2024-03-13 14:54 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss220/fulton-system.ftl
> +fulton-is-restricted = Пространство заблокированно.
```suggestion
fulton-is-restricted = Пространство заблокировано.
```

2024-03-24 06:45 UTC, DexlerXD approved these changes

2024-03-24 06:45 UTC, merged