new jobs block
SerbiaStrong-220/space-station-14 pull request #810
Opened 2024-03-10 14:20 UTC by ZoNeSRuS

## Описание PR

Новые ограничения по расам. Теперь можно делать ограничения еще и по полу.

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: ZoNeSRuS
- add: Ограничения ролей по расам.

2024-03-13 15:09 UTC, Kit0vras requested changes

2024-03-13 15:09 UTC, Kit0vras commented on Resources/Prototypes/Species/arachnid.yml
> +    Brigmedic: [ famele ]
```suggestion
    Brigmedic: [ female ]
```

2024-03-13 15:09 UTC, Kit0vras commented on Resources/Prototypes/Species/arachnid.yml
> +    AtmosphericTechnician: [ famele ]
```suggestion
    AtmosphericTechnician: [ female ]
```

2024-03-13 15:11 UTC, Kit0vras requested changes

2024-03-13 15:11 UTC, Kit0vras commented on Resources/Prototypes/Species/arachnid.yml
> +    Janitor: [ female ]
```suggestion

```
повторяется ниже

2024-03-24 14:41 UTC, ZoNeSRuS commented
Секунду забыл проставить комментарии с лицензией.

2024-03-24 14:54 UTC, ZoNeSRuS commented
готово

2024-03-24 15:41 UTC, Kit0vras requested changes

2024-03-24 15:41 UTC, Kit0vras commented on Resources/Prototypes/SS220/spo9k/Species/felinid.yml
> +
боксёр

2024-03-27 04:56 UTC, ZoNeSRuS commented on Resources/Prototypes/SS220/spo9k/Species/felinid.yml
> +
Почему ты вообще решил что у них боксер должен быть ограничен? Они же имею ограничения только по полит причинам.

2024-03-28 12:58 UTC, ZoNeSRuS commented
Намержат своих апстримов, что у нормальных людей конфликты!!!

2024-03-28 13:23 UTC, ZoNeSRuS commented
Так не мержить, у нас кое что сломалось.

2024-03-28 13:41 UTC, ZoNeSRuS commented
Вот теперь 100по 100 готово, честно, честно.

2024-03-28 23:37 UTC, Kit0vras approved these changes

2024-03-29 18:08 UTC, DexlerXD approved these changes

2024-03-29 18:09 UTC, merged