Новые посылки с масками для антагов
SerbiaStrong-220/space-station-14 pull request #827
Opened 2024-03-19 18:46 UTC by SkaldetSkaeg

## Описание PR
Добавлены 2 новые посылки содержащие в себе маски из пэйдея и хотлайн маями.

**Медиа**

**Проверки**
- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлена посылка содержащая маски из Хотлайн Майами
- add: Добавлена посылка содержащая маски из ПэйДея
- fix: пофиксил, чтобы у предметов использованных в руке срабатывали звуки.
<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-03-20 00:25 UTC, Kit0vras requested changes

2024-03-20 00:25 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss220/store/uplink-catalog.ftl
> +uplink-criminal-delivery-desc = Содержит случайную маску замешанную в самых громких ограбления прошлого.
```suggestion
uplink-criminal-delivery-desc = Содержит случайную маску, замешанную в самых громких ограблениях прошлого.
```

2024-03-20 00:25 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Head/HotMasks.yml
> +  description: Ааа, вот ты где! А я всё думал, когда ты вернешься?
```suggestion
  description: Ааа, вот ты где! А я всё думал, когда ты вернёшься?
```

2024-03-20 00:25 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Head/PaydayMasks.yml
> +  name: Маска Далласа
```suggestion
  name: маска Далласа
```

2024-03-20 00:25 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Head/PaydayMasks.yml
> +  name: Маска Чейнса
```suggestion
  name: маска Чейнса
```

2024-03-20 00:25 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Head/HotMasks.yml
> +  name: Алекс #С большой, ибо оффовская маска Ричарда тоже
```suggestion
  name: маска Алекса
```
Это ж по идее тоже маска, может тоже поставить в начале "маска"? или так и надо?

2024-03-20 00:25 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Head/PaydayMasks.yml
> +  name: Маска Вульфа
```suggestion
  name: маска Вульфа
```

2024-03-20 00:25 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Head/PaydayMasks.yml
> +  name: Маска Хокстона
```suggestion
  name: маска Хокстона
```

2024-03-20 00:25 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Clothing/Head/PaydayMasks.yml
> +  description: Мне нужно, чтобы вы стояли смирно как е***ые садовые гномы.
```suggestion
  description: Мне нужно, чтобы вы стояли смирно, как е***ые садовые гномы.
```

2024-03-20 00:25 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Misc/specialdelivery.yml
> +  id: SpecialDeliveryBoxTrash
а зачем 2 одинаковых обёртки? просто сделай, чтобы из этой коробки падала тоже та обёртка, это же одно и то же

2024-03-20 00:25 UTC, Kit0vras commented on Resources/Textures/SS220/Clothing/Head/PayDay/dallas.rsi/equipped-HELMET.png
тут кажется много где почему-то лежит утка

2024-03-20 03:42 UTC, Qwerlink commented on Resources/Prototypes/SS220/Entities/Clothing/Head/HotMasks.yml
> +  name: Алекс #С большой, ибо оффовская маска Ричарда тоже
Так и надо

2024-03-20 03:45 UTC, SkaldetSkaeg commented on Resources/Prototypes/SS220/Entities/Objects/Misc/specialdelivery.yml
> +  id: SpecialDeliveryBoxTrash
Да я вчера думал о таком, но подзабыл, лег спать, спасибо за ревью Кит

2024-03-20 03:45 UTC, SkaldetSkaeg commented on Resources/Textures/SS220/Clothing/Head/PayDay/dallas.rsi/equipped-HELMET.png
Это заглушка, сегодня Scaven перерисует как надо

2024-03-20 18:23 UTC, SkaldetSkaeg commented
сделано

2024-03-21 08:55 UTC, DexlerXD approved these changes

2024-03-21 19:54 UTC, Kit0vras approved these changes

2024-03-22 06:04 UTC, merged