NukeOps ExtraFix
SerbiaStrong-220/space-station-14 pull request #832
Opened 2024-03-21 19:08 UTC by Surani1

## Описание PR
Пофикшены баги с закупкой вещей на аванпосте. 
Шаттл и Аванпост были немного переработаны ( снова )
Пофикшен баг с отображением времени объявления войны и вылета.

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Surani
- tweak: Изменен Аванпост и Шаттл оперативников.
- fix: Исправлено отображение времени объявления.

2024-03-23 17:52 UTC, Kit0vras commented on Resources/Prototypes/SS220/Maps/SS220_syndicate.yml
> +          mapNameTemplate: "SI-NO220 Heavy Hell "
```suggestion
          mapNameTemplate: "SI-NO220 Heavy Hell"
```
а мне больше Outer Heaven нравилось, так прикольно звучало...

2024-03-23 18:07 UTC, Kit0vras requested changes

2024-03-23 18:08 UTC, Kit0vras commented on Resources/Prototypes/SS220/Maps/SS220_syndicate.yml
> +          mapNameTemplate: "SI-NO220 Heavy Hell "
Но как хочешь, конечно, я не настаиваю
тут просто пробел лишний

2024-03-23 18:08 UTC, Kit0vras commented
По самой карте отписал в лс

2024-03-23 22:51 UTC, Surani1 commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
адуч так сказал сделать

2024-03-24 09:57 UTC, DexlerXD requested changes

2024-03-24 09:57 UTC, DexlerXD commented on Content.Server/GameTicking/Rules/NukeopsRuleSystem.cs
> +            _store.TryAddCurrency(new() { { TelecrystalCurrencyPrototype, nukieRule.WarTCAmountPerNukie } }, uid, component);
?

2024-03-24 10:33 UTC, DexlerXD approved these changes

2024-03-24 10:33 UTC, merged