Pilot HardSuit Security
SerbiaStrong-220/space-station-14 pull request #835
Opened 2024-03-22 12:34 UTC by Surani1

## Описание PR
Добавлен особый скафандр для пилотов сб с небольшими изменениями в характеристиках и модифицированным
шлемным фонарём.

В шкафе пилота сб - скафандр сб был заменен на скафандр пилота сб.

**Медиа**

![ApplicationFrameHost_oQB4UuAzKE](https://github.com/SerbiaStrong-220/space-station-14/assets/154987464/01d646be-b7a5-4a45-a08f-d983b79d8071)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl: Surani
- add: Добавлен скафандр пилота сб
- tweak: Новый скафандр добавлен в шкаф пилота СБ.

2024-03-22 12:45 UTC, Kit0vras commented
выглядит стрёмно

2024-03-22 12:47 UTC, Surani1 commented
> выглядит стрёмно

УЭЭЭЭЭЭЭЭЭЭЭЭЭЭЭ

2024-03-22 12:52 UTC, Kit0vras commented
шлем говно, сам скаф вообще не стилёвый и никак не отличается

2024-03-23 00:11 UTC, Surani1 commented
@Kit0vras Ревью

2024-03-23 02:48 UTC, Kit0vras commented
Шлем говно, че это за маяк

2024-03-27 23:09 UTC, Kit0vras approved these changes

2024-03-28 04:49 UTC, DexlerXD requested changes

2024-03-28 04:49 UTC, DexlerXD commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> +      - id: ClothingOuterHardsuitSecurityPilot
```suggestion
      - id: ClothingOuterHardsuitSecurityPilot #ss220-pilot-hardsuit
```

2024-03-28 12:18 UTC, merged