Hot bug fix
SerbiaStrong-220/space-station-14 pull request #846
Opened 2024-03-27 22:54 UTC by Surani1

## Описание PR

Небольшой багфикс
Исправлен спрайт рига ОСЩ.
Теперь через риги ОСЩ и ГСБ можно дышать без маски
Исправлен спрайт спонсорской одежды
Изменены спрайты спидлоадеров
Пофикшены звуки Унатхов женских особей
Добавлен ПЛАСТИКОВЫЙ СТУЛ!!!

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Surani
- add: Добавлен пластиковый стул.
- tweak: Изменен спрайт спидлоадера.
- fix: Исправлены спрайты рига ОСЩ и спонсорской одежды.
- fix: Исправлены звуки унатхов женского пола.
- tweak: Через риг ГСБ и ОСЩ можно дышать без маски.

2024-03-27 23:08 UTC, Kit0vras requested changes

2024-03-27 23:08 UTC, Kit0vras commented on Resources/Prototypes/SS220/Recipes/Construction/Furniture/chairplastic.yml
> +  description: Вы сидите на этом. Либо по вашей воле, либо по принуждению, либо ради мотивации и силы!
```suggestion
  description: You're sitting on it. Either by your will, or by compulsion, or for the sake of motivation and power!
```
Пока не добавят локали для рецептов, нужно либо делать всё на инглише, либо переводить вообще всё (а без локалей это как то кринжово, хз, да и работа впустую, ибо локали рано или поздно сделают, а работу придётся откатывать), чтобы не выбивалось

2024-03-27 23:08 UTC, Kit0vras commented on Resources/Prototypes/SS220/Recipes/Construction/Graphs/furniture/chairplastic.yml
> +              southRotation: true
```suggestion

```

2024-03-27 23:08 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/Furniture/chairs.yml
> +    graph: Seat
```suggestion
    graph: SeatPlastic
```

2024-03-27 23:08 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Structures/Furniture/chairs.yml
> +    node: plastic-overlay
```suggestion
    node: chairPlastic
```

2024-03-27 23:08 UTC, Kit0vras commented on Resources/Textures/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Magnum/magnum_speed_loader.rsi/meta.json
> +            "name": "practice" //ss-220 sprite fix
```suggestion
            "name": "practice"
```
в мете не нужны комменты, никто этого никогда не делает, да и выглядит странно, так что не стоит

2024-03-27 23:08 UTC, Kit0vras commented on Resources/Textures/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Magnum/magnum_speed_loader.rsi/meta.json
> +            "name": "rubber" //ss-220 sprite fix
```suggestion
            "name": "rubber"
```

2024-03-27 23:08 UTC, Kit0vras commented on Resources/Textures/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Magnum/magnum_speed_loader.rsi/meta.json
> +            "name": "uranium" //ss-220 sprite fix
```suggestion
            "name": "uranium"
```

2024-03-27 23:08 UTC, Kit0vras commented on Resources/Textures/Objects/Weapons/Guns/Ammunition/SpeedLoaders/Magnum/magnum_speed_loader.rsi/meta.json
> +            "name": "piercing" //ss-220 sprite fix
```suggestion
            "name": "piercing"
```

2024-03-28 04:47 UTC, DexlerXD requested changes

2024-03-28 04:47 UTC, DexlerXD commented on Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
> +      Female: FemaleReptilian
```suggestion
      Female: FemaleReptilian #ss220-fix
```

2024-03-28 04:47 UTC, DexlerXD commented on Resources/Prototypes/Entities/Mobs/Species/reptilian.yml
> +      Female: FemaleReptilian
```suggestion
      Female: FemaleReptilian #ss220-fix
```

2024-03-28 12:17 UTC, DexlerXD approved these changes

2024-03-28 12:17 UTC, merged