Tables Update
SerbiaStrong-220/space-station-14 pull request #849
Opened 2024-03-29 09:22 UTC by Surani1

## Описание PR

Добавлены новые столы и крафты к ним
Стол из уранового стекла
Стол из уранового бронестекла
Стол из плазменного бронестекла

**Медиа**

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/154987464/a5e89397-8412-4af7-a29a-07034dc77e3a)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Surani, Nightmare stalker
- add: Добавлено 3 новых вида столов

2024-03-29 09:26 UTC, Surani1 commented
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⠉⠉⠉⠉⠉⠉⠉⠛⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⢀⣠⣶⣶⣶⣶⣤⡀ ⠀ ⠹⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⡏⠀⠀⠀⣾⡿⢿⣿⣿⡿⢿⣿⡆ ⠀ ⢻⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⡿⠃⠀⠀⠀⢿⣇⣸⣿⣿⣇⣸⡿⠃⠀⠀⠸⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠉⠛⠛⠛⠛⠉⠀⠀⠀⠀⠀⠀⠀⠙⣿⣿⣿⣿⣿
⢿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿
⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀Я НАСРАЛ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⣿⣿
⣿⡟⠀⠀⠀⠀⠀⣿⣿⠀⠀@kit0vras УБЕРИ⠀ ⣧⠀⠀⠀⠀⠀ ⢿⣿
⣿⡇⠀⠀⠀⠀⠀⣾⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣧⠀⠀⠀⠀⠀⢸⣿
⣿⣇⠀⠀⣰⣶⣿⣿⣿⣦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣶⣆⠀⠀⢀⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⢸⣿⠇⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣤⣴⣾⣿⣶⣤⣤⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿

2024-03-29 10:19 UTC, Kit0vras requested changes
добавьте стол из пластитана (просто пока что с крафтом из пластали, наверно, просто чтоб её было нужно больше) и мы в расчёте

2024-03-29 10:19 UTC, Kit0vras commented on Resources/Textures/SS220/Structures/Furniture/Tables/rp_glass.rsi/meta.json
> +          1.0
а зачем им всем дилеи?

2024-03-29 10:31 UTC, Surani1 commented on Resources/Textures/SS220/Structures/Furniture/Tables/rp_glass.rsi/meta.json
> +          1.0
> а зачем им всем дилеи?

Мета скопирована у обычного стола, не имею понятия

2024-04-08 21:11 UTC, DexlerXD commented
@Kit0vras а тут че как?

2024-04-08 21:44 UTC, Kit0vras commented
> @Kit0vras а тут че как?

чек первый мой коммент тут

2024-04-14 20:54 UTC, Surani1 commented
@Kit0vras я думаю не дождусь пластитановых. Ревью?

2024-04-14 23:00 UTC, Kit0vras approved these changes
Excellent Argument

2024-04-15 20:38 UTC, Surani1 commented
@DexlerXD merge

2024-04-15 20:41 UTC, DexlerXD approved these changes

2024-04-15 20:41 UTC, merged