UplinkFixStore
SerbiaStrong-220/space-station-14 pull request #875
Opened 2024-04-03 14:55 UTC by Helm4142

## Описание PR

Исправил баг из-за которого в продаже у агента исчезли большинство гранат, пулемёт и кровавый хардсьют. Возможно лишним добавил чинуку, но это легко исправить.

**Медиа**

https://github.com/SerbiaStrong-220/space-station-14/assets/158806576/b7dc2b41-2107-48a8-8b2d-9f73c560992f

**Проверки**

 PR полностью завершён и мне не нужна помощь чтобы его закончить.

- [ + ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ + ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ + ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- fix: Возвращены некоторые предметы для Агентов синдиката

2024-04-03 15:12 UTC, Helm4142 commented
Я не понимаю, с проверками всё хорошо или всё плохо?

2024-04-03 15:15 UTC, SkaldetSkaeg commented
> Я не понимаю, с проверками всё хорошо или всё плохо?

вроде норм, ждем аппрува

2024-04-04 17:46 UTC, Surani1 commented
@Helm4142 выбери время как сможешь зайти в дискорд, я объясню тебе как грамотно сделать PR

2024-04-04 22:01 UTC, DexlerXD approved these changes

2024-04-04 22:03 UTC, DexlerXD requested changes
упс, чуть не забыл, те строчки лучше закомментить и написать, что это убрано нами

2024-04-05 10:12 UTC, Helm4142 commented
@DexlerXD Надеюсь всё правильно сделал?

2024-04-05 10:35 UTC, DexlerXD requested changes
Предлагаю всё сделать в таком формате:
```
# SS220-uplink-fix begin
#   whitelist: 
#      tags: 
#       - NukeOpsUplink 
#       - LoneOpsUplink
# SS220-uplink-fix end
```

2024-04-05 10:36 UTC, Helm4142 commented
Пока всё чекал, заметил одну вещичку, что у нас граната белой дыры стоит 6 ТК, а у оффов 3.

2024-04-05 10:54 UTC, Helm4142 commented
@DexlerXD У меня созрел вопрос, у оффов граната белой дыры стоит 3 ТК, у нас 6 ТК, но я не знаю с чем это связанно, лучше не трогать? И ещё я сделал по твоему образцу комментарии.

2024-04-05 16:03 UTC, DexlerXD requested changes

2024-04-05 16:03 UTC, DexlerXD commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> -        - LoneOpsUplink
по образцу с предыдущими сделай

2024-04-05 16:08 UTC, Helm4142 commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> -        - LoneOpsUplink
Ну я и огрызок, удалил прошлый коментарий и забыл вставить новый, ещё же было чувство что что-то не так.

2024-04-05 16:15 UTC, DexlerXD commented on Resources/Prototypes/Catalog/uplink_catalog.yml
> +#SS220fix
```suggestion
```

2024-04-05 16:21 UTC, Helm4142 commented
Куда я жмал! Прошу прощения, немного туплю

2024-04-05 17:14 UTC, DexlerXD approved these changes

2024-04-05 17:14 UTC, merged