Autoinjectors220
SerbiaStrong-220/space-station-14 pull request #881
Opened 2024-04-04 20:29 UTC by Gnomeev

## Описание PR

Добавлены автоинжекторы, по таску от сурани и трекера
Добавлен AfterHypoEvent, вызывающийся после использования гипоспрея и ему подобных

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [X] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

- add: Добавлены автоинжекторы

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-04-05 03:41 UTC, Surani1 commented
@DexlerXD ревью мальчика

2024-04-05 10:42 UTC, Kit0vras requested changes

2024-04-05 10:42 UTC, Kit0vras commented on Resources/Prototypes/SS220/Chemistry/autoinjectors.yml
> +  id: BaseAutoinjectorss220
у тебя есть базовый инъектор, задай максимум компонентов у него, (к примеру, вместимость поставь на 10), сделай его абстрактным и наследуй в обычном инъекторе ниже этот инъектор (что и делается)
За счёт наследования ты сможешь не повторять кучу строк
если понадобится бОльший инжектор - вот конкретно на нём можно будет дописать вместимость на 15

2024-04-05 16:13 UTC, DexlerXD requested changes

2024-04-05 16:13 UTC, DexlerXD commented on Content.Server/Chemistry/EntitySystems/ChemistrySystemHypospray.cs
> -
???

2024-04-05 16:13 UTC, DexlerXD commented on Content.Server/Chemistry/EntitySystems/AutoinjectorSystem.cs
> +        private void OnCheck(EntityUid uid, AutoinjectorComponent component, AfterHypoEvent args)
лучшим неймингом будет OnAfterHypo, т. к. такое название отображает к чему подсосан метод

2024-04-14 20:55 UTC, Surani1 commented
@Gnomeev с чем тебе помочь, чтобы закончить?

2024-05-13 20:51 UTC, DexlerXD commented
@Gnomeev конфликты бро

2024-05-15 18:36 UTC, DexlerXD approved these changes
lgtm

2024-05-15 18:36 UTC, merged