Add detective camera
SerbiaStrong-220/space-station-14 pull request #885
Opened 2024-04-05 17:27 UTC by Skriler

## Описание PR

Добавлена скрытая камера детектива. Использование в руке включает/выключает камеру. Камера крепится на структурном предмете или элементе одежды. Время крепления/снятия - 3 секунды. 

**Медиа**

![Content Client_ymIE3sMich](https://github.com/SerbiaStrong-220/space-station-14/assets/66323284/d0c0ff10-41f8-4546-9afc-a76b4d74f17e)
![Content Client_1DGK6hzIt5](https://github.com/SerbiaStrong-220/space-station-14/assets/66323284/96a0641f-3e80-4ac4-8304-d08c45fd4d9d)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl:
- add: Добавлена скрытая камера детектива.

2024-04-05 17:52 UTC, Kit0vras requested changes

2024-04-05 17:52 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss220/prototypes/entities/objects/detective/detective-camera.ftl
> +ent-DetectiveHiddenCamera = Скрытая камера
```suggestion
ent-DetectiveHiddenCamera = скрытая камера
```

2024-04-05 17:52 UTC, Kit0vras commented on Resources/Locale/ru-RU/ss220/detective/camera/detective-camera.ftl
> +detective-camera-attached-description = [color=lightblue]Вам кажется, тут что-то закреплено. Или всё же просто паранойя?[/color]
```suggestion
detective-camera-attached-description = [color=lightblue]Вам кажется, что тут что-то закреплено. Или это всё же просто паранойя?[/color]
```

2024-04-06 13:48 UTC, DexlerXD approved these changes

2024-04-07 17:41 UTC, DexlerXD commented
@Kit0vras ничего, что камера спавнится в секьюрити локерах? Разве дек не в сервисе?

2024-04-07 19:19 UTC, Kit0vras commented
> @Kit0vras ничего, что камера спавнится в секьюрити локерах? Разве дек не в сервисе?

так его шкаф то в юмле с секьюрити локерами лежит

2024-04-07 21:26 UTC, DexlerXD commented
excellent argument

2024-04-07 21:27 UTC, merged