Fix goals text
SerbiaStrong-220/space-station-14 pull request #887
Opened 2024-04-05 22:25 UTC by Kirus59

## Описание PR

Исправлен текст в описании некоторых целей станции
**Медиа**

**Проверки**

- [X] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [X] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [X] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: kirus59
- fix: Исправлен текст в описании целей станции

2024-04-07 12:42 UTC, Kit0vras requested changes

2024-04-07 12:42 UTC, Kit0vras commented on Resources/PhotocopierForms/nanotrasen_station/goal/goal_robotisation.xml
> +  <PhotocopierTitle>Отчет о кибернетизации процессов станции</PhotocopierTitle>
это синонимы, если менять - то в цели везде тоже, потому что там вроде "кибернизация"

2024-04-07 19:31 UTC, Kirus59 commented on Resources/PhotocopierForms/nanotrasen_station/goal/goal_robotisation.xml
> +  <PhotocopierTitle>Отчет о кибернетизации процессов станции</PhotocopierTitle>
В цели и в самом отчете как раз таки и написано "кибернетизация", и только тут была кибернизация...

2024-04-07 19:51 UTC, Kirus59 commented
@Kit0vras рофлопинг, хз пингануло ли тебя на ответ выше

2024-04-07 21:00 UTC, Kit0vras commented on Resources/PhotocopierForms/nanotrasen_station/goal/goal_robotisation.xml
> +  <PhotocopierTitle>Отчет о кибернетизации процессов станции</PhotocopierTitle>
оки

2024-04-07 21:00 UTC, Kit0vras approved these changes

2024-04-08 18:51 UTC, DexlerXD approved these changes

2024-04-08 18:51 UTC, merged