Update arachnid.yml
SerbiaStrong-220/space-station-14 pull request #889
Opened 2024-04-06 12:38 UTC by EstKemran

## Описание PR
Изменены урон и скорость атаки некоторых рас согласно   [трекеру](https://discord.com/channels/1097181193939730453/1225896002670694460) 

Одобрение от Адуча не получено, ждем когда он проснется

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Kemran
- tweak: Изменены урон и скорость атаки в кулачном бою для некоторых рас

2024-04-08 07:34 UTC, Ady4ik requested changes
@ZoNeSRuS обрати внимание на соответствие с лором

2024-04-08 07:34 UTC, Ady4ik commented on Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
> +        Blunt: 7.15
```suggestion
        Blunt: 8
```

2024-04-08 07:34 UTC, Ady4ik commented on Resources/Prototypes/Entities/Mobs/Species/dwarf.yml
> +    attackRate: 0.7
```suggestion
    attackRate: 0.625
```

2024-04-11 19:04 UTC, DexlerXD commented
@Ady4ik all good now?

2024-04-11 19:05 UTC, DexlerXD commented on Content.Server/Corvax/ChatFilter/ChatSystem.cs
> +        {"пидро","мужеложец"}, //SS220 Filter Update end
?????

2024-04-12 15:14 UTC, EstKemran commented on Content.Server/Corvax/ChatFilter/ChatSystem.cs
> +        {"пидро","мужеложец"}, //SS220 Filter Update end
Не хотел гадить ПРами, если нужно - уберу ＾▽＾

2024-04-19 06:30 UTC, Ady4ik commented
all good

2024-04-20 21:28 UTC, DexlerXD commented on Content.Server/Corvax/ChatFilter/ChatSystem.cs
> +        {"пидро","мужеложец"}, //SS220 Filter Update end
> Не хотел гадить ПРами, если нужно - уберу ＾▽＾

все еще жду фикса

2024-04-20 22:27 UTC, EstKemran commented on Content.Server/Corvax/ChatFilter/ChatSystem.cs
> +        {"пидро","мужеложец"}, //SS220 Filter Update end
А я ждал ответа xd

2024-04-20 23:14 UTC, DexlerXD approved these changes

2024-04-20 23:14 UTC, merged