Resprite
SerbiaStrong-220/space-station-14 pull request #902
Opened 2024-04-10 17:18 UTC by TheNekoWiz

## Описание PR
мной был переделан спрайт генератора сингулярности по таску от китовраса 

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
- tweak: Обновлён спрайт генератора сингулярности

:cl: Neko_Wiz

2024-04-10 21:19 UTC, TheNekoWiz commented
надеюсь оно понравится людям

2024-04-11 00:29 UTC, VladIsLove-e commented
Прикольная концепция, но как будто деталей не хватает. Мб попробовать сделать вид, что там в центре плазма? Всё же по лору- плазма очень необычное в физическом смысле вещество и логичнее использовать её, а не просто какой-то стержень из непойми чего...

2024-04-11 14:02 UTC, TheNekoWiz commented
в принципе можно попробовать сделать плазму внутри

2024-04-17 07:30 UTC, Kit0vras commented
плазма как-то не очень нарисована, возможно, её стоит попробовать анимировать, и эта анимация должна идти отдельным слоем, чтобы можно было сделать так, чтобы она светилась
А ещё убери вот этот пиксель слева-сверху, я про него забыл
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/d837b02d-53d1-46dd-8b5b-8cc6c064d1bf)

2024-04-17 07:31 UTC, Kit0vras requested changes
Уээ

2024-04-18 15:52 UTC, TheNekoWiz commented
> Уээ

пон, срайтшит есть, как заставить его быть анимированным?

2024-04-20 21:22 UTC, DexlerXD commented
@Kit0vras

2024-04-21 21:36 UTC, Kit0vras commented
я ж говорил, плазму стоит сделать отдельным слоем - у тебя 1 спрайт - это генератор синги, и второй - спрайтлист из плазмы
тоесть, 2 файла - 1 это то, что было в прошлый раз, а второй - то же, что сейчас, но без генератора, только с плазмой

2024-05-22 15:21 UTC, Surani1 commented
@TheNekoWiz ты переделывать то будешь?

2024-06-08 13:36 UTC, DexlerXD commented
@TheNekoWiz закрываем?

2024-06-13 20:43 UTC, Surani1 commented
@DexlerXD закрывай

2024-06-13 20:46 UTC, closed without merging