lone_ops_comms
SerbiaStrong-220/space-station-14 pull request #915
Opened 2024-04-17 15:32 UTC by VladIsLove-e

## Описание PR

Добавляет консоль связи одиночного оперативника в игру и на шаттл. Отличие от консоли яо на скрине.
C пультом объявления войны аналогично.
Делается с целью соблюдения п.3.1 и п.8 ведь ПГ и Валидхант против соло нюки запрещён. Это позволит игрокам не путаться
**Медиа**

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/139070688/f34d675e-cb58-49fe-92b4-6de149fa996d)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: VladIsLove
- add: Добавлена консоль связи одиночного ядерного оперативника.
- add: Добавлен пульт объявления войны одиночного ядерного оперативника.
- fix: Подправил локализацию в пульте войны.

2024-04-17 15:33 UTC, VladIsLove-e commented
@Ady4ik

2024-04-17 18:27 UTC, VladIsLove-e commented
> Тк дают?

Тк через пуль объявления войны даётся

2024-04-17 18:34 UTC, Kit0vras requested changes

2024-04-17 18:34 UTC, Kit0vras commented on Resources/Locale/ru-RU/communications/communications-console-component.ftl
> +comms-console-announcement-title-solo-nukie = Объявление Одиночного Ядерного оперативника Синдиката
```suggestion
comms-console-announcement-title-solo-nukie = Одиночного Ядерного оперативника Синдиката
```

2024-04-17 18:42 UTC, Kirus59 commented
> Тк через пульт объявления войны даётся

Так при объяве через пульт будет же объява как от обычных ЯО, или ты в пульте тоже изменишь на объяву солонюки?

2024-04-17 18:42 UTC, VladIsLove-e commented
> > Тк через пульт объявления войны даётся
> 
> Так при объяве через пульт будет же объява как от обычных ЯО, или ты в пульте тоже изменишь на объяву солонюки?

спс что напомнил

2024-04-19 06:11 UTC, VladIsLove-e commented
@Ady4ik

2024-04-19 06:31 UTC, Ady4ik commented
all good

2024-04-19 06:31 UTC, Ady4ik approved these changes

2024-04-19 13:35 UTC, VladIsLove-e commented
@DexlerXD

2024-04-19 17:04 UTC, DexlerXD approved these changes

2024-04-19 17:04 UTC, DexlerXD commented on Resources/Prototypes/Catalog/Fills/Backpacks/duffelbag.yml
> +      - id: NukeLoneOpsDeclarationOfWar
```suggestion
      - id: NukeLoneOpsDeclarationOfWar #SS220-lone-ops-comms
```

2024-04-19 17:18 UTC, merged