loxotron
SerbiaStrong-220/space-station-14 pull request #934
Opened 2024-04-22 16:45 UTC by VladIsLove-e

## Описание PR

Добавляет лотерейные билеты, которые совершенно точно окупаются!
Их можно найти на обломках/экспедициях, в технических шкафах или целенаправленно заказать в карго. Таблица exel с расчётам во вложении.
**Медиа**

[Лист Microsoft Excel.xlsx](https://github.com/SerbiaStrong-220/space-station-14/files/15066037/Microsoft.Excel.xlsx)
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/139070688/3d4e35da-336d-4d63-9388-f8756ec4881e)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: VladIsLove, glek3197
- add: Добавлены лотерейные билеты в технические шкафы и заказы карго.

2024-04-24 17:46 UTC, DexlerXD requested changes

2024-04-24 17:46 UTC, DexlerXD commented on Resources/Prototypes/Entities/Objects/Misc/space_cash.yml
> +
```suggestion
#SS220-loxotron begin
- type: entity
  parent: SpaceCash
  id: SpaceCash50000
  suffix: 50000
  components:
  - type: Icon
    sprite: Objects/Economy/cash.rsi
    state: cash_1000000
  - type: Stack
    count: 50000

- type: entity
  parent: SpaceCash
  id: SpaceCash100000
  suffix: 100000
  components:
  - type: Icon
    sprite: Objects/Economy/cash.rsi
    state: cash_1000000
  - type: Stack
    count: 100000
#SS220-loxotron end

```

2024-04-25 13:31 UTC, VladIsLove-e commented
@DexlerXD ну шо?

2024-04-25 14:02 UTC, DexlerXD commented
> @DexlerXD ну шо?
> 

по спрайтам одобрение от Кито было?

2024-04-25 14:51 UTC, VladIsLove-e commented
> > @DexlerXD ну шо?
> 
> по спрайтам одобрение от Кито было?

вроде они их совместно рисовали

2024-04-25 17:07 UTC, Kit0vras requested changes

2024-04-25 17:07 UTC, Kit0vras commented on Resources/Prototypes/SS220/Catalog/Cargo/cargo_fun.yml
> +  description: Больше билетов больше выйгрыш! Стань миллионером уже сегодня!
```suggestion
  description: Больше билетов - больше выигрыш! Стань миллионером уже сегодня!
```

2024-04-25 17:07 UTC, Kit0vras commented on Resources/Prototypes/SS220/Entities/Objects/Misc/lottery.yml
> +  description: Лотеря исполняющая мечты! Стань миллионером прямо сейчас!
```suggestion
  description: Лотерея, исполняющая мечты! Стань миллионером прямо сейчас!
```

2024-04-25 17:07 UTC, Kit0vras commented on Resources/Textures/SS220/Objects/Fun/Lottery.rsi/meta.json
> +  "copyright": "Created by VladIsLove and discord glek3197 for SS220 ",
```suggestion
  "copyright": "Created by glek3197 (Discord) for SS220",
```
спрайт рисовал глек, копирайт - его

2024-04-26 08:36 UTC, VladIsLove-e commented on Resources/Textures/SS220/Objects/Fun/Lottery.rsi/meta.json
> +  "copyright": "Created by VladIsLove and discord glek3197 for SS220 ",
ой баляяяять

2024-04-26 14:47 UTC, DexlerXD approved these changes

2024-04-26 14:51 UTC, DexlerXD commented
@VladIsLove-e чейнджлог добавь пожалуйста, игровая фича вроде...

2024-04-26 15:00 UTC, VladIsLove-e commented
> @VladIsLove-e чейнджлог добавь пожалуйста, игровая фича вроде...

строчку со стрелочками удалить забыл

2024-04-26 15:03 UTC, merged