PipeSound
SerbiaStrong-220/space-station-14 pull request #936
Opened 2024-04-23 08:58 UTC by Helm4142

## Описание PR

Сделал по трекеру новый звук трубы, когда падает на тайл воспроизводится звук трубы.
https://ptb.discord.com/channels/1097181193939730453/1231526588911325216
**Медиа**

https://github.com/SerbiaStrong-220/space-station-14/assets/158806576/4575cd88-9992-4900-8b31-e46cd1552fe1

**Проверки**

- [х] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [х] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [х] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [х] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl: Helm
- tweak: Изменён звук трубы при падении на тайл!

2024-04-23 09:04 UTC, Helm4142 commented
Какие-то ошибки повылезали, увы...

2024-04-23 09:40 UTC, ZoNeSRuS commented
> Какие-то ошибки повылезали, увы...

Чини ошибки хули

2024-04-23 13:05 UTC, Helm4142 commented
Вообще всё работает отлично, а ошибки ошибаются. Без сторонней помощи я никак не смогу это пофиксить...

2024-04-23 13:10 UTC, Helm4142 commented
У меня в компоненте каких-то какашек не хватает, если в игре найду каких то попытаюсь допилить, но скорее всего я ничё не смогу сделать.

2024-04-23 13:50 UTC, Helm4142 commented
ЮХУ!!! Быть таким глупым как я это ужас что-бы вставить 2 строчки готового кода у меня ушло 2 дня!

2024-04-24 17:49 UTC, DexlerXD commented
@Ady4ik это одобрено? это же -уши

2024-04-25 01:49 UTC, Helm4142 commented
> @Ady4ik это одобрено? это же -уши

Насчёт -уши, могу сегодня через код уменьшить звук, через сайт пытался но там либо тихо либо громко, усреднённое выбрал

2024-04-25 08:51 UTC, Helm4142 commented
Ломал голову час как изменить код что-бы сделать тише звук

2024-04-25 17:17 UTC, EstKemran commented
@Helm4142 Ты не обновил медиа после убавления громкости. Сделать бы, что бы ревьюер смог оценить

2024-04-25 21:52 UTC, Kit0vras requested changes
![sonic-boom-knuckles (2)](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/12eedd5d-fe66-47b2-92c7-15e08a68ea88)
Это нужно было добавлять на первое апреля. Делать такое на постоянку - явно плохая идея и слишком кринж.

2024-04-26 00:27 UTC, Helm4142 commented
> @Helm4142 Ты не обновил медиа после убавления громкости. Сделать бы, что бы ревьюер смог оценить

Буэээ... А как?

2024-04-26 00:29 UTC, Helm4142 commented
@Kit0vras А эт для чего?

2024-04-26 01:01 UTC, Kit0vras commented
> @Kit0vras А эт для чего?

Первое апреля уже закончилось, месяц назад

2024-04-26 01:20 UTC, Helm4142 commented
> > @Kit0vras А эт для чего?
> 
> Первое апреля уже закончилось, месяц назад

Так это мем, смешной звук для атмосов.

2024-04-26 01:21 UTC, Helm4142 commented
Я не задумывал это как прикол на 1 апреля

2024-04-26 10:53 UTC, Helm4142 commented
Я куда-то понатыкал...

2024-04-26 11:00 UTC, Helm4142 commented
И как фиксить эту ошибку?

2024-04-26 11:02 UTC, DexlerXD commented
? 
у тебя всё нормально

2024-04-26 11:06 UTC, Helm4142 commented
> ? у тебя всё нормально

Спасибо, думал опять фиксить придётся

2024-04-26 14:46 UTC, DexlerXD commented
@Ady4ik я закрываю пр? Я с Кито против, такое максимум на первое апреля добавлять.

2024-04-29 08:39 UTC, Ady4ik commented
Если он сделает его очень тихим,чтобы не било по ушам, накинет на него эффект эха и т.д, то посмотрим

2024-04-29 09:03 UTC, Helm4142 commented
Насчёт тише могу сделать, а вот эффект эхо никак не получается, увы...

2024-04-30 16:41 UTC, closed without merging