MORE&MORE-turtleneck
SerbiaStrong-220/space-station-14 pull request #937
Opened 2024-04-23 20:40 UTC by EstKemran

![изображение](https://github.com/SerbiaStrong-220/space-station-14/assets/157578255/61a59aeb-f477-4a52-aa69-fa290aa2d2f3)

## Описание PR
МНОГО и МНОГО Водолазок для общественного доступа.

- [x] ~~Водолазки + брюки черного цвета~~
- [x] ~~Водолазки + брюки основного цвета~~
- [x] Водолазки + юбка черного цвета
- [x] Водолазка для ОСЩ
- [x] Добавить водолазки в общественные одеждоматы и одеждоматы отделов

**Проверки**
<!-- Выполнение всех следующих действий, если это приемлемо для вида изменений сильно ускорит разбор вашего PR -- - [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [ ] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [ ] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [ ] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
 :cl: Kemran 
- add: Добавлены 48 водолазок по 3 типа.

2024-04-23 20:56 UTC, Ady4ik commented
ничего себе, а с чего вдруг 48 водолазок?

2024-04-23 20:57 UTC, EstKemran commented
> ничего себе, а с чего вдруг 48 водолазок?

Они красивые :)

2024-04-26 13:31 UTC, EstKemran commented
@Kit0vras ревью, @Ady4ik одобрено/отказано

2024-04-27 12:19 UTC, EstKemran commented
Два ленивых котика

2024-04-27 16:57 UTC, Kit0vras commented
Сделай пояс у водолазки Осщ золотым, теми же тонами, что у бейджика на водолазке
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/f1c238cb-41d5-4195-bd0c-5f02bc5576cb)

2024-04-27 16:59 UTC, EstKemran commented
> Сделай пояс у водолазки Осщ золотым, теми же тонами, что у бейджика на водолазке

Это фича, но раз надо, поменяем

2024-04-27 17:01 UTC, Kit0vras commented
не, не надо, не меняй, всё в порядке

2024-04-27 17:04 UTC, Kit0vras requested changes

2024-04-27 17:04 UTC, Kit0vras commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
> +    ClothingUniformJumpsuitBlackTurtle: 2 #SS220-MORE&MORE-turtleneck-Begin
мне кажется, не стоит добавлять в Одеждомат ещё больше одежды, там и так насыпано килограммами. Пусть выбирают через лоадаут
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/7c8fcfc6-4cf3-44bb-9ea9-cdbf8206a924)

2024-04-27 17:07 UTC, EstKemran commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
> +    ClothingUniformJumpsuitBlackTurtle: 2 #SS220-MORE&MORE-turtleneck-Begin
Этот лодаут тысячи лет ждать (т_т), а так в одеждомате будет 5 водолазок из 50-и

2024-04-27 17:32 UTC, Kit0vras commented on Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
> +    ClothingUniformJumpsuitBlackTurtle: 2 #SS220-MORE&MORE-turtleneck-Begin
не ждать, он в следующем апстриме
от того, что в нём будут эти пять водолазок, погоды не сделает, потому что тебе потом самому же придётся делать двойную работу и убирать их , а чтобы что

2024-04-28 05:32 UTC, Kit0vras approved these changes

2024-04-28 19:54 UTC, Kit0vras commented
> @DexlerXD Мне закрыть этот ПР, и сделать с новой системой цветной одежды, или так сойдет?

закрывай :С

2024-04-28 20:00 UTC, closed without merging