admin_memes
SerbiaStrong-220/space-station-14 pull request #951
Opened 2024-04-29 10:37 UTC by VladIsLove-e

## Описание PR

Добавление вещей админам согласно: https://discord.com/channels/1097181193939730453/1232033635029221397
А именно:
-Добавлен слот очков админ госту.
-Карта в админ пда заменена на дебагнутую.
-Анализатор здоровья в сумке админ призрака заменён на кпк врача, ибо последний не имеет заряда.
-В сумку админ призрака добавлены админ пульт и мулти-худ, а так же монитор экипажа.
-Добавлены бутылочки Дексалина +, бикаридина, диловена, аритразина, дермалина.
-Добавлен мыломёт.
-Добавлено 6 новых частот и гарнитур.
**Медиа**

![666](https://github.com/SerbiaStrong-220/space-station-14/assets/139070688/a4bae754-7075-41fb-bffc-71dcef1a82dc)

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: VladIsLove
- add: Добавлены админ приколы, подробности в стаффе.

2024-04-29 10:38 UTC, VladIsLove-e commented
скрин старый, названия частот с большой буквы*

2024-04-30 13:53 UTC, VladIsLove-e commented
ой ноу, я забыл кое-что сделать
момент

2024-04-30 16:40 UTC, Helm4142 commented
Скажите *хуй* разными голосами!

2024-04-30 17:02 UTC, VladIsLove-e commented
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/139070688/5256207e-8c45-42e5-988c-1ee5dcabac6c)
Сумка буквально невидимая. нужно для того, чтобы "шляпы" работали корректно, а то раньше сумки приходилось удалять.

2024-04-30 17:03 UTC, DexlerXD commented
> ![image](https://github.com/SerbiaStrong-220/space-station-14/assets/139070688/5256207e-8c45-42e5-988c-1ee5dcabac6c)
> Сумка буквально невидимая. нужно для того, чтобы "шляпы" работали корректно, а то раньше сумки приходилось удалять.

так скрытие тела и сумки скрывает

2024-04-30 17:06 UTC, DexlerXD commented
> > > ![image](https://private-user-images.githubusercontent.com/139070688/326911305-5256207e-8c45-42e5-988c-1ee5dcabac6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTY5MTcsIm5iZiI6MTcxNDQ5NjYxNywicGF0aCI6Ii8xMzkwNzA2ODgvMzI2OTExMzA1LTUyNTYyMDdlLThjNDUtNDJlNS05ODhjLTFlZTVkY2FiYWM2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNzAzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzg0NTlmYjUxOTVhYjIwNDk2MjNmOGMwNzI3MGFjZDc5YjZjY2MxOGI0NGExNTU2MzBjYTMxY2VmZWNkOGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8tySx2vjnK0yi50AlppWr080QsbQQf5_4HP_ITm4-k8)
> > > Сумка буквально невидимая. нужно для того, чтобы "шляпы" работали корректно, а то раньше сумки приходилось удалять.
> > 
> > так скрытие тела и сумки скрывает
> 
> нет. оно скрывает только для того, кто кнопку прожал. у остальных это лямки в воздухе

а я тестил, у меня и сумку скрывало... 
че сразу не сказали, я бы пофиксил

2024-04-30 17:07 UTC, VladIsLove-e commented
> > > > ![image](https://private-user-images.githubusercontent.com/139070688/326911305-5256207e-8c45-42e5-988c-1ee5dcabac6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTY5MTcsIm5iZiI6MTcxNDQ5NjYxNywicGF0aCI6Ii8xMzkwNzA2ODgvMzI2OTExMzA1LTUyNTYyMDdlLThjNDUtNDJlNS05ODhjLTFlZTVkY2FiYWM2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNzAzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzg0NTlmYjUxOTVhYjIwNDk2MjNmOGMwNzI3MGFjZDc5YjZjY2MxOGI0NGExNTU2MzBjYTMxY2VmZWNkOGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8tySx2vjnK0yi50AlppWr080QsbQQf5_4HP_ITm4-k8)
> > > > Сумка буквально невидимая. нужно для того, чтобы "шляпы" работали корректно, а то раньше сумки приходилось удалять.
> > > 
> > > 
> > > так скрытие тела и сумки скрывает
> > 
> > 
> > нет. оно скрывает только для того, кто кнопку прожал. у остальных это лямки в воздухе
> 
> а я тестил, у меня и сумку скрывало... че сразу не сказали, я бы пофиксил

да проще так сделать, чем с кодом ебаться

2024-04-30 17:08 UTC, VladIsLove-e commented
> > > > > > ![image](https://private-user-images.githubusercontent.com/139070688/326911305-5256207e-8c45-42e5-988c-1ee5dcabac6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTY5MTcsIm5iZiI6MTcxNDQ5NjYxNywicGF0aCI6Ii8xMzkwNzA2ODgvMzI2OTExMzA1LTUyNTYyMDdlLThjNDUtNDJlNS05ODhjLTFlZTVkY2FiYWM2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNzAzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzg0NTlmYjUxOTVhYjIwNDk2MjNmOGMwNzI3MGFjZDc5YjZjY2MxOGI0NGExNTU2MzBjYTMxY2VmZWNkOGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8tySx2vjnK0yi50AlppWr080QsbQQf5_4HP_ITm4-k8)
> > > > > > Сумка буквально невидимая. нужно для того, чтобы "шляпы" работали корректно, а то раньше сумки приходилось удалять.
> > > > > 
> > > > > 
> > > > > так скрытие тела и сумки скрывает
> > > > 
> > > > 
> > > > нет. оно скрывает только для того, кто кнопку прожал. у остальных это лямки в воздухе
> > > 
> > > 
> > > а я тестил, у меня и сумку скрывало... че сразу не сказали, я бы пофиксил
> > 
> > 
> > да проще так сделать, чем с кодом ебаться
> 
> так ебаться я буду в любом случае

в любом случае я уже сделал, пусть так будет

2024-04-30 17:09 UTC, DexlerXD commented
> > > > > > > ![image](https://private-user-images.githubusercontent.com/139070688/326911305-5256207e-8c45-42e5-988c-1ee5dcabac6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTY5MTcsIm5iZiI6MTcxNDQ5NjYxNywicGF0aCI6Ii8xMzkwNzA2ODgvMzI2OTExMzA1LTUyNTYyMDdlLThjNDUtNDJlNS05ODhjLTFlZTVkY2FiYWM2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNzAzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzg0NTlmYjUxOTVhYjIwNDk2MjNmOGMwNzI3MGFjZDc5YjZjY2MxOGI0NGExNTU2MzBjYTMxY2VmZWNkOGVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8tySx2vjnK0yi50AlppWr080QsbQQf5_4HP_ITm4-k8)
> > > > > > > Сумка буквально невидимая. нужно для того, чтобы "шляпы" работали корректно, а то раньше сумки приходилось удалять.
> > > > > > 
> > > > > > 
> > > > > > так скрытие тела и сумки скрывает
> > > > > 
> > > > > 
> > > > > нет. оно скрывает только для того, кто кнопку прожал. у остальных это лямки в воздухе
> > > > 
> > > > 
> > > > а я тестил, у меня и сумку скрывало... че сразу не сказали, я бы пофиксил
> > > 
> > > 
> > > да проще так сделать, чем с кодом ебаться
> > 
> > так ебаться я буду в любом случае
> 
> в любом случае я уже сделал, пусть так будет

я на заметку проблему возьму

2024-04-30 17:11 UTC, DexlerXD commented
чекам плохо упупууу

2024-04-30 17:31 UTC, VladIsLove-e commented
я хуй знает чё он на ёмкость ругается

2024-04-30 18:38 UTC, VladIsLove-e commented
короче размер контейнера должен быть ≥ максимальному размеру предметов внутри него.

2024-04-30 19:57 UTC, DexlerXD approved these changes

2024-04-30 19:58 UTC, DexlerXD requested changes

2024-04-30 19:58 UTC, DexlerXD commented on Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml
> +  parent: ClothingBackpackSatchel
ааа блядь пометки где

2024-04-30 19:58 UTC, DexlerXD commented on Resources/Prototypes/Catalog/Fills/Backpacks/StarterGear/satchel.yml
> +    - id: MedicalPDA
и тут

2024-05-01 13:32 UTC, VladIsLove-e commented
@DexlerXD 
![image](https://github.com/SerbiaStrong-220/space-station-14/assets/139070688/c14e6d58-f651-435f-8ad7-bdec8a407bab)

2024-05-01 16:54 UTC, DexlerXD approved these changes

2024-05-01 16:54 UTC, merged