CentComm Map v0.1
SerbiaStrong-220/space-station-14 pull request #976
Opened 2024-05-07 10:13 UTC by Surani1

## Описание PR
Добавлена новая карта CentComm

**Медиа**

**Проверки**

- [ ] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
no cl no fun

2024-05-07 10:15 UTC, Surani1 commented
Мерджить после фикса доступов адуча

2024-05-08 08:51 UTC, Surani1 commented
А да? Да ну нахуй, все чеки прошел

2024-05-11 18:17 UTC, Surani1 commented
@Kit0vras last rewiew, and @DexlerXD merge this bullshit

2024-05-11 18:22 UTC, Kit0vras commented
> @Kit0vras last rewiew, and @DexlerXD merge this bullshit

а что по доступам, ты ж говорил, что они не работают

2024-05-11 18:25 UTC, Surani1 commented
> > @Kit0vras last rewiew, and @DexlerXD merge this bullshit
> 
> а что по доступам, ты ж говорил, что они не работают

фикшу RN

2024-05-11 18:30 UTC, Kit0vras requested changes

2024-05-11 18:30 UTC, Kit0vras commented on Resources/Prototypes/SS220/Maps/centcomm.yml
> +            prefixCreator: 'TG'
```suggestion
            prefixCreator: 'SS220'
```
ну или просто 220, я хз
типа тг это как понимаю отсылка на тгстейшен

2024-05-11 18:48 UTC, Kit0vras approved these changes
https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/a5fd2dd3-8bb4-4a42-a8e4-ee6d9afaec38

2024-05-11 19:34 UTC, DexlerXD approved these changes

2024-05-11 19:35 UTC, merged