Winter boots resprite
SerbiaStrong-220/space-station-14 pull request #985
Opened 2024-05-10 15:37 UTC by RobUster0

## Описание PR

Избавьтесь от старых, ужасных спрайтов зимних ботинок! Теперь и с цветным мехом под каждый отдел станции!(и не только станции)
Заменяет оригинальные спрайты на новые.

**Медиа**

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/160126098/ad8622d5-3acf-4ace-a50b-e0b1288e0b37)

**Проверки**

- [+] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [+] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [+] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [+] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**

:cl: Vimenant
- tweak: Зимние ботинки были перерисованы.
<!--
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-05-10 15:49 UTC, DexlerXD requested changes
Привет, есть несколько проблем с этим пром:
1. хоть это и перерисовка, но стоит всё таки создать новые файлы под новые спрайты и уже менять путь к спрайту в прототипе ботинок;
2. лицензия, если это нарисовано нами, обозначается как `EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt`
3. копирайт пишется в формате: `Made by Ник (Github) for SS220` или `Made by Ник (Discord) For SS220`;
4. в проверках пометки нужно ставить в формате `[x]` (именно латинская x).

Жду изменений...

2024-05-10 16:31 UTC, RobUster0 commented
Готово

2024-05-10 20:33 UTC, DexlerXD requested changes
На изменения файлов оффов мы должны ставить пометки, к примеру:
`sprite: SS220/Clothing/Shoes/Boots/winterboots.rsi #SS220-wboots-resprite`.

Эти моментики тогда исправь тоже и в принципе всё.

2024-05-10 22:35 UTC, RobUster0 commented
Всё

2024-05-11 05:56 UTC, Kit0vras approved these changes
![sonic-boom-knuckles](https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/842c6284-ce74-4bb1-a5d2-7821c24dc74b)

2024-05-11 08:57 UTC, DexlerXD approved these changes

2024-05-11 17:39 UTC, merged