[WIP] Porting sprites from TG
SerbiaStrong-220/space-station-14 pull request #992
Opened 2024-05-11 13:10 UTC by EstKemran

## Описание PR
Портирование спрайтов из ТГ

**Медиа**

**Проверки**

- [x] PR полностью завершён и мне не нужна помощь чтобы его закончить.
- [x] Я внимательно просмотрел все свои изменения и багов в них не нашёл.
- [x] Я запускал локальный сервер со своими изменениями и всё протестировал.
- [x] Я добавил скриншот/видео демонстрации PR в игре, **или** этот PR этого не требует.

**Изменения**
:cl: Kemran

- add: Добавлено веселье!
- remove: Убрано веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

2024-05-11 16:23 UTC, Kirus59 commented
:catDespair:
![Screenshot_20240511_192308_Chrome](https://github.com/SerbiaStrong-220/space-station-14/assets/145689588/c22c8800-ed7f-40a2-9ad6-ef1a69d076eb)

2024-05-11 16:28 UTC, EstKemran commented
> :catDespair:

Доделаю, потом оформлю :okayge:

2024-05-11 17:06 UTC, Kirus59 commented
> > :catDespair:
> 
> Доделаю, потом оформлю :okayge:

В чейнджлоге вроде будет тот вариант, который был изначально.

2024-05-11 17:08 UTC, EstKemran commented
> > > :catDespair:
> > 
> > 
> > Доделаю, потом оформлю :okayge:
> 
> В чейнджлоге вроде будет тот вариант, который был изначально.

:catDespair: пиздец...

2024-05-11 18:00 UTC, EstKemran commented
@Kit0vras с корзиной там немного посложнее, поэтому его пока не будет. Ревью, и особое внимание на лицензии

2024-05-11 18:22 UTC, Kit0vras requested changes

2024-05-11 18:22 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/anesthetic.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken: https://github.com/tgstation/tgstation/commit/324f016c8af32
```suggestion
  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken at https://github.com/tgstation/tgstation/commit/324f016c8af32738430aacfd0c4f5888976c9438",
```

2024-05-11 18:22 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/emergency.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken: https://github.com/tgstation/tgstation/commit/324f016c8af32
```suggestion
  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken at https://github.com/tgstation/tgstation/commit/324f016c8af32738430aacfd0c4f5888976c9438",
```

2024-05-11 18:22 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/emergency_double.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken: https://github.com/tgstation/tgstation/commit/324f016c8af32
```suggestion
  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken at https://github.com/tgstation/tgstation/commit/324f016c8af32738430aacfd0c4f5888976c9438",
```

2024-05-11 18:22 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/emergency_double_red.rsi/meta.json
> +  "copyright": "Adapted by DangerRevolution from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken: https://github.com/tgstation/tgstatio
```suggestion
  "copyright": "Adapted by DangerRevolution from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken at https://github.com/tgstation/tgstation/commit/324f016c8af32738430aacfd0c4f5888976c9438",
```

2024-05-11 18:22 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/emergency_extended.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken: https://github.com/tgstation/tgstation/commit/324f016c8af32
```suggestion
  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken at https://github.com/tgstation/tgstation/commit/324f016c8af32738430aacfd0c4f5888976c9438",
```

2024-05-11 18:22 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/emergency_red.rsi/meta.json
> +  "copyright": "Adapted by DangerRevolution from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken: https://github.com/tgstation/tgstatio
```suggestion
  "copyright": "Adapted by DangerRevolution from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken at https://github.com/tgstation/tgstation/commit/324f016c8af32738430aacfd0c4f5888976c9438",
```

2024-05-11 18:22 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/emergency_yellow.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken: https://github.com/tgstation/tgstation/commit/324f016c8af32
```suggestion
  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken at https://github.com/tgstation/tgstation/commit/324f016c8af32738430aacfd0c4f5888976c9438",
```

2024-05-11 18:22 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/generic.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken: https://github.com/tgstation/tgstation/commit/324f016c8af32
```suggestion
  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken at https://github.com/tgstation/tgstation/commit/324f016c8af32738430aacfd0c4f5888976c9438",
```

2024-05-11 18:22 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/oxygen.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken: https://github.com/tgstation/tgstation/commit/324f016c8af32
```suggestion
  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken at https://github.com/tgstation/tgstation/commit/324f016c8af32738430aacfd0c4f5888976c9438",
```

2024-05-11 18:22 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/plasma.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken: https://github.com/tgstation/tgstation/commit/324f016c8af32
```suggestion
  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken at https://github.com/tgstation/tgstation/commit/324f016c8af32738430aacfd0c4f5888976c9438",
```

2024-05-11 18:22 UTC, Kit0vras commented on Resources/Textures/Objects/Tanks/red.rsi/meta.json
> +  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken: https://github.com/tgstation/tgstation/commit/324f016c8af32
```suggestion
  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/e1142f20f5e4661cb6845cfcf2dd69f864d67432, icon taken at https://github.com/tgstation/tgstation/commit/324f016c8af32738430aacfd0c4f5888976c9438",
```

2024-05-11 18:22 UTC, Kit0vras commented on Resources/Textures/SS220/Structures/Specific/broken_entities.rsi/meta.json
> +  "copyright": "Made by gabova (Discord) for SS220, grinder modifed by EstKemran (Github) for SS220",
```suggestion
  "copyright": "Made by gabova (Discord) for SS220, grinder modified by EstKemran (Github) for SS220",
```

2024-05-11 18:22 UTC, Kit0vras commented on Resources/Textures/SS220/Structures/Specific/broken_entities.rsi/meta.json
> +        "name": "grill"
?

2024-05-11 19:03 UTC, Kit0vras approved these changes
https://github.com/SerbiaStrong-220/space-station-14/assets/123590995/e4d969f0-8640-476e-b371-c725fc83eca6

2024-05-12 04:57 UTC, Surani1 commented
@DexlerXD merge?

2024-05-12 10:28 UTC, DexlerXD approved these changes

2024-05-12 10:32 UTC, DexlerXD requested changes

2024-05-12 10:32 UTC, DexlerXD commented on Resources/Textures/Structures/Machines/juicer.rsi/meta.json
> +  "copyright": "https://github.com/tgstation/tgstation/commit/7da3ba9773922ad75eb4fe2c5f9df88068674ca5",
```suggestion
  "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/7da3ba9773922ad75eb4fe2c5f9df88068674ca5",
```

2024-05-12 10:51 UTC, DexlerXD approved these changes

2024-05-12 10:53 UTC, merged